"""CdnLoadbalancer resource exports."""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from f5xc_py_substrate.resources.cdn_loadbalancer.models import *
    from f5xc_py_substrate.resources.cdn_loadbalancer.resource import CdnLoadbalancerResource

# Cache for lazy-loaded modules
_models_module = None


def __getattr__(name: str):
    """Lazy load exports."""
    global _models_module

    if name == "CdnLoadbalancerResource":
        from f5xc_py_substrate.resources.cdn_loadbalancer.resource import CdnLoadbalancerResource
        return CdnLoadbalancerResource

    # Load models module once and cache it
    if _models_module is None:
        _models_module = importlib.import_module(
            "f5xc_py_substrate.resources.cdn_loadbalancer.models"
        )

    # Try to get attribute from models
    try:
        return getattr(_models_module, name)
    except AttributeError:
        pass

    raise AttributeError(f"module 'f5xc_py_substrate.resources.cdn_loadbalancer' has no attribute '{name}'")


__all__ = [
    "CdnLoadbalancerResource",
    "DiscoveredAPISettings",
    "CDNAccessLogFilter",
    "CDNAccessLogAggregationRequest",
    "CDNAccessLogRequest",
    "Empty",
    "CDNTLSConfig",
    "CDNHTTPSAutoCertsType",
    "ObjectRefType",
    "CustomCiphers",
    "TlsConfig",
    "XfccHeaderKeys",
    "DownstreamTlsValidationContext",
    "DownstreamTLSCertsParams",
    "HashAlgorithms",
    "BlindfoldSecretInfoType",
    "ClearSecretInfoType",
    "SecretType",
    "TlsCertificateType",
    "DownstreamTlsParamsType",
    "TlsCertOptions",
    "CDNHTTPSCustomCertsType",
    "CDNLoadBalancerList",
    "CDNLogAggregationResponse",
    "LilacCDNAccessLogsResponseData",
    "CDNLogResponse",
    "ObjectCreateMetaType",
    "ServicePolicyList",
    "HttpMethodMatcherType",
    "AsnMatchList",
    "ObjectRefType",
    "AsnMatcherType",
    "LabelSelectorType",
    "IpMatcherType",
    "PrefixMatchList",
    "IPThreatCategoryListType",
    "TlsFingerprintMatcherType",
    "ClientMatcher",
    "InlineRateLimiter",
    "MatcherType",
    "CookieMatcherType",
    "HeaderMatcherType",
    "JWTClaimMatcherType",
    "QueryParameterMatcherType",
    "RequestMatcher",
    "ApiEndpointRule",
    "ApiEndpointDetails",
    "APIGroups",
    "BypassRateLimitingRule",
    "BypassRateLimitingRules",
    "CustomIpAllowedList",
    "PrefixStringListType",
    "ServerUrlRule",
    "APIRateLimit",
    "MessageMetaType",
    "FallThroughRule",
    "CustomFallThroughMode",
    "OpenApiFallThroughMode",
    "ValidationSettingForQueryParameters",
    "ValidationPropertySetting",
    "OpenApiValidationCommonSettings",
    "OpenApiValidationModeActiveResponse",
    "OpenApiValidationModeActive",
    "OpenApiValidationMode",
    "OpenApiValidationAllSpecEndpointsSettings",
    "OpenApiValidationRule",
    "ValidateApiBySpecRule",
    "APISpecificationSettings",
    "HeaderMatcherType",
    "HttpHeaderMatcherList",
    "SimpleClientSrcRule",
    "ShapeJavaScriptInsertAllType",
    "DomainType",
    "PathMatcherType",
    "ShapeJavaScriptExclusionRule",
    "ShapeJavaScriptInsertAllWithExceptionsType",
    "ShapeJavaScriptInsertionRule",
    "ShapeJavaScriptInsertType",
    "HeaderMatcherTypeBasic",
    "MobileTrafficIdentifierType",
    "MobileSDKConfigType",
    "BotDefenseFlowLabelAccountManagementChoiceType",
    "BotDefenseTransactionResultCondition",
    "BotDefenseTransactionResultType",
    "BotDefenseTransactionResult",
    "BotDefenseFlowLabelAuthenticationChoiceType",
    "BotDefenseFlowLabelFinancialServicesChoiceType",
    "BotDefenseFlowLabelFlightChoiceType",
    "BotDefenseFlowLabelProfileManagementChoiceType",
    "BotDefenseFlowLabelSearchChoiceType",
    "BotDefenseFlowLabelShoppingGiftCardsChoiceType",
    "BotDefenseFlowLabelCategoriesChoiceType",
    "ShapeBotBlockMitigationActionType",
    "ShapeBotFlagMitigationActionType",
    "ShapeBotFlagMitigationActionChoiceType",
    "ShapeBotRedirectMitigationActionType",
    "ShapeBotMitigationAction",
    "WebMobileTrafficType",
    "AppEndpointType",
    "ShapeBotDefensePolicyType",
    "ShapeBotDefenseType",
    "CaptchaChallengeType",
    "CSDJavaScriptInsertAllWithExceptionsType",
    "CSDJavaScriptInsertionRule",
    "CSDJavaScriptInsertType",
    "ClientSideDefensePolicyType",
    "ClientSideDefenseType",
    "CorsPolicy",
    "DomainNameList",
    "CsrfPolicy",
    "CustomCacheRule",
    "SimpleDataGuardRule",
    "JA4TlsFingerprintMatcherType",
    "DDoSClientSource",
    "DDoSMitigationRule",
    "DefaultCacheAction",
    "SimpleLogin",
    "DomainConfiguration",
    "ApiCrawlerConfiguration",
    "ApiCrawler",
    "ApiCodeRepos",
    "CodeBaseIntegrationSelection",
    "ApiDiscoveryFromCodeScan",
    "ApiDiscoveryAdvancedSettings",
    "ApiDiscoverySetting",
    "JavascriptChallengeType",
    "EnableChallenge",
    "IPThreatCategoryListType",
    "GraphQLSettingsType",
    "GraphQLRule",
    "ProxyTypeHttp",
    "Action",
    "JWKS",
    "MandatoryClaims",
    "Audiences",
    "ReservedClaims",
    "BasePathsType",
    "Target",
    "TokenLocation",
    "JWTValidation",
    "OriginAdvancedConfiguration",
    "OriginServerPublicIP",
    "OriginServerPublicName",
    "CDNOriginServerType",
    "TlsCertificatesType",
    "UpstreamTlsValidationContext",
    "UpstreamTlsParameters",
    "CdnOriginPoolType",
    "HeaderManipulationOptionType",
    "HeaderControlType",
    "LogHeaderOptions",
    "LoggingOptionsType",
    "OtherSettings",
    "ArgMatcherType",
    "MatcherTypeBasic",
    "PathMatcherType",
    "ChallengeRuleSpec",
    "ChallengeRule",
    "ChallengeRuleList",
    "TemporaryUserBlockingType",
    "PolicyBasedChallenge",
    "CookieManipulationOptionType",
    "PolicyList",
    "InputHours",
    "InputMinutes",
    "InputSeconds",
    "RateLimitBlockAction",
    "LeakyBucketRateLimiter",
    "TokenBucketRateLimiter",
    "RateLimitValue",
    "RateLimitConfigType",
    "SensitiveDataPolicySettings",
    "SlowDDoSMitigation",
    "AppFirewallAttackTypeContext",
    "BotNameContext",
    "AppFirewallSignatureContext",
    "AppFirewallViolationContext",
    "AppFirewallDetectionControl",
    "SimpleWafExclusionRule",
    "WafExclusionInlineRules",
    "WafExclusion",
    "CreateSpecType",
    "CreateRequest",
    "ObjectGetMetaType",
    "DNSRecord",
    "AutoCertInfoType",
    "DnsInfo",
    "ServiceDomain",
    "GetSpecType",
    "InitializerType",
    "StatusType",
    "InitializersType",
    "ViewRefType",
    "SystemObjectGetMetaType",
    "CreateResponse",
    "DeleteRequest",
    "GetCDNSecurityConfigReq",
    "ObjectReplaceMetaType",
    "ReplaceSpecType",
    "ReplaceRequest",
    "CDNSiteStatus",
    "CDNControllerStatus",
    "ConditionType",
    "StatusMetaType",
    "DNSVHostStatusType",
    "StatusObject",
    "GetResponse",
    "LilacCDNMetricsFilter",
    "LilacCDNMetricsRequest",
    "LilacCDNMetricsResponseGroupBy",
    "LilacCDNMetricsResponseValue",
    "LilacCDNMetricsResponseSeries",
    "LilacCDNMetricsResponseData",
    "LilacCDNMetricsResponse",
    "ProtobufAny",
    "ErrorType",
    "ListResponseItem",
    "ListResponse",
    "ReplaceResponse",
    "SubscribeRequest",
    "SubscribeResponse",
    "UnsubscribeRequest",
    "UnsubscribeResponse",
    "GetServiceOperationReq",
    "PurgeOperationItem",
    "ServiceOperationItem",
    "GetServiceOperationRsp",
    "LilacCDNCachePurgeRequest",
    "LilacCDNCachePurgeResponse",
    "ServiceOperationsTimeRange",
    "ListServiceOperationsReq",
    "ServiceOperationsItem",
    "ListServiceOperationsRsp",
    "DeleteDoSAutoMitigationRuleRsp",
    "Destination",
    "GetSpecType",
    "DoSMitigationRuleInfo",
    "GetDoSAutoMitigationRulesRsp",
    "GetSecurityConfigRsp",
    "Spec",
]
