# This file was auto-generated by Fern from our API Definition.

import typing

EntitlementValueType = typing.Union[
    typing.Literal["boolean", "credit", "numeric", "trait", "unknown", "unlimited"], typing.Any
]
