# This file was auto-generated by Fern from our API Definition.

import typing

RulesengineCompanyMetricPeriod = typing.Union[
    typing.Literal["all_time", "current_day", "current_month", "current_week"], typing.Any
]
