RECIPES = {
    "amethyst boiler": (
        (("steam fluid", 10), (("water fluid", 10), ("purple mana", 1))),
    ),
    "burner drill": (
        (("amethyst", 1), (("fuel", 4), ("quartz", 1), ("amethyst mineable", 1))),
        (("amethyst", 2), (("fuel", 16), ("quartz", 2), ("amethyst mineable", 1))),
        (("coal", 1), (("fuel", 2), ("coal mineable", 1))),
        (("coal", 2), (("fuel", 8), ("coal mineable", 1))),
        (("raw copper", 1), (("fuel", 4), ("copper mineable", 1))),
        (("raw copper", 2), (("fuel", 16), ("copper mineable", 1))),
    ),
    "caelium sieve": (
        (("caelium leaf sift", 1), (("caelium leaf", 1), ("water fluid", 1))),
        (("coal leaf sift", 1), (("coal leaf", 1), ("water fluid", 1))),
        (("copper leaf sift", 1), (("copper leaf", 1), ("water fluid", 1))),
        (("tin leaf sift", 1), (("tin leaf", 1), ("water fluid", 1))),
        (("raw caelium", 1), (("caelium acorn", 1), ("water fluid", 1))),
        (("coal", 4), (("coal acorn", 1), ("water fluid", 1))),
        (("raw copper", 4), (("copper acorn", 1), ("water fluid", 1))),
        (("raw tin", 4), (("tin acorn", 1), ("water fluid", 1))),
    ),
    "campfire": (
        (("brick", 2), (("clay", 1),)),
        (("copper needle", 1), (("raw copper", 2),)),
        (("glass", 1), (("sand", 3),)),
        (("mushroom stew", 2), (("carrot", 1), ("mushroom", 3), ("water", 2))),
        (("roasted mushroom", 1), (("mushroom", 1), ("stick", 1))),
        (("roasted rabbit meat", 1), (("rabbit meat", 1),)),
        (("stone", 1), (("rock", 1),)),
        (("torch", 1), (("stick", 1), ("coal", 1))),
        (("water", 1), (("bowl", 1), ("ice", 1))),
    ),
    "composter": (
        (("dirt", 1), (("compost", 4),)),
        (("fertilizer", 1), (("compost", 12), ("dirt", 1))),
        (("pebble", 1), (("compost", 6),)),
        (("flint", 1), (("compost", 10), ("pebble", 1))),
        (("moist dirt", 2), (("fertilizer", 1), ("dirt", 2), ("water", 1))),
    ),
    "copper anvil": (
        (("burner drill", 1), (("copper ingot", 2), ("copper gear", 1), ("rock pickaxe", 1))),
        (("copper axe", 1), (("handle", 1), ("slime crystal", 2), ("copper ingot", 3))),
        (("copper constructor", 1), (("copper sheet", 1), ("copper shaft", 1), ("copper gear", 2), ("tin ingot", 4))),
        (("copper gear", 1), (("copper ingot", 4),)),
        (("copper hammer", 1), (("handle", 2), ("slime crystal", 2), ("copper ingot", 5))),
        (("copper pickaxe", 1), (("handle", 1), ("slime crystal", 2), ("copper ingot", 3))),
        (("copper press", 1), (("copper block", 1), ("copper shaft", 1), ("tin ingot", 1))),
        (("copper shaft", 2), (("copper ingot", 3),)),
        (("copper shovel", 1), (("handle", 1), ("slime crystal", 1), ("copper ingot", 2))),
        (("copper sword", 1), (("handle", 1), ("slime crystal", 1), ("ice", 1), ("copper ingot", 3))),
        (("life crystal", 1), (("slime crystal", 2), ("copper ingot", 3), ("ice", 1))),
        (("rail 0", 4), (("copper shaft", 1), ("pebble", 1), ("wood fence 0", 1))),
        (("slime summon", 1), (("slime crystal", 3), ("life crystal", 1))),
    ),
    "copper boiler": (
        (("steam fluid", 5), (("water fluid", 5), ("fuel", 16))),
    ),
    "copper constructor": (
        (("copper boiler", 1), (("copper tank", 3), ("copper pipe 0", 5), ("tin ingot", 2))),
        (("copper gear", 1), (("copper ingot", 3),)),
        (("copper pipe 0", 2), (("copper sheet", 2), ("copper ingot", 1))),
        (("copper pump 0", 1), (("copper pipe 0", 1), ("copper gear", 1))),
        (("copper shaft", 1), (("copper ingot", 1),)),
        (("copper tank", 1), (("copper sheet", 4), ("copper shaft", 1))),
        (("copper wrench", 1), (("copper gear", 1), ("copper shaft", 1))),
    ),
    "copper press": (
        (("copper sheet", 1), (("copper ingot", 1), ("fuel", 8))),
    ),
    "dye bench": (
        (("blue dye", 1), (("bluebell", 1),)),
        (("brown dye", 1), (("mushroom", 2),)),
        (("purple dye", 1), (("bluebell", 1), ("amethyst", 1))),
        (("white dye", 1), (("quartz", 1),)),
    ),
    "furnace": (
        (("caelium ingot", 1), (("raw caelium", 1), ("fuel", 16))),
        (("coal", 1), (("log", 1), ("fuel", 2))),
        (("copper ingot", 1), (("raw copper", 1), ("fuel", 6))),
        (("glass", 1), (("sand", 2), ("fuel", 4))),
        (("pure crystal", 1), (("quartz", 1), ("fuel", 8))),
        (("slime crystal", 1), (("slime ball", 1), ("fuel", 8))),
        (("tin ingot", 1), (("raw tin", 1), ("fuel", 12))),
    ),
    "mana converter": (
        (("amethyst", 1), (("quartz", 1), ("mana", 1)), 1),
        (("amethyst boiler", 1), (("citrine rune", 2), ("amethyst pipe 0", 5), ("tin ingot", 2)), 5),
        (("amethyst dirt", 2), (("fertilizer", 1), ("moist dirt", 2), ("amethyst", 1)), 4),
        (("amethyst pipe 0", 2), (("citrine", 1), ("amethyst", 1)), 3),
        (("amethyst pump 0", 1), (("amethyst pipe 0", 1), ("amethyst rune", 1)), 3),
        (("amethyst wrench", 1), (("citrine", 1), ("amethyst rune", 1)), 3),
        (("citrine", 1), (("amethyst", 1), ("mana", 1)), 2),
        (("mana", 2), (), 1),
        (("mana converter", 1), (("purple mana", 1), ("quartz", 1), ("amethyst", 1), ("citrine", 1)), 5),
        (("purple mana", 2), (("mana", 7), ("purple dye", 2)), 3),
        (("slime summon", 1), (("slime crystal", 3), ("life crystal", 1)), 1),
    ),
    "manual press": (
        (("blue dye", 1), (("bluebell", 1), ("bowl", 1))),
        (("copper pit", 1), (("raw copper", 1), ("flint shovel", 1), ("coal", 1), ("clay", 1))),
        (("package", 1), (("paper", 4), ("water", 1))),
        (("paper", 1), (("wood", 2),)),
        (("rock", 1), (("pebble", 3),)),
        (("sand", 1), (("pebble", 2),)),
        (("water axe", 1), (("handle", 1), ("water", 3), ("rabbit fur", 1))),
        (("water hammer", 1), (("handle", 2), ("water", 5), ("rabbit fur", 2))),
        (("water pickaxe", 1), (("handle", 1), ("water", 3), ("rabbit fur", 1))),
        (("water shovel", 1), (("handle", 1), ("water", 2), ("rabbit fur", 1))),
        (("water sword", 1), (("handle", 1), ("water", 3), ("slime ball", 2), ("rabbit fur", 1))),
    ),
    "masonry bench": (
        (("amethyst brick", 2), (("amethyst", 1), ("stone brick", 2))),
        (("amethyst brick floor", 2), (("amethyst brick", 1))),
        (("brick floor", 2), (("brick", 1),)),
        (("copper anvil", 1), (("copper block", 1), ("copper ingot", 2))),
        (("copper brick", 2), (("copper ingot", 1), ("stone brick", 2))),
        (("copper brick floor", 2), (("copper brick", 1),)),
        (("copper door", 1), (("copper brick", 1), ("copper brick floor", 1))),
        (("furnace", 1), (("copper ingot", 6), ("stone brick", 8))),
        (("glass key", 1), (("glass", 3), ("coal", 1), ("handle", 1))),
        (("lavastone brick", 1), (("lavastone", 1),)),
        (("lavastone brick floor", 2), (("lavastone brick", 1),)),
        (("lavastone floor", 2), (("lavastone", 1),)),
        (("rock axe", 1), (("handle", 1), ("rock", 4))),
        (("rock hammer", 1), (("handle", 2), ("rock", 6))),
        (("rock pickaxe", 1), (("handle", 1), ("rock", 4))),
        (("rock shovel", 1), (("handle", 1), ("rock", 3))),
        (("rock sword", 1), (("handle", 1), ("ice", 1), ("rock", 4))),
        (("stone brick", 1), (("stone", 1),)),
        (("stone brick floor", 2), (("stone brick", 1),)),
        (("stone floor", 2), (("stone", 1),)),
    ),
    "mushroom shaper": (
        (("bluebell jar", 1), (("brick", 1), ("dirt", 2), ("bluebell", 1), ("glass", 1))),
        (("composter", 1), (("mushroom", 2), ("paper", 2), ("small barrel", 1))),
        (("mushroom block", 1), (("mushroom", 2), ("wood", 1))),
        (("mushroom door", 1), (("mushroom floor", 1), ("mushroom block", 1))),
        (("mushroom floor", 2), (("mushroom block", 1),)),
        (("mushroom table", 1), (("mushroom floor", 4), ("stick", 4))),
        (("plant bouquet", 1), (("bluebell", 1), ("carrot", 1), ("sapling", 1), ("spore", 1))),
    ),
    "obelisk piece": (
        (("amethyst", 1), (("quartz", 2), ("mana", 1)), 1),
        (("citrine", 1), (("amethyst", 2), ("mana", 1)), 2),
        (("mana", 1), (), 1),
        (("purple mana", 1), (("mana", 5), ("purple dye", 1)), 3),
        (("slime summon", 1), (("slime crystal", 3), ("life crystal", 1)), 1),
    ),
    "packager bench": (
        (("amethyst", 8), (("amethyst block", 1),)),
        (("amethyst block", 1), (("amethyst", 8),)),
        (("amethyst rune", 1), (("amethyst", 4), ("stone brick floor", 2))),
        (("citrine", 8), (("citrine block", 1),)),
        (("citrine block", 1), (("citrine", 8),)),
        (("citrine rune", 1), (("citrine", 4), ("amethyst rune", 2))),
        (("coal", 8), (("coal block", 1),)),
        (("coal block", 1), (("coal", 8),)),
        (("copper block", 1), (("copper ingot", 8),)),
        (("copper ingot", 8), (("copper block", 1),)),
        (("gift", 1), (("package", 1), ("coal", 1))),
        (("lava rune", 1), (("lava", 2), ("purple mana", 4), ("citrine rune", 2))),
        (("quartz block", 1), (("quartz", 8),)),
        (("quartz", 8), (("quartz block", 1),)),
    ),
    "player": (
        (("snowball", 4), (("snow", 1),)),
        (("stick", 4), (("wood", 2),)),
        (("wood", 2), (("log", 1),)),
        (("wood door", 1), (("wood floor", 1), ("wood", 1))),
        (("wood floor", 2), (("wood", 1),)),
        (("workbench", 1), (("flint", 1), ("wood", 4))),
    ),
    "quartz altar": (
        (("amethyst axe", 1), (("handle", 1), ("amethyst", 3), ("pure crystal", 1))),
        (("amethyst hammer", 1), (("handle", 2), ("amethyst", 5), ("pure crystal", 2))),
        (("amethyst pickaxe", 1), (("handle", 1), ("amethyst", 3), ("pure crystal", 1))),
        (("amethyst shovel", 1), (("handle", 1), ("amethyst", 2), ("pure crystal", 1))),
        (("amethyst sword", 1), (("handle", 1), ("amethyst", 3), ("slime ball", 2), ("pure crystal", 1))),
        (("life crystal", 1), (("pure crystal", 2), ("amethyst", 3), ("slime ball", 1))),
        (("mana converter", 1), (("obelisk piece", 1), ("purple mana", 1))),
        (("quartz child", 1), (("glass", 5), ("life crystal", 1))),
    ),
    "sawbench": (
        (("bookshelf", 1), (("paper", 3), ("wood", 2))),
        (("handle", 1), (("blue dye", 1), ("stick", 4))),
        (("log floor", 2), (("log", 1),)),
        (("mushroom shaper", 1), (("composter", 1), ("mushroom", 12))),
        (("small barrel", 1), (("stick", 4), ("wood", 6))),
        (("small crate", 1), (("stick", 4), ("wood", 6))),
        (("stick", 2), (("wood", 1),)),
        (("wood crucible", 1), (("small barrel", 1), ("log", 2))),
        (("wood fence 0", 1), (("wood", 1), ("stick", 2))),
        (("wooden bed", 1), (("blue dye", 3), ("rabbit fur", 2), ("wood", 10))),
        (("wooden sieve", 1), (("thread", 3), ("small barrel", 1))),
        (("wooden table", 1), (("wood floor", 4), ("stick", 4))),
    ),
    "sewbench": (
        (("anklet of the tree", 1), (("acorn", 1), ("thread", 2), ("log", 1), ("brown dye", 1))),
        (("boots", 1), (("thread", 4), ("brown dye", 1))),
        (("small backpack", 1), (("thread", 4), ("white dye", 1))),
        (("thread", 1), (("rabbit fur", 1), ("stick", 1))),
    ),
    "slime shaper": (
        (("slime block", 2), (("slime crystal", 1), ("wood", 2))),
        (("slime door", 1), (("slime floor", 1), ("slime block", 1))),
        (("slime floor", 2), (("slime block", 1),)),
        (("slime table", 1), (("slime floor", 4), ("stick", 4))),
    ),
    "tree constructor": (
        (("sapling", 1), (("wood", 1), ("stick", 2))),
        (("coal sapling", 1), (("sapling", 1), ("handle", 1), ("slime ball", 2))),
        (("copper sapling", 1), (("coal sapling", 1), ("glass key", 1), ("amethyst", 2))),
        (("tin sapling", 1), (("copper sapling", 1), ("burner drill", 1), ("slime block", 2))),
        (("caelium sapling", 1), (("sapling", 1), ("coal sapling", 1), ("copper sapling", 1), ("tin sapling", 1))),
    ),
    "void converter": (
        (("sapling", 1), (("log", 1), ("wood", 1))),
        (("rabbit child", 1), (("blue dye", 1), ("carrot", 4))),
        (("tree constructor", 1), (("sapling", 4), ("small crate", 1))),
        (("quartz altar", 1), (("glass key", 1), ("stone", 4))),
        (("caelium sieve", 1), (("caelium leaf", 1), ("wooden sieve", 1))),
    ),
    "wood crucible": (
        (("water", 1), (("fuel", 4),)),
        (("slime ball", 1), (("fuel", 10), ("water fluid", 4))),
    ),
    "wooden sieve": (
        (("basic sift", 1), (("rock", 1), ("water fluid", 2))),
        (("leaf sift", 1), (("leaf", 1), ("water fluid", 1))),
    ),
    "workbench": (
        (("bowl", 1), (("stick", 1), ("wood", 1))),
        (("campfire", 1), (("flint", 2), ("stick", 6), ("wood", 4))),
        (("dye bench", 1), (("manual press", 1), ("blue dye", 1))),
        (("flint axe", 1), (("flint", 2), ("stick", 3))),
        (("flint hammer", 1), (("flint", 4), ("stick", 4))),
        (("flint pickaxe", 1), (("flint", 2), ("stick", 3))),
        (("flint shovel", 1), (("flint", 1), ("stick", 2))),
        (("flint sword", 1), (("flint", 1), ("ice", 1), ("stick", 2))),
        (("manual press", 1), (("flint hammer", 1), ("workbench", 1))),
        (("masonry bench", 1), (("flint pickaxe", 2), ("rock", 1), ("workbench", 1))),
        (("packager bench", 1), (("package", 1), ("masonry bench", 1))),
        (("sawbench", 1), (("flint axe", 2), ("rock", 1), ("workbench", 1))),
        (("sewbench", 1), (("copper needle", 1), ("rabbit fur", 2), ("workbench", 1))),
    ),
}
