from ..render import FPS


FLOOR = {
    "amethyst brick floor",
    "amethyst dirt",
    "amethyst mineable",
    "amethyst rune",
    "brick floor",
    "citrine rune",
    "coal mineable",
    "copper brick floor",
    "copper door",
    "copper door open",
    "copper mineable",
    "copper pit",
    "dirt",
    "ice",
    "lava",
    "lava rune",
    "lavastone brick floor",
    "lavastone floor",
    "log floor",
    "moist dirt",
    "mushroom door",
    "mushroom door open",
    "mushroom floor",
    "pebble",
    "rail 0",
    "rail 1",
    "rail 2",
    "rail 3",
    "rail 4",
    "rail 5",
    "sand",
    "slime door",
    "slime door open",
    "slime floor",
    "snow",
    "stone brick floor",
    "stone floor",
    "void",
    "water",
    "wood door",
    "wood door open",
    "wood floor",
}
FLOOR_TYPE = {
    "amethyst mineable": "block",
    "copper pit": "tile",
    "ice": "block",
    "lava": "fluid",
    "void": "block",
    "water": "fluid",
}
FLOOR_DAMAGE = {
    "lava": 3,
    "water": 1,
}
SOIL_STRENGTH = {
    "snow": 0.85,
    "dirt": 1,
    "moist dirt": 1.25,
    "amethyst dirt": 1.4,
}
GROW_TIME = {
    "amethyst mineable": 120,
    "bluebell": 400,
    "caelium sapling": 200,
    "caelium treeling": 250,
    "carrot": 160,
    "coal sapling": 200,
    "coal treeling": 250,
    "copper pit": 600,
    "copper sapling": 200,
    "copper treeling": 250,
    "furless rabbit": 120,
    "lava": 150,
    "potato": 240,
    "quartz child": 40,
    "rabbit child": 200,
    "sapling": 80,
    "slime summon": 40,
    "spore": 120,
    "tin sapling": 200,
    "tin treeling": 250,
    "treeling": 100,
    "water": 60,
}
GROW_TILES = {
    "amethyst mineable": {"kind": "amethyst"},
    "bluebell": {"kind": "bluebell grown", "inventory": {"bluebell": 2}},
    "caelium sapling": {"kind": "caelium treeling", "inventory": {"caelium sapling": 1, "log": 1}},
    "caelium treeling": {"kind": "caelium tree", "inventory": {"caelium sapling": 1, "log": 2}},
    "carrot": {"kind": "carrot grown", "inventory": {"carrot": 2}},
    "coal sapling": {"kind": "coal treeling", "inventory": {"coal": 1, "coal sapling": 1, "log": 1}},
    "coal treeling": {"kind": "coal tree", "inventory": {"coal": 3, "coal sapling": 1, "log": 1}},
    "copper pit": {"kind": "copper pit grown", "inventory": {"copper ingot": 1}},
    "copper sapling": {"kind": "copper treeling", "inventory": {"raw copper": 1, "copper sapling": 1, "log": 1}},
    "copper treeling": {"kind": "copper tree", "inventory": {"raw copper": 2, "copper ingot": 1, "copper sapling": 1, "log": 2}},
    "furless rabbit": {"kind": "rabbit adult", "inventory": {"rabbit fur": 1, "rabbit meat": 1}},
    "lava": {"floor": "lavastone floor", "kind": "lavastone"},
    "potato": {"kind": "potato grown", "inventory": {"potato": 2}},
    "quartz child": {"kind": "quartz adult"},
    "rabbit child": {"kind": "rabbit adult", "inventory": {"rabbit fur": 1, "rabbit meat": 1}},
    "sapling": {"kind": "treeling", "inventory": {"sapling": 1, "log": 1}},
    "slime summon": {"kind": "slime prince", "inventory": {"slife crystal": 1, "slime shaper": 1}},
    "spore": {"kind": "mushroom", "inventory": {"spore": 2}},
    "tin sapling": {"kind": "tin treeling", "inventory": {"raw tin": 1, "tin sapling": 1, "log": 1}},
    "tin treeling": {"kind": "tin tree", "inventory": {"raw tin": 2, "tin ingot": 1, "tin sapling": 1, "log": 2}},
    "treeling": {"kind": "tree", "inventory": {"sapling": 2, "log": 2}},
    "water": {"floor": "ice"},
}
GROW_REQUIREMENT = {
    "bluebell": 1.25,
    "caelium sapling": 1.4,
    "caelium treeling": 1.5,
    "copper treeling": 1.25,
    "tin sapling": 1.25,
    "tin treeling": 1.4,
}
GROW_DIRT_IGNORE = {
    "furless rabbit",
    "quartz child",
    "rabbit child",
    "slime summon",
}
GROW_FLOOR_DELETE = {"copper pit"}
MULTI_TILES = {
    "amethyst boiler": (3, 2),
    "copper boiler": (3, 2),
    "copper constructor": (2, 2),
    "destroyed obelisk": (1, 2),
    "dye bench": (2, 1),
    "furnace": (2, 2),
    "manual press": (2, 1),
    "masonry bench": (2, 1),
    "obelisk": (1, 2),
    "packager bench": (2, 1),
    "sawbench": (2, 1),
    "sewbench": (2, 1),
    "wooden bed": (1, 2),
}
PROCESSING_TIME = {
    "amethyst boiler": 5 * FPS,
    "burner drill": 30 * FPS,
    "caelium sieve": 15 * FPS,
    "composter": 2 * FPS,
    "copper boiler": 5 * FPS,
    "copper press": 20 * FPS,
    "furnace": 10 * FPS,
    "mana converter": 15 * FPS,
    "obelisk piece": 10 * FPS,
    "wood crucible": 60 * FPS,
    "wooden sieve": 15 * FPS,
}
STORAGE = {
    "destroyed void crate": (6, 64),
    "small barrel": (1, 512),
    "small crate": (8, 64),
    "void crate": (8, 64),
}
UNBREAK = {
    "amethyst mineable",
    "coal mineable",
    "copper mineable",
    "copper pit",
    "destroyed obelisk",
    "destroyed void crate",
    "glass lock",
    "left",
    "obelisk",
    "slime summon",
    "up",
    "void",
    "void converter",
    "void crate",
}
MODIFICATIONS = {
    "amethyst pipe": 2,
    "amethyst pump": 2,
    "copper pipe": 2, 
    "copper pump": 2,
    "rail": 6,
    "wood fence": 3,
}
SHEARABLE = {
    "caelium tree": ("caelium leaf", 2, {"kind": "log", "inventory": {"log": 1}}),
    "caelium treeling": ("caelium leaf", 1, {"kind": "log", "inventory": {}}),
    "coal tree": ("coal leaf", 2, {"kind": "log", "inventory": {"log": 1}}),
    "coal treeling": ("coal leaf", 1, {"kind": "log", "inventory": {}}),
    "copper tree": ("copper leaf", 2, {"kind": "log", "inventory": {"log": 1}}),
    "copper treeling": ("copper leaf", 1, {"kind": "log", "inventory": {}}),
    "obelisk": ("obelisk piece", 1, {"kind": "destroyed obelisk"}),
    "quartz adult": ("quartz", 1, {"kind": "quartz child"}),
    "rabbit adult": ("rabbit fur", 1, {"kind": "furless rabbit", "inventory": {"rabbit meat": 1}}),
    "tin tree": ("tin leaf", 2, {"kind": "log", "inventory": {"log": 1}}),
    "tin treeling": ("tin leaf", 1, {"kind": "log", "inventory": {}}),
    "tree": ("leaf", 2, {"kind": "log", "inventory": {"log": 1}}),
    "treeling": ("leaf", 1, {"kind": "log", "inventory": {}}),
    "void crate": ("obelisk piece", 1, {"kind": "destroyed void crate"}),
}
RUNES = {
    "amethyst rune": (0, 1),
    "citrine rune": (0, 2),
    "lava rune": (1, 0.8, 5)
}
RUNES_USER = {
    "mana converter": 2,
    "obelisk piece": 1,
}