"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CheckpointingTypeTypedDict(TypedDict):
    enabled: NotRequired[bool]
    r"""Resume processing files after an interruption"""
    retries: NotRequired[float]
    r"""The number of times to retry processing when a processing error occurs. If Skip file on error is enabled, this setting is ignored."""


class CheckpointingType(BaseModel):
    enabled: Optional[bool] = False
    r"""Resume processing files after an interruption"""

    retries: Optional[float] = 5
    r"""The number of times to retry processing when a processing error occurs. If Skip file on error is enabled, this setting is ignored."""
