from typing import Any

class QueryOptions:
    params: dict[str, Any]
    def __init__(self, **kwargs) -> None: ...
    def set_context(self, operation: str | None = None, output_format: str | None = None): ...
    def contextual_validate(self) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def __getitem__(self, key): ...
    def to_query_string(self) -> str: ...
    @classmethod
    def from_query_string(cls, qs: str) -> QueryOptions: ...
    def items(self): ...
