from .correlations import (
    add_correlation,
    add_correlation_with_telemetry,
    get_correlation,
    get_correlations_by_channel,
    get_correlations_by_task_and_action,
    update_correlation,
)
from .deferral import get_deferral_report_context, save_deferral_report_mapping

# Backwards compatibility - DSAR functions now use universal tickets table
from .dsar import (
    create_dsar_ticket,
    get_dsar_ticket,
    list_dsar_tickets_by_email,
    list_dsar_tickets_by_status,
    update_dsar_ticket_status,
)
from .graph import (
    add_graph_edge,
    add_graph_node,
    delete_graph_edge,
    delete_graph_node,
    get_all_graph_nodes,
    get_edges_for_node,
    get_graph_node,
    get_nodes_by_type,
)
from .identity import (
    get_identity_for_context,
    retrieve_agent_identity,
    store_agent_identity,
    store_creation_ceremony,
    update_agent_identity,
)
from .queue_status import QueueStatus, get_queue_status
from .tasks import (
    add_task,
    clear_task_images,
    count_tasks,
    delete_tasks_by_ids,
    get_all_tasks,
    get_pending_tasks_for_activation,
    get_recent_completed_tasks,
    get_task_by_id,
    get_tasks_by_status,
    get_tasks_older_than,
    get_top_tasks,
    task_exists,
    update_task_context_and_signing,
    update_task_status,
)
from .thoughts import (
    add_thought,
    async_get_thought_by_id,
    async_get_thought_status,
    async_get_thoughts_by_ids,
    count_thoughts,
    delete_thoughts_by_ids,
    get_thought_by_id,
    get_thoughts_by_ids,
    get_thoughts_by_status,
    get_thoughts_by_task_id,
    get_thoughts_older_than,
    update_thought_status,
)
from .tickets import (
    create_ticket,
    delete_ticket,
    get_ticket,
    get_tickets_by_correlation_id,
    list_tickets,
    update_ticket_metadata,
    update_ticket_status,
)

__all__ = [
    "update_task_status",
    "task_exists",
    "add_task",
    "clear_task_images",
    "get_all_tasks",
    "get_task_by_id",
    "get_tasks_by_status",
    "get_recent_completed_tasks",
    "get_top_tasks",
    "get_pending_tasks_for_activation",
    "count_tasks",
    "delete_tasks_by_ids",
    "get_tasks_older_than",
    "update_task_context_and_signing",
    "add_thought",
    "get_thought_by_id",
    "async_get_thought_by_id",
    "async_get_thought_status",
    "async_get_thoughts_by_ids",
    "get_thoughts_by_ids",
    "update_thought_status",
    "get_thoughts_by_status",
    "get_thoughts_older_than",
    "get_thoughts_by_task_id",
    "count_thoughts",
    "delete_thoughts_by_ids",
    "save_deferral_report_mapping",
    "get_deferral_report_context",
    "add_graph_node",
    "get_graph_node",
    "get_all_graph_nodes",
    "get_nodes_by_type",
    "delete_graph_node",
    "add_graph_edge",
    "delete_graph_edge",
    "get_edges_for_node",
    "add_correlation",
    "add_correlation_with_telemetry",
    "update_correlation",
    "get_correlation",
    "get_correlations_by_task_and_action",
    "get_correlations_by_channel",
    "store_agent_identity",
    "retrieve_agent_identity",
    "update_agent_identity",
    "store_creation_ceremony",
    "get_identity_for_context",
    "get_queue_status",
    "QueueStatus",
    # Universal tickets (new)
    "create_ticket",
    "get_ticket",
    "update_ticket_status",
    "update_ticket_metadata",
    "list_tickets",
    "delete_ticket",
    "get_tickets_by_correlation_id",
    # DSAR backwards compatibility (deprecated - use tickets)
    "create_dsar_ticket",
    "get_dsar_ticket",
    "update_dsar_ticket_status",
    "list_dsar_tickets_by_status",
    "list_dsar_tickets_by_email",
]
