from __future__ import annotations
import pxr.UsdSkel._usdSkel
import typing
import Boost.Python
import pxr.Usd
import pxr.UsdGeom

__all__ = [
    "AnimMapper",
    "AnimQuery",
    "Animation",
    "ApplyBlendShape",
    "BakeSkinning",
    "Binding",
    "BindingAPI",
    "BlendShape",
    "BlendShapeQuery",
    "Cache",
    "ComputeJointLocalTransforms",
    "ComputeJointsExtent",
    "ConcatJointTransforms",
    "DecomposeTransform",
    "DecomposeTransforms",
    "ExpandConstantInfluencesToVarying",
    "InbetweenShape",
    "InterleaveInfluences",
    "IsSkelAnimationPrim",
    "IsSkinnablePrim",
    "MakeTransform",
    "MakeTransforms",
    "NormalizeWeights",
    "ResizeInfluences",
    "Root",
    "Skeleton",
    "SkeletonQuery",
    "SkinNormals",
    "SkinNormalsLBS",
    "SkinPoints",
    "SkinPointsLBS",
    "SkinTransform",
    "SkinTransformLBS",
    "SkinningQuery",
    "SortInfluences",
    "Tokens",
    "Topology"
]


class AnimMapper(Boost.Python.instance):
    @staticmethod
    def IsIdentity(*args, **kwargs) -> None: ...
    @staticmethod
    def IsNull(*args, **kwargs) -> None: ...
    @staticmethod
    def IsSparse(*args, **kwargs) -> None: ...
    @staticmethod
    def Remap(*args, **kwargs) -> None: ...
    @staticmethod
    def RemapTransforms(*args, **kwargs) -> None: ...
    pass
class AnimQuery(Boost.Python.instance):
    @staticmethod
    def BlendShapeWeightsMightBeTimeVarying(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeBlendShapeWeights(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeJointLocalTransformComponents(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeJointLocalTransforms(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBlendShapeOrder(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBlendShapeWeightTimeSamples(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBlendShapeWeightTimeSamplesInInterval(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointOrder(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointTransformTimeSamples(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointTransformTimeSamplesInInterval(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def JointTransformsMightBeTimeVarying(*args, **kwargs) -> None: ...
    pass
class Animation(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateBlendShapeWeightsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateBlendShapesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateJointsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateRotationsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateScalesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateTranslationsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Define(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBlendShapeWeightsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBlendShapesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetRotationsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetScalesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTransforms(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTranslationsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def SetTransforms(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class Binding(Boost.Python.instance):
    @staticmethod
    def GetSkeleton(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSkinningTargets(*args, **kwargs) -> None: ...
    __instance_size__ = 88
    pass
class BindingAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> None: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateAnimationSourceRel(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateBlendShapeTargetsRel(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateBlendShapesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateGeomBindTransformAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateJointIndicesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateJointIndicesPrimvar(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateJointWeightsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateJointWeightsPrimvar(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateJointsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateSkeletonRel(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateSkinningMethodAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAnimationSource(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAnimationSourceRel(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBlendShapeTargetsRel(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBlendShapesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetGeomBindTransformAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetInheritedAnimationSource(*args, **kwargs) -> None: ...
    @staticmethod
    def GetInheritedSkeleton(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointIndicesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointIndicesPrimvar(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointWeightsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointWeightsPrimvar(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSkeleton(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSkeletonRel(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSkinningMethodAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def SetRigidJointInfluence(*args, **kwargs) -> None: ...
    @staticmethod
    def ValidateJointIndices(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 56
    pass
class BlendShape(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateInbetween(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateNormalOffsetsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateOffsetsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreatePointIndicesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Define(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAuthoredInbetweens(*args, **kwargs) -> None: ...
    @staticmethod
    def GetInbetween(*args, **kwargs) -> None: ...
    @staticmethod
    def GetInbetweens(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNormalOffsetsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetOffsetsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPointIndicesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def HasInbetween(*args, **kwargs) -> None: ...
    @staticmethod
    def ValidatePointIndices(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class BlendShapeQuery(Boost.Python.instance):
    @staticmethod
    def ComputeBlendShapePointIndices(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeDeformedPoints(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeSubShapePointOffsets(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeSubShapeWeights(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBlendShape(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBlendShapeIndex(*args, **kwargs) -> None: ...
    @staticmethod
    def GetInbetween(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNumBlendShapes(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNumSubShapes(*args, **kwargs) -> None: ...
    __instance_size__ = 128
    pass
class Cache(Boost.Python.instance):
    @staticmethod
    def Clear(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeSkelBinding(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeSkelBindings(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAnimQuery(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSkelQuery(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSkinningQuery(*args, **kwargs) -> None: ...
    @staticmethod
    def Populate(*args, **kwargs) -> None: ...
    __instance_size__ = 40
    pass
class InbetweenShape(Boost.Python.instance):
    @staticmethod
    def CreateNormalOffsetsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNormalOffsets(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNormalOffsetsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetOffsets(*args, **kwargs) -> None: ...
    @staticmethod
    def GetWeight(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredWeight(*args, **kwargs) -> None: ...
    @staticmethod
    def IsDefined(*args, **kwargs) -> None: ...
    @staticmethod
    def IsInbetween(*args, **kwargs) -> None: ...
    @staticmethod
    def SetNormalOffsets(*args, **kwargs) -> None: ...
    @staticmethod
    def SetOffsets(*args, **kwargs) -> None: ...
    @staticmethod
    def SetWeight(*args, **kwargs) -> None: ...
    __instance_size__ = 56
    pass
class Root(pxr.UsdGeom.Boundable, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Define(*args, **kwargs) -> None: ...
    @staticmethod
    def Find(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class Skeleton(pxr.UsdGeom.Boundable, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateBindTransformsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateJointNamesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateJointsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateRestTransformsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Define(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBindTransformsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointNamesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetRestTransformsAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class SkeletonQuery(Boost.Python.instance):
    @staticmethod
    def ComputeJointLocalTransforms(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeJointRestRelativeTransforms(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeJointSkelTransforms(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeJointWorldTransforms(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeSkinningTransforms(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAnimQuery(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointOrder(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointWorldBindTransforms(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMapper(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSkeleton(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTopology(*args, **kwargs) -> None: ...
    @staticmethod
    def HasBindPose(*args, **kwargs) -> None: ...
    @staticmethod
    def HasRestPose(*args, **kwargs) -> None: ...
    pass
class SkinningQuery(Boost.Python.instance):
    @staticmethod
    def ComputeExtentsPadding(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeJointInfluences(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeSkinnedPoints(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeSkinnedTransform(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeVaryingJointInfluences(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBlendShapeMapper(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBlendShapeOrder(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBlendShapeTargetsRel(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBlendShapesAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetGeomBindTransform(*args, **kwargs) -> None: ...
    @staticmethod
    def GetGeomBindTransformAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetInterpolation(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointIndicesPrimvar(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointMapper(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointOrder(*args, **kwargs) -> None: ...
    @staticmethod
    def GetJointWeightsPrimvar(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMapper(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNumInfluencesPerComponent(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSkinningMethod(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSkinningMethodAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTimeSamples(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTimeSamplesInInterval(*args, **kwargs) -> None: ...
    @staticmethod
    def HasBlendShapes(*args, **kwargs) -> None: ...
    @staticmethod
    def HasJointInfluences(*args, **kwargs) -> None: ...
    @staticmethod
    def IsRigidlyDeformed(*args, **kwargs) -> None: ...
    __instance_size__ = 424
    pass
class Tokens(Boost.Python.instance):
    BlendShape = 'BlendShape'
    SkelAnimation = 'SkelAnimation'
    SkelBindingAPI = 'SkelBindingAPI'
    SkelRoot = 'SkelRoot'
    Skeleton = 'Skeleton'
    bindTransforms = 'bindTransforms'
    blendShapeWeights = 'blendShapeWeights'
    blendShapes = 'blendShapes'
    classicLinear = 'classicLinear'
    dualQuaternion = 'dualQuaternion'
    jointNames = 'jointNames'
    joints = 'joints'
    normalOffsets = 'normalOffsets'
    offsets = 'offsets'
    pointIndices = 'pointIndices'
    primvarsSkelGeomBindTransform = 'primvars:skel:geomBindTransform'
    primvarsSkelJointIndices = 'primvars:skel:jointIndices'
    primvarsSkelJointWeights = 'primvars:skel:jointWeights'
    primvarsSkelSkinningMethod = 'primvars:skel:skinningMethod'
    restTransforms = 'restTransforms'
    rotations = 'rotations'
    scales = 'scales'
    skelAnimationSource = 'skel:animationSource'
    skelBlendShapeTargets = 'skel:blendShapeTargets'
    skelBlendShapes = 'skel:blendShapes'
    skelJoints = 'skel:joints'
    skelSkeleton = 'skel:skeleton'
    translations = 'translations'
    weight = 'weight'
    pass
class Topology(Boost.Python.instance):
    @staticmethod
    def GetNumJoints(*args, **kwargs) -> None: ...
    @staticmethod
    def GetParent(*args, **kwargs) -> None: ...
    @staticmethod
    def GetParentIndices(*args, **kwargs) -> None: ...
    @staticmethod
    def IsRoot(*args, **kwargs) -> None: ...
    @staticmethod
    def Validate(*args, **kwargs) -> None: ...
    pass
class _CanApplyResult(Boost.Python.instance):
    @property
    def whyNot(self) -> None:
        """
        :type: None
        """
    __instance_size__ = 64
    pass
def ApplyBlendShape(*args, **kwargs) -> None:
    pass
def BakeSkinning(*args, **kwargs) -> None:
    pass
def ComputeJointLocalTransforms(*args, **kwargs) -> None:
    pass
def ComputeJointsExtent(*args, **kwargs) -> None:
    pass
def ConcatJointTransforms(*args, **kwargs) -> None:
    pass
def DecomposeTransform(*args, **kwargs) -> None:
    """
    Decompose a transform into a (translate,rotate,scale) tuple.

    Decompose a transform into a (translate,rotate,scale) tuple.
    """
def DecomposeTransforms(*args, **kwargs) -> None:
    """
    Decompose a transform array into a (translations,rotations,scales) tuple.

    Decompose a transform array into a (translations,rotations,scales) tuple.
    """
def ExpandConstantInfluencesToVarying(*args, **kwargs) -> None:
    pass
def InterleaveInfluences(*args, **kwargs) -> None:
    pass
def IsSkelAnimationPrim(*args, **kwargs) -> None:
    pass
def IsSkinnablePrim(*args, **kwargs) -> None:
    pass
def MakeTransform(*args, **kwargs) -> None:
    pass
def MakeTransforms(*args, **kwargs) -> None:
    pass
def NormalizeWeights(*args, **kwargs) -> None:
    pass
def ResizeInfluences(*args, **kwargs) -> None:
    pass
def SkinNormals(*args, **kwargs) -> None:
    pass
def SkinNormalsLBS(*args, **kwargs) -> None:
    pass
def SkinPoints(*args, **kwargs) -> None:
    pass
def SkinPointsLBS(*args, **kwargs) -> None:
    pass
def SkinTransform(*args, **kwargs) -> None:
    pass
def SkinTransformLBS(*args, **kwargs) -> None:
    pass
def SortInfluences(*args, **kwargs) -> None:
    pass
__MFB_FULL_PACKAGE_NAME = 'usdSkel'
