from ailingues_core.utils.archive_io import ArchiveType as ArchiveType
from os import PathLike
from rdkit import Chem
from rdkit.Chem import SDMolSupplier as SDMolSupplier
from rdkit.Chem.rdchem import Mol as Mol
from typing import Literal

class SDFLoader:
    @staticmethod
    def closeWarning() -> None: ...
    @staticmethod
    def openWarning() -> None: ...
    @staticmethod
    def __readDataFromFile__(sdfDoc: str | PathLike, startIndex: int = 0, endIndex: int = -1, removeHs: bool = False, sanitize: bool = False, ignore_error: bool = True) -> tuple[list[Chem.Mol], int, int]: ...
    @staticmethod
    def readDataFromFile(sdfDoc: str | PathLike, startIndex: int = 0, endIndex: int = -1, removeHs: bool = False, sanitize: bool = False, ignore_error: bool = True) -> tuple[list[Mol], int, int]: ...
    @staticmethod
    def readDataFromDir(sdfDir: str, recursive: bool = True, ignore_error: bool = True) -> tuple[list[Mol], int, int]: ...
    @staticmethod
    def readDataFromText(sdfText: str, ignore_error: bool = True) -> tuple[list[Mol], int, int]: ...
    @staticmethod
    def splitDataByMarker(sdfText: str, marker: str = '$$$$\n', strict: bool = True, splitType: Literal['Compound', 'Conformer'] = 'Compound') -> dict[str, str] | list[str]: ...
