from ..Base import *
from ..Proxy import *
from ..AcadObject import IAcadObjectCollection as IAcadObjectCollection
from .AcadBlock import AcadBlock as AcadBlock

class AcadBlocks(IAcadObjectCollection):
    def __init__(self, obj) -> None: ...
    def Add(self, InsertionPoint: PyGePoint3d, Name: str) -> AcadBlock: ...
    def Item(self, Index: int) -> AcadBlock: ...
    def __iter__(self): ...
