# This file was auto-generated by Fern from our API Definition.

import typing

PlanChangeSubscriptionAction = typing.Union[
    typing.Literal["downgrade", "invalid", "subscribe", "unsubscribe", "upgrade", "upgrade_trial"], typing.Any
]
