from array import array

def decode(
    in_bytes: bytes | bytearray | array[int], *, strict: bool = True
) -> bytes: ...
def encode(in_bytes: bytes | bytearray | array[int]) -> bytes: ...

class Decoder:
    max_length: int | None = None
    strict: bool = False

    def __init__(
        self, *, max_length: int | None = None, strict: bool = False
    ) -> None: ...
    def advance(self, byte: int) -> bytes | None: ...
    def advance_many(self, bytes: bytes | bytearray) -> list[bytes]: ...
    def reset(self) -> None: ...
    @property
    def num_pending(self) -> int: ...
    @property
    def pending(self) -> bytes: ...

    __call__ = advance_many

class DecodeError(RuntimeError): ...
