from pybiotech.classes.nih.https.pubchem.section.namespace import DOMAIN_NAMESPACE_MAP as DOMAIN_NAMESPACE_MAP, NamespaceModel as NamespaceModel

class NS(NamespaceModel):
    def validate_namespace_and_domain(self): ...
    def as_url_part(self): ...
