"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel
from enum import Enum
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PipelineFunctionUnionID(str, Enum):
    r"""Function ID"""

    UNION = "union"


class UnionConfigurationTypedDict(TypedDict):
    search_job_id: str
    r"""The id for this search job."""
    stage_ids: List[str]
    r"""The stages we are unioning with."""


class UnionConfiguration(BaseModel):
    search_job_id: Annotated[str, pydantic.Field(alias="searchJobId")]
    r"""The id for this search job."""

    stage_ids: Annotated[List[str], pydantic.Field(alias="stageIds")]
    r"""The stages we are unioning with."""


class PipelineFunctionUnionTypedDict(TypedDict):
    id: PipelineFunctionUnionID
    r"""Function ID"""
    conf: UnionConfigurationTypedDict
    filter_: NotRequired[str]
    r"""Filter that selects data to be fed through this Function"""
    description: NotRequired[str]
    r"""Simple description of this step"""
    disabled: NotRequired[bool]
    r"""If true, data will not be pushed through this function"""
    final: NotRequired[bool]
    r"""If enabled, stops the results of this Function from being passed to the downstream Functions"""
    group_id: NotRequired[str]
    r"""Group ID"""


class PipelineFunctionUnion(BaseModel):
    id: PipelineFunctionUnionID
    r"""Function ID"""

    conf: UnionConfiguration

    filter_: Annotated[Optional[str], pydantic.Field(alias="filter")] = "true"
    r"""Filter that selects data to be fed through this Function"""

    description: Optional[str] = None
    r"""Simple description of this step"""

    disabled: Optional[bool] = None
    r"""If true, data will not be pushed through this function"""

    final: Optional[bool] = None
    r"""If enabled, stops the results of this Function from being passed to the downstream Functions"""

    group_id: Annotated[Optional[str], pydantic.Field(alias="groupId")] = None
    r"""Group ID"""
