"""Constants for Pylon toolkit configuration."""

import os

PYLON_API_URL = "https://api.usepylon.com"
PYLON_APP_URL = "https://app.usepylon.com"

PYLON_API_TOKEN = "PYLON_API_TOKEN"  # noqa: S105 - This is the secret key name, not the value

try:
    PYLON_MAX_TIMEOUT_SECONDS = int(os.getenv("PYLON_MAX_TIMEOUT_SECONDS", 30))
except ValueError:
    PYLON_MAX_TIMEOUT_SECONDS = 30

LOCK_ACQUIRE_TIMEOUT_SECONDS = 60.0

FUZZY_MATCH_THRESHOLD = 0.60
FUZZY_AUTO_ACCEPT_CONFIDENCE = 0.90
DISABLE_AUTO_ACCEPT_THRESHOLD = 1.01
EXACT_MATCH_CONFIDENCE = 1.0

MAX_FUZZY_SUGGESTIONS = 10
MAX_DISPLAY_SUGGESTIONS = 5

DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

MAX_CONTACTS_PAGE_SIZE = 50

MAX_DATE_RANGE_DAYS = 30

BM25_MAX_ISSUES_TO_INDEX = 400
BM25_DEFAULT_TOP_K = 10
BM25_MIN_SCORE_THRESHOLD = 0.0
BM25_AUTO_ACCEPT_THRESHOLD = 0.85
