"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .executorspecificsettingstypesavedjobexecutorexecutor import (
    ExecutorSpecificSettingsTypeSavedJobExecutorExecutor,
    ExecutorSpecificSettingsTypeSavedJobExecutorExecutorTypedDict,
)
from cribl_control_plane.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ExecutorTypeSavedJobExecutorTypedDict(TypedDict):
    type: str
    r"""The type of executor to run"""
    store_task_results: NotRequired[bool]
    r"""Determines whether or not to write task results to disk"""
    conf: NotRequired[ExecutorSpecificSettingsTypeSavedJobExecutorExecutorTypedDict]


class ExecutorTypeSavedJobExecutor(BaseModel):
    type: str
    r"""The type of executor to run"""

    store_task_results: Annotated[
        Optional[bool], pydantic.Field(alias="storeTaskResults")
    ] = True
    r"""Determines whether or not to write task results to disk"""

    conf: Optional[ExecutorSpecificSettingsTypeSavedJobExecutorExecutor] = None
