const SUCCESS_RESPONSE_STATUS = [200, 201];

const SAGEMAKER_CONTEXT_ENDPOINT = '/aws/sagemaker/api/context';
const SAGEMAKER_AUTH_DETAILS_ENDPOINT = '/aws/sagemaker/api/auth-details';
const SAGEMAKER_AI_CONFIG_ENDPOINT = '/api/ai/config';
const SAGEMAKER_CLEAR_CACHE_ENDPOINT = '/aws/sagemaker/api/cache';
const Q_DEVELOPER_CODE_COMPLETIONS_CACHE_ENDPOINT = '/amazon_q_developer_jupyterlab_ext/clear_environment_cache';

export {
  SUCCESS_RESPONSE_STATUS,
  SAGEMAKER_CONTEXT_ENDPOINT,
  SAGEMAKER_CLEAR_CACHE_ENDPOINT,
  SAGEMAKER_AUTH_DETAILS_ENDPOINT,
  SAGEMAKER_AI_CONFIG_ENDPOINT,
  Q_DEVELOPER_CODE_COMPLETIONS_CACHE_ENDPOINT,
};
