from .utils import Utils as Utils
from typing import Any

class Collections(dict):
    def __init__(self, service: Any, metadata: dict[str, Any] = None) -> None: ...
    @property
    def collection_type(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def detail(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def period(self) -> str | None: ...
    @property
    def temporal_resolution(self) -> str: ...
    @property
    def spatial_extent(self) -> dict[str, Any]: ...
    @property
    def classification_system(self) -> dict[str, Any]: ...
