import pandas as pd
from .allen import ALLEN_RELATIONS as ALLEN_RELATIONS
from .collection import Collections as Collections
from .trajectories import Trajectories as Trajectories
from .trajectory import Trajectory as Trajectory
from .utils import Utils as Utils
from _typeshed import Incomplete

class WLTS:
    lccs_service: Incomplete
    def __init__(self, url, lccs_url=None, access_token=None, language=None) -> None: ...
    @property
    def collections(self): ...
    def tj(self, latitude, longitude, **options): ...
    def __getitem__(self, key): ...
    @property
    def url(self): ...
    def build_color_dict(self, collections) -> dict: ...
    def plot(self, dataframe, **parameters): ...
    def __iter__(self): ...
    @staticmethod
    def temporal_filter(df: pd.DataFrame, target_classes: list[str], start_date: str | None = None, end_date: str | None = None, relation_op: str = 'contains') -> pd.DataFrame: ...
    @staticmethod
    def temporal_relation(a: pd.DataFrame, b: pd.DataFrame, temp_fn: str = 'before') -> pd.DataFrame: ...
