

class _CudaDeviceProperties:
    @property
    def name(self) -> str: ...

    @property
    def major(self) -> int: ...

    @property
    def minor(self) -> int: ...

    @property
    def total_memory(self) -> int: ...

    @property
    def multi_processor_count(self) -> int: ...

    def __repr__(self) -> str: ...

def get_version() -> int: ...

def is_available() -> bool: ...

def device_count() -> int: ...

def current_device() -> int: ...

def set_device(device: int) -> None: ...

def get_device_name(device: int = 0) -> str: ...

def get_device_capability(device: int = 0) -> tuple[int, int]: ...

def get_device_properties(device: int = 0) -> _CudaDeviceProperties: ...

def synchronize(device: int = -1) -> None: ...

def memory_allocated(device: int = 0) -> int: ...

def max_memory_allocated(device: int = 0) -> int: ...

def reset_max_memory_allocated(device: int = 0) -> None: ...

def empty_cache() -> None: ...

def manual_seed(seed: int) -> None: ...
