# coding: utf-8

"""
    XOTP Integration Gateway (IG) REST API

     # Introduction Paymentus REST API exposes payment, profile and account data to authenticated users through a widely accepted REST technology. REST APIs are based on representation state transfer (REST) technology, an architectural style and approach to communications often used in web services development. REST technology is generally preferred to SOAP technology because REST leverages less bandwidth, making it more suitable for internet usage. A RESTful API explicitly takes advantage for HTTP methodologies defined by the RFC 2616 protocol. It uses GET to retrieve a resource, PUT to change the state or update a resource, which can be an object, file or block, POST to create the resource and DELETE to remove it.  Paymentus REST API acts as a wrapper around Paymentus XOTP API and maps HTTP GET, PUT, POST and DELETE verbs to corresponding endpoints of the XOTP API.  Paymentus API's use Bearer authentication.To authenticate you will:  - Click on Authorize button above and provide the Request secret, jwt token will generated and will be persisted for all requests. 

    The version of the OpenAPI document: v3
    Contact: apiteam@paymentus.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PaymentSearchRequest(BaseModel):
    """
    Schema: PaymentSearchRequest
    """ # noqa: E501
    account_number: StrictStr = Field(description="Property: account-number", alias="account-number")
    payment_type_code: Optional[StrictStr] = Field(default=None, description="Property: payment-type-code", alias="payment-type-code")
    auth_token1: Optional[StrictStr] = Field(default=None, description="Property: auth-token1", alias="auth-token1")
    auth_token2: Optional[StrictStr] = Field(default=None, description="Property: auth-token2", alias="auth-token2")
    auth_token3: Optional[StrictStr] = Field(default=None, description="Property: auth-token3", alias="auth-token3")
    account_token: Optional[StrictStr] = Field(default=None, description="Property: account-token", alias="account-token")
    routing_number: Optional[StrictStr] = Field(default=None, description="Property: routing-number", alias="routing-number")
    date_from: Optional[StrictStr] = Field(default=None, description="date format in MMDDYYYY", alias="date-from")
    date_to: Optional[StrictStr] = Field(default=None, description="date format in MMDDYYYY", alias="date-to")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["account-number", "payment-type-code", "auth-token1", "auth-token2", "auth-token3", "account-token", "routing-number", "date-from", "date-to"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentSearchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "additional_properties",
            },
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PaymentSearchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account-number": obj.get("account-number"),
            "payment-type-code": obj.get("payment-type-code"),
            "auth-token1": obj.get("auth-token1"),
            "auth-token2": obj.get("auth-token2"),
            "auth-token3": obj.get("auth-token3"),
            "account-token": obj.get("account-token"),
            "routing-number": obj.get("routing-number"),
            "date-from": obj.get("date-from"),
            "date-to": obj.get("date-to")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


