def CreateCodeFile(fileCode="""""", name=""):
    """This function creates a .java file with the DocString you gave to the parameter file. Make sure that the variable that you stored your Java code into is specifically a DocString, and not anything else. Oh yeah, you can also set a name for the file(Make sure to set a name!). If you don't give anything to the name parameter, this function will automatically set the name to "Default Java Code File". Make sure that the Java code you're making is compatible with Python's String or DocString format. The file will be saved in your downloads folder. If you want to learn the basics required for this library, call the help function using help(). DON'T try to change the file extension. YOUR ATTEMPTS WILL FALL WITH LINGERING PAIN."""
    if name in ["", " "]:
        with open(rf"Downloads\Default Java Code File.java", "w") as f:
            f.write(fileCode)
            print("Created Java code file.")
    else:
        with open(rf"Downloads\{name}.java", "w") as f:
            f.write(fileCode)
            print("Created Java code file.")

def help():
    docstring = """Hello there! It seems like you have called the help function. Now, I assume that you want to learn the basics required for this library. So, let's get right into it!
    Calling Functions: There's a little something in Python called a function. Now, a function is a block of code executed by calling the function. By that, I mean that when you call something like this help function using help(), it will execute a block of code inside the function(In this case, it prints this guide fpr you.). It can also have parameters, which is kind of like the properties of the function. You put the thing specified inside the parameters, and it executes the block of code inside it using the parameters you gave, which it might append to something, print it, etc. In this case, my function(CreateCodeFile()) has two parameters, file and name, with file being a DocString, and name being a String. I'll explain what are those two on the next topic in this guide.
    DocStrings And Strings: There's something called a DocString and a String in Python, which are pretty much text in Python. However, there are two differences: A DocString is something you use to contain text, along with special characters(Really good for code.). You make a DocString using three double quotes covering both sides of the text(""" """). A String is pretty much the same thing, except it can't handle backslashes(Which the DocSting can't handle as well!). You make a String using one double quotes(" "). Since I told you that both types of text can't handle backspaces, you might think that there is no difference. However, a DocString allow you to type Java code as is. However, for Strings, you need to use newlines to move to the next piece of code. Try it by clicking enter inside both types of text. To handle backslashes in Strings and DocStrings, you use something called a prefix. Anyways, onto explaining the next topic: Prefixes!
    Prefixes: Prefixes are the letters you add before defining a String or DocString, which allows it to handle certain characters such as backslashes. For this library, you only need to know the "r" prefix. The "r" prefix is a prefix that you add before defining a String or a DocString, that allows it to handle backslashes. Example: r""" """. Make sure to use it when typing in Java code, so that Python can handle the backslashes. Onto the next lilypad, Frogenstein!
    Variables: Variables are containers that contain your Strings and DocStrings in Python. Nothing much to explain here. Anyways, here's the syntax: name = your DocString or String. You can use a variable to contain your Java code, then give it to the CreateCodeFile function, instead of typing the entire DocString into the CreateCodeFile function."""
    print(docstring)