from _typeshed import Incomplete

DATA_FILE_NAME: str
DATA_FILE_PATH: Incomplete
DEFAULT_TIMEOUT: int
DEFAULT_LANGUAGE: str
FILE_WATCHER_POLL_INTERVAL_SECONDS: float
E2B_API_KEY_ENV: str
E2B_DOMAIN_ENV: str
E2B_TEMPLATE_PYTHON_ENV: str
E2B_TEMPLATE_PYTHON_ASYNC_ENV: str
