import enum


class StatusEnum(enum.Enum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    DELETED = "DELETED"
    PENDING = "PENDING"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"
    WITHDRAWN = "WITHDRAWN"
    GRADUATED = "GRADUATED"
    ALUMNI = "ALUMNI"
    EXPELLED = "EXPELLED"
    PROBATION = "PROBATION"
    ENROLLED = "ENROLLED"
    WAITLISTED = "WAITLISTED"
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"


class GenderEnum(enum.Enum):
    MALE = "MALE"
    FEMALE = "FEMALE"
    OTHER = "OTHER"


class DeviceTypeEnum(enum.Enum):
    MOBILE = "MOBILE"
    DESKTOP = "DESKTOP"
    TABLET = "TABLET"
    WEB = "WEB"
    BOT = "BOT"
    UNKNOWN = "UNKNOWN"


class OwnerTypeEnum(enum.Enum):
    STUDENT = "STUDENT"
    PARENT = "PARENT"
    STAFF = "STAFF"
    EVENTS = "EVENTS"
    NEWS = "NEWS"
    ASSIGNMENT = "ASSIGNMENT"
    CERTIFICATE = "CERTIFICATE"


class PermissionEnum(enum.Enum):
    VIEW = "VIEW"
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    USER_CREATION = "USER_CREATION"
    AUTH_MANAGEMENT = "AUTH_MANAGEMENT"
    PAYMENT_MANAGEMENT = "PAYMENT_MANAGEMENT"
    FEE_MANAGEMENT = "FEE_MANAGEMENT"
    STUDENT_MANAGEMENT = "STUDENT_MANAGEMENT"
    TIME_TABLE_MANAGEMENT = "TIME_TABLE_MANAGEMENT"
    ADMINISTRATIVE_MANAGEMENT = "ADMINISTRATIVE_MANAGEMENT"
    TENANCY_MANAGEMENT = "TENANCY_MANAGEMENT"


class AttendanceStatus(enum.Enum):
    """
    Enumeration for different attendance statuses.
    """
    PRESENT = "PRESENT"
    ABSENT = "ABSENT"
    LATE = "LATE"
    EXCUSED = "EXCUSED"
    SICK_LEAVE = "SICK_LEAVE"
    HALF_DAY = "HALF_DAY"


class PresentTypeEnum(enum.Enum):
    """
    enumeration for different types of presence.
    """
    FULL_DAY = "FULL_DAY"
    HALF_DAY = "HALF_DAY"
    ONLINE = "ONLINE"


class EventNewsTypeEnum(enum.Enum):
    EVENT = "EVENT"
    NEWS = "NEWS"
    ANNOUNCEMENT = "ANNOUNCEMENT"
    HOLIDAY = "HOLIDAY"
    EXAM_SCHEDULE = "EXAM_SCHEDULE"


class PriorityEnum(enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class TargetAudienceEnum(enum.Enum):
    ALL = "ALL"
    STUDENTS = "STUDENTS"
    TEACHERS = "TEACHERS"
    PARENTS = "PARENTS"
    DRIVERS = "DRIVERS"
    STAFF = "STAFF"
    SPECIFIC_CLASS = "SPECIFIC_CLASS"
    SPECIFIC_SECTION = "SPECIFIC_SECTION"


class PaymentStatusEnum(enum.Enum):
    PENDING = "PENDING"  # The payment is outstanding and due in the future.
    PAID = "PAID"  # The payment has been successfully received.
    OVERDUE = "OVERDUE"  # The payment's due date has passed without full payment.
    WAIVED = "WAIVED"  # The payment obligation has been officially cancelled or excused.
    WAIVED_PARTIAL = "WAIVED_PARTIAL"  # A portion of the payment has been waived.
    PARTIALLY_PAID = "PARTIALLY_PAID"  # A portion of the payment has been made, but not the full amount.


class RelationshipEnum(enum.Enum):
    FATHER = "FATHER"
    MOTHER = "MOTHER"
    GUARDIAN = "GUARDIAN"
    OTHER = "OTHER"


class RoutineDayEnum(enum.Enum):
    MONDAY = "MONDAY"
    TUESDAY = "TUESDAY"
    WEDNESDAY = "WEDNESDAY"
    THURSDAY = "THURSDAY"
    FRIDAY = "FRIDAY"
    SATURDAY = "SATURDAY"
    SUNDAY = "SUNDAY"


class StaffTypeEnum(enum.Enum):
    TEACHING = "TEACHING"
    NON_TEACHING = "NON_TEACHING"
    ADMIN = "ADMIN"
    DRIVER = "DRIVER"
    OTHER = "OTHER"


class SalaryMonthEnum(enum.Enum):
    JANUARY = "JANUARY"
    FEBRUARY = "FEBRUARY"
    MARCH = "MARCH"
    APRIL = "APRIL"
    MAY = "MAY"
    JUNE = "JUNE"
    JULY = "JULY"
    AUGUST = "AUGUST"
    SEPTEMBER = "SEPTEMBER"
    OCTOBER = "OCTOBER"
    NOVEMBER = "NOVEMBER"
    DECEMBER = "DECEMBER"


class CTCComponentTypeEnum(enum.Enum):
    ALLOWANCE = "ALLOWANCE"
    DEDUCTION = "DEDUCTION"
    BONUS = "BONUS"
    REIMBURSEMENT = "REIMBURSEMENT"
    TAX = "TAX"
    HRA = "HRA"
    BASIC_SALARY = "BASIC_SALARY"
    MEDICAL_ALLOWANCE = "MEDICAL_ALLOWANCE"
    TRANSPORT_ALLOWANCE = "TRANSPORT_ALLOWANCE"
    OTHER = "OTHER"


class StudentStatusEnum(enum.Enum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    DELETED = "DELETED"
    DROPPED_OUT = "DROPPED_OUT"


class SubjectCategoryEnum(enum.Enum):
    ACADEMIC = "ACADEMIC"
    ACTIVITY = "ACTIVITY"
    ELECTIVE = "ELECTIVE"
    VOCATIONAL = "VOCATIONAL"
    LIFE_SKILLS = "LIFE_SKILLS"
    SPORTS = "SPORTS"
    CULTURAL = "CULTURAL"
    TECHNICAL = "TECHNICAL"
    LANGUAGE = "LANGUAGE"
    MORAL_EDUCATION = "MORAL_EDUCATION"
    SPECIAL_EDUCATION = "SPECIAL_EDUCATION"


class TripStatusEnum(enum.Enum):
    ACTIVE = 'ACTIVE'
    ENDED = 'ENDED'
    CANCELLED = 'CANCELLED'
    PAUSED = 'PAUSED'
    RESUMED = 'RESUMED'


class UserFileTypeEnum(enum.Enum):
    PROFILE_PHOTO = 'PROFILE_PHOTO'
    DOCUMENTS = 'DOCUMENTS'
    SELFI_ATTENDANCE = 'SELFI_ATTENDANCE'
    TRANSCRIPT = 'TRANSCRIPT'
    ID_CARD = 'ID_CARD'
    REPORT_CARD = 'REPORT_CARD'
    ASSIGNMENT = 'ASSIGNMENT'
    CERTIFICATE = 'CERTIFICATE'
    FEE_RECEIPT = 'FEE_RECEIPT'
    HOMEWORK = 'HOMEWORK'
    TIMETABLE = 'TIMETABLE'
    SYLLABUS = 'SYLLABUS'
    LEAVE_APPLICATION = 'LEAVE_APPLICATION'
    MARKSHEET = 'MARKSHEET'
    ADMISSION_FORM = 'ADMISSION_FORM'
    BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE'
    PARENT_ID_PROOF = 'PARENT_ID_PROOF'
    MEDICAL_REPORT = 'MEDICAL_REPORT'
    TC = 'TC'
    IMAGES = 'IMAGES'
    OTHERS = 'OTHERS'


class UserType(enum.Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    SCHOOL_ADMIN = "SCHOOL_ADMIN"
    TEACHER = "TEACHER"
    STUDENT = "STUDENT"
    PARENT = "PARENT"
    DRIVER = "DRIVER"
    STAFF = "STAFF"
    PRINCIPAL = "PRINCIPAL"
    VICE_PRINCIPAL = "VICE_PRINCIPAL"
    ACCOUNT_MANAGER = "ACCOUNT_MANAGER"
    SYSTEM_ADMIN = "SYSTEM_ADMIN"
    ACCOUNTANT = "ACCOUNTANT"
    LIBRARIAN = "LIBRARIAN"
    ADMISSIONS_OFFICER = "ADMISSIONS_OFFICER"
    TRANSPORT_MANAGER = "TRANSPORT_MANAGER"
    HR_MANAGER = "HR_MANAGER"
    FRONT_DESK = "FRONT_DESK"
    GUEST = "GUEST"


class LoginStatus(enum.Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    LOCKED = "LOCKED"


class LoginMethod(enum.Enum):
    PASSWORD = "PASSWORD"
    OTP = "OTP"
    GOOGLE_SSO = "GOOGLE_SSO"
    ADMIN = "ADMIN"


class TenantTypeEnum(enum.Enum):
    STAFF = "STAFF"
    PARENT = "PARENT"


class HolidayTypeEnum(enum.Enum):
    SCHOOL_BREAK = "SCHOOL_BREAK"
    PUBLIC_HOLIDAY = "PUBLIC_HOLIDAY"
    SUMMER_VACATION = "SUMMER_VACATION"
    WINTER_VACATION = "WINTER_VACATION"
    MID_TERM_BREAK = "MID_TERM_BREAK"
    EXAM_BREAK = "EXAM_BREAK"
    NATIONAL_HOLIDAY = "NATIONAL_HOLIDAY"
    STATE_HOLIDAY = "STATE_HOLIDAY"
    FESTIVAL = "FESTIVAL"
    RELIGIOUS_HOLIDAY = "RELIGIOUS_HOLIDAY"
    OPTIONAL_HOLIDAY = "OPTIONAL_HOLIDAY"
    COMPENSATORY_HOLIDAY = "COMPENSATORY_HOLIDAY"
    TEACHERS_DAY = "TEACHERS_DAY"
    CHILDREN_DAY = "CHILDREN_DAY"
    INDEPENDENCE_DAY = "INDEPENDENCE_DAY"
    REPUBLIC_DAY = "REPUBLIC_DAY"
    GANDHI_JAYANTI = "GANDHI_JAYANTI"
    DIWALI = "DIWALI"
    HOLI = "HOLI"
    EID = "EID"
    CHRISTMAS = "CHRISTMAS"
    PONGAL = "PONGAL"
    ONAM = "ONAM"
    NAVRATRI = "NAVRATRI"
    DUSSEHRA = "DUSSEHRA"
    GOOD_FRIDAY = "GOOD_FRIDAY"
    OTHER = "OTHER"
    # Additional specific festival/observance entries
    RAMADAN = "RAMADAN"
    EID_UL_FITR = "EID_UL_FITR"
    EID_UL_ADHA = "EID_UL_ADHA"
    MUHARRAM = "MUHARRAM"
    MILAD_UN_NABI = "MILAD_UN_NABI"
    SHAB_E_BARAT = "SHAB_E_BARAT"
    EASTER = "EASTER"
    PALM_SUNDAY = "PALM_SUNDAY"
    NEW_YEAR = "NEW_YEAR"
    GURU_NANAK_JAYANTI = "GURU_NANAK_JAYANTI"
    GURU_GOBIND_SINGH_JAYANTI = "GURU_GOBIND_SINGH_JAYANTI"
    BAISAKHI = "BAISAKHI"
    MAGHI = "MAGHI"
    HOLA_MOHALLA = "HOLA_MOHALLA"
    MAHAVIR_JAYANTI = "MAHAVIR_JAYANTI"
    PARYUSHAN_PARVA = "PARYUSHAN_PARVA"
    BUDDHA_PURNIMA = "BUDDHA_PURNIMA"
    VESAK = "VESAK"
    BIHU = "BIHU"
    POILA_BAISAKH = "POILA_BAISAKH"
    TAMIL_NEW_YEAR = "TAMIL_NEW_YEAR"
    UGADI = "UGADI"
    VISHWAKARMA_PUJA = "VISHWAKARMA_PUJA"
    CHHATH_PUJA = "CHHATH_PUJA"
    LOSAR = "LOSAR"
    GOA_FEAST_ST_FRANCIS_XAVIER = "GOA_FEAST_ST_FRANCIS_XAVIER"
    KARNATAKA_RAJYOTSAVA = "KARNATAKA_RAJYOTSAVA"
    HARYANA_DAY = "HARYANA_DAY"
    RAJASTHAN_FOUNDATION_DAY = "RAJASTHAN_FOUNDATION_DAY"
    MAY_DAY = "MAY_DAY"
    DOCTORS_DAY = "DOCTORS_DAY"
    ENGINEERS_DAY = "ENGINEERS_DAY"
    NATIONAL_SCIENCE_DAY = "NATIONAL_SCIENCE_DAY"
    ARMY_DAY = "ARMY_DAY"
    REPUBLIC_WEEK = "REPUBLIC_WEEK"
    BANK_HOLIDAY = "BANK_HOLIDAY"
    STATE_FOUNDATION_DAY = "STATE_FOUNDATION_DAY"
    FINANCIAL_YEAR_END = "FINANCIAL_YEAR_END"
    YEAR_CLOSING = "YEAR_CLOSING"
    RESTRICTED_OPTIONAL = "RESTRICTED_OPTIONAL"
    OBSERVANCE_DAY = "OBSERVANCE_DAY"
    ENVIRONMENT_DAY = "ENVIRONMENT_DAY"
    YOGA_DAY = "YOGA_DAY"
    MARTYRS_DAY = "MARTYRS_DAY"
    ARMED_FORCES_FLAG_DAY = "ARMED_FORCES_FLAG_DAY"
    NATIONAL_VOTERS_DAY = "NATIONAL_VOTERS_DAY"
    WORLD_HEALTH_DAY = "WORLD_HEALTH_DAY"

class PaymentMethodEnum(enum.Enum):
    CASH = "CASH"
    CARD = "CARD"
    ONLINE = "ONLINE"
    UPI = "UPI"
    BANK_TRANSFER = "BANK_TRANSFER"
    CHEQUE = "CHEQUE"
    MOBILE_WALLET = "MOBILE_WALLET"
    NET_BANKING = "NET_BANKING"
    OTHER = "OTHER"