# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: safari_sdk/protos/monitoring.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'safari_sdk/protos/monitoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from safari_sdk.protos import vector_pb2 as safari__sdk_dot_protos_dot_vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"safari_sdk/protos/monitoring.proto\x12\x11safari_sdk.protos\x1a\x1esafari_sdk/protos/vector.proto\"\xbf\x02\n\x15MonitoringMeasurement\x12\x13\n\x0bmeasure_key\x18\x01 \x01(\t\x12\x44\n\x06labels\x18\x02 \x03(\x0b\x32\x34.safari_sdk.protos.MonitoringMeasurement.LabelsEntry\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x13\n\tint_value\x18\x08 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\t \x01(\x01H\x00\x12\x43\n\x13named_vector_double\x18\n \x01(\x0b\x32$.safari_sdk.protos.NamedVectorDoubleH\x00\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x07\n\x05value\"\xc3\x01\n\x0fMonitoringEvent\x12\x30\n\x08severity\x18\x01 \x01(\x0e\x32\x1e.safari_sdk.protos.LogSeverity\x12\x0f\n\x07message\x18\x02 \x01(\t\x12>\n\x06labels\x18\x03 \x03(\x0b\x32..safari_sdk.protos.MonitoringEvent.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x94\x01\n\x11MonitoringPayload\x12?\n\x0bmeasurement\x18\x02 \x01(\x0b\x32(.safari_sdk.protos.MonitoringMeasurementH\x00\x12\x33\n\x05\x65vent\x18\x03 \x01(\x0b\x32\".safari_sdk.protos.MonitoringEventH\x00\x42\t\n\x07payload*\xf7\x01\n\x0bLogSeverity\x12\x18\n\x14LOG_SEVERITY_DEFAULT\x10\x00\x12\x16\n\x12LOG_SEVERITY_DEBUG\x10\x64\x12\x16\n\x11LOG_SEVERITY_INFO\x10\xc8\x01\x12\x18\n\x13LOG_SEVERITY_NOTICE\x10\xac\x02\x12\x19\n\x14LOG_SEVERITY_WARNING\x10\x90\x03\x12\x17\n\x12LOG_SEVERITY_ERROR\x10\xf4\x03\x12\x1a\n\x15LOG_SEVERITY_CRITICAL\x10\xd8\x04\x12\x17\n\x12LOG_SEVERITY_ALERT\x10\xbc\x05\x12\x1b\n\x16LOG_SEVERITY_EMERGENCY\x10\xa0\x06')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'safari_sdk.protos.monitoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MONITORINGMEASUREMENT_LABELSENTRY']._loaded_options = None
  _globals['_MONITORINGMEASUREMENT_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_MONITORINGEVENT_LABELSENTRY']._loaded_options = None
  _globals['_MONITORINGEVENT_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_LOGSEVERITY']._serialized_start=761
  _globals['_LOGSEVERITY']._serialized_end=1008
  _globals['_MONITORINGMEASUREMENT']._serialized_start=90
  _globals['_MONITORINGMEASUREMENT']._serialized_end=409
  _globals['_MONITORINGMEASUREMENT_LABELSENTRY']._serialized_start=355
  _globals['_MONITORINGMEASUREMENT_LABELSENTRY']._serialized_end=400
  _globals['_MONITORINGEVENT']._serialized_start=412
  _globals['_MONITORINGEVENT']._serialized_end=607
  _globals['_MONITORINGEVENT_LABELSENTRY']._serialized_start=355
  _globals['_MONITORINGEVENT_LABELSENTRY']._serialized_end=400
  _globals['_MONITORINGPAYLOAD']._serialized_start=610
  _globals['_MONITORINGPAYLOAD']._serialized_end=758
# @@protoc_insertion_point(module_scope)
