"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel
from enum import Enum
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PipelineFunctionEventstatsID(str, Enum):
    r"""Function ID"""

    EVENTSTATS = "eventstats"


class EventstatsConfigurationTypedDict(TypedDict):
    aggregations: List[str]
    r"""Aggregate function(s) to perform on events. E.g., sum(bytes).where(action=='REJECT').as(TotalBytes)"""
    group_bys: NotRequired[List[str]]
    r"""Fields to group aggregates by, supports wildcard expressions."""
    max_events: NotRequired[float]
    r"""Specifies how many events are at max kept in memory to be enriched with aggregations"""
    flush_on_input_close: NotRequired[bool]
    r"""Determines if aggregations should flush when an input stream is closed. If disabled, time window settings will control flush behavior."""


class EventstatsConfiguration(BaseModel):
    aggregations: List[str]
    r"""Aggregate function(s) to perform on events. E.g., sum(bytes).where(action=='REJECT').as(TotalBytes)"""

    group_bys: Annotated[Optional[List[str]], pydantic.Field(alias="groupBys")] = None
    r"""Fields to group aggregates by, supports wildcard expressions."""

    max_events: Annotated[Optional[float], pydantic.Field(alias="maxEvents")] = 50000
    r"""Specifies how many events are at max kept in memory to be enriched with aggregations"""

    flush_on_input_close: Annotated[
        Optional[bool], pydantic.Field(alias="flushOnInputClose")
    ] = False
    r"""Determines if aggregations should flush when an input stream is closed. If disabled, time window settings will control flush behavior."""


class PipelineFunctionEventstatsTypedDict(TypedDict):
    id: PipelineFunctionEventstatsID
    r"""Function ID"""
    conf: EventstatsConfigurationTypedDict
    filter_: NotRequired[str]
    r"""Filter that selects data to be fed through this Function"""
    description: NotRequired[str]
    r"""Simple description of this step"""
    disabled: NotRequired[bool]
    r"""If true, data will not be pushed through this function"""
    final: NotRequired[bool]
    r"""If enabled, stops the results of this Function from being passed to the downstream Functions"""
    group_id: NotRequired[str]
    r"""Group ID"""


class PipelineFunctionEventstats(BaseModel):
    id: PipelineFunctionEventstatsID
    r"""Function ID"""

    conf: EventstatsConfiguration

    filter_: Annotated[Optional[str], pydantic.Field(alias="filter")] = "true"
    r"""Filter that selects data to be fed through this Function"""

    description: Optional[str] = None
    r"""Simple description of this step"""

    disabled: Optional[bool] = None
    r"""If true, data will not be pushed through this function"""

    final: Optional[bool] = None
    r"""If enabled, stops the results of this Function from being passed to the downstream Functions"""

    group_id: Annotated[Optional[str], pydantic.Field(alias="groupId")] = None
    r"""Group ID"""
