"""Index of author ids to author names."""

from tlg_indices.data_types import AuthorID


AUTHOR_ID_TO_AUTHOR_NAME: dict[AuthorID, str] = {
    AuthorID("2434"): "Aelius Dius Hist.",
    AuthorID("2035"): "Athanasius Theol.",
    AuthorID("2012"): "Acta Eupli",
    AuthorID("1578"): "Phaenias Phil.",
    AuthorID("1220"): "Batrachomyomachia",
    AuthorID("1222"): "Beros(s)us Astrol. et Hist.",
    AuthorID("0474"): "Magnes Comic.",
    AuthorID("0559"): "Heron Mech.",
    AuthorID("4138"): "Ephraem Syrus Theol.",
    AuthorID("1639"): "Pseudo-Auctores Hellenistae (PsVTGr)",
    AuthorID("4075"): "Marinus Phil.",
    AuthorID("1413"): "Heraclitus Paradox.",
    AuthorID("2120"): "Panteleius Epic.",
    AuthorID("2595"): "Philo Paradox.",
    AuthorID("2744"): "Historia Monachorum In Aegypto",
    AuthorID("1397"): "Hegesippus Hist.",
    AuthorID("1634"): "Prodicus Soph.",
    AuthorID("2566"): "[Agathon] Hist.",
    AuthorID("4291"): "Verba In Scripturis De Christo",
    AuthorID("0373"): "Melanippides Lyr.",
    AuthorID("2648"): "Adespota Papyracea (SH)",
    AuthorID("1817"): "Fragmenta Anonyma (PsVTGr)",
    AuthorID("1871"): "Bion Hist.",
    AuthorID("1105"): "Timaeus Praxidas Astrol.",
    AuthorID("0552"): "Archimedes Geom.",
    AuthorID("1407"): "Heraclides Lembus Hist.",
    AuthorID("0766"): "Alcmaeon Phil.",
    AuthorID("1725"): "Theophilus Apol.",
    AuthorID("2391"): "Hippostratus Hist.",
    AuthorID("0446"): "Dioxippus Comic.",
    AuthorID("2650"): "Arrianus Epic.",
    AuthorID("2371"): "Chronicon Paschale",
    AuthorID("2657"): "Martyrium Ignatii",
    AuthorID("0673"): "Aeschines Socraticus Phil.",
    AuthorID("4290"): "Lexicon Artis Grammaticae",
    AuthorID("1527"): "Nepualius Med. et Phil.",
    AuthorID("2109"): "Pseudo-Macarius Scr. Eccl.",
    AuthorID("2571"): "Hierocles Phil.",
    AuthorID("1149"): "Antonini Pii Imperatoris Epistula",
    AuthorID("0252"): "Hermippus Comic.",
    AuthorID("1227"): "Blaesus Comic.",
    AuthorID("0726"): "Palladius Med.",
    AuthorID("1836"): "Anonymi Aulodia",
    AuthorID("1324"): "Dionysius Hist.",
    AuthorID("0562"): "Marcus Aurelius Antoninus Imperator Phil.",
    AuthorID("4339"): "Archelaus Alchem. et Poeta",
    AuthorID("0644"): "Aristophanes Gramm.",
    AuthorID("1351"): "Epigoni",
    AuthorID(
        "4032"
    ): "Anonymi In Aristotelis Librum Primum Analyticorum Posteriorum Commentarium",
    AuthorID("4018"): "Asclepius Phil.",
    AuthorID("1843"): "Nicomachus Trag.",
    AuthorID("0558"): "Hellenica",
    AuthorID("1163"): "Claudius Apollinarius Apol.",
    AuthorID("2482"): "Daimachus Hist.",
    AuthorID("2397"): "Boethus Phil.",
    AuthorID("9009"): "Michael Apostolius Paroemiogr.",
    AuthorID("0303"): "Phrynichus Trag.",
    AuthorID("1219"): "Bato Hist. et Rhet.",
    AuthorID("0647"): "Triphiodorus Epic. et Gramm.",
    AuthorID("2547"): "Antigonus",
    AuthorID("5004"): "Epimerismi",
    AuthorID("1354"): "Ergias Hist.",
    AuthorID("1760"): "Gaius Suetonius Tranquillus Gramm. et Hist.",
    AuthorID("0721"): "Anonymi Medici Med.",
    AuthorID("1172"): "Arcesilaus Phil.",
    AuthorID("4287"): "Etymologia Alphabeti",
    AuthorID("0399"): "Eudoxus Comic.",
    AuthorID("0062"): "Lucianus Soph.",
    AuthorID("1489"): "Megasthenes Hist.",
    AuthorID("4303"): "Lexica In Opera Gregorii Nazianzeni",
    AuthorID("2956"): "Sextus Julius Africanus Hist.",
    AuthorID("2894"): "Constitutiones Apostolorum",
    AuthorID("0638"): "Flavius Philostratus Soph.",
    AuthorID("0040"): "Calani Epistula",
    AuthorID("0291"): "Alcman Lyr.",
    AuthorID("0337"): "Python Trag.",
    AuthorID("0492"): "Philonides Comic.",
    AuthorID("1846"): "Spintharus Trag.",
    AuthorID("0077"): "Periplus Maris Magni",
    AuthorID("1923"): "Stesimbrotus Hist.",
    AuthorID("2063"): "Gregorius Thaumaturgus Scr. Eccl.",
    AuthorID("0635"): "Zeno Phil.",
    AuthorID("0417"): "Archippus Comic.",
    AuthorID("0695"): "Alcimus Hist.",
    AuthorID("1752"): "Xenagoras Geogr. et Hist.",
    AuthorID("0346"): "Pompeius Macer [Trag.]",
    AuthorID("0509"): "[Myia] Phil.",
    AuthorID("0398"): "Simylus Comic.",
    AuthorID("1194"): "Aristonicus Gramm.",
    AuthorID("0257"): "Philiscus Rhet.",
    AuthorID("0324"): "Patrocles Trag.",
    AuthorID("3139"): "Laonicus Chalcocondyles Hist.",
    AuthorID("2703"): "Anna Comnena Hist.",
    AuthorID("5009"): "Scholia In Aeschinem",
    AuthorID("0313"): "Theognis Trag.",
    AuthorID("2237"): "Theodorus Math.",
    AuthorID("2277"): "Hypermenes Hist.",
    AuthorID("4171"): "Anonymi In Oppiani Opera",
    AuthorID("0547"): "Anaximenes Hist. et Rhet.",
    AuthorID("2995"): "Orus Gramm.",
    AuthorID("2331"): "Myrsilus Hist.",
    AuthorID("4346"): "Menecrates Hist.",
    AuthorID("4374"): "Anonymi De Astrologia Dialogus Astrol.",
    AuthorID("5030"): "Scholia In Lycophronem",
    AuthorID("0751"): "Pseudo-Hippocrates Med.",
    AuthorID("2644"): "Sminthes Astron.",
    AuthorID("1321"): "Diogenes Phil.",
    AuthorID("1833"): "Pratinas Trag.",
    AuthorID("0525"): "Pausanias Perieg.",
    AuthorID("1890"): "Moderatus Phil.",
    AuthorID("2051"): "Himerius Soph.",
    AuthorID("1805"): "Vitae Homeri",
    AuthorID("1439"): "Hermarchus Phil.",
    AuthorID("2307"): "Artemon Hist.",
    AuthorID("0368"): "Cydias Lyr.",
    AuthorID("0582"): "Paradoxographus Vaticanus",
    AuthorID("1123"): "Andron Hist.",
    AuthorID("2970"): "Severus Phil.",
    AuthorID("2236"): "Eutropius Hist.",
    AuthorID("0458"): "Eubulus Comic.",
    AuthorID("0042"): "Alexandri Magni Epistulae",
    AuthorID("1907"): "Cratippus Hist.",
    AuthorID("0201"): "Isyllus Lyr.",
    AuthorID("0404"): "Amphis Comic.",
    AuthorID("4174"): "Paraphrases In Dionysium Periegetam",
    AuthorID("1587"): "Philiades Eleg.",
    AuthorID("0319"): "Critias Eleg., Phil. et Trag.",
    AuthorID("1596"): "Philolaus Phil.",
    AuthorID("2011"): "Martyrium Agapae, Irenae, Chionae Et Sodalium",
    AuthorID("4324"): "Synesius Alchem.",
    AuthorID("0730"): "Meletius Med.",
    AuthorID("0022"): "Nicander Epic.",
    AuthorID("1801"): "Parodica Anonyma",
    AuthorID("5045"): "Anonymi In Aphthonium Rhet.",
    AuthorID("1260"): "[Chersias] Epic.",
    AuthorID("1257"): "Charinus Choliamb.",
    AuthorID("2696"): "Theodorus Poeta",
    AuthorID("1693"): "Sphaerus Phil.",
    AuthorID("1204"): "Athenaeus Mech.",
    AuthorID("3143"): "Georgius Sphrantzes Hist.",
    AuthorID("3100"): "Nicolaus I Mysticus Theol. et Epist.",
    AuthorID("0633"): "[Lysis] Phil.",
    AuthorID("2216"): "Aristippus Hist.",
    AuthorID("0545"): "Claudius Aelianus Soph.",
    AuthorID("1237"): "[Callicratidas] Phil.",
    AuthorID("1436"): "[Hippodamus] Phil.",
    AuthorID("1726"): "Theopompus Epic.",
    AuthorID("0540"): "Lysias Orat.",
    AuthorID("1241"): "Carmen Naupactium",
    AuthorID("9008"): "Macarius Chrysocephalus Paroemiogr.",
    AuthorID("1627"): "Polycrates Hist.",
    AuthorID("0571"): "Aristocles Paradox.",
    AuthorID("0473"): "Machon Comic.",
    AuthorID("2182"): "Staphylus Hist.",
    AuthorID("1361"): "Eumedes Comic.",
    AuthorID("4237"): "Joannes Argyropulus Gramm.",
    AuthorID("4301"): "Lexicon Rhetoricum Cantabrigiense",
    AuthorID("0256"): "Panarces Scriptor Aenigmatum",
    AuthorID("1604"): "Phocylides Eleg. et Gnom.",
    AuthorID("1797"): "Choliambica Adespota (ALG)",
    AuthorID("1746"): "Valentinus Gnost.",
    AuthorID("0074"): "Flavius Arrianus Hist. et Phil.",
    AuthorID("1785"): "Paramonus Comic.",
    AuthorID("2002"): "Anonymus Seguerianus Rhet.",
    AuthorID("4338"): "Theophrastus Alchem. et Poeta",
    AuthorID("2654"): "Physiologus",
    AuthorID("0039"): "Mithridatis Epistula",
    AuthorID("0500"): "Posidippus Comic.",
    AuthorID("2173"): "Antileon Hist.",
    AuthorID("0390"): "Martyrium Carpi, Papyli Et Agathonicae",
    AuthorID("4326"): "Pappus Alchem.",
    AuthorID("1978"): "Leo Hist.",
    AuthorID("2148"): "Aristodemus Hist.",
    AuthorID("1463"): "Liber Enoch",
    AuthorID("2313"): "Antisthenes Phil.",
    AuthorID("1228"): "[Boeo] Epic.",
    AuthorID("2061"): "Asterius Sophista Scr. Eccl.",
    AuthorID("4390"): "Democles Hist.",
    AuthorID("1602"): "Philoxenus Gramm.",
    AuthorID("4292"): "Lexicon De Atticis Nominibus",
    AuthorID("1545"): "Ocellus Phil.",
    AuthorID("2055"): "Serenus Geom.",
    AuthorID("3156"): "Anonymi Exegesis In Hesiodi Theogoniam",
    AuthorID("2968"): "Monimus Phil.",
    AuthorID("1212"): "Atridarum Reditus",
    AuthorID("0241"): "Aristoxenus [Comic.]",
    AuthorID("0043"): "Amasis Epistulae",
    AuthorID("1511"): "Mimnermus Trag.",
    AuthorID("0031"): "Novum Testamentum, New Testament",
    AuthorID("2949"): "Acta Barnabae",
    AuthorID("2053"): "Paulus Astrol.",
    AuthorID("0388"): "Acta Pauli",
    AuthorID("4036"): "Proclus Phil.",
    AuthorID("1584"): "Pherecydes Hist.",
    AuthorID("0889"): "Timesitheus Trag.",
    AuthorID("0661"): "Archigenes Med.",
    AuthorID("1783"): "Callicrates Comic.",
    AuthorID("2022"): "Gregorius Nazianzenus Theol.",
    AuthorID("2019"): "Pelagius Alchem.",
    AuthorID("0317"): "Acta Joannis",
    AuthorID("0092"): "Anonymi Geographiae Expositio Compendiaria",
    AuthorID("0687"): "Agaclytus Hist.",
    AuthorID("5026"): "Scholia In Homerum",
    AuthorID("4236"): "Trophonius Rhet. et Soph.",
    AuthorID("1868"): "Damastes Hist.",
    AuthorID("1368"): "Evangelium Ebionitum",
    AuthorID("0511"): "Theognetus Comic.",
    AuthorID("4097"): "Etymologicum Genuinum",
    AuthorID("1338"): "Dosiadas Hist.",
    AuthorID("0693"): "Albinus Phil.",
    AuthorID("2946"): "Priscus Hist. et Rhet.",
    AuthorID("0483"): "Nicophon Comic.",
    AuthorID("0097"): "Diogenianus Gramm.",
    AuthorID("0508"): "Strattis Comic.",
    AuthorID("2247"): "Petron Phil.",
    AuthorID("2314"): "Diogenes Phil.",
    AuthorID("2158"): "Eutychianus Hist.",
    AuthorID("2892"): "Maximus Confessor Theol.",
    AuthorID("2384"): "Hermias Hist.",
    AuthorID("1390"): "Hecataeus Hist.",
    AuthorID("1555"): "Pancrates Epic.",
    AuthorID("9022"): "Joannes Tzetzes Gramm. et Poeta",
    AuthorID("0059"): "Plato Phil.",
    AuthorID("1795"): "Chaerion Comic.",
    AuthorID("2546"): "Publius Rutilius Rufus Hist.",
    AuthorID("2015"): "Testamentum XL Martyrum",
    AuthorID("2001"): "Themistius Phil. et Rhet.",
    AuthorID("9006"): "Gregorius Paroemiogr.",
    AuthorID("0066"): "Dicaearchus Phil.",
    AuthorID("3181"): "Nicephorus II Phocas Imperator Tact.",
    AuthorID("1566"): "Parmeno Iamb.",
    AuthorID("2945"): "Gnomologium Vaticanum",
    AuthorID("4149"): "Sophronius Gramm.",
    AuthorID("2000"): "Plotinus Phil.",
    AuthorID("0279"): "Discipulorum Cantiuncula",
    AuthorID("0445"): "Dionysius Comic.",
    AuthorID("2157"): "Magnus Hist.",
    AuthorID("1648"): "Pyrgion Hist.",
    AuthorID("4017"): "Syrianus Phil.",
    AuthorID("0615"): "Aspasius Phil.",
    AuthorID("1521"): "Vita Et Sententiae Secundi",
    AuthorID("1782"): "Augeas Comic.",
    AuthorID("3039"): "Joannes Galenus Gramm.",
    AuthorID("0234"): "Elegiaca Adespota (IEG)",
    AuthorID("2618"): "Didymarchus Poeta",
    AuthorID("0555"): "Clemens Alexandrinus Theol.",
    AuthorID("1633"): "Praxiteles [Epigr.]",
    AuthorID("1179"): "[Arimnestus] Phil.",
    AuthorID("1320"): "Diogenes Phil.",
    AuthorID("0401"): "Alexander Comic.",
    AuthorID("1136"): "Anonymus Presbyter Scr. Eccl.",
    AuthorID("0344"): "Melanthius Trag.",
    AuthorID("1970"): "Silenus Hist.",
    AuthorID("2115"): "Hippolytus Scr. Eccl.",
    AuthorID("4395"): "Menetor Hist.",
    AuthorID("4193"): "Anonymi In Aristotelis Sophisticos Elenchos Phil.",
    AuthorID("1242"): "Canon Librorum",
    AuthorID("1867"): "Crito Hist.",
    AuthorID("2533"): "Timolaus Hist.",
    AuthorID("2333"): "Possis Hist.",
    AuthorID("1174"): "Archemachus Hist.",
    AuthorID("2412"): "Androetas Hist.",
    AuthorID("1551"): "Oracula Sibyllina",
    AuthorID("0442"): "Dexicrates Comic.",
    AuthorID("0465"): "Heniochus Comic.",
    AuthorID("1311"): "Didache XII Apostolorum",
    AuthorID("2020"): "Theodosius Gramm.",
    AuthorID("0353"): "[Sclerias] Trag.",
    AuthorID("0420"): "Aristonymus Comic.",
    AuthorID("0825"): "Melito Trag.",
    AuthorID("1792"): "Biottus Comic.",
    AuthorID("0240"): "Hermolochus Lyr.",
    AuthorID("2187"): "Posidonius Hist.",
    AuthorID("1344"): "Epica Adespota (CA)",
    AuthorID("0514"): "Thugenides Comic.",
    AuthorID("0489"): "Philetaerus Comic.",
    AuthorID("0348"): "Biotus Trag.",
    AuthorID("0451"): "Epicrates Comic.",
    AuthorID("1369"): "Evangelium Mariae",
    AuthorID("0506"): "Stephanus Comic.",
    AuthorID("1406"): "Heraclides Hist.",
    AuthorID("4337"): "Heliodorus Alchem. et Poeta",
    AuthorID("2587"): "Ariston Phil.",
    AuthorID("3142"): "Georgius Pachymeres Hist.",
    AuthorID("1171"): "Apollonius Scr. Eccl.",
    AuthorID("5039"): "Scholia In Thucydidem",
    AuthorID("0485"): "Ophelio Comic.",
    AuthorID("2317"): "Hermias Phil.",
    AuthorID("1157"): "Apocalypsis Esdrae",
    AuthorID("2615"): "Daphitas Gramm. vel Soph.",
    AuthorID("0554"): "Chariton Scr. Erot.",
    AuthorID("2219"): "Amelesagoras Hist.",
    AuthorID("0250"): "Euclides Comic. vel Iamb.",
    AuthorID("0488"): "Philemon Junior Comic.",
    AuthorID("2762"): "Gennadius I Scr. Eccl.",
    AuthorID("0533"): "Callimachus Philol.",
    AuthorID("0209"): "Seleucus Lyr.",
    AuthorID("0383"): "Alcaeus Lyr.",
    AuthorID("0696"): "Alcmaeonis",
    AuthorID("2681"): "Diodorus Phil.",
    AuthorID("0298"): "Eumelus Epic.",
    AuthorID("1274"): "Cleobulus Epigr. et Lyr.",
    AuthorID("1329"): "Dionysius Scr. Eccl.",
    AuthorID("0505"): "Sotades Comic.",
    AuthorID("1231"): "[Bryson] Phil.",
    AuthorID("0522"): "Pisander Epic.",
    AuthorID("2021"): "Epiphanius Scr. Eccl.",
    AuthorID("1523"): "Myron Hist.",
    AuthorID("1188"): "Aristocles Phil.",
    AuthorID("1259"): "[Charondas Nomographus] [Phil.]",
    AuthorID("4302"): "Lexicon Patmense",
    AuthorID("5013"): "Scholia In Aratum",
    AuthorID("0469"): "Laon Comic.",
    AuthorID("1362"): "[Eurytus] Phil.",
    AuthorID("2228"): "Menestor Phil.",
    AuthorID("1186"): "Aristobulus Judaeus Phil.",
    AuthorID("0374"): "Licymnius Lyr.",
    AuthorID("2638"): "Philo Poeta",
    AuthorID("0396"): "Euphanes Comic.",
    AuthorID("1391"): "Hegemon Epic.",
    AuthorID("2466"): "Dionysius Hist.",
    AuthorID("2127"): "Troilus Soph.",
    AuthorID("4361"): "Apomasar Astrol.",
    AuthorID("5034"): "Scholia In Pindarum",
    AuthorID("0014"): "Demosthenes Orat.",
    AuthorID("2049"): "Sallustius Phil.",
    AuthorID("1815"): "Sappho et Alcaeus Lyr.",
    AuthorID("1546"): "Oechaliae Halosis",
    AuthorID("2040"): "Basilius Theol.",
    AuthorID("3027"): "Joannes Doxapatres Rhet.",
    AuthorID("0698"): "Alexander Rhet.",
    AuthorID("1766"): "Tatianus Apol.",
    AuthorID("0561"): "Longus Scr. Erot.",
    AuthorID("4311"): "Etymologicum Symeonis",
    AuthorID("1835"): "Agroetas Hist.",
    AuthorID("2042"): "Origenes Theol.",
    AuthorID("0369"): "Telesilla Lyr.",
    AuthorID("1643"): "Ptolemaeus Gramm.",
    AuthorID("0232"): "Archilochus Eleg. et Iamb.",
    AuthorID("4099"): "Etymologicum Magnum",
    AuthorID("4016"): "Ammonius Phil.",
    AuthorID("4034"): "Michael Phil.",
    AuthorID("0750"): "Heliodorus Trag.",
    AuthorID("0616"): "Polyaenus Rhet.",
    AuthorID("4201"): "Joannes Chortasmenus Phil.",
    AuthorID("2548"): "Promathion Hist.",
    AuthorID("0601"): "[Zaleucus Nomographus] [Phil.]",
    AuthorID("1121"): "Anaximenis Milesii Epistulae",
    AuthorID("3063"): "Joannes Scylitzes Hist.",
    AuthorID("1599"): "Philo Mech.",
    AuthorID("2282"): "Melisseus Hist.",
    AuthorID("1229"): "[Boeus] Epic.",
    AuthorID("1626"): "Polycrates Scr. Eccl.",
    AuthorID("1156"): "Apocalypsis Eliae",
    AuthorID("2010"): "Martyrium Dasii",
    AuthorID("4340"): "Salmanas Alchem.",
    AuthorID("0263"): "Solon Nomographus et Poeta",
    AuthorID("0343"): "Ezechiel Trag.",
    AuthorID("1381"): "Fragmentum Synodicae Epistulae Concilii Caesariensis",
    AuthorID("2234"): "Oenopides Phil.",
    AuthorID("2608"): "Archebulus Poeta",
    AuthorID("4334"): "[Isis Prophetissa] Alchem.",
    AuthorID("4076"): "Menander Protector Hist.",
    AuthorID("0009"): "Sappho Lyr.",
    AuthorID("0244"): "Cleobulina Scriptor Aenigmatum",
    AuthorID("2621"): "Diophilus vel Diophila Poeta",
    AuthorID("0493"): "Philostephanus Comic.",
    AuthorID("2162"): "Aratus Hist.",
    AuthorID("0325"): "Astydamas Trag.",
    AuthorID("0019"): "Aristophanes Comic.",
    AuthorID("0266"): "Tyrtaeus Eleg.",
    AuthorID("1949"): "Potamon Hist.",
    AuthorID("2116"): "Arcadius Gramm.",
    AuthorID("0690"): "Erasistratus Med.",
    AuthorID("1326"): "Dionysius Epic.",
    AuthorID("1698"): "Telephus Gramm.",
    AuthorID("1507"): "[Metopus] Phil.",
    AuthorID("0233"): "Hipponax Iamb.",
    AuthorID("4170"): "Vitae Pindari Et Varia De Pindaro",
    AuthorID("2027"): "Valerius Apsines Rhet.",
    AuthorID("0603"): "Silenus Trag.",
    AuthorID("5016"): "Scholia In Callimachum",
    AuthorID("5028"): "Scholia In Isocratem",
    AuthorID("0649"): "Lesbonax Rhet.",
    AuthorID("1141"): "Antimachus Epic.",
    AuthorID("1736"): "Timonax Hist.",
    AuthorID("2770"): "Callinicus Biogr.",
    AuthorID("0443"): "Diocles Comic.",
    AuthorID("1386"): "Historia Alexandri Magni",
    AuthorID("1771"): "Montanus et Montanistae Theol.",
    AuthorID("4392"): "Joannes Epiphaniensis Hist.",
    AuthorID("4000"): "Aristaenetus Epist.",
    AuthorID("2194"): "[Aristides] Hist.",
    AuthorID("3070"): "Symeon Logothetes Hist.",
    AuthorID("3045"): "Georgius Syncellus Chronogr.",
    AuthorID("2555"): "Agesilaus Hist.",
    AuthorID("0083"): "Dionysius Geogr.",
    AuthorID("0660"): "Apollonius Med.",
    AuthorID("2455"): "Aristocreon Hist.",
    AuthorID("1256"): "Chares Gnom.",
    AuthorID("5021"): "Scholia In Diophantum",
    AuthorID("1332"): "[Diotogenes] Phil.",
    AuthorID("0275"): "Peirazomene",
    AuthorID("1372"): "Evangelium Evae",
    AuthorID("5003"): "Erotica Adespota",
    AuthorID("1296"): "Cypria",
    AuthorID("0703"): "Numenius Poet. Didac.",
    AuthorID("1232"): "[Butherus] Phil.",
    AuthorID("2007"): "Martyrium Potamiaenae Et Basilidis",
    AuthorID("0604"): "Ptolemaeus IV Philopator Trag.",
    AuthorID("3043"): "Georgius Monachus Chronogr.",
    AuthorID("5008"): "Scholia In Aelium Aristidem",
    AuthorID("4335"): "Cleopatra Alchem.",
    AuthorID("2800"): "Basilius Scr. Eccl.",
    AuthorID("2635"): "Persinus Poeta",
    AuthorID("0478"): "Nausicrates Comic.",
    AuthorID("1953"): "Hieronymus Hist.",
    AuthorID("0326"): "Sophocles Junior Trag.",
    AuthorID("2816"): "Joannes Gramm. et Theol.",
    AuthorID("1691"): "Sotades Iamb.",
    AuthorID("1569"): "Pausanias Attic.",
    AuthorID("1343"): "Eparchides Hist.",
    AuthorID("2153"): "Bion Math. et Phil.",
    AuthorID("1490"): "[Megillus] Phil.",
    AuthorID("0332"): "Cleaenetus Trag.",
    AuthorID("1568"): "Parthax Hist.",
    AuthorID("0429"): "Cephisodorus Comic.",
    AuthorID("1729"): "Thrasymachus Rhet. et Soph.",
    AuthorID("2396"): "Hyperochus Hist.",
    AuthorID("1430"): "Hieronymus Phil.",
    AuthorID("0336"): "Crates Poet. Phil.",
    AuthorID("1096"): "Euaretus Trag.",
    AuthorID("1216"): "Barnabae Epistula",
    AuthorID("1757"): "Julius Epic.",
    AuthorID("0312"): "Philocles Trag.",
    AuthorID("1574"): "Persaeus Phil.",
    AuthorID(
        "9004"
    ): "Anonymi In Aristotelis Librum Alterum Analyticorum Posteriorum Commentarium",
    AuthorID("1969"): "Philinus Hist.",
    AuthorID("2357"): "Gorgon Hist.",
    AuthorID("1411"): "Heracliti Ephesii Epistulae",
    AuthorID("1402"): "Hephaestion Gramm.",
    AuthorID("2865"): "Olympiodorus Diaconus Scr. Eccl.",
    AuthorID("2330"): "Scamon Hist.",
    AuthorID("0421"): "Aristophon Comic.",
    AuthorID("0515"): "Timocles Comic.",
    AuthorID("1786"): "Sogenes Comic.",
    AuthorID("4327"): "Joannes Archiereus Alchem.",
    AuthorID("2239"): "Pythagoristae (D-K) Phil.",
    AuthorID("1327"): "Dionis Epistulae",
    AuthorID("4003"): "Marcianus Geogr.",
    AuthorID("0205"): "Philodamus Lyr.",
    AuthorID("2328"): "Diogenes Hist.",
    AuthorID("2474"): "Nicander Hist.",
    AuthorID("1371"): "Evangelium Petri",
    AuthorID("1132"): "Anonymus Alexandri Phil.",
    AuthorID("0044"): "Antiochi Regis Epistulae",
    AuthorID("2647"): "Zenothemis Geogr.",
    AuthorID("0307"): "Neophron Trag.",
    AuthorID("0345"): "Apollonides Trag.",
    AuthorID("2742"): "Apophthegmata",
    AuthorID("2058"): "Philostorgius Scr. Eccl.",
    AuthorID("0058"): "Aeneas Tact.",
    AuthorID("2059"): "Alexander Theol.",
    AuthorID("2475"): "Menecrates Hist.",
    AuthorID("2346"): "Andriscus Hist.",
    AuthorID("1270"): "Clearchus Phil.",
    AuthorID("1486"): "Matron Parodius",
    AuthorID("0749"): "Antyllus Med.",
    AuthorID("0254"): "Melanthius Eleg. et Trag.",
    AuthorID("1263"): "Choerilus Epic.",
    AuthorID("2227"): "Paron Phil.",
    AuthorID("0724"): "Stephanus Med. et Phil.",
    AuthorID("0481"): "Nicolaus Comic.",
    AuthorID("1544"): "Nymphis Hist.",
    AuthorID("5022"): "Scholia In Euclidem",
    AuthorID("0971"): "Oeniades Lyr.",
    AuthorID("0038"): "Arcesilai Epistula",
    AuthorID("0624"): "Demetrius Hist. et Phil.",
    AuthorID("2611"): "Butas Eleg.",
    AuthorID("1450"): "Ister Hist.",
    AuthorID("2609"): "Asopodorus Iamb.",
    AuthorID("4396"): "Timagetus Hist.",
    AuthorID("0447"): "Diphilus Comic.",
    AuthorID("0456"): "Euangelus Comic.",
    AuthorID("0713"): "Anaxagoras Phil.",
    AuthorID("4040"): "Photius Lexicogr., Scr. Eccl. et Theol.",
    AuthorID("2270"): "Callippus Hist.",
    AuthorID("2589"): "Olympiodorus Alchem.",
    AuthorID("0648"): "Onasander Tact.",
    AuthorID("0295"): "Carmina Popularia (PMG)",
    AuthorID("2322"): "Antenor Hist.",
    AuthorID("1224"): "Bion Phil.",
    AuthorID("2383"): "Diodorus Phil.",
    AuthorID("2387"): "Athanis Hist.",
    AuthorID("2117"): "Anonymus De Metrorum Ratione",
    AuthorID("2226"): "Iccus Phil.",
    AuthorID("3047"): "Michael Glycas Astrol. et Hist.",
    AuthorID("4019"): "Olympiodorus Phil.",
    AuthorID("0090"): "Agathemerus Geogr.",
    AuthorID("0605"): "Polybius Rhet.",
    AuthorID("0733"): "Cassius Iatrosophista Med.",
    AuthorID("0028"): "Antiphon Orat.",
    AuthorID("0564"): "Rufus Med.",
    AuthorID("0551"): "Appianus Hist.",
    AuthorID("2605"): "Agamestor Eleg.",
    AuthorID("0288"): "Pisander Epic.",
    AuthorID("0315"): "Sthenelus Trag.",
    AuthorID("1632"): "Posidippus Epigr.",
    AuthorID("1845"): "Callistratus Trag.",
    AuthorID("0752"): "Eutecnius Soph.",
    AuthorID("2345"): "Agl(a)osthenes Hist.",
    AuthorID("3075"): "Pseudo-Mauricius Tact.",
    AuthorID("1713"): "Themison Hist.",
    AuthorID("1374"): "Evangelium Secundum Hebraeos",
    AuthorID("0538"): "Hecataeus Hist.",
    AuthorID("2655"): "[Damigeron Magus]",
    AuthorID("0045"): "Artaxerxis Epistulae",
    AuthorID("2031"): "Sopater Rhet.",
    AuthorID("0876"): "Phrynichus II Trag.",
    AuthorID("0490"): "Philippides Comic.",
    AuthorID("4037"): "Anonymi Paradoxographi",
    AuthorID("0203"): "Limenius Lyr.",
    AuthorID("4029"): "Procopius Hist.",
    AuthorID("1728"): "Theseus Hist.",
    AuthorID("0556"): "Asclepiodotus Tact.",
    AuthorID("1679"): "Socrates Hist.",
    AuthorID("3173"): "Joannes Theol.",
    AuthorID("2230"): "Boïdas Phil.",
    AuthorID("1483"): "Martyrium Et Ascensio Isaiae",
    AuthorID("2118"): "Gryllus",
    AuthorID("0088"): "Aristoxenus Mus.",
    AuthorID("1269"): "Cleanthes Phil.",
    AuthorID("0521"): "Epicharmus Comic. et Pseudepicharmea",
    AuthorID("2971"): "Georgius Peccator Poeta",
    AuthorID("1211"): "Balagrus Hist.",
    AuthorID("0716"): "Erotianus Gramm. et Med.",
    AuthorID("4139"): "Severianus Scr. Eccl.",
    AuthorID("5017"): "Scholia In Demosthenem",
    AuthorID("1498"): "Menander Hist.",
    AuthorID("0054"): "[Theano] Phil.",
    AuthorID("0364"): "Danaïs vel Danaïdes",
    AuthorID("0544"): "Sextus Empiricus Phil.",
    AuthorID("4147"): "Florilegium Cyrillianum",
    AuthorID("0536"): "Ephorus Hist.",
    AuthorID("0386"): "Chilonis Epistula",
    AuthorID("0516"): "Timostratus Comic.",
    AuthorID("0339"): "Moschion Trag.",
    AuthorID("2617"): "Demetrius Poeta",
    AuthorID("0067"): "Agatharchides Geogr.",
    AuthorID("1754"): "Xenophontis Epistulae",
    AuthorID("0457"): "Eubulides Comic.",
    AuthorID("1148"): "Antonius Diogenes Scr. Erot.",
    AuthorID("4397"): "Myronianus Hist.",
    AuthorID("0282"): "Anonymus De Viribus Herbarum",
    AuthorID("1541"): "Nostoi",
    AuthorID("1094"): "Theodorides Trag.",
    AuthorID("0592"): "Hermogenes Rhet.",
    AuthorID("1475"): "Maiistas Epic.",
    AuthorID("0602"): "Comica Adespota (FCG)",
    AuthorID("1432"): "[Hipparchus] Phil.",
    AuthorID("1305"): "Democritus Hist.",
    AuthorID("0833"): "Anaxion Trag.",
    AuthorID("0472"): "Lysippus Comic.",
    AuthorID("2029"): "Anonymi Geographia In Sphaera Intelligenda",
    AuthorID("0283"): "Heraclides Ponticus Junior Gramm.",
    AuthorID("1625"): "Polyclitus Phil.",
    AuthorID("4166"): "Vitae Aeschinis",
    AuthorID("3023"): "Constantinus VII Porphyrogenitus Imperator Hist.",
    AuthorID("1364"): "Evangelium Aegyptium",
    AuthorID("0125"): "Zenonis Epistula",
    AuthorID("4021"): "David Phil.",
    AuthorID("1146"): "Antipater Phil.",
    AuthorID("0466"): "Heraclides Comic.",
    AuthorID("1360"): "[Euryphamus] Phil.",
    AuthorID("1387"): "(H)agias-Dercylus Hist.",
    AuthorID("1688"): "Sostratus Gramm.",
    AuthorID("4094"): "Choricius Rhet. et Soph.",
    AuthorID("1702"): "Testamentum Jobi",
    AuthorID("0579"): "Orphica",
    AuthorID("0001"): "Apollonius Rhodius Epic.",
    AuthorID("0462"): "Euthycles Comic.",
    AuthorID("0455"): "Eriphus Comic.",
    AuthorID("1611"): "Tyrannion Junior Gramm.",
    AuthorID("0572"): "Gaius Scr. Eccl.",
    AuthorID("4096"): "Dositheus Magister Gramm.",
    AuthorID("0496"): "Phrynichus Comic.",
    AuthorID("0422"): "Athenio Comic.",
    AuthorID("0261"): "Simonides Lyr.",
    AuthorID("4300"): "Lexicon Sabbaiticum",
    AuthorID("2679"): "Testamentum Salomonis",
    AuthorID("1277"): "[Clinias] Phil.",
    AuthorID("0666"): "Adrianus Rhet. et Soph.",
    AuthorID("2583"): "Manetho Astrol.",
    AuthorID("2641"): "Priscus Epic.",
    AuthorID("0370"): "Lamprocles Lyr.",
    AuthorID("1839"): "Polyphrasmon Trag.",
    AuthorID("1124"): "Andronicus Rhodius Phil.",
    AuthorID("2542"): "Quintus Fabius Pictor Hist.",
    AuthorID("2680"): "Scythinus Epigr.",
    AuthorID("0523"): "Menecrates Comic.",
    AuthorID("4242"): "Cyrus Rhet.",
    AuthorID("1431"): "Hipparchus Astron. et Geogr.",
    AuthorID("0204"): "Aristonous Lyr.",
    AuthorID("0720"): "Harmodius Trag.",
    AuthorID("7051"): "Doctrina Patrum",
    AuthorID("4082"): "Musaeus Grammaticus Epic.",
    AuthorID("0056"): "Thrasybuli Epistula",
    AuthorID("0746"): "Theophilus Protospatharius et Stephanus Atheniensis Med.",
    AuthorID("1840"): "Euripides II Trag.",
    AuthorID("2531"): "Metrophanes Hist.",
    AuthorID("0541"): "Menander Comic.",
    AuthorID("3145"): "Joannes Anagnostes Hist. et Poeta",
    AuthorID("0449"): "Ecphantides Comic.",
    AuthorID("1945"): "Antigenes Hist.",
    AuthorID("3168"): "Pseudo-Codinus Hist.",
    AuthorID("1358"): "Eudoxus Astron.",
    AuthorID("1298"): "Demetrii Phalerei Epistula",
    AuthorID("1180"): "[Aristaeus] Phil.",
    AuthorID("1524"): "Naumachius Epic.",
    AuthorID("4184"): "Dionysius Soph.",
    AuthorID("0631"): "Pittacus [Lyr.]",
    AuthorID("0273"): "Scolia Alphabetica",
    AuthorID("0212"): "Philetas Eleg. et Gramm.",
    AuthorID("5014"): "Scholia In Aristophanem",
    AuthorID("0392"): "Acusilaus Hist.",
    AuthorID("9012"): "Ignatius Biogr. et Poeta",
    AuthorID("2217"): "Nicias Hist.",
    AuthorID("0034"): "Lycurgus Orat.",
    AuthorID("1488"): "Maximus Theol.",
    AuthorID("1464"): "Liber Jubilaeorum",
    AuthorID("1787"): "[Menippus] Comic.",
    AuthorID("1735"): "Timon Phil.",
    AuthorID("4394"): "Joannes Antiochenus Hist.",
    AuthorID("0012"): "Homerus Epic., Homer",
    AuthorID("0264"): "Susarion Comic.",
    AuthorID("2598"): "Procopius Rhet. et Scr. Eccl.",
    AuthorID("2274"): "Hesychius Illustrius Hist.",
    AuthorID("0096"): "Aesopus Scr. Fab. et Aesopica",
    AuthorID("1976"): "Metrodorus Hist.",
    AuthorID("2291"): "Cratylus Phil.",
    AuthorID("0394"): "Apollonius Comic.",
    AuthorID("0341"): "Lycophron Trag.",
    AuthorID("0718"): "Aëtius Med.",
    AuthorID("0691"): "Harpocrationis Epistula",
    AuthorID("0688"): "Agathocles Hist.",
    AuthorID("1286"): "Corpus Hermeticum",
    AuthorID("1799"): "Euclides Geom.",
    AuthorID("0416"): "Archedicus Comic.",
    AuthorID("0290"): "Encomium Ducis Thebaidos",
    AuthorID("2062"): "Joannes Chrysostomus Scr. Eccl., John Chrysostom",
    AuthorID("2336"): "Hereas Hist.",
    AuthorID("0239"): "Antimachus Eleg. et Epic.",
    AuthorID("1811"): "Metrodorus Major Phil.",
    AuthorID("0377"): "Telestes Lyr.",
    AuthorID("4039"): "Paulus Silentiarius Poeta",
    AuthorID("1676"): "Simylus Iamb.",
    AuthorID("1981"): "Theophanes Hist.",
    AuthorID("1485"): "Martyrium Ptolemaei Et Lucii",
    AuthorID("0502"): "Sophilus Comic.",
    AuthorID("1506"): "Menodotus Hist.",
    AuthorID("0426"): "Callias Comic.",
    AuthorID("3130"): "Theophylactus Simocatta Epist. et Hist.",
    AuthorID("0734"): "[Lucas Apostolus] Med.",
    AuthorID("0497"): "Plato Comic.",
    AuthorID("0460"): "Euphro Comic.",
    AuthorID("1664"): "Seniores Alexandrini Scr. Eccl.",
    AuthorID("1583"): "Phanodemus Hist.",
    AuthorID("4165"): "Anonymi In Aristotelis Librum De Interpretatione Phil.",
    AuthorID("0499"): "Polyzelus Comic.",
    AuthorID("2025"): "Maximus Rhet.",
    AuthorID("2355"): "Xeniades Soph.",
    AuthorID("0334"): "Diogenes Phil. et Trag.",
    AuthorID("2205"): "Autesion Hist.",
    AuthorID("4091"): "Callistratus Soph.",
    AuthorID("0453"): "Epilycus Comic.",
    AuthorID("0643"): "Anonymus Londinensis Med.",
    AuthorID("3120"): "Patria Constantinopoleos",
    AuthorID("0981"): "Stesichorus II Lyr.",
    AuthorID("1549"): "[Onatas] Phil.",
    AuthorID("0338"): "Sosiphanes Trag.",
    AuthorID("2972"): "Anonymi De Terrae Motibus",
    AuthorID("1302"): "Demetrius Rhet.",
    AuthorID("0046"): "Niciae Epistula",
    AuthorID("1328"): "Dionysius Hist.",
    AuthorID("1365"): "Melampus Scriptor De Divinatione",
    AuthorID("2218"): "Calliphon et Democedes Med. et Phil.",
    AuthorID("4304"): "Glossae In Herodotum",
    AuthorID("0360"): "Armenidas Hist.",
    AuthorID("3002"): "Prolegomena De Comoedia",
    AuthorID("2557"): "[Aristobulus] Hist.",
    AuthorID("2030"): "Geographica Adespota (GGM)",
    AuthorID("0744"): "Alexander Med.",
    AuthorID("1750"): "Vitae Prophetarum",
    AuthorID("0543"): "Polybius Hist.",
    AuthorID("1607"): "Phoronis",
    AuthorID("4072"): "Eutocius Math.",
    AuthorID("1977"): "Lucius Licinius Lucullus Hist.",
    AuthorID("1276"): "Clidemus Hist.",
    AuthorID("1941"): "Leo Hist.",
    AuthorID("4325"): "[Hermes] Alchem.",
    AuthorID("2458"): "Marcellus Hist.",
    AuthorID("2294"): "Zeno Phil.",
    AuthorID("0653"): "Aratus Astron. et Epic.",
    AuthorID("0482"): "Nicomachus Comic.",
    AuthorID("4332"): "Hierotheus Alchem. et Poeta",
    AuthorID("1414"): "Heraclitus Phil.",
    AuthorID("0727"): "Joannes Med.",
    AuthorID("0598"): "Rhetorica Anonyma",
    AuthorID("1203"): "Paeanes (CA)",
    AuthorID("1505"): "Menesthenes Hist.",
    AuthorID("4028"): "Stephanus Gramm.",
    AuthorID("2645"): "Stratonicus Poeta",
    AuthorID("1665"): "Seniores Apud Irenaeum Scr. Eccl.",
    AuthorID("0349"): "Demonax [Trag.]",
    AuthorID("1670"): "Serapion Scr. Eccl.",
    AuthorID("1398"): "Hegesippus Scr. Eccl.",
    AuthorID("0412"): "Apollodorus Carystius vel Apollodorus Gelous Comic.",
    AuthorID("2160"): "Pyrrhus Hist.",
    AuthorID("9021"): "Stephanus Alchem.",
    AuthorID("1530"): "Nicanor Gramm.",
    AuthorID("0397"): "Pronomus Lyr.",
    AuthorID("2181"): "Moses Alchem.",
    AuthorID("2697"): "Timolaus Rhet.",
    AuthorID("2560"): "Pythocles Hist.",
    AuthorID("1083"): "Isigonus Paradox.",
    AuthorID("1315"): "Dinolochus Comic.",
    AuthorID("1389"): "Harpocration Gramm.",
    AuthorID("2456"): "Nessas Phil.",
    AuthorID("1515"): "Moeris Attic.",
    AuthorID("2032"): "Pappus Math.",
    AuthorID("0027"): "Andocides Orat.",
    AuthorID("2937"): "Lachares Soph.",
    AuthorID("0900"): "Cleomenes Lyr.",
    AuthorID("0549"): "Apollodorus Gramm.",
    AuthorID("2423"): "Asclepiades Gramm. et Hist.",
    AuthorID("1732"): "Timachidas Hist.",
    AuthorID("1734"): "Timaeus Phil.",
    AuthorID("2539"): "Diophantus Hist.",
    AuthorID("2192"): "[Agatharchides] Hist.",
    AuthorID("5037"): "Scholia In Sophoclem",
    AuthorID("2225"): "Parm(en)iscus Phil.",
    AuthorID("0297"): "Lyrica Adespota (PMG)",
    AuthorID("0646"): "Pseudo-Justinus Martyr",
    AuthorID("4347"): "Andron Hist.",
    AuthorID("1004"): "Thessalus Astrol. et Med.",
    AuthorID("1310"): "Dictys Hist.",
    AuthorID("1303"): "Demochares Hist. et Orat.",
    AuthorID("0098"): "Zenobius Sophista [Paroemiogr.]",
    AuthorID("0198"): "Hedylus Epigr.",
    AuthorID("1821"): "Iambica Adespota (ALG)",
    AuthorID("2568"): "[Sosthenes] Hist.",
    AuthorID("0606"): "Rufus Soph.",
    AuthorID("2714"): "Theodorus Studites Scr. Eccl. et Theol.",
    AuthorID("1325"): "Diogenis Sinopensis Epistulae",
    AuthorID("4105"): "Julianus Scr. Eccl.",
    AuthorID("1349"): "Epistula A Martyribus Lugdunensibus",
    AuthorID("1832"): "Acesander Hist.",
    AuthorID("0498"): "Poliochus Comic.",
    AuthorID("1476"): "Mamercus Eleg.",
    AuthorID("2006"): "Synesius Phil.",
    AuthorID("0249"): "Echembrotus Eleg. et Lyr.",
    AuthorID("1637"): "Protevangelium Jacobi",
    AuthorID("3169"): "Joannes VI Cantacuzenus",
    AuthorID("2642"): "[Astrampsychus Magus] Onir.",
    AuthorID("0340"): "Sositheus Trag.",
    AuthorID("2048"): "Salaminius Hermias Sozomenus Scr. Eccl.",
    AuthorID("1812"): "Demaratus Hist.",
    AuthorID("2807"): "Antonius Hagiographus Scr. Eccl.",
    AuthorID("1491"): "Melanthius Hist.",
    AuthorID("0331"): "[Polyidus] Trag.",
    AuthorID("2215"): "Ar(i)aethus Hist.",
    AuthorID("4391"): "Glaucus Hist.",
    AuthorID("1479"): "Marci Aurelii Epistula",
    AuthorID("1427"): "Herodorus Hist.",
    AuthorID("1508"): "Metrodorus Phil.",
    AuthorID("3136"): "Pseudo-Zonaras Lexicogr.",
    AuthorID("2169"): "Herillus Phil.",
    AuthorID("2729"): "Prorus Phil.",
    AuthorID("1281"): "[Clitophon] Hist.",
    AuthorID("1289"): "Crates Hist.",
    AuthorID("0041"): "Chionis Epistulae",
    AuthorID("0418"): "Aristagoras Comic.",
    AuthorID("2594"): "Phillis Hist.",
    AuthorID("1451"): "Josephus Et Aseneth",
    AuthorID("0237"): "Anacreon Lyr.",
    AuthorID("1308"): "Demosthenes Epic.",
    AuthorID("2636"): "Pherenicus Epic.",
    AuthorID("0301"): "Thespis Trag.",
    AuthorID("0082"): "Apollonius Dyscolus Gramm.",
    AuthorID("0127"): "Aulus Licinius Archias Epigr.",
    AuthorID("0260"): "Semonides Eleg. et Iamb.",
    AuthorID("0484"): "Nicostratus Comic.",
    AuthorID("0513"): "Theopompus Comic.",
    AuthorID("1447"): "Irenaeus Theol.",
    AuthorID("1247"): "[Cebes] Phil.",
    AuthorID("0230"): "Lyrica Adespota (CA)",
    AuthorID("0286"): "Carmen Astrologicum",
    AuthorID("4089"): "Theodoretus Scr. Eccl. et Theol.",
    AuthorID("1813"): "Anonymus De Plantis Aegyptiis",
    AuthorID("0477"): "Myrtilus Comic.",
    AuthorID("1794"): "Philocles Comic.",
    AuthorID("3094"): "Nicetas Choniates Hist., Scr. Eccl. et Rhet.",
    AuthorID("0581"): "Paradoxographus Palatinus",
    AuthorID("2278"): "Phanodicus Hist.",
    AuthorID("1239"): "Domitius Callistratus Hist.",
    AuthorID("0053"): "Phalaridis Epistulae",
    AuthorID("0272"): "De Arboribus Avibusque Fabulae",
    AuthorID("0657"): "Crateuas Med.",
    AuthorID("1775"): "Pseudo-Agathon Epigr.",
    AuthorID("0371"): "Diagoras Lyr.",
    AuthorID("2240"): "Hicetas Phil.",
    AuthorID("1383"): "Geminus Astron.",
    AuthorID("1165"): "Apollodorus Mech.",
    AuthorID("1606"): "Phoenix Iamb.",
    AuthorID("4005"): "Anonymus Discipulus Isidori Milesii Mech.",
    AuthorID("2189"): "Callinicus Soph.",
    AuthorID("2233"): "Pseudo-Polemon",
    AuthorID("0655"): "Parthenius Myth.",
    AuthorID("2625"): "Herodicus Gramm.",
    AuthorID("1814"): "Ptolemais Phil.",
    AuthorID("1133"): "Anonymus Diodori Phil.",
    AuthorID("2133"): "Achilles Tatius Astron.",
    AuthorID("1301"): "Demetrius Poet. Phil.",
    AuthorID("0197"): "Hedyle Epigr.",
    AuthorID("0071"): "Periplus Maris Erythraei",
    AuthorID("0289"): "Ammonius Epigr.",
    AuthorID("4150"): "Anacreontea",
    AuthorID("1285"): "Conon Hist.",
    AuthorID("3177"): "Scriptor Incertus De Leone Armenio Hist.",
    AuthorID("1275"): "Cleostratus Poet. Phil.",
    AuthorID("1297"): "Damippus Phil.",
    AuthorID("2601"): "Tiberius Rhet.",
    AuthorID("2241"): "Xenophilus Mus. et Phil.",
    AuthorID("1685"): "Sosibius Gramm.",
    AuthorID("0450"): "Ephippus Comic.",
    AuthorID("5010"): "Scholia In Aeschylum",
    AuthorID("2235"): "Hippocrates Math.",
    AuthorID("1577"): "Phaedimus Epigr.",
    AuthorID("1802"): "Homerica",
    AuthorID("2367"): "Theognis Hist.",
    AuthorID("1282"): "Clytus Hist.",
    AuthorID("5032"): "Scholia In Oppianum",
    AuthorID("0611"): "Theodorus Trag.",
    AuthorID("1682"): "Sopater Comic.",
    AuthorID("1788"): "Phormis Comic.",
    AuthorID("1125"): "Androtion Hist.",
    AuthorID("1649"): "Pythaenetus Hist.",
    AuthorID("1662"): "Sciras Comic.",
    AuthorID("2151"): "Praxagoras Hist.",
    AuthorID("3015"): "Joannes Cameniates Hist.",
    AuthorID("1675"): "Simylus Eleg.",
    AuthorID("0441"): "Demonicus Comic.",
    AuthorID("2255"): "Gorgias Hist.",
    AuthorID("2246"): "Lycon Phil.",
    AuthorID("1912"): "Euphantus Phil.",
    AuthorID("2229"): "Xuthus Phil.",
    AuthorID("4329"): "Philosophus Anonymus Alchem.",
    AuthorID("4014"): "Priscianus Phil.",
    AuthorID("0593"): "Gorgias Rhet. et Soph.",
    AuthorID("2334"): "Nausiphanes Phil.",
    AuthorID("1322"): "Diogenianus Phil.",
    AuthorID("0294"): "Corinna Lyr.",
    AuthorID("0008"): "Athenaeus Soph.",
    AuthorID("0199"): "Bacchylides Lyr.",
    AuthorID("0548"): "Pseudo-Apollodorus Myth.",
    AuthorID("1687"): "Sosicrates Hist.",
    AuthorID("2532"): "[Hermesianax] Hist.",
    AuthorID("0049"): "Pisistrati Epistula",
    AuthorID("0531"): "Hermias Apol.",
    AuthorID("1727"): "Theotimus Hist.",
    AuthorID("3146"): "Ducas Hist.",
    AuthorID("2620"): "Dionysius Iambus Gramm. et Poeta",
    AuthorID("5048"): "Scholia In Clementem Alexandrinum",
    AuthorID("2967"): "Theodorus Heracleensis vel Theodorus Mopsuestenus Scr. Eccl.",
    AuthorID("1710"): "[Theages] Phil.",
    AuthorID("3079"): "Michael Attaliates Hist.",
    AuthorID("2701"): "Georgius Pisides Poeta",
    AuthorID("0619"): "Apollonius Phil.",
    AuthorID("1816"): "Epica Adespota (GDRK)",
    AuthorID("2556"): "[Alexarchus] Hist.",
    AuthorID("1319"): "Diogenes Phil.",
    AuthorID("1352"): "Epistula Ecclesiarum Apud Lugdunum Et Viennam",
    AuthorID("1399"): "Pamphilus Trag.",
    AuthorID("2196"): "[Dercyllus] Hist.",
    AuthorID("0361"): "Cleonides Mus.",
    AuthorID("2592"): "Joannes Pediasimus Philol. et Rhet.",
    AuthorID("1382"): "Fragmentum Teliambicum",
    AuthorID("1567"): "Parrhasius Epigr.",
    AuthorID("1590"): "Philippus Hist.",
    AuthorID("0618"): "Antigoni Epistula",
    AuthorID("1667"): "[Septem Sapientes] Phil.",
    AuthorID("1138"): "Lycon Phil.",
    AuthorID("3128"): "Theognostus Gramm.",
    AuthorID("0243"): "Callinus Eleg.",
    AuthorID("1595"): "Philodemus Phil.",
    AuthorID("1753"): "Xenion Hist.",
    AuthorID("3147"): "Michael Critobulus Hist.",
    AuthorID("1441"): "Iamblichus Scr. Erot.",
    AuthorID("1143"): "Antiochus Phil.",
    AuthorID("1556"): "Pancrates Epigr.",
    AuthorID("2585"): "Marcellinus Biogr.",
    AuthorID("0586"): "Polemon Perieg.",
    AuthorID("2610"): "Boiscus Iamb.",
    AuthorID("1318"): "Diodorus Rhet.",
    AuthorID("1663"): "Semus Gramm.",
    AuthorID("0211"): "Simias Gramm.",
    AuthorID("0051"): "[Melissa] Phil.",
    AuthorID("0430"): "Chariclides Comic.",
    AuthorID("1911"): "Diyllus Hist.",
    AuthorID("3155"): "Joannes Protospatharius Gramm.",
    AuthorID("4333"): "Nicephorus Blemmydes Alchem.",
    AuthorID("1500"): "Menecrates Poet. Phil.",
    AuthorID("3157"): "Theodorus Scutariota Hist.",
    AuthorID("1896"): "[Dositheus] Hist.",
    AuthorID("1287"): "Crantor Phil.",
    AuthorID("1800"): "Euboeus Parodius",
    AuthorID("0723"): "Leo Phil.",
    AuthorID("3178"): "Anonymi Lexeis Rhetoricae",
    AuthorID("1323"): "Aelius Dionysius Attic.",
    AuthorID("0578"): "Nymphodorus Hist.",
    AuthorID("2074"): "Apollinaris Theol.",
    AuthorID("1737"): "Titanomachia",
    AuthorID("2623"): "Euanthes Epic.",
    AuthorID("2036"): "Dexippus Phil.",
    AuthorID("4345"): "Menecrates Hist.",
    AuthorID("0717"): "Hypsicles Astron. et Math.",
    AuthorID("1803"): "Bruti Epistulae",
    AuthorID("2738"): "Chronographiae Anonymae",
    AuthorID("4163"): "Telegonia",
    AuthorID("2111"): "Palladius Scr. Eccl.",
    AuthorID("0023"): "Oppianus Epic.",
    AuthorID("2041"): "Marcellus Theol.",
    AuthorID("2499"): "Eustochius Soph.",
    AuthorID("0574"): "Lysimachus Hist.",
    AuthorID("1638"): "Proxenus Hist.",
    AuthorID("0089"): "Praxiphanes Phil.",
    AuthorID("2614"): "Cleomachus Poeta",
    AuthorID("0621"): "[Ath]enodorus Trag.",
    AuthorID("1712"): "Thebaïs",
    AuthorID("1493"): "Melinno Lyr.",
    AuthorID("0372"): "Praxilla Lyr.",
    AuthorID("1353"): "Epitaphium Abercii",
    AuthorID("2626"): "Hipparchus Parodius",
    AuthorID("1804"): "Ninus",
    AuthorID("5024"): "Anonymi In Hermogenem Rhet.",
    AuthorID("0740"): "Jusjurandum Medicum",
    AuthorID("5000"): "Concilia Oecumenica (ACO)",
    AuthorID("2349"): "[Pyrander] Hist.",
    AuthorID("1512"): "Minyas",
    AuthorID("0068"): "Pseudo-Scymnus Geogr.",
    AuthorID("2630"): "Lobo Poeta",
    AuthorID("1175"): "Archestratus Parodius",
    AuthorID("2284"): "Anaxandridas Hist.",
    AuthorID("0708"): "[Ammonius] Gramm.",
    AuthorID("1230"): "[Brotinus] Phil.",
    AuthorID("1608"): "Phrynichus Attic.",
    AuthorID("1756"): "Demetrius Gramm.",
    AuthorID("2506"): "Capito Hist.",
    AuthorID("0617"): "Anaximenes Phil.",
    AuthorID("0350"): "[Dionysius Scymnaeus] Trag. vel Comic.",
    AuthorID("0504"): "Sosipater Comic.",
    AuthorID("1972"): "Eumachus Hist.",
    AuthorID("2034"): "Porphyrius Phil.",
    AuthorID("1115"): "Archestratus Trag.",
    AuthorID("0335"): "Philiscus Trag.",
    AuthorID("1557"): "Panyassis Epic.",
    AuthorID("1495"): "Melito Apol.",
    AuthorID("4157"): "Joannes Rhet.",
    AuthorID("1376"): "Eudemus Rhet.",
    AuthorID("5027"): "Scholia In Iamblichum Philosophum",
    AuthorID("5029"): "Scholia In Lucianum",
    AuthorID("2607"): "Alexinus Phil.",
    AuthorID("3176"): "Pseudo-Sphrantzes Hist.",
    AuthorID("0439"): "Demetrius Comic.",
    AuthorID("1690"): "Sotadea",
    AuthorID("0061"): "Pseudo-Lucianus Soph.",
    AuthorID("0235"): "Iambica Adespota (IEG)",
    AuthorID("2691"): "[Musaeus] Phil.",
    AuthorID("1428"): "Hestiaeus Hist.",
    AuthorID("1954"): "Heraclides Phil.",
    AuthorID("2243"): "Apocalypsis Sedrach",
    AuthorID("1622"): "Polycarpus Scr. Eccl.",
    AuthorID("2175"): "[Autocharis] Hist.",
    AuthorID("2693"): "Ptolemaeus III Euergetes I [Epigr.]",
    AuthorID("2651"): "Artemidorus Eleg.",
    AuthorID("0748"): "Severus Iatrosophista Med.",
    AuthorID("2033"): "Theon Math.",
    AuthorID("0206"): "Theocles Lyr.",
    AuthorID("2242"): "Echecrates Phil.",
    AuthorID("4024"): "Agathias Scholasticus Epigr. et Hist.",
    AuthorID("0583"): "Philochorus Hist.",
    AuthorID("0219"): "Rhianus Epic.",
    AuthorID("1482"): "Cyranides",
    AuthorID("1334"): "Dius Phil.",
    AuthorID("0628"): "Gaius Musonius Rufus Phil.",
    AuthorID("1164"): "Apollodorus Hist.",
    AuthorID("1254"): "Charax Hist.",
    AuthorID("2461"): "Uranius Hist.",
    AuthorID("1208"): "Atticus Phil.",
    AuthorID("0530"): "Pseudo-Galenus Med.",
    AuthorID("0277"): "Monodia",
    AuthorID("9019"): "Stephanus Phil.",
    AuthorID("4038"): "Pamprepius Epic.",
    AuthorID("1293"): "Crinis Phil.",
    AuthorID("0622"): "Cleobuli Epistula",
    AuthorID("0013"): "Hymni Homerici, Homeric Hymns",
    AuthorID("1791"): "Menandri Et Philistionis Sententiae",
    AuthorID("2289"): "Echephylidas Hist.",
    AuthorID("0656"): "Dioscorides Pedanius Med.",
    AuthorID("4027"): "Anonymi In Aristotelis Categorias Phil.",
    AuthorID("1278"): "Clitarchus Gnom.",
    AuthorID("0236"): "Alcibiades [Eleg.]",
    AuthorID("0207"): "Hermocles Lyr.",
    AuthorID("4172"): "Vitae Oppiani",
    AuthorID("0221"): "Euphorion Epic.",
    AuthorID("0245"): "Demodocus Eleg.",
    AuthorID("5012"): "Scholia In Apollonium Rhodium",
    AuthorID("4282"): "Anonymus Manichaeus Biogr.",
    AuthorID("0086"): "Aristoteles Phil. et Corpus Aristotelicum, Aristotle",
    AuthorID("2386"): "Timonides Hist.",
    AuthorID("1466"): "Lollianus Scr. Erot.",
    AuthorID("2171"): "Stesiclides Hist.",
    AuthorID("0065"): "Scylax Perieg.",
    AuthorID("0650"): "Herodas Mimogr.",
    AuthorID("1635"): "Protagoras Soph.",
    AuthorID("3125"): "Theodosius Diaconus Hist. et Poeta",
    AuthorID("2121"): "Dioscorus Poeta",
    AuthorID("2340"): "Diotimus Phil.",
    AuthorID("2871"): "Joannes Malalas Chronogr.",
    AuthorID("1445"): "Iliu Persis",
    AuthorID("2962"): "Petrus Scr. Eccl. et Theol.",
    AuthorID("0200"): "Mantissa Proverbiorum",
    AuthorID("1346"): "Ephraem Scr. Eccl.",
    AuthorID("2045"): "Nonnus Epic.",
    AuthorID("0030"): "Hyperides Orat.",
    AuthorID("2591"): "Orion Gramm.",
    AuthorID("2479"): "Patrocles Hist.",
    AuthorID("0255"): "Mimnermus Eleg.",
    AuthorID("1533"): "Nicias Epigr.",
    AuthorID("2275"): "Theagenes Phil.",
    AuthorID("0316"): "Xenocles Trag.",
    AuthorID("1571"): "[Pempelus] Phil.",
    AuthorID("2695"): "Vitae Aristotelis",
    AuthorID("0510"): "Teleclides Comic.",
    AuthorID("0087"): "Aelius Herodianus et Pseudo-Herodianus Gramm. et Rhet.",
    AuthorID("0210"): "Euphronius Lyr.",
    # AuthorID("DOCCAN2"): "TLG Canon, data base",
    AuthorID("2305"): "Clidemus Phil.",
    AuthorID("0048"): "Philippus II Rex Macedonum [Epist.]",
    AuthorID("1609"): "Phylarchus Hist.",
    AuthorID("1494"): "Melissus Phil.",
    AuthorID("0085"): "Aeschylus Trag.",
    AuthorID("1181"): "Aristarchus Astron.",
    AuthorID("0532"): "Achilles Tatius Scr. Erot.",
    AuthorID("0528"): "Aëtius Doxogr.",
    AuthorID("2616"): "Demareta Poeta",
    AuthorID("4026"): "Anonymi In Aristotelis Artem Rhetoricam Rhet.",
    AuthorID("1459"): "Lepidus Hist.",
    AuthorID("0384"): "Acta Justini Et Septem Sodalium",
    AuthorID("0213"): "Hermesianax Eleg.",
    AuthorID("4161"): "Vitae Arati Et Varia De Arato",
    AuthorID("1168"): "Apollonius Soph.",
    AuthorID("0405"): "Anaxandrides Comic.",
    AuthorID("0378"): "Ariphron Lyr.",
    AuthorID("0300"): "Acta Alexandrinorum",
    AuthorID("4098"): "Etymologicum Gudianum",
    AuthorID("0016"): "Herodotus Hist.",
    AuthorID("1192"): "Ariston Phil.",
    AuthorID("0352"): "Isidorus Trag.",
    AuthorID("0471"): "Lynceus Comic.",
    AuthorID("2213"): "[Timotheus] Hist.",
    AuthorID("1503"): "Menecrates Hist.",
    AuthorID("0609"): "Tryphon I Gramm.",
    AuthorID("1162"): "Apollas Hist.",
    AuthorID("0063"): "Dionysius Thrax Gramm.",
    AuthorID("0299"): "Terpander Lyr.",
    AuthorID("0246"): "Dionysius Chalcus Eleg.",
    AuthorID("2008"): "Martyrium Cononis",
    AuthorID("1408"): "Heraclides Gramm.",
    AuthorID("1535"): "Nicocrates Hist.",
    AuthorID("0736"): "Stephanus Med.",
    AuthorID("1899"): "Aristonicus Hist.",
    AuthorID("0036"): "Bion Bucol.",
    AuthorID("2178"): "Cassius Longinus Phil. et Rhet.",
    AuthorID("1700"): "Testamenta XII Patriarcharum",
    AuthorID("1340"): "[Eccelus] Phil.",
    AuthorID("0640"): "Alciphron Rhet. et Soph.",
    AuthorID("2960"): "Oracula Tiburtina",
    AuthorID("0093"): "Theophrastus Phil.",
    AuthorID("2057"): "Socrates Scholasticus Hist.",
    AuthorID("1161"): "Apocryphon Ezechiel",
    AuthorID("0375"): "Cinesias Lyr.",
    AuthorID("2702"): "Michael Psellus Polyhist.",
    AuthorID("3170"): "Ephraem Hist. et Poeta",
    AuthorID("3074"): "Constantinus Manasses Hist. et Poeta",
    AuthorID("0614"): "Valerius Babrius Scr. Fab.",
    AuthorID("1875"): "Aristodemus Hist. et Myth.",
    AuthorID("0632"): "[Pythagoras] Phil.",
    AuthorID("2604"): "Ulpianus Gramm. et Rhet.",
    AuthorID("0918"): "Lamynthius Lyr.",
    AuthorID("4110"): "Evagrius Scr. Eccl.",
    AuthorID("4117"): "Eustathius Scr. Eccl. et Theol.",
    AuthorID("1646"): "Ptolemaeus Hist.",
    AuthorID("2543"): "Lucius Cincius Alimentus Hist.",
    AuthorID("0706"): "Philo Med.",
    AuthorID("0637"): "Socraticorum Epistulae",
    AuthorID("0566"): "Theopompus Hist.",
    AuthorID("2860"): "Alexander Scr. Eccl.",
    AuthorID("0308"): "Ion Phil. et Poeta",
    AuthorID("1764"): "Vettius Valens Astrol.",
    AuthorID("2047"): "Syriani, Sopatri Et Marcellini Scholia Ad Hermogenis Status",
    AuthorID("0424"): "Axionicus Comic.",
    AuthorID("0613"): "[Demetrius] Rhet.",
    AuthorID("0251"): "Euenus Eleg.",
    AuthorID("0535"): "Demades Orat. et Rhet.",
    AuthorID("0026"): "Aeschines Orat.",
    AuthorID("2948"): "Acta Philippi",
    AuthorID("0553"): "Artemidorus Onir.",
    AuthorID("1435"): "Hippias Hist.",
    AuthorID("1838"): "Theon Gramm.",
    AuthorID("2628"): "Idaeus Epic.",
    AuthorID("0248"): "Diphilus Epic. et Iamb.",
    AuthorID("1438"): "Hippys Hist.",
    AuthorID("0050"): "Ptolemaei II Philadelphi Et Eleazari Epistulae",
    AuthorID("1763"): "Tryphon II Gramm.",
    AuthorID("0387"): "Sapphus vel Alcaei Fragmenta",
    AuthorID("0380"): "Philoxenus Lyr.",
    AuthorID("4239"): "Severus Soph.",
    AuthorID("3020"): "Joannes Cinnamus Gramm. et Hist.",
    AuthorID("1196"): "Aristophanes Hist.",
    AuthorID("1167"): "Apollonius Biogr.",
    AuthorID("1967"): "Leschides Epic.",
    AuthorID("0385"): "Cassius Dio Hist., Dio Cassius",
    AuthorID("0700"): "Apollodorus Trag.",
    AuthorID("1724"): "Theon Phil.",
    AuthorID("2372"): "Euagon Hist.",
    AuthorID("2545"): "Gaius Acilius Hist. et Phil.",
    AuthorID("1704"): "Teucer Hist.",
    AuthorID("2903"): "Minucianus Junior Rhet.",
    AuthorID("4330"): "Cosmas Hieromonachus Alchem.",
    AuthorID("1918"): "Timagenes Hist.",
    AuthorID("1189"): "Aristocrates Hist.",
    AuthorID("4090"): "Cyrillus Theol.",
    AuthorID("1692"): "Speusippus Phil.",
    AuthorID("1580"): "Phaestus Epic.",
    AuthorID("1591"): "Philistus Hist.",
    AuthorID("2559"): "[Chrysippus] Hist.",
    AuthorID("0409"): "Antidotus Comic.",
    AuthorID("0322"): "Dicaeogenes Trag.",
    AuthorID("1373"): "Evangelium Philippi",
    AuthorID("0503"): "Sosicrates Comic.",
    AuthorID("2578"): "Joannes Gramm. et Poeta",
    AuthorID("2718"): "Manuel Philes Poeta et Scr. Rerum Nat.",
    AuthorID("2798"): "Pseudo-Dionysius Areopagita Scr. Eccl. et Theol.",
    AuthorID("1182"): "[Aristeas] Epic.",
    AuthorID("1201"): "Assumptio Mosis",
    AuthorID("1715"): "Theodoridas Epigr.",
    AuthorID("0679"): "Aeschrion Lyr.",
    AuthorID("2633"): "Niceratus Epic.",
    AuthorID("0321"): "Aeschylus Trag.",
    AuthorID("1779"): "Anonymus Epicureus Phil.",
    AuthorID("0402"): "Alexis Comic.",
    AuthorID("2409"): "Dioscurides Hist.",
    AuthorID("2613"): "Callimachus Junior Epic.",
    AuthorID("0007"): "Plutarchus Biogr. et Phil.",
    AuthorID("2303"): "Archelaus Phil.",
    AuthorID("1273"): "Cleon Eleg.",
    AuthorID("0311"): "Iophon Trag.",
    AuthorID("2016"): "Passio Perpetuae Et Felicitatis",
    AuthorID("0610"): "Alcidamas Rhet.",
    AuthorID("0636"): "Socratis Epistulae",
    AuthorID("1437"): "Hippon Phil.",
    AuthorID("0594"): "Alexander Rhet. et Soph.",
    AuthorID("4238"): "Athanasius Soph.",
    AuthorID("0005"): "Theocritus Bucol.",
    AuthorID("1153"): "Apocalypsis Adam",
    AuthorID("0668"): "Aegimius",
    AuthorID("0327"): "Carcinus Junior Trag.",
    AuthorID("2577"): "Anatolius Math. et Phil.",
    AuthorID("1213"): "Julia Balbilla Lyr.",
    AuthorID("0410"): "Antiphanes Comic.",
    AuthorID("1416"): "(H)eren(n)ius Philo Gramm. et Hist.",
    AuthorID("1193"): "Ariston Phil.",
    AuthorID("1709"): "Theagenes Hist.",
    AuthorID("1337"): "Dorotheus Astrol.",
    AuthorID("0351"): "[Hippothoon] Trag.",
    AuthorID("0268"): "Mesomedes Lyr.",
    AuthorID("0218"): "Nicaenetus Epic.",
    AuthorID("1288"): "Craterus Hist.",
    AuthorID("9018"): "Arsenius Paroemiogr.",
    AuthorID("3185"): "Anonymus De Scientia Politica Hist.",
    AuthorID("2110"): "Cyrillus Scr. Eccl.",
    AuthorID("1603"): "[Phintys] Phil.",
    AuthorID("0314"): "Morsimus Trag.",
    AuthorID("1314"): "Dinias Hist.",
    AuthorID("1881"): "Dionysius Scytobrachion Gramm.",
    AuthorID("2612"): "Caecalus (?) Epic.",
    AuthorID("1309"): "Dialexeis (Δισσοὶ λόγοι)",
    AuthorID("2724"): "Ammonius Scr. Eccl.",
    AuthorID("0524"): "Sophron Mimogr.",
    AuthorID("0347"): "Serapion Trag.",
    AuthorID("0448"): "Dromo Comic.",
    AuthorID("0732"): "Alexander Phil.",
    AuthorID("0467"): "Timotheus Trag.",
    AuthorID("2186"): "Leo Hist.",
    AuthorID("2445"): "Amometus Hist.",
    AuthorID("0208"): "Dosiadas Lyr.",
    AuthorID("0406"): "Anaxilas Comic.",
    AuthorID("0414"): "Apollophanes Comic.",
    AuthorID("2619"): "Dionysius Epic.",
    AuthorID("1681"): "Solonis Epistulae",
    AuthorID("2004"): "Amelii Epistula",
    AuthorID("1271"): "Clemens Romanus Theol. et Clementina",
    AuthorID("2273"): "Damon Hist.",
    AuthorID("2260"): "Hippasus Phil.",
    AuthorID("0550"): "Apollonius Geom.",
    AuthorID("0146"): "Boethus Epigr.",
    AuthorID("0433"): "Crates Comic.",
    AuthorID("0630"): "Pherecydes Myth. et Phil.",
    AuthorID("0663"): "Praecepta Salubria",
    AuthorID("4393"): "Nonnosus Hist.",
    AuthorID("1016"): "Ostanes Magus Alchem.",
    AuthorID("0623"): "Cratetis Epistulae",
    AuthorID("0470"): "Leuco Comic.",
    AuthorID("1304"): "Democritus Phil.",
    AuthorID("0585"): "Publius Aelius Phlegon Paradox.",
    AuthorID("1225"): "Bion Hist.",
    AuthorID("0052"): "Menippus Phil.",
    AuthorID("1395"): "[Hegesinus] Epic.",
    AuthorID("2364"): "Zeno Hist.",
    AuthorID("1412"): "Pseudo-Heracliti Epistulae",
    AuthorID("0342"): "Nicomachus Trag.",
    AuthorID("1160"): "Apocalypsis Sophoniae",
    AuthorID("0463"): "Hegemon Parodius",
    AuthorID("1772"): "Paraleipomena Jeremiou",
    AuthorID("0057"): "Galenus Med.",
    AuthorID("0395"): "Diophantus Comic.",
    AuthorID("0141"): "Athenaeus Epigr.",
    AuthorID("0512"): "Theophilus Comic.",
    AuthorID("0719"): "Aretaeus Med.",
    AuthorID("2043"): "Hephaestion Astrol.",
    AuthorID("0494"): "Philyllius Comic.",
    AuthorID("0265"): "Timocreon Lyr.",
    AuthorID("1529"): "Nicander Gramm.",
    AuthorID("0743"): "Nemesius Theol.",
    AuthorID("1516"): "Molpis Hist.",
    AuthorID("2580"): "Joannes Laurentius Lydus Hist.",
    AuthorID("3141"): "Georgius Acropolites Hist.",
    AuthorID("0542"): "Julius Pollux Gramm.",
    AuthorID("1210"): "Autolycus Astron.",
    AuthorID("1393"): "Hegesianax Astron. et Epic.",
    AuthorID("0520"): "Arcesilaus Comic.",
    AuthorID("1701"): "Testamentum Abrahae",
    AuthorID("0518"): "Xenarchus Comic.",
    AuthorID("0529"): "Arius Didymus Doxogr.",
    AuthorID("0220"): "Moero Epic.",
    AuthorID("1460"): "Lesbonax Gramm.",
    AuthorID("2023"): "Iamblichus Phil.",
    AuthorID("2404"): "Philogelos",
    AuthorID("0376"): "Timotheus Lyr.",
    AuthorID("2204"): "Autocrates Hist.",
    AuthorID("0333"): "Timocles Trag.",
    AuthorID("0707"): "Alexis Hist.",
    AuthorID("0645"): "Justinus Martyr Apol.",
    AuthorID("1248"): "Celsus Phil.",
    AuthorID("1316"): "Dinon Hist.",
    AuthorID("0729"): "Theophilus Protospatharius Med.",
    AuthorID("1705"): "Thales Phil.",
    AuthorID("0174"): "Diotimus Epic.",
    AuthorID("2914"): "Leontius Scr. Eccl.",
    AuthorID("1377"): "Favorinus Phil. et Rhet.",
    AuthorID("1127"): "Anonyma De Musica Scripta Bellermanniana",
    AuthorID("0437"): "Crobylus Comic.",
    AuthorID("1345"): "Epica Incerta (CA)",
    AuthorID("0217"): "Anacreon Junior Eleg.",
    AuthorID("1680"): "[Sodamus] Eleg.",
    AuthorID("0292"): "Stesichorus Lyr.",
    AuthorID("2201"): "[Ctesiphon] Hist.",
    AuthorID("2733"): "Evagrius Scholasticus Scr. Eccl.",
    AuthorID("0714"): "Anaxarchus Phil.",
    AuthorID("1629"): "Polystratus Phil.",
    AuthorID("2881"): "Romanus Melodus Hymnographus",
    AuthorID("1190"): "Aristagoras Hist.",
    AuthorID("2039"): "Diophantus Math.",
    AuthorID("0591"): "Antisthenes Phil. et Rhet.",
    AuthorID("3127"): "Pseudo-Nonnus",
    AuthorID("2766"): "Eudocia Augusta Poeta",
    AuthorID("0436"): "Crito Comic.",
    AuthorID("1191"): "[Aristombrotus] Phil.",
    AuthorID("4015"): "Joannes Philoponus Phil.",
    AuthorID("0253"): "[Homerus] [Epic.]",
    AuthorID("0444"): "Diodorus Comic.",
    AuthorID("1514"): "Mnaseas Perieg.",
    AuthorID("3188"): "Joannes Actuarius Med.",
    AuthorID("0557"): "Epictetus Phil.",
    AuthorID("2300"): "Promathidas Hist.",
    AuthorID("1202"): "[Athamas] Phil.",
    AuthorID("0137"): "Asclepiades Epigr.",
    AuthorID("1723"): "Theolytus Epic.",
    AuthorID("1206"): "Athenodorus Phil.",
    AuthorID("3135"): "Joannes Zonaras Gramm. et Hist.",
    AuthorID("0302"): "Choerilus Trag.",
    AuthorID("1720"): "Theodotus Judaeus Epic.",
    AuthorID("2428"): "Thrasyllus Hist.",
    AuthorID("0612"): "Dio Chrysostomus Soph.",
    AuthorID("4081"): "Colluthus Epic.",
    AuthorID("2009"): "Martyrium Marini",
    AuthorID("2969"): "Demonax Phil.",
    AuthorID("0029"): "Dinarchus Orat.",
    AuthorID("1844"): "Hera[clides] Trag.",
    AuthorID("5035"): "Scholia In Platonem",
    AuthorID("5019"): "Scholia In Dionysium Periegetam",
    AuthorID("0003"): "Thucydides Hist.",
    AuthorID("0856"): "Dieuches Med.",
    AuthorID("9020"): "Stephanus Gramm.",
    AuthorID("7052"): "Anthologiae Graecae Appendix",
    AuthorID("1177"): "Pseudo-Archytas Phil.",
    AuthorID("1292"): "Crito Phil.",
    AuthorID("1594"): "Philo Judaeus Senior Epic.",
    AuthorID("0710"): "Amphiarai Exilium (?)",
    AuthorID("0526"): "Flavius Josephus Hist.",
    AuthorID("1477"): "Manetho Hist.",
    AuthorID("0037"): "Anacharsidis Epistulae",
    AuthorID("0634"): "Xenocrates Phil.",
    AuthorID("2640"): "Eusebius Phil.",
    AuthorID("0284"): "Aelius Aristides Rhet.",
    AuthorID("1509"): "[Milon] [Phil.]",
    AuthorID("0597"): "Zenodorus Gramm.",
    AuthorID("2005"): "Martyrium Pionii",
    AuthorID("2797"): "Hesychius Scr. Eccl.",
    AuthorID("2424"): "Chaeremon Hist. et Phil.",
    AuthorID("4286"): "Lexica Syntactica",
    AuthorID("4173"): "Vitae Dionysii Periegetae",
    AuthorID("2052"): "Horapollo Gramm.",
    AuthorID("1434"): "Hippias Soph.",
    AuthorID("4323"): "Eugenius Alchem.",
    AuthorID("1155"): "Apocalypsis Syriaca Baruchi",
    AuthorID("0269"): "Nautarum Cantiunculae",
    AuthorID("4088"): "Anthemius Math. et Mech.",
    AuthorID("1484"): "Martyrium Polycarpi",
    AuthorID("0095"): "Hermodorus Phil.",
    AuthorID("4093"): "Georgius Choeroboscus Gramm.",
    AuthorID("2565"): "Mnesimachus Hist.",
    AuthorID("4344"): "Menecrates Hist.",
    AuthorID("1733"): "Timaeus Hist.",
    AuthorID("0075"): "Periplus Ponti Euxini",
    AuthorID("2586"): "Menander Rhet.",
    AuthorID("0020"): "Hesiodus Epic.",
    AuthorID("5038"): "Scholia In Theocritum",
    AuthorID("0435"): "Cratinus Junior Comic.",
    AuthorID("1597"): "[Telauges] Phil.",
    AuthorID("5040"): "Scholia In Xenophontem",
    AuthorID("3086"): "Nicephorus I Scr. Eccl., Hist. et Theol.",
    AuthorID("1367"): "Euripidis Epistulae",
    AuthorID("1426"): "Herodes Atticus Soph.",
    AuthorID("1572"): "[Perictione] Phil.",
    AuthorID("2653"): "Erycius Poeta",
    AuthorID("0461"): "Eupolis Comic.",
    AuthorID("1780"): "Alcimenes Comic.",
    AuthorID("5015"): "Scholia In Aristotelem",
    AuthorID("1154"): "Apocalypsis Baruch",
    AuthorID("1135"): "Anonymus Photii Phil.",
    AuthorID("1859"): "Liber Jannes Et Jambres",
    AuthorID("1134"): "Anonymus Iamblichi Phil.",
    AuthorID("1350"): "Epistula Ad Diognetum",
    AuthorID("0238"): "Ananius Iamb.",
    AuthorID("2646"): "Fragmenta Adespota (SH)",
    AuthorID("1849"): "Demetrius Trag.",
    AuthorID("0320"): "Diogenes Trag.",
    AuthorID("2511"): "Demetrius Hist.",
    AuthorID("1366"): "Evangelium Bartholomaei",
    AuthorID("0438"): "Damoxenus Comic.",
    AuthorID("1207"): "Attalus Astron. et Math.",
    AuthorID("2631"): "Menophilus Poeta",
    AuthorID("0304"): "Acta Et Martyrium Apollonii",
    AuthorID("1636"): "Protagorides Hist.",
    AuthorID("1738"): "Tragica Adespota",
    AuthorID("2734"): "Flavius Justinianus Imperator Theol.",
    AuthorID("1147"): "Antiphon Soph.",
    AuthorID("4145"): "Nicephorus Gregoras Hist.",
    AuthorID("0534"): "Callisthenes Hist.",
    AuthorID("0079"): "Menippus Geogr.",
    AuthorID("0408"): "Comica Adespota (CAF)",
    AuthorID("1129"): "Anonymi De Barbarismo Et Soloecismo Gramm.",
    AuthorID("0006"): "Euripides Trag.",
    AuthorID("1552"): "Oratio Josephi",
    AuthorID("4066"): "Damascius Phil.",
    AuthorID("0069"): "Dionysius Geogr.",
    AuthorID("4085"): "Hesychius Lexicogr.",
    AuthorID("0480"): "Nicochares Comic.",
    AuthorID("4135"): "Theodorus Theol.",
    AuthorID("1600"): "Philostratus Major Soph.",
    AuthorID("0017"): "Isaeus Orat.",
    AuthorID("5031"): "Scholia In Nicandrum",
    AuthorID("0507"): "Straton Comic.",
    AuthorID("3158"): "Theodorus Epist.",
    AuthorID("0367"): "Tynnichus Lyr.",
    AuthorID("1294"): "Critolaus Phil.",
    AuthorID("0517"): "Timotheus Comic.",
    AuthorID("0423"): "Autocrates Comic.",
    AuthorID("5052"): "Scholia in Maximum Confessorem",
    AuthorID("2950"): "Adamantius Theol.",
    AuthorID("2385"): "Polycritus Hist.",
    AuthorID("1379"): "Fragmenta Alchemica",
    AuthorID("2130"): "Arethas Philol. et Scr. Eccl.",
    AuthorID("2634"): "Pamphilus Poeta",
    AuthorID("1534"): "Nicocles Hist.",
    AuthorID("0641"): "Xenophon Scr. Erot.",
    AuthorID("0651"): "Antoninus Liberalis Myth.",
    AuthorID("1452"): "Juba II Rex Mauretaniae [Hist.]",
    AuthorID("1312"): "Didymus Gramm.",
    AuthorID("2084"): "Basilius Med. et Scr. Eccl.",
    AuthorID("1642"): "Pseudo-Ptolemaeus",
    AuthorID("0363"): "Claudius Ptolemaeus Math.",
    AuthorID("1550"): "Oracula Chaldaica",
    AuthorID("0676"): "Aglaïs Poet. Med.",
    AuthorID("1240"): "Callixenus Hist.",
    AuthorID("1559"): "Bucolicum",
    AuthorID("2536"): "Andron Geogr.",
    AuthorID("2287"): "Fragmentum Stoicum",
    AuthorID("2122"): "Gaius Asinius Quadratus Hist.",
    AuthorID("2573"): "Pausanias Hist.",
    AuthorID("0222"): "Eratosthenes et Eratosthenica Philol.",
    AuthorID("4084"): "Zosimus Hist.",
    AuthorID("0577"): "Nicolaus Hist.",
    AuthorID("4235"): "Joannes Rhet.",
    AuthorID("1244"): "Carneiscus Phil.",
    AuthorID("0686"): "Aethlius Hist.",
    AuthorID("4100"): "Aphthonius Rhet.",
    AuthorID("0391"): "Acta Scillitanorum Martyrum",
    AuthorID("2140"): "Iamblichus Alchem.",
    AuthorID("0569"): "Apollonius Paradox.",
    AuthorID("2512"): "Paeon Hist.",
    AuthorID("2649"): "Amyntas Epigr.",
    AuthorID("1499"): "Menecles Hist.",
    AuthorID("4033"): "Anonymi In Aristotelis Ethica Nicomachea Phil.",
    AuthorID("1139"): "Anonymi Historici (FGrH)",
    AuthorID("0576"): "Musaeus Epic.",
    AuthorID("0434"): "Cratinus Comic.",
    AuthorID("2632"): "Comarius Alchem.",
    AuthorID("2721"): "Theodorus Prodromus Poeta et Polyhist.",
    AuthorID("1197"): "Artemon Gramm.",
    AuthorID("0259"): "Scythinus Poet. Phil.",
    AuthorID("0072"): "Anonymi Grammatici Gramm.",
    AuthorID("0658"): "Heliodorus Scr. Erot.",
    AuthorID("0024"): "Oppianus Epic.",
    AuthorID("0033"): "Pindarus Lyr.",
    AuthorID("0323"): "Antiphon Trag.",
    AuthorID("1425"): "Hermonax Epic.",
    AuthorID("0519"): "Xeno Comic.",
    AuthorID("4318"): "Vita Sophoclis",
    AuthorID("0330"): "Dionysius I [Trag.]",
    AuthorID("1828"): "Pamphila Hist.",
    AuthorID("0486"): "Pherecrates Comic.",
    AuthorID("1547"): "Oedipodea",
    AuthorID("1347"): "Epimenides Phil.",
    AuthorID("0731"): "Adamantius Judaeus Med.",
    AuthorID("4101"): "Etymologicum Parvum",
    AuthorID("4124"): "Eusebius Scr. Eccl.",
    AuthorID("0227"): "Anonymi Curetum Hymnus",
    AuthorID("1748"): "Sosigenes Phil.",
    AuthorID("2652"): "Diodorus Eleg.",
    AuthorID("1747"): "Vita Adam Et Evae",
    AuthorID("0432"): "Clearchus Comic.",
    AuthorID("0845"): "Ctesias Hist. et Med.",
    AuthorID("1703"): "Teucer Astrol.",
    AuthorID("4086"): "[Agathodaemon] Alchem.",
    AuthorID("4031"): "Eustratius Phil.",
    AuthorID("2102"): "Didymus Caecus Scr. Eccl., Didymus the Blind",
    AuthorID("0464"): "Hegesippus Comic.",
    AuthorID("0271"): "Conventus Avium",
    AuthorID("1342"): "Empedocles Poet. Phil.",
    AuthorID("2866"): "Oecumenius Phil. et Rhet.",
    AuthorID("1526"): "Neoptolemus Gramm.",
    AuthorID("0428"): "Cantharus Comic.",
    AuthorID("0365"): "Apollodorus Lyr.",
    AuthorID("1339"): "Duris Hist.",
    AuthorID("1917"): "Demetrius Hist.",
    AuthorID("0247"): "Dionysius II [Eleg.]",
    AuthorID("2624"): "Hermias Poeta",
    AuthorID("1218"): "Basilis Hist.",
    AuthorID("1021"): "Meropis",
    AuthorID("0459"): "Eunicus Comic.",
    AuthorID("0329"): "Theodectas Trag.",
    AuthorID("1471"): "Lyrica Adespota (SLG)",
    AuthorID("0032"): "Xenophon Hist.",
    AuthorID("2037"): "Joannes Stobaeus Anthologus",
    AuthorID("4115"): "Theophilus Scr. Eccl.",
    AuthorID("2622"): "Dorieus Poeta",
    AuthorID("1152"): "Apion Gramm.",
    AuthorID("0004"): "Diogenes Laertius Biogr.",
    AuthorID("5033"): "Scholia In Pausaniam",
    AuthorID("2806"): "Marcus Diaconus Scr. Eccl.",
    AuthorID("1645"): "Ptolemaeus VIII Euergetes II [Hist.]",
    AuthorID("0094"): "Pseudo-Plutarchus",
    AuthorID("1183"): "Aristeae Epistula",
    AuthorID("2699"): "Amphicrates Rhet.",
    AuthorID("0281"): "Marcellus Poet. Med.",
    AuthorID("4175"): "Commentaria In Dionysii Thracis Artem Grammaticam",
    AuthorID("9023"): "Thomas Magister Philol.",
    AuthorID("1560"): "Matthiae Traditiones",
    AuthorID("5046"): "Scholia In Theonem Rhetorem",
    AuthorID("2444"): "Lycophron Soph.",
    AuthorID("3140"): "Joel Chronogr.",
    AuthorID("0697"): "Cornelius Alexander Polyhist.",
    AuthorID("3088"): "Nicephorus Bryennius Hist.",
    AuthorID("1487"): "Maximus Astrol.",
    AuthorID("0228"): "Anonymi Hymnus In Dactylos Idaeos",
    AuthorID("1793"): "Timoxenus Comic.",
    AuthorID("2038"): "Acta Thomae",
    AuthorID("1131"): "Anonymus Ad Avircium Marcellum Contra Cataphrygas",
    AuthorID("0671"): "Philumenus Med.",
    AuthorID("0563"): "Maximus Soph.",
    AuthorID("5023"): "Scholia In Euripidem",
    AuthorID("2319"): "Apollodorus Phil.",
    AuthorID("0667"): "Marcellinus I Med.",
    AuthorID("5002"): "Magica",
    AuthorID("0683"): "Aethiopis",
    AuthorID("0099"): "Strabo Geogr.",
    AuthorID("0654"): "Lucius Annaeus Cornutus Phil.",
    AuthorID("0231"): "Elegiaca Adespota (CA)",
    AuthorID("1699"): "Teles Phil.",
    AuthorID("1683"): "Sophaenetus Hist.",
    AuthorID("2210"): "Anaxicrates Hist.",
    AuthorID("0725"): "Anaximander Phil.",
    AuthorID("0214"): "Phanocles Eleg.",
    AuthorID("0568"): "Antigonus Paradox.",
    AuthorID("4134"): "Diodorus Scr. Eccl.",
    AuthorID("0897"): "Euthydemus Med.",
    AuthorID("0639"): "Menecrates Med.",
    AuthorID("0309"): "Achaeus Trag.",
    AuthorID("1615"): "Platonius Gramm.",
    AuthorID("1258"): "Charon Hist.",
    AuthorID("2112"): "Amphilochius Scr. Eccl.",
    AuthorID("1375"): "Evangelium Thomae",
    AuthorID("0476"): "Mnesimachus Comic.",
    AuthorID("0888"): "Eudemus Poet. Med.",
    AuthorID("4331"): "Hierotheus Alchem.",
    AuthorID("1251"): "Chamaeleon Phil.",
    AuthorID("4307"): "Lexica Synonymica",
    AuthorID("0595"): "Zeno Phil.",
    AuthorID("2399"): "Eudromus Phil.",
    AuthorID("1307"): "Demon Hist.",
    AuthorID("1496"): "Memnon Hist.",
    AuthorID("0258"): "Pigres Eleg.",
    AuthorID("1446"): "Ion Eleg.",
    AuthorID("1666"): "Sententiae Sexti",
    AuthorID("1585"): "Pherecydis Epistula",
    AuthorID("0570"): "Archelaus Paradox.",
    AuthorID("1223"): "Bias [Phil.]",
    AuthorID("4061"): "Cosmas Indicopleustes Geogr.",
    AuthorID("4288"): "Lexicon αἱμωδεῖν",
    AuthorID("0662"): "Comica Adespota (CGFPR)",
    AuthorID("1357"): "Eudemus Phil.",
    AuthorID("2966"): "Phileas Scr. Eccl.",
    AuthorID("2231"): "Thrasyalces Phil.",
    AuthorID("2190"): "[Clitonymus] Hist.",
    AuthorID("0018"): "Philo Judaeus Phil.",
    AuthorID("1118"): "Pseudo-Dioscorides Med.",
    AuthorID("1848"): "Meletus Junior Trag.",
    # AuthorID("DOCCAN1"): "TLG Canon, bibliography",
    AuthorID("1605"): "Pseudo-Phocylides Gnom.",
    AuthorID("0475"): "Metagenes Comic.",
    AuthorID("0479"): "Nico Comic.",
    AuthorID("1915"): "Eudoxus Hist.",
    AuthorID("0060"): "Diodorus Siculus Hist.",
    AuthorID("0537"): "Epicurus Phil.",
    AuthorID("1184"): "Aristides Apol.",
    AuthorID("2185"): "Dionysius Μεταθέμενος Phil.",
    AuthorID("2354"): "Dionysius Hist.",
    AuthorID("0620"): "Archytas Phil.",
    AuthorID("5018"): "Scholia In Dionysium Byzantium",
    AuthorID("2202"): "[Menyllus] Hist.",
    AuthorID("0186"): "Marcus Cornelius Fronto Rhet.",
    AuthorID("1548"): "Oenomaus Phil.",
    AuthorID("1245"): "Carystius Hist.",
    AuthorID("4126"): "Theodorus Scr. Eccl.",
    AuthorID("0427"): "[Callippus] Comic.",
    AuthorID("2398"): "Basilides Phil.",
    AuthorID("0440"): "Demetrius Junior Comic.",
    AuthorID("0495"): "Phoenicides Comic.",
    AuthorID("0816"): "Theudo[tus] Trag.",
    AuthorID("2141"): "Publius Herennius Dexippus Hist.",
    AuthorID("2602"): "Timaeus Sophista Gramm.",
    AuthorID("1711"): "[Thearidas] Phil.",
    AuthorID("0738"): "Hippiatrica",
    AuthorID("0468"): "Hipparchus Comic.",
    AuthorID("0722"): "Oribasius Med.",
    AuthorID("0580"): "Paradoxographus Florentinus",
    AuthorID("3069"): "Leo Diaconus Hist.",
    AuthorID("0652"): "Philostratus Junior Soph.",
    AuthorID("3051"): "Georgius Monachus Continuatus",
    AuthorID("2877"): "Cyrillus Biogr.",
    AuthorID("2232"): "Damon Mus.",
    AuthorID("3014"): "Joannes Camaterus Astrol. et Astron.",
    AuthorID("0737"): "Julianus Scriptor Legis De Medicis",
    AuthorID("1525"): "Neanthes Hist.",
    AuthorID("2606"): "Agathyllus Eleg.",
    AuthorID("2525"): "Laetus Hist.",
    AuthorID("2172"): "Andron Hist.",
    AuthorID("0306"): "Aristarchus Trag.",
    AuthorID("0382"): "Castorion Lyr.",
    AuthorID("1987"): "Theodorus Poeta",
    AuthorID(
        "0728"
    ): "Theophilus Protospatharius, Damascius et Stephanus Atheniensis Med.",
    AuthorID("0431"): "Chionides Comic.",
    AuthorID("1409"): "Heraclides Ponticus Phil.",
    AuthorID("0527"): "Septuaginta",
    AuthorID("1128"): "Anonymi Commentarius In Platonis Theaetetum",
    AuthorID("0355"): "Zopyrus Trag.",
    AuthorID("0047"): "Pausaniae I Et Xerxis Epistulae",
    AuthorID("1421"): "Hermippus Gramm. et Hist.",
    AuthorID("1420"): "Hermias Iamb.",
    AuthorID("4102"): "Catenae (Novum Testamentum)",
    AuthorID("0267"): "Xenophanes Poet. Phil.",
    AuthorID("2304"): "Idaeus Phil.",
    AuthorID("0010"): "Isocrates Orat.",
    AuthorID("0131"): "Archimelus Epigr.",
    AuthorID("1173"): "Archedemus Phil.",
    AuthorID("0358"): "Nicomachus Math.",
    AuthorID("0055"): "Themistoclis Epistulae",
    AuthorID("1178"): "[Aresas] Phil.",
    AuthorID("1087"): "Cleophon Trag.",
    AuthorID("1504"): "Menelaus Epic.",
    AuthorID("2265"): "Diodorus Perieg.",
    AuthorID("1470"): "Lycus Hist.",
    AuthorID("1461"): "Leucippus Phil.",
    AuthorID("0715"): "Paulus Med.",
    AuthorID("4293"): "Fragmentum Lexici Graeci",
    AuthorID("1176"): "Archytas Epic.",
    AuthorID("2326"): "Dei(l)ochus Hist.",
    AuthorID("0425"): "Bato Comic.",
    AuthorID("0407"): "Anaxippus Comic.",
    AuthorID("1819"): "Pseudo-Demosthenes Epigr.",
    AuthorID("1200"): "Asclepiades Myth.",
    AuthorID("0165"): "Diodorus Rhet.",
    AuthorID("1443"): "Ignatius Scr. Eccl.",
    AuthorID("1419"): "Hermas Scr. Eccl., Pastor Hermae",
    AuthorID("2268"): "Timagoras Hist.",
    AuthorID("2119"): "Christodorus Epic.",
    AuthorID("0411"): "Apollodorus Comic.",
    AuthorID("1252"): "Certamen Homeri Et Hesiodi",
    AuthorID("2904"): "Nicolaus Rhet. et Soph.",
    AuthorID("0278"): "Praelusio Mimi",
    AuthorID("0359"): "Isidorus Scriptor Hymnorum",
    AuthorID("4187"): "Leo Magentinus Phil.",
    AuthorID("1388"): "Harmodius Hist.",
    AuthorID("0262"): "Socrates Phil.",
    AuthorID("0487"): "Philemon Comic.",
    AuthorID("2552"): "Critolaus Hist.",
    AuthorID("3159"): "Barlaam Math., Theol. et Epist.",
    AuthorID("2060"): "Asterius Scr. Eccl.",
    AuthorID("2449"): "Timotheus Gramm.",
    AuthorID("0491"): "Philiscus Comic.",
    AuthorID("4046"): "Theophanes Confessor Chronogr.",
    AuthorID("2639"): "Posidonius Epic.",
    AuthorID("0216"): "Alexander Lyr. et Trag.",
    AuthorID("0607"): "Aelius Theon Rhet.",
    AuthorID("1272"): "Cleomedes Astron.",
    AuthorID("0357"): "Didymus Scriptor De Mensuris",
    AuthorID("1266"): "Tyrannion Gramm.",
    AuthorID("1696"): "Straton Phil.",
    AuthorID("0454"): "Epinicus Comic.",
    AuthorID("1158"): "Apocalypsis Joannis",
    AuthorID("0011"): "Sophocles Trag.",
    AuthorID("3040"): "Josephus Genesius Hist.",
    AuthorID("4153"): "Theophanes Continuatus",
    AuthorID("2200"): "Libanius Rhet. et Soph.",
    AuthorID("2306"): "Xenomedes Hist.",
    AuthorID("2193"): "[Aretades] Hist.",
    AuthorID("1906"): "Simonides Epic.",
    AuthorID("0452"): "Epigenes Comic.",
    AuthorID("0625"): "Polemaeus Trag.",
    AuthorID("1166"): "Apollodorus Phil.",
    AuthorID("1442"): "Idomeneus Hist.",
    AuthorID("4080"): "Geoponica",
    AuthorID("2298"): "Lysanias Hist.",
    AuthorID("1306"): "Bolus Med. et Phil.",
    AuthorID("2393"): "Andreas Hist.",
    AuthorID("0081"): "Dionysius Halicarnassensis Hist. et Rhet.",
    AuthorID("0389"): "Acta Petri",
    AuthorID("0354"): "Zenodotus Trag.",
    AuthorID("1462"): "Liber Eldad Et Modad",
    AuthorID("3144"): "Joannes Cananus Hist.",
    AuthorID("1562"): "Parmenides Poet. Phil.",
    AuthorID("4289"): "Lexica Segueriana",
    AuthorID("9007"): "Appendix Proverbiorum",
    AuthorID("1313"): "Dieuchidas Hist.",
    AuthorID("1588"): "Philicus Lyr.",
    AuthorID("1651"): "Pythermus Hist.",
    AuthorID("1170"): "Apollonius Hist.",
    AuthorID("1199"): "Asclepiades Gramm. et Hist.",
    AuthorID("1784"): "[Heraclitus] Comic.",
    AuthorID("0215"): "Antagoras Epic.",
    AuthorID("2627"): "Damianus Scriptor De Opticis",
    AuthorID("2418"): "Archinus Hist.",
    AuthorID("0002"): "Theognis Eleg.",
    AuthorID("0366"): "Lasus Lyr.",
    AuthorID("0242"): "Asius Eleg. et Epic.",
    AuthorID("1262"): "Choerilus Epic.",
    AuthorID("3182"): "Pseudo-Symeon Hist.",
    AuthorID("0035"): "Moschus Bucol.",
    AuthorID("1641"): "Ptolemaeus Gnost.",
    AuthorID("1765"): "Vitae Aesopi",
    AuthorID("2168"): "Apollophanes Phil.",
    AuthorID("2203"): "[Theophilus] Hist.",
    AuthorID("0629"): "Periander [Phil.]",
    AuthorID("1052"): "Posidonius Phil.",
    AuthorID("0560"): "[Longinus] Rhet., Pseudo-Longinus",
    AuthorID("4020"): "Elias Phil.",
    AuthorID("4030"): "Sophonias Phil.",
    AuthorID("1650"): "Pytheas Perieg.",
    AuthorID("1264"): "Chrysippus Phil.",
    AuthorID("0565"): "Soranus Med.",
    AuthorID("2426"): "Hermaeus Hist.",
    AuthorID("1205"): "Athenagoras Apol.",
    AuthorID("2014"): "Acta Phileae",
    AuthorID("2054"): "Aristides Quintilianus Mus.",
    AuthorID("1249"): "Cephalion Hist. et Rhet.",
    AuthorID("0296"): "Carmina Convivialia (PMG)",
    AuthorID("1661"): "Satyrus Hist.",
    AuthorID("2245"): "Simus Phil.",
    AuthorID("1759"): "Sententiae Pythagoreorum",
    AuthorID("1706"): "Thallus Hist.",
    AuthorID("2286"): "Cercops Phil.",
    AuthorID("4227"): "Anonymus De Philosophia Platonica Phil.",
    AuthorID("5025"): "Scholia In Hesiodum",
    AuthorID("1553"): "[Palaephatus] Myth.",
    AuthorID("4013"): "Simplicius Phil.",
    AuthorID("3064"): "Scylitzes Continuatus",
    AuthorID("0381"): "Lycophronides Lyr.",
    AuthorID("0415"): "Araros Comic.",
    AuthorID("0403"): "Amipsias Comic.",
    AuthorID("0539"): "Hellanicus Hist.",
    AuthorID("2018"): "Eusebius Scr. Eccl. et Theol.",
    AuthorID("0293"): "Ibycus Lyr.",
    AuthorID("0501"): "Sannyrion Comic.",
    AuthorID("1392"): "Hegesander Hist.",
    AuthorID("2460"): "Glaucus Hist.",
    AuthorID("2017"): "Gregorius Nyssenus Theol.",
    AuthorID("4305"): "Claudius Casilon Gramm.",
    AuthorID("1623"): "Polycharmus Hist.",
    AuthorID("0015"): "Herodianus Hist.",
    AuthorID("2694"): "Sostratus Poeta",
    AuthorID("0116"): "Abydenus Hist.",
    AuthorID("2417"): "Cineas Rhet.",
    AuthorID("1433"): "Hipparchus [Epigr.]",
    AuthorID("0379"): "Philoxenus Lyr.",
    AuthorID("2212"): "Lyceas Hist.",
    AuthorID("0310"): "Carcinus Trag.",
    AuthorID("2934"): "Joannes Damascenus Scr. Eccl. et Theol., John of Damascus",
    AuthorID("0202"): "Mace(donius) Lyr.",
    AuthorID("1226"): "Biton Mech.",
    AuthorID("4001"): "Aeneas Phil. et Rhet.",
    AuthorID("1751"): "Xanthus Hist.",
    AuthorID("0745"): "Hierophilus Phil. et Soph.",
    AuthorID("1678"): "Socrates Hist.",
    AuthorID("1719"): "Theodosius Astron. et Math.",
    AuthorID("0328"): "Chaeremon Trag.",
    AuthorID("2392"): "Artemon Hist.",
    AuthorID("0419"): "Aristomenes Comic.",
    AuthorID("2003"): "Flavius Claudius Julianus Imperator Phil., Julian the Apostate",
    AuthorID("2339"): "Maeandrius Hist.",
    AuthorID("0276"): "Cantus Lugubris",
    AuthorID("1992"): "Ariston Apol.",
    AuthorID("1695"): "[Sthenidas] Phil.",
    AuthorID("1405"): "Heraclides Criticus Perieg.",
    AuthorID("2064"): "Acacius Theol.",
    AuthorID("0400"): "Alcaeus Comic.",
    AuthorID("0608"): "Satyrus Biogr.",
    AuthorID("1355"): "Erinna Lyr.",
    AuthorID("0280"): "Andromachus Poet. Med.",
    AuthorID("2050"): "Eunapius Hist. et Soph.",
    AuthorID("1400"): "Heliodorus Perieg.",
    AuthorID("2195"): "[Chrysermus] Hist.",
    AuthorID("1250"): "Cercidas Iamb.",
    AuthorID("1749"): "Vitae Hesiodi Particula",
    AuthorID("9003"): "Anonymus Lexicographus Lexicogr.",
    AuthorID("3187"): "Georgius Gramm.",
    AuthorID("2341"): "Aristocritus Hist.",
    AuthorID("0318"): "Agathon Trag.",
    AuthorID("1654"): "Rhinthon Comic.",
    AuthorID("1570"): "Epitaphium Pectorii",
    AuthorID("2046"): "Quintus Epic.",
    AuthorID("7000"): "Anthologia Graeca, AG",
    AuthorID("1558"): "Papias Scr. Eccl.",
    AuthorID("1469"): "Lyceas Hist.",
    AuthorID("2244"): "Damon et Phintias Phil.",
    AuthorID("1714"): "Theocritus Soph.",
    AuthorID("0626"): "Heraclitus Phil.",
    AuthorID("1444"): "Ilias Parva",
    AuthorID("4328"): "Philosophus Christianus Alchem.",
    AuthorID("0627"): "Hippocrates Med. et Corpus Hippocraticum",
    AuthorID("4167"): "Leontius Mech.",
    AuthorID("2600"): "Simon Scriptor De Re Equestri",
    AuthorID("1268"): "Claudius Iolaus Hist.",
    AuthorID("4083"): "Eustathius Philol. et Scr. Eccl.",
    AuthorID("1150"): "Aphareus Rhet.",
    AuthorID("3186"): "Anonymus Dialogus Cum Judaeis",
    AuthorID("1908"): "Daimachus Hist.",
    AuthorID("0064"): "Periplus Hannonis",
    AuthorID("4319"): "Zosimus Alchem.",
    AuthorID("0413"): "Apollodorus Comic.",
    AuthorID("1341"): "[Ecphantus] Phil.",
    AuthorID("1781"): "Philippus Comic.",
    AuthorID("0742"): "Hymni Anonymi",
    AuthorID("0587"): "Sotion [Paradox.]",
    AuthorID("1858"): "Oratio Manassis",
    AuthorID("1429"): "Hierocles Phil.",
    AuthorID("9010"): "Suda, Suidas",
    AuthorID("1145"): "Antiochus Hist.",
    AuthorID("1542"): "Numenius Phil.",
    AuthorID("3115"): "Symeon Metaphrastes Biogr. et Hist.",
    AuthorID("4294"): "Lexicon Vindobonense",
    AuthorID("0546"): "Aelianus Tact.",
    AuthorID("3018"): "Georgius Cedrenus Chronogr.",
    AuthorID("2596"): "Phoebammon Soph.",
    AuthorID("0584"): "Philostephanus Hist.",
    AuthorID("1613"): "Pittaci Epistula",
    AuthorID("1617"): "Marcus Antonius Polemon Soph.",
    AuthorID("1576"): "Phaedimus [Epic.]",
    AuthorID("1291"): "Creophylus Hist.",
    AuthorID("0084"): "Dionysius Perieg.",
    AuthorID("0305"): "Aristias Trag.",
    AuthorID("2248"): "Acta Xanthippae Et Polyxenae",
    AuthorID("0659"): "Comica Adespota (Suppl. Com.)",
}
