"""Indices to the PHI5 Latin corpus."""

from typing import Union

from tlg_indices.data_types import AuthorID

MAP_PHI5_AUTHOR_ID_TO_NAME: dict[AuthorID, str] = {
    AuthorID("0428"): "Bellum Alexandrinum [Anonymous]",
    AuthorID("1276"): "Decimus Iunius Iuvenalis, Juvenal",
    AuthorID("0448"): "Gaius Iulius Caesar, Caesar",
    AuthorID("0490"): "Publius Cominius",
    AuthorID("0514"): "Egnatius",
    AuthorID("9254"): "Titius, gram.",
    AuthorID("2305"): "Caelius Aurelianus",
    AuthorID("0484"): "Lucius Cincius",
    AuthorID("1345"): "Silius Italicus",
    AuthorID("0474"): "Marcus Tullius Cicero, Cicero, Tully",
    AuthorID("0614"): "Q. Pompeius Q.f.A.n. Rufus",
    AuthorID("0510"): "Publius Cornelius Dolabella",
    AuthorID("0413"): "Gavius Bassus",
    AuthorID("9510"): "Anonymi Grammatici",
    AuthorID("0452"): "Gaius Iulius Caesar Strabo",
    AuthorID("0875"): "Cn. Cornel. Lentulus Gaetulicus",
    AuthorID("0648"): "Staberius Eros",
    AuthorID("0990"): "Precatio Omnium Herbarum",
    AuthorID("1672"): "Iulius Valerius",
    AuthorID("0451"): "Sinnius Capito",
    AuthorID("0404"): "Lucius Afranius",
    AuthorID("0143"): "Trabea",
    AuthorID("0528"): "Granius Flaccus",
    AuthorID("0455"): "Gaius Calpurnius Piso",
    AuthorID("0635"): "Publius Saturius",
    AuthorID("1212"): "Apuleius Madaurensis",
    AuthorID("0624"): "Quintus Claudius Quadrigarius",
    AuthorID("0592"): "Novius, comoed.",
    AuthorID("0478"): "Quintus Tullius Cicero",
    AuthorID("0472"): "Gaius Valerius Catullus",
    AuthorID("0568"): "Gnaeus Matius",
    AuthorID("0450"): "Lucius Iulius Caesar",
    AuthorID("2003"): "Caelius Apicius",
    AuthorID("0420"): "Publius Aufidius Namusa",
    AuthorID("0564"): "Manius Manilius",
    AuthorID("0806"): "Gaius Ateius Capito",
    AuthorID("0923"): "Aemilius Macer",
    AuthorID("0905"): "Marcus Antistius Labeo",
    AuthorID("1363"): "Aemilius Asper",
    AuthorID("0469"): "Lucius Cassius Longinus",
    AuthorID("0630"): "Sacra Argeorum",
    AuthorID("1291"): "Marianus",
    AuthorID("0116"): "Marcus Pacuvius",
    AuthorID("0306"): "Carmen Devotionis",
    AuthorID("0987"): "Publius Pomponius Secundus",
    AuthorID("0646"): "Lucius Cornelius Sisenna",
    AuthorID("0552"): "Quintus Lutatius Catulus",
    AuthorID("0730"): "Tarquitius Priscus",
    AuthorID("0405"): "Clodius Tuscus",
    AuthorID("9505"): "Anonymi Comici et Tragici",
    AuthorID("0727"): "Cornificius Longus",
    AuthorID("0082"): "Decimus Iunius Silanus",
    AuthorID("2002"): "Albinus, poet.",
    AuthorID("1221"): "C. Iul. Caes. Augustus Octavianus",
    AuthorID("0466"): "Aulus Cascellius",
    AuthorID("0972"): "Petronius",
    AuthorID("0073"): "Gaius Sempronius Gracchus",
    AuthorID("2301"): "Q. Aurelius Memmius Symmachus",
    AuthorID("1100"): "Calpurnius Flaccus",
    AuthorID("0104"): "Gaius Memmius",
    AuthorID("0929"): "Pomponius Mela",
    AuthorID("1020"): "Publius Papinius Statius",
    AuthorID("1050"): "Lucius Verginius Rufus",
    AuthorID("1294"): "Marcus Valerius Martialis",
    AuthorID("0574"): "Gaius Memmius L. f.",
    AuthorID("0402"): "Valerius Aedituus",
    AuthorID("0530"): "Aulus Hirtius",
    AuthorID("0500"): "Lucius Licinius Crassus",
    AuthorID("0591"): "Ninnius Crassus",
    AuthorID("0486"): "Gaius Helvius Cinna",
    AuthorID("0400"): "Lucius Accius",
    AuthorID("1206"): "Lucius Ampelius",
    AuthorID("0058"): "Q. Fabius Maximus Servilianus",
    AuthorID("0920"): "Lucilius iunior",
    AuthorID("0007"): "Atilius",
    AuthorID("1103"): "Priapea",
    AuthorID("0944"): "Imperator Nero",
    AuthorID("0815"): "Bruttedius Niger",
    AuthorID("0494"): "Commentarii Consulares",
    AuthorID("0409"): "Quintus Cornificius",
    AuthorID("0496"): "Commentarius Anquisit. Sergii",
    AuthorID("0812"): "Gaius Caesius Bassus",
    AuthorID("0085"): "Gaius Laelius Sapiens",
    AuthorID("0690"): "Publius Vergilius Maro, Virgil, Vergil",
    AuthorID("0149"): "Carmen Arvale",
    AuthorID("0887"): "Grattius",
    AuthorID("0966"): "Passienus Crispus",
    AuthorID("1321"): "Sextus Pomponius",
    AuthorID("0140"): "Gaius Titius",
    AuthorID("1263"): "Hyginus, myth.",
    AuthorID("1380"): "Philumenus medicus",
    AuthorID("0587"): "Naevius, iunior",
    AuthorID("0533"): "Gaius Iulius Hyginus",
    AuthorID("0596"): "Numitorius",
    AuthorID("0821"): "Bucolica Einsidlensia",
    AuthorID("0301"): "Gnaeus Domitius Ahenobarbus",
    AuthorID("0456"): "Gaius Licinius Macer Calvus",
    AuthorID("0031"): "Cornelia, mater Gracchorum",
    AuthorID("0959"): "Publius Ovidius Naso",
    AuthorID("1342"): "Siculus Flaccus",
    AuthorID("0309"): "Carmen Evocationis",
    AuthorID("0926"): "Marcus Manilius, Manilius",
    AuthorID("0586"): "Mummius",
    AuthorID("0444"): "Marcus Caelius Rufus",
    AuthorID("0112"): "Gnaeus Naevius",
    AuthorID("0682"): "Lucius Varius Rufus",
    AuthorID("1377"): "Fragmenta Bobiensia",
    AuthorID("0534"): "Iuventius, comoed.",
    AuthorID("0588"): "Cornelius Nepos",
    AuthorID("0425"): "Publius Rutilius Lupus",
    AuthorID("0984"): "Pompeius Trogus",
    AuthorID("0824"): "Cn. Arulenus Caelius Sabinus",
    AuthorID("1236"): "Sextus Pompeius Festus",
    AuthorID("1500"): "Altercatio Hadr. et Epicteti",
    AuthorID("0302"): "Marcus Antonius",
    AuthorID("0076"): "Gaius Cassius Hemina",
    AuthorID("1035"): "Gaius Valerius Flaccus",
    AuthorID("2150"): "Zeno of Verona",
    AuthorID("0536"): "Decimus Laberius",
    AuthorID("9221"): "Paulus Quaestor",
    AuthorID("0863"): "Dorcatius",
    AuthorID("0636"): "Quintus Mucius Scaevola",
    AuthorID("0661"): "Ticidas",
    AuthorID("0576"): "M. Valerius Messalla Rufus",
    AuthorID("0067"): "Favorinus",
    AuthorID("0538"): "Laevius",
    AuthorID("1254"): "Aulus Gellius",
    AuthorID("0556"): "Gaius Licinius Macer",
    AuthorID("0640"): "Marcus Aemilius Scaurus",
    AuthorID("1374"): "Velius Longus",
    AuthorID("2331"): "Scriptores Historiae Augustae",
    AuthorID("0103"): "Gnaeus Marcius vates",
    AuthorID("1279"): "Laelius Felix",
    AuthorID("0010"): "Marcus Iunius Brutus [iur.]",
    AuthorID("0106"): "Caecilius Metellus",
    AuthorID("0584"): "Mimi Poetarum Incertorum",
    AuthorID("1044"): "Velleius Paterculus",
    AuthorID("1056"): "Vitruvius",
    AuthorID("0709"): "Domitius Marsus",
    AuthorID("0134"): "Publius Terentius Afer, Terence",
    AuthorID("0836"): "Aulus Cornelius Celsus",
    AuthorID("0088"): "M. Aemilius Lepidus Porcina",
    AuthorID("1348"): "Gaius Suetonius Tranquillus",
    AuthorID("0013"): "Caecilius Statius",
    AuthorID("0109"): "Q. Caecilius Metellus Maced.",
    AuthorID("0684"): "Marcus Terentius Varro, Varro",
    AuthorID("0638"): "Q. Mucius Scaevola [pontifex]",
    AuthorID("0324"): "Saserna",
    AuthorID("0692"): "Appendix Vergiliana",
    AuthorID("0498"): "Gaius Aurelius Cotta",
    AuthorID("0845"): "L. Iunius Moderatus Columella",
    AuthorID("1047"): "Veranius",
    AuthorID("0899"): "Hyginus Astronomus",
    AuthorID("0878"): "Gaius Asinius Gallus",
    AuthorID("0724"): "Cloatius Verus",
    AuthorID("1038"): "Valerius Maximus",
    AuthorID("0703"): "Arbonius Silo",
    AuthorID("0721"): "Antonius Panurgus",
    AuthorID("0418"): "Titus Quinctius Atta",
    AuthorID("2300"): "Aemilius Sura",
    AuthorID("0662"): "Marcus Tullius Tiro",
    AuthorID("0540"): "Tullius Laurea",
    AuthorID("0432"): "Marcus Furius Bibaculus",
    AuthorID("1242"): "Annius Florus",
    AuthorID("1512"): "Pomponius Porphyrio",
    AuthorID("0416"): "Lucius Ateius Praetextatus",
    AuthorID("0327"): "L. Aelius Praeconinus Stilo",
    AuthorID("0932"): "M. Valerius Messalla Corvinus",
    AuthorID("0097"): "Gaius Lucilius",
    AuthorID("0866"): "Fenestella",
    AuthorID("0458"): "Publius Cannutius",
    AuthorID("0127"): "P. Cornel. Scipio Afr. ma.",
    AuthorID("0034"): "Gaius Scribonius Curio avus",
    AuthorID("0079"): "Hostius",
    AuthorID("0996"): "Marcus Valerius Probus",
    AuthorID("0430"): "Bellum Hispaniense [Anonymous]",
    AuthorID("1011"): "Scribonius Largus",
    AuthorID("0043"): "Quintus Ennius",
    AuthorID("0546"): "Gaius Licinius Mucianus",
    AuthorID("0674"): "Valerius, comoed.",
    AuthorID("1053"): "Vibius Crispus",
    AuthorID("2097"): "Sextus Paconianus",
    AuthorID("0827"): "Caesellius Vindex",
    AuthorID("1029"): "Turnus",
    AuthorID("0061"): "Fabius Pictor",
    AuthorID("0656"): "Servius Sulpicius Rufus",
    AuthorID("0869"): "Marcus Verrius Flaccus",
    AuthorID("1306"): "Lucius Neratius Priscus",
    AuthorID("1005"): "Rabirius",
    AuthorID("1235"): "Didascaliae et Per. in Terentium",
    AuthorID("0975"): "Phaedrus",
    AuthorID("0541"): "Cn. Cornel. Lentulus Marcell.",
    AuthorID("1908"): "Gallus Antipater",
    AuthorID("0694"): "Volumnius",
    AuthorID("0582"): "Q. Caecilius Metellus Numid.",
    AuthorID("0706"): "Carmen de Bello Aegyptiaco",
    AuthorID("1518"): "Terentianus Maurus",
    AuthorID("0650"): "Sueius",
    AuthorID("0446"): "Quintus Servilius Caepio",
    AuthorID("0419"): "Lucius Orbilius Pupillus",
    AuthorID("0644"): "Sextilius Ena",
    AuthorID("0100"): "Luscius Lanuvinus",
    AuthorID("0600"): "Gaius Oppius",
    AuthorID("0442"): "Aulus Caecina",
    AuthorID("0423"): "Lucius Herennius Balbus",
    AuthorID("0408"): "Marcus Antonius triumvir",
    AuthorID("0854"): "Cornificius Gallus",
    AuthorID("1336"): "Scaevus Memor",
    AuthorID("0590"): "Publius Nigidius Figulus",
    AuthorID("0628"): "Publius Rutilius Rufus",
    AuthorID("1351"): "Cornelius Tacitus",
    AuthorID("0028"): "Lucius Coelius Antipater",
    AuthorID("0642"): "Sevius Nicanor",
    AuthorID("0117"): "Papinius, epigram.",
    AuthorID("0615"): "Q. Pompeius Q.f.Q.n. Rufus",
    AuthorID("0914"): "Titus Livius, Livy",
    AuthorID("0460"): "Gaius Papirius Carbo Arvina",
    AuthorID("1014"): "Lucius Annaeus Seneca senior",
    AuthorID("0025"): "Marcus Porcius Cato M.f.M.n.",
    AuthorID("1604"): "Iulius Atherianus",
    AuthorID("0128"): "P. Cornel. Scipio Aem. Afr.",
    AuthorID("2302"): "L. Aurel. Avianius Symmachus",
    AuthorID("0893"): "Quintus Horatius Flaccus, Horace",
    AuthorID("1282"): "Lentulus, mimus",
    AuthorID("2434"): "Hilarius Arelatensis",
    AuthorID("0426"): "Bellum Africum [Anonymous]",
    AuthorID("0016"): "Lucius Calpurnius Piso Frugi",
    AuthorID("0981"): "Gaius Asinius Pollio",
    AuthorID("0445"): "Gaius vel Lucius Caepasius",
    AuthorID("0660"): "Albius Tibullus",
    AuthorID("0631"): "Gaius Sallustius Crispus",
    AuthorID("1318"): "C. Plinius Caecilius Secundus, Pliny",
    AuthorID("0522"): "Gaius Aelius Gallus",
    AuthorID("0488"): "Servius Clodius",
    AuthorID("0678"): "Quintus Valerius Soranus",
    AuthorID("1002"): "Marcus Fabius Quintilianus",
    AuthorID("1339"): "Septimius Serenus",
    AuthorID("1266"): "Hyginus Gromaticus",
    AuthorID("0676"): "Valerius Antias",
    AuthorID("1506"): "Anonymi Fragmenta de Iure Fisci",
    AuthorID("0686"): "P. Terentius Varro Atacinus",
    AuthorID("0064"): "Gaius Fannius",
    AuthorID("0857"): "Lucius Annaeus Cornutus",
    AuthorID("0518"): "Aulus Furius Antias",
    AuthorID("0537"): "Titus Labienus",
    AuthorID("0890"): "Homerus Latinus",
    AuthorID("0550"): "Titus Lucretius Carus",
    AuthorID("0406"): "Publius Alfenus Varus",
    AuthorID("0881"): "Claudius Caesar Germanicus",
    AuthorID("0620"): "Sextus Propertius",
    AuthorID("0137"): "Titinius",
    AuthorID("0512"): "Marcus Duronius",
    AuthorID("0911"): "Laus Pisonis",
    AuthorID("0625"): "Lucius Quinctius",
    AuthorID("0005"): "Aquilius, comoed.",
    AuthorID("0963"): "Quintus Remmius Palaemon",
    AuthorID("0122"): "Aulus Postumius Albinus",
    AuthorID("0473"): "Q. Lutatius Catulus iunior",
    AuthorID("0809"): "Aufidius Bassus",
    AuthorID("0527"): "Gannius",
    AuthorID("0454"): "Marcus Calidius",
    AuthorID("1251"): "Gaius, iur., Gaius",
    AuthorID("1370"): "Quintus Terentius Scaurus",
    AuthorID("0146"): "Sextus Turpilius",
    AuthorID("0842"): "Gaius Clodius Licinus",
    AuthorID("2335"): "Anonymi de Differentiis [Fronto]",
    AuthorID("0532"): "Quintus Hortensius Hortalus",
    AuthorID("0004"): "Appius Claudius Caecus",
    AuthorID("0594"): "Lucius Novius",
    AuthorID("0410"): "Aprissius (?)",
    AuthorID("0526"): "Gaius Servilius Glaucia",
    AuthorID("0800"): "Albinovanus Pedo",
    AuthorID("0884"): "Gracchus, trag.",
    AuthorID("0094"): "Lucius Livius Andronicus",
    AuthorID("0652"): "Lucius Cornelius Sulla",
    AuthorID("0618"): "Lucius Pomponius Bononiensis",
    AuthorID("0412"): "Gaius Aquilius Gallus",
    AuthorID("1248"): "Marcus Cornelius Fronto",
    AuthorID("1234"): "Didascaliae et Argum. in Plautum",
    AuthorID("1203"): "Alfius Avitus",
    AuthorID("0622"): "Publilius Syrus",
    AuthorID("0851"): "Cornelius Severus",
    AuthorID("3211"): "Argum. Aen. et Tetrast.",
    AuthorID("0606"): "Lucius Marcius Philippus",
    AuthorID("1041"): "Pseudo-Varro",
    AuthorID("0830"): "Titus Calpurnius Siculus",
    AuthorID("0002"): "Titus Annius Luscus",
    AuthorID("0664"): "Gaius Trebatius Testa",
    AuthorID("0046"): "Cornelius Epicadus",
    AuthorID("0680"): "Gaius Valgius Rufus",
    AuthorID("0902"): "Iulius Africanus",
    AuthorID("2000"): "Ablabius",
    AuthorID("0993"): "Precatio Terrae",
    AuthorID("9500"): "Anonymi Epici et Lyrici",
    AuthorID("0470"): "Marcus Porcius Cato Uticensis",
    AuthorID("0487"): "Publius Clodius Pulcher",
    AuthorID("1023"): "Sulpicia, Caleni uxor",
    AuthorID("0312"): "Fabius Dossennus",
    AuthorID("0670"): "Quintus Aelius Tubero",
    AuthorID("1285"): "Lucius Volusius Maecianus",
    AuthorID("0022"): "Marcus Porcius Cato, Cato",
    AuthorID("1245"): "Sextus Iulius Frontinus",
    AuthorID("0935"): "Iulius Modestus",
    AuthorID("1032"): "Vagellius",
    AuthorID("0130"): "P. Cornel. Scipio Nasica Ser.",
    AuthorID("1017"): "Lucius Annaeus Seneca iunior",
    AuthorID("0414"): "Lucius Arruntius",
    AuthorID("0330"): "Volcacius Sedigitus",
    AuthorID("0634"): "Santra",
    AuthorID("1227"): "Balbus, grom.",
    AuthorID("1515"): "Quintus Serenus (Sammonicus)",
    AuthorID("0401"): "Aufustius",
    AuthorID("0908"): "Attius Labeo",
    AuthorID("0938"): "Iulius Montanus",
    AuthorID("0091"): "Licinius Imbrex",
    AuthorID("1357"): "Imp. Marcus Ulpius Traianus, Trajan",
    AuthorID("0037"): "Gaius Scribonius Curio pater",
    AuthorID("1224"): "Marcus Aurelius",
    AuthorID("0492"): "Commentarii Augurum",
    AuthorID("0535"): "Marcus Iuventius Laterensis",
    AuthorID("0978"): "Gaius Plinius Secundus, Pliny",
    AuthorID("2468"): "Aurelius Augustinus",
    AuthorID("1327"): "Sabidius",
    AuthorID("0860"): "Quintus Curtius Rufus",
    AuthorID("1260"): "Hadrianus",
    AuthorID("1218"): "Sentius Augurinus",
    AuthorID("0125"): "Publius Mucius Scaevola",
    AuthorID("0119"): "Titus Maccius Plautus",
    AuthorID("0502"): "Aulus Cremutius Cordus",
    AuthorID("1297"): "Marullus",
    AuthorID("0668"): "Gnaeus Tremelius Scrofa",
    AuthorID("1229"): "Flavius Caper",
    AuthorID("0515"): "Sextus (vel Spurius) Ennius",
    AuthorID("0672"): "Turranius Niger",
    AuthorID("0019"): "Gaius Papirius Carbo",
    AuthorID("0917"): "Marcus Annaeus Lucanus",
    AuthorID("9969"): "Vita Iuvenalis",
    AuthorID("0516"): "Gaius Erucius",
    AuthorID("1209"): "Annianus",
    AuthorID("2123"): "Publilius Optatianus Porfyrius",
    AuthorID("2456"): "Parthenius Presbyter",
    AuthorID("2028"): "Chalcidius",
    AuthorID("0303"): "Aurelius Opillus",
    AuthorID("2349"): "Maurus Servius Honoratus, Servius",
    AuthorID("1257"): "Granius Licinianus",
    AuthorID("1000"): "Pupius (?)",
    AuthorID("0070"): "Gnaeus Gellius",
    AuthorID("2806"): "Iustinianus, Justinian, Digest",
    AuthorID("0658"): "Tabulae Censoriae",
    AuthorID("0027"): "Lucius Cincius Alimentus",
    AuthorID("0524"): "Gaius Cornelius Gallus, Gallus",
    AuthorID("0560"): "Helvius Mancia",
    AuthorID("0558"): "Gaius Cilnius Maecenas",
    AuthorID("0562"): "Manilius, poet.",
    AuthorID("0436"): "Marcus Iunius Brutus [tyr.]",
    AuthorID("0803"): "Quintus Asconius Pedianus",
    AuthorID("0118"): "L. Aemilius L.f.M.n. Paulus",
    AuthorID("0321"): "Porcius Licinus",
    AuthorID("0616"): "Pompilius",
    AuthorID("0300"): "Sempronius Asellio",
    AuthorID("0315"): "Marcus Iunius Gracchanus",
    AuthorID("0969"): "Aulus Persius Flaccus",
}
