# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pulpcore.client.pulpcore
from pulpcore.client.pulpcore.models.paginated_user_role_response_list import PaginatedUserRoleResponseList  # noqa: E501
from pulpcore.client.pulpcore.rest import ApiException

class TestPaginatedUserRoleResponseList(unittest.TestCase):
    """PaginatedUserRoleResponseList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PaginatedUserRoleResponseList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pulpcore.client.pulpcore.models.paginated_user_role_response_list.PaginatedUserRoleResponseList()  # noqa: E501
        if include_optional :
            return PaginatedUserRoleResponseList(
                count = 123, 
                next = 'http://api.example.org/accounts/?offset=400&limit=100', 
                previous = 'http://api.example.org/accounts/?offset=200&limit=100', 
                results = [
                    pulpcore.client.pulpcore.models.user_role_response.UserRoleResponse(
                        pulp_href = '0', 
                        pulp_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        pulp_last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        role = '0', 
                        content_object = '0', 
                        description = '0', 
                        permissions = [
                            '0'
                            ], 
                        domain = '0', )
                    ]
            )
        else :
            return PaginatedUserRoleResponseList(
                count = 123,
                results = [
                    pulpcore.client.pulpcore.models.user_role_response.UserRoleResponse(
                        pulp_href = '0', 
                        pulp_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        pulp_last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        role = '0', 
                        content_object = '0', 
                        description = '0', 
                        permissions = [
                            '0'
                            ], 
                        domain = '0', )
                    ],
        )

    def testPaginatedUserRoleResponseList(self):
        """Test PaginatedUserRoleResponseList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
