from pydantic import BaseModel
from typing import ClassVar

class OperationSpec(BaseModel):
    OPERATION_MAP: ClassVar[dict[str, list[str]]]
    MULTI_LEVEL_OP: ClassVar[list[str]]
    operation: str
    tags: str | list[str] | None
    domain: str | None
    @classmethod
    def normalize_domain(cls, v): ...
    def auto_split_tags(cls, values: dict = {}) -> dict: ...
    def check_operation_for_domain(cls, values): ...
    def check_tags_for_property(cls, values): ...
    def to_url_path(self) -> str: ...
    @classmethod
    def from_url_path(cls, path: str, domain: str | None = None) -> OperationSpec: ...
    def validate(self): ...
