from _typeshed import Incomplete
from pybiotech.classes.nih.https.pubchem.input_spec import InputSpec as InputSpec
from pybiotech.classes.nih.https.pubchem.opera_spec import OperationSpec as OperationSpec
from pybiotech.classes.nih.https.pubchem.output_spec import OutputSpec as OutputSpec
from pybiotech.classes.nih.https.pubchem.query_options import QueryOptions as QueryOptions
from typing import Any

class PubChemRequest:
    input_spec: Incomplete
    operation_spec: Incomplete
    output_spec: Incomplete
    query_options: Incomplete
    use_post: Incomplete
    post_body: Incomplete
    def __init__(self, input_spec: InputSpec, operation_spec: OperationSpec, output_spec: OutputSpec, query_options: QueryOptions | None = None, use_post: bool = False, post_body: dict[str, Any] | None = None) -> None: ...
    def validate(self) -> None: ...
    def build_url(self, base_url: str = 'https://pubchem.ncbi.nlm.nih.gov/rest/pug') -> str: ...
    def build_headers(self): ...
    def build_body(self): ...
    def process_response(self, status_code: int, response_text: str): ...
    @classmethod
    def from_url(cls, url: str) -> PubChemRequest: ...
