class RayInitError(Exception): ...


class RayTypeRegistryError(Exception): ...


class RayEvaluationError(Exception): ...


class RayConversionError(Exception): ...


class PartedTableError(Exception): ...
