RESISTANCE = {
    "amethyst": 2,
    "amethyst brick": 3,
    "amethyst brick floor": 3,
    "amethyst block": 2,
    "amethyst boiler": 2,
    "amethyst dirt": 2,
    "amethyst pipe 0": 2,
    "amethyst pipe 1": 2,
    "amethyst pump 0": 2,
    "amethyst pump 1": 2,
    "amethyst rune": 2,
    "anklet of the tree": 1,
    "bluebell jar": 2,
    "bluebell grown": 1,
    "boots": 1,
    "brick": 1,
    "brick floor": 1,
    "burner drill": 2,
    "caelium ingot": 3,
    "caelium sapling": 4,
    "caelium sieve": 3,
    "caelium treeling": 4,
    "caelium tree": 5,
    "citrine": 3,
    "citrine block": 3,
    "citrine rune": 3,
    "clay": 1,
    "coal": 1,
    "coal block": 1,
    "coal ore": 2,
    "coal sapling": 1,
    "coal treeling": 1,
    "coal tree": 2,
    "composter": 1,
    "copper anvil": 2,
    "copper block": 2,
    "copper boiler": 2,
    "copper brick": 3,
    "copper brick floor": 3,
    "copper constructor": 2,
    "copper door": 3,
    "copper door open": 3,
    "copper gear": 2,
    "copper ingot": 2,
    "copper ore": 2,
    "copper pipe 0": 2,
    "copper pipe 1": 2,
    "copper pit grown": 2,
    "copper press": 2,
    "copper pump 0": 2,
    "copper pump 1": 2,
    "copper sapling": 2,
    "copper shaft": 2,
    "copper sheet": 2,
    "copper tank": 2,
    "copper treeling": 2,
    "copper tree": 3,
    "dye bench": 1,
    "furless rabbit": 1,
    "furnace": 3,
    "ice": 1,
    "judge": 2,
    "lava rune": 3,
    "lavastone": 3,
    "lavastone brick": 3,
    "lavastone brick floor": 3,
    "lavastone floor": 3,
    "life crystal": 1,
    "mana converter": 3,
    "manual press": 1,
    "masonry bench": 1,
    "moist dirt": 1,
    "mushroom block": 1,
    "mushroom door": 1,
    "mushroom door open": 1,
    "mushroom floor": 1,
    "mushroom shaper": 2,
    "mushroom table": 1,
    "obelisk piece": 2,
    "packager bench": 1,
    "pebble": 1,
    "potato": 1,
    "potato grown": 1,
    "pure crystal": 2,
    "quartz": 2,
    "quartz adult": 2,
    "quartz altar": 2,
    "quartz block": 2,
    "quartz child": 2,
    "rabbit adult": 1,
    "rail 0": 2,
    "rail 1": 2,
    "rail 2": 2,
    "rail 3": 2,
    "rail 4": 2,
    "rail 5": 2,
    "raw caelium": 3,
    "raw copper": 2,
    "raw tin": 2,
    "rock": 1,
    "sand": 1,
    "sawbench": 1,
    "sewbench": 1,
    "skeleton": 1,
    "slife crystal": 1,
    "slime block": 1,
    "slime crystal": 1,
    "slime door": 1,
    "slime door open": 1,
    "slime floor": 1,
    "slime prince": 1,
    "slime shaper": 1,
    "slime table": 1,
    "stone": 1,
    "stone brick": 1,
    "stone brick floor": 1,
    "stone floor": 1,
    "thread": 2,
    "tin ingot": 2,
    "tin ore": 3,
    "tin sapling": 3,
    "tin treeling": 3,
    "tin tree": 4,
    "tree": 1,
    "wooden sieve": 1,
}
