from ..Base import *
from ..Proxy import *
from ..AcadObject import *
from .AcadSelectionSet import *

class AcadSelectionSets(AppObject):
    def __init__(self, obj) -> None: ...
    Application: AcadApplication
    Count: int
    def Add(self, Name: str = None) -> AcadSelectionSet: ...
    def Item(self, Index: int | str) -> AcadSelectionSet: ...
    def __iter__(self): ...
