# ENV variables
ENV_FASTMCP_LOG_LEVEL = "FASTMCP_LOG_LEVEL"

# OpenAI compatible API ENV variables
ENV_OPENAI_API_KEY = "OPENAI_API_KEY"
ENV_OPENAI_API_BASE = "OPENAI_API_BASE"
ENV_OPENAI_MODEL = "OPENAI_MODEL"