# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/iec61970/base/core/IdentifiedObject.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.protobuf.cim.iec61970.base.core import Name_pb2 as zepben_dot_protobuf_dot_cim_dot_iec61970_dot_base_dot_core_dot_Name__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=zepben/protobuf/cim/iec61970/base/core/IdentifiedObject.proto\x12&zepben.protobuf.cim.iec61970.base.core\x1a\x31zepben/protobuf/cim/iec61970/base/core/Name.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfa\x02\n\x10IdentifiedObject\x12\x0c\n\x04mRID\x18\x01 \x01(\t\x12.\n\x08nameNull\x18\x02 \x01(\x0e\x32\x1a.google.protobuf.NullValueH\x00\x12\x11\n\x07nameSet\x18\x03 \x01(\tH\x00\x12;\n\x15numDiagramObjectsNull\x18\x04 \x01(\x0e\x32\x1a.google.protobuf.NullValueH\x01\x12\x1e\n\x14numDiagramObjectsSet\x18\x05 \x01(\x05H\x01\x12\x35\n\x0f\x64\x65scriptionNull\x18\x06 \x01(\x0e\x32\x1a.google.protobuf.NullValueH\x02\x12\x18\n\x0e\x64\x65scriptionSet\x18\x07 \x01(\tH\x02\x12;\n\x05names\x18\x08 \x03(\x0b\x32,.zepben.protobuf.cim.iec61970.base.core.NameB\x06\n\x04nameB\x13\n\x11numDiagramObjectsB\r\n\x0b\x64\x65scriptionB.\n*com.zepben.protobuf.cim.iec61970.base.coreP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zepben.protobuf.cim.iec61970.base.core.IdentifiedObject_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*com.zepben.protobuf.cim.iec61970.base.coreP\001'
  _globals['_IDENTIFIEDOBJECT']._serialized_start=187
  _globals['_IDENTIFIEDOBJECT']._serialized_end=565
# @@protoc_insertion_point(module_scope)
