# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.webhook_event_detail_response_data import WebhookEventDetailResponseData
from .list_webhook_events_params import ListWebhookEventsParams


class ListWebhookEventsResponse(UniversalBaseModel):
    data: typing.List[WebhookEventDetailResponseData]
    params: ListWebhookEventsParams = pydantic.Field()
    """
    Input parameters
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
