from omu_chat.const import PLUGIN_ID

CHAT_PERMISSION_ID = PLUGIN_ID
CHAT_READ_PERMISSION_ID = CHAT_PERMISSION_ID / "read"
CHAT_WRITE_PERMISSION_ID = CHAT_PERMISSION_ID / "write"
CHAT_SEND_PERMISSION_ID = CHAT_PERMISSION_ID / "send"
CHAT_CHANNEL_TREE_PERMISSION_ID = CHAT_PERMISSION_ID / "create_channel_tree"
CHAT_REACTION_PERMISSION_ID = CHAT_PERMISSION_ID / "reaction"
