"""Feedback chunks changes

Revision ID: 58be389d0ed7
Revises: 80f5954656f0
Create Date: 2025-11-20 01:09:23.916265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58be389d0ed7'
down_revision: Union[str, Sequence[str], None] = '80f5954656f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_chunk_update', sa.Column('source', sa.String(length=50), nullable=False))
    op.drop_column('feedback_chunk_update', 'was_cited')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_chunk_update', sa.Column('was_cited', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('feedback_chunk_update', 'source')
    # ### end Alembic commands ###
