from viralqc import DATASETS_CONFIG_PATH, RUN_ANALYSIS_SNK_PATH

DEFAULT_SNK_FILE = RUN_ANALYSIS_SNK_PATH
DEFAULT_CONFIG_FILE = DATASETS_CONFIG_PATH
DEFAULT_CORES = 1
DEFAULT_OUTPUT_DIR = "outputs"
DEFAULT_OUTPUT_FILE = "results.tsv"
DEFAULT_OUTPUT_FORMAT = "tsv"
DEFAULT_DATASETS_LOCAL_PATH = "datasets"
DEFAULT_NEXTCLADE_SORT_MIN_SCORE = 0.1
DEFAULT_NEXTCLADE_SORT_MIN_HITS = 10
DEFAULT_BLAST_DATABASE = "datasets/blast.fasta"
DEFAULT_BLAST_DATABASE_METADATA = "datasets/blast.tsv"
DEFAULT_BLAST_IDENTITY_THRESHOLD = 80
DEFAULT_BLAST_EVALUE = 1e-10
DEFAULT_BLAST_QCOV = 80
DEFAULT_BLAST_TASK = "megablast"
DEFAULT_VERBOSE = False
