"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cribl_control_plane.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FunctionConfSchemaGeoipAdditionalFieldTypedDict(TypedDict):
    extra_in_field: str
    r"""Field name in which to find an IP to look up. Can be nested."""
    extra_out_field: str
    r"""Field name in which to store the GeoIP lookup results"""


class FunctionConfSchemaGeoipAdditionalField(BaseModel):
    extra_in_field: Annotated[str, pydantic.Field(alias="extraInField")]
    r"""Field name in which to find an IP to look up. Can be nested."""

    extra_out_field: Annotated[str, pydantic.Field(alias="extraOutField")]
    r"""Field name in which to store the GeoIP lookup results"""


class FunctionConfSchemaGeoipOutputFieldMappingsTypedDict(TypedDict):
    r"""Search-specific mappings for granular control over event enrichment"""


class FunctionConfSchemaGeoipOutputFieldMappings(BaseModel):
    r"""Search-specific mappings for granular control over event enrichment"""


class FunctionConfSchemaGeoipTypedDict(TypedDict):
    file: NotRequired[str]
    r"""Select an uploaded Maxmind database, or specify path to a Maxmind database with .mmdb extension"""
    in_field: NotRequired[str]
    r"""Field name in which to find an IP to look up. Can be nested."""
    out_field: NotRequired[str]
    r"""Field name in which to store the GeoIP lookup results"""
    additional_fields: NotRequired[
        List[FunctionConfSchemaGeoipAdditionalFieldTypedDict]
    ]
    out_field_mappings: NotRequired[FunctionConfSchemaGeoipOutputFieldMappingsTypedDict]
    r"""Search-specific mappings for granular control over event enrichment"""


class FunctionConfSchemaGeoip(BaseModel):
    file: Optional[str] = None
    r"""Select an uploaded Maxmind database, or specify path to a Maxmind database with .mmdb extension"""

    in_field: Annotated[Optional[str], pydantic.Field(alias="inField")] = "ip"
    r"""Field name in which to find an IP to look up. Can be nested."""

    out_field: Annotated[Optional[str], pydantic.Field(alias="outField")] = "geoip"
    r"""Field name in which to store the GeoIP lookup results"""

    additional_fields: Annotated[
        Optional[List[FunctionConfSchemaGeoipAdditionalField]],
        pydantic.Field(alias="additionalFields"),
    ] = None

    out_field_mappings: Annotated[
        Optional[FunctionConfSchemaGeoipOutputFieldMappings],
        pydantic.Field(alias="outFieldMappings"),
    ] = None
    r"""Search-specific mappings for granular control over event enrichment"""
