from pydantic import BaseModel

class Identifier(BaseModel):
    raw: str
    type_hint: str | None
    @classmethod
    def validate_and_normalize(cls, v: str, info): ...
    def is_int(self) -> bool: ...
    def as_url_part(self) -> str: ...

class Identifiers(BaseModel):
    items: list[Identifier]
    @classmethod
    def from_string(cls, s: str, type_hint: str | None = None) -> Identifiers: ...
    def as_url_part(self) -> str: ...
