from typing import Callable, Generic, Iterable, TypeVar

T = TypeVar('T')

class Cycle(Generic[T]):
    elements: tuple[T, ...]
    def __init__(self, elements: Iterable[T]) -> None: ...
    @staticmethod
    def normalize(cycle: Iterable[T]) -> tuple[T, ...]: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

def find_cycles(function: Callable[[T], Iterable[T]], elements: Iterable[T], /) -> set[Cycle[T]]: ...
