"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from abc import (
    ABCMeta,
    abstractmethod,
)
from chalk._gen.chalk.server.v1.script_tasks_pb2 import (
    CreateScriptTaskRequest,
    CreateScriptTaskResponse,
    GetScriptTaskRequest,
    GetScriptTaskResponse,
    GetScriptTaskSourceRequest,
    GetScriptTaskSourceResponse,
    ListScriptTasksRequest,
    ListScriptTasksResponse,
)
from grpc import (
    Channel,
    Server,
    ServicerContext,
    UnaryUnaryMultiCallable,
)

class ScriptTaskServiceStub:
    def __init__(self, channel: Channel) -> None: ...
    CreateScriptTask: UnaryUnaryMultiCallable[
        CreateScriptTaskRequest,
        CreateScriptTaskResponse,
    ]
    ListScriptTasks: UnaryUnaryMultiCallable[
        ListScriptTasksRequest,
        ListScriptTasksResponse,
    ]
    GetScriptTask: UnaryUnaryMultiCallable[
        GetScriptTaskRequest,
        GetScriptTaskResponse,
    ]
    GetScriptTaskSource: UnaryUnaryMultiCallable[
        GetScriptTaskSourceRequest,
        GetScriptTaskSourceResponse,
    ]

class ScriptTaskServiceServicer(metaclass=ABCMeta):
    @abstractmethod
    def CreateScriptTask(
        self,
        request: CreateScriptTaskRequest,
        context: ServicerContext,
    ) -> CreateScriptTaskResponse: ...
    @abstractmethod
    def ListScriptTasks(
        self,
        request: ListScriptTasksRequest,
        context: ServicerContext,
    ) -> ListScriptTasksResponse: ...
    @abstractmethod
    def GetScriptTask(
        self,
        request: GetScriptTaskRequest,
        context: ServicerContext,
    ) -> GetScriptTaskResponse: ...
    @abstractmethod
    def GetScriptTaskSource(
        self,
        request: GetScriptTaskSourceRequest,
        context: ServicerContext,
    ) -> GetScriptTaskSourceResponse: ...

def add_ScriptTaskServiceServicer_to_server(servicer: ScriptTaskServiceServicer, server: Server) -> None: ...
