from __future__ import annotations
import pxr.Usd._usd
import typing
import Boost.Python
import pxr.Sdf
import pxr.Tf
import pxr.Usd

__all__ = [
    "APISchemaBase",
    "AssetInfoKeys",
    "Attribute",
    "AttributeQuery",
    "BlockStageCachePopulation",
    "BlockStageCaches",
    "ClipsAPI",
    "CollectionAPI",
    "ColorSpaceAPI",
    "ColorSpaceCache",
    "ColorSpaceDefinitionAPI",
    "ColorSpaceHashCache",
    "CompositionArc",
    "ComputeIncludedObjectsFromCollection",
    "ComputeIncludedPathsFromCollection",
    "ComputePathExpressionFromCollectionMembershipQueryRuleMap",
    "CrateInfo",
    "Describe",
    "EditContext",
    "EditTarget",
    "FlattenLayerStack",
    "FlattenLayerStackAdvanced",
    "FlattenLayerStackResolveAssetPath",
    "FlattenLayerStackResolveAssetPathAdvanced",
    "FlattenResolveAssetPathContext",
    "GetMajorVersion",
    "GetMinorVersion",
    "GetPatchVersion",
    "GetVersion",
    "Inherits",
    "InterpolationType",
    "InterpolationTypeHeld",
    "InterpolationTypeLinear",
    "ListPosition",
    "ListPositionBackOfAppendList",
    "ListPositionBackOfPrependList",
    "ListPositionFrontOfAppendList",
    "ListPositionFrontOfPrependList",
    "LoadPolicy",
    "LoadWithDescendants",
    "LoadWithoutDescendants",
    "ModelAPI",
    "NamespaceEditor",
    "Notice",
    "Object",
    "Payloads",
    "Prim",
    "PrimAllPrimsPredicate",
    "PrimCompositionQuery",
    "PrimDefaultPredicate",
    "PrimDefinition",
    "PrimHasDefiningSpecifier",
    "PrimIsAbstract",
    "PrimIsActive",
    "PrimIsDefined",
    "PrimIsGroup",
    "PrimIsInstance",
    "PrimIsLoaded",
    "PrimIsModel",
    "PrimRange",
    "PrimTypeInfo",
    "Property",
    "References",
    "Relationship",
    "ResolveInfo",
    "ResolveInfoSource",
    "ResolveInfoSourceDefault",
    "ResolveInfoSourceFallback",
    "ResolveInfoSourceNone",
    "ResolveInfoSourceSpline",
    "ResolveInfoSourceTimeSamples",
    "ResolveInfoSourceValueClips",
    "ResolveTarget",
    "SchemaBase",
    "SchemaKind",
    "SchemaRegistry",
    "Specializes",
    "Stage",
    "StageCache",
    "StageCacheContext",
    "StageCacheContextBlockType",
    "StageLoadRules",
    "StagePopulationMask",
    "TimeCode",
    "Tokens",
    "TraverseInstanceProxies",
    "Typed",
    "UsdCollectionMembershipQuery",
    "UsdFileFormat",
    "UseButDoNotPopulateCache",
    "VariantSet",
    "VariantSets",
    "ZipFile",
    "ZipFileWriter"
]


class APISchemaBase(SchemaBase, Boost.Python.instance):
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    pass
class AssetInfoKeys(Boost.Python.instance):
    identifier = 'identifier'
    name = 'name'
    payloadAssetDependencies = 'payloadAssetDependencies'
    version = 'version'
    pass
class Attribute(Property, Object, Boost.Python.instance):
    @staticmethod
    def AddConnection(*args, **kwargs) -> None: ...
    @staticmethod
    def Block(*args, **kwargs) -> None: ...
    @staticmethod
    def Clear(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearAtTime(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearColorSpace(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearConnections(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearDefault(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBracketingTimeSamples(*args, **kwargs) -> None: ...
    @staticmethod
    def GetColorSpace(*args, **kwargs) -> None: ...
    @staticmethod
    def GetConnections(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNumTimeSamples(*args, **kwargs) -> None: ...
    @staticmethod
    def GetResolveInfo(*args, **kwargs) -> None: ...
    @staticmethod
    def GetRoleName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSpline(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTimeSamples(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTimeSamplesInInterval(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTypeName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetUnionedTimeSamples(*args, **kwargs) -> None: ...
    @staticmethod
    def GetUnionedTimeSamplesInInterval(*args, **kwargs) -> None: ...
    @staticmethod
    def GetVariability(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredConnections(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredValue(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredValueOpinion(*args, **kwargs) -> None: ...
    @staticmethod
    def HasColorSpace(*args, **kwargs) -> None: ...
    @staticmethod
    def HasFallbackValue(*args, **kwargs) -> None: ...
    @staticmethod
    def HasSpline(*args, **kwargs) -> None: ...
    @staticmethod
    def HasValue(*args, **kwargs) -> None: ...
    @staticmethod
    def RemoveConnection(*args, **kwargs) -> None: ...
    @staticmethod
    def Set(*args, **kwargs) -> None: ...
    @staticmethod
    def SetColorSpace(*args, **kwargs) -> None: ...
    @staticmethod
    def SetConnections(*args, **kwargs) -> None: ...
    @staticmethod
    def SetSpline(*args, **kwargs) -> None: ...
    @staticmethod
    def SetTypeName(*args, **kwargs) -> None: ...
    @staticmethod
    def SetVariability(*args, **kwargs) -> None: ...
    @staticmethod
    def ValueMightBeTimeVarying(*args, **kwargs) -> None: ...
    __instance_size__ = 56
    pass
class AttributeQuery(Boost.Python.instance):
    @staticmethod
    def CreateQueries(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAttribute(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBracketingTimeSamples(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNumTimeSamples(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTimeSamples(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTimeSamplesInInterval(*args, **kwargs) -> None: ...
    @staticmethod
    def GetUnionedTimeSamples(*args, **kwargs) -> None: ...
    @staticmethod
    def GetUnionedTimeSamplesInInterval(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredValue(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredValueOpinion(*args, **kwargs) -> None: ...
    @staticmethod
    def HasFallbackValue(*args, **kwargs) -> None: ...
    @staticmethod
    def HasValue(*args, **kwargs) -> None: ...
    @staticmethod
    def IsValid(*args, **kwargs) -> None: ...
    @staticmethod
    def ValueMightBeTimeVarying(*args, **kwargs) -> None: ...
    pass
class ClipsAPI(APISchemaBase, SchemaBase, Boost.Python.instance):
    @staticmethod
    def ComputeClipAssetPaths(*args, **kwargs) -> None: ...
    @staticmethod
    def GenerateClipManifest(*args, **kwargs) -> None: ...
    @staticmethod
    def GenerateClipManifestFromLayers(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetClipActive(*args, **kwargs) -> None: ...
    @staticmethod
    def GetClipAssetPaths(*args, **kwargs) -> None: ...
    @staticmethod
    def GetClipManifestAssetPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetClipPrimPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetClipSets(*args, **kwargs) -> None: ...
    @staticmethod
    def GetClipTemplateActiveOffset(*args, **kwargs) -> None: ...
    @staticmethod
    def GetClipTemplateAssetPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetClipTemplateEndTime(*args, **kwargs) -> None: ...
    @staticmethod
    def GetClipTemplateStartTime(*args, **kwargs) -> None: ...
    @staticmethod
    def GetClipTemplateStride(*args, **kwargs) -> None: ...
    @staticmethod
    def GetClipTimes(*args, **kwargs) -> None: ...
    @staticmethod
    def GetClips(*args, **kwargs) -> None: ...
    @staticmethod
    def GetInterpolateMissingClipValues(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def SetClipActive(*args, **kwargs) -> None: ...
    @staticmethod
    def SetClipAssetPaths(*args, **kwargs) -> None: ...
    @staticmethod
    def SetClipManifestAssetPath(*args, **kwargs) -> None: ...
    @staticmethod
    def SetClipPrimPath(*args, **kwargs) -> None: ...
    @staticmethod
    def SetClipSets(*args, **kwargs) -> None: ...
    @staticmethod
    def SetClipTemplateActiveOffset(*args, **kwargs) -> None: ...
    @staticmethod
    def SetClipTemplateAssetPath(*args, **kwargs) -> None: ...
    @staticmethod
    def SetClipTemplateEndTime(*args, **kwargs) -> None: ...
    @staticmethod
    def SetClipTemplateStartTime(*args, **kwargs) -> None: ...
    @staticmethod
    def SetClipTemplateStride(*args, **kwargs) -> None: ...
    @staticmethod
    def SetClipTimes(*args, **kwargs) -> None: ...
    @staticmethod
    def SetClips(*args, **kwargs) -> None: ...
    @staticmethod
    def SetInterpolateMissingClipValues(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 56
    pass
class CollectionAPI(APISchemaBase, SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> None: ...
    @staticmethod
    def BlockCollection(*args, **kwargs) -> None: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> None: ...
    @staticmethod
    def CanContainPropertyName(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeIncludedObjects(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeIncludedPaths(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeMembershipQuery(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateCollectionAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateExcludesRel(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateExpansionRuleAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateIncludeRootAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateIncludesRel(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateMembershipExpressionAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def ExcludePath(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAll(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAllCollections(*args, **kwargs) -> None: ...
    @staticmethod
    def GetCollection(*args, **kwargs) -> None: ...
    @staticmethod
    def GetCollectionAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetCollectionPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetExcludesRel(*args, **kwargs) -> None: ...
    @staticmethod
    def GetExpansionRuleAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetIncludeRootAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetIncludesRel(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMembershipExpressionAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNamedCollectionPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def HasNoIncludedPaths(*args, **kwargs) -> None: ...
    @staticmethod
    def IncludePath(*args, **kwargs) -> None: ...
    @staticmethod
    def IsCollectionAPIPath(*args, **kwargs) -> None: ...
    @staticmethod
    def IsInExpressionMode(*args, **kwargs) -> None: ...
    @staticmethod
    def IsInRelationshipsMode(*args, **kwargs) -> None: ...
    @staticmethod
    def IsSchemaPropertyBaseName(*args, **kwargs) -> None: ...
    @staticmethod
    def ResetCollection(*args, **kwargs) -> None: ...
    @staticmethod
    def ResolveCompleteMembershipExpression(*args, **kwargs) -> None: ...
    @staticmethod
    def Validate(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 56
    pass
class ColorSpaceAPI(APISchemaBase, SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> None: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeColorSpace(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeColorSpaceName(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateColorSpaceNameAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetColorSpaceNameAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def IsValidColorSpaceName(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 56
    pass
class ColorSpaceCache(Boost.Python.instance):
    @staticmethod
    def Find(*args, **kwargs) -> None: ...
    @staticmethod
    def Insert(*args, **kwargs) -> None: ...
    __instance_size__ = 40
    pass
class ColorSpaceDefinitionAPI(APISchemaBase, SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> None: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeColorSpaceFromDefinitionAttributes(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateBlueChromaAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateColorSpaceAttrsWithChroma(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateColorSpaceAttrsWithMatrix(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateGammaAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateGreenChromaAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateLinearBiasAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateNameAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateRedChromaAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateWhitePointAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAll(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBlueChromaAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetGammaAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetGreenChromaAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetLinearBiasAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNameAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetRedChromaAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetWhitePointAttr(*args, **kwargs) -> None: ...
    @staticmethod
    def IsColorSpaceDefinitionAPIPath(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 56
    pass
class ColorSpaceHashCache(ColorSpaceCache, Boost.Python.instance):
    @staticmethod
    def Find(*args, **kwargs) -> None: ...
    @staticmethod
    def Insert(*args, **kwargs) -> None: ...
    __instance_size__ = 120
    pass
class CompositionArc(Boost.Python.instance):
    @staticmethod
    def GetArcType(*args, **kwargs) -> None: ...
    @staticmethod
    def GetIntroducingLayer(*args, **kwargs) -> None: ...
    @staticmethod
    def GetIntroducingListEditor(*args, **kwargs) -> None: ...
    @staticmethod
    def GetIntroducingNode(*args, **kwargs) -> None: ...
    @staticmethod
    def GetIntroducingPrimPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTargetLayer(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTargetNode(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTargetPrimPath(*args, **kwargs) -> None: ...
    @staticmethod
    def HasSpecs(*args, **kwargs) -> None: ...
    @staticmethod
    def IsAncestral(*args, **kwargs) -> None: ...
    @staticmethod
    def IsImplicit(*args, **kwargs) -> None: ...
    @staticmethod
    def IsIntroducedInRootLayerPrimSpec(*args, **kwargs) -> None: ...
    @staticmethod
    def IsIntroducedInRootLayerStack(*args, **kwargs) -> None: ...
    @staticmethod
    def MakeResolveTargetStrongerThan(*args, **kwargs) -> None: ...
    @staticmethod
    def MakeResolveTargetUpTo(*args, **kwargs) -> None: ...
    pass
class CrateInfo(Boost.Python.instance):
    class Section(Boost.Python.instance):
        @property
        def name(self) -> None:
            """
            :type: None
            """
        @property
        def size(self) -> None:
            """
            :type: None
            """
        @property
        def start(self) -> None:
            """
            :type: None
            """
        __instance_size__ = 72
        pass
    class SummaryStats(Boost.Python.instance):
        @property
        def numSpecs(self) -> None:
            """
            :type: None
            """
        @property
        def numUniqueFieldSets(self) -> None:
            """
            :type: None
            """
        @property
        def numUniqueFields(self) -> None:
            """
            :type: None
            """
        @property
        def numUniquePaths(self) -> None:
            """
            :type: None
            """
        @property
        def numUniqueStrings(self) -> None:
            """
            :type: None
            """
        @property
        def numUniqueTokens(self) -> None:
            """
            :type: None
            """
        __instance_size__ = 72
        pass
    @staticmethod
    def GetFileVersion(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSections(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSoftwareVersion(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSummaryStats(*args, **kwargs) -> None: ...
    @staticmethod
    def Open(*args, **kwargs) -> None: ...
    __instance_size__ = 40
    pass
class EditContext(Boost.Python.instance):
    __instance_size__ = 128
    pass
class EditTarget(Boost.Python.instance):
    @staticmethod
    def ComposeOver(*args, **kwargs) -> None: ...
    @staticmethod
    def ForLocalDirectVariant(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAttributeSpecForScenePath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetLayer(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMapFunction(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrimSpecForScenePath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPropertySpecForScenePath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetRelationshipSpecForScenePath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSpecForScenePath(*args, **kwargs) -> None: ...
    @staticmethod
    def IsNull(*args, **kwargs) -> None: ...
    @staticmethod
    def IsValid(*args, **kwargs) -> None: ...
    @staticmethod
    def MapToSpecPath(*args, **kwargs) -> None: ...
    __instance_size__ = 96
    pass
class FlattenResolveAssetPathContext(Boost.Python.instance):
    @property
    def assetPath(self) -> None:
        """
        :type: None
        """
    @property
    def expressionVariables(self) -> None:
        """
        :type: None
        """
    @property
    def sourceLayer(self) -> None:
        """
        :type: None
        """
    pass
class Inherits(Boost.Python.instance):
    @staticmethod
    def AddInherit(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearInherits(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAllDirectInherits(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def RemoveInherit(*args, **kwargs) -> None: ...
    @staticmethod
    def SetInherits(*args, **kwargs) -> None: ...
    pass
class InterpolationType(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
    @staticmethod
    def GetValueFromName(*args, **kwargs) -> None: ...
    _baseName = ''
    allValues: tuple # value = (Usd.InterpolationTypeHeld, Usd.InterpolationTypeLinear)
    pass
class ListPosition(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
    @staticmethod
    def GetValueFromName(*args, **kwargs) -> None: ...
    _baseName = ''
    allValues: tuple # value = (Usd.ListPositionFrontOfPrependList, Usd.ListPositionBackOfPrependList, Usd.ListPositionFrontOfAppendList, Usd.ListPositionBackOfAppendList)
    pass
class LoadPolicy(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
    @staticmethod
    def GetValueFromName(*args, **kwargs) -> None: ...
    _baseName = ''
    allValues: tuple # value = (Usd.LoadWithDescendants, Usd.LoadWithoutDescendants)
    pass
class ModelAPI(APISchemaBase, SchemaBase, Boost.Python.instance):
    class KindValidation(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
        @staticmethod
        def GetValueFromName(*args, **kwargs) -> None: ...
        _baseName = 'ModelAPI'
        allValues: tuple # value = (Usd.ModelAPI.KindValidationNone, Usd.ModelAPI.KindValidationModelHierarchy)
        pass
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAssetIdentifier(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAssetInfo(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAssetName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAssetVersion(*args, **kwargs) -> None: ...
    @staticmethod
    def GetKind(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPayloadAssetDependencies(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def IsGroup(*args, **kwargs) -> None: ...
    @staticmethod
    def IsKind(*args, **kwargs) -> None: ...
    @staticmethod
    def IsModel(*args, **kwargs) -> None: ...
    @staticmethod
    def SetAssetIdentifier(*args, **kwargs) -> None: ...
    @staticmethod
    def SetAssetInfo(*args, **kwargs) -> None: ...
    @staticmethod
    def SetAssetName(*args, **kwargs) -> None: ...
    @staticmethod
    def SetAssetVersion(*args, **kwargs) -> None: ...
    @staticmethod
    def SetKind(*args, **kwargs) -> None: ...
    @staticmethod
    def SetPayloadAssetDependencies(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    KindValidationModelHierarchy: pxr.Usd.KindValidation # value = Usd.ModelAPI.KindValidationModelHierarchy
    KindValidationNone: pxr.Usd.KindValidation # value = Usd.ModelAPI.KindValidationNone
    __instance_size__ = 56
    pass
class NamespaceEditor(Boost.Python.instance):
    class EditOptions(Boost.Python.instance):
        @property
        def allowRelocatesAuthoring(self) -> None:
            """
            :type: None
            """
        __instance_size__ = 32
        pass
    @staticmethod
    def AddDependentStage(*args, **kwargs) -> None: ...
    @staticmethod
    def ApplyEdits(*args, **kwargs) -> None: ...
    @staticmethod
    def CanApplyEdits(*args, **kwargs) -> None: ...
    @staticmethod
    def DeletePrim(*args, **kwargs) -> None: ...
    @staticmethod
    def DeletePrimAtPath(*args, **kwargs) -> None: ...
    @staticmethod
    def DeleteProperty(*args, **kwargs) -> None: ...
    @staticmethod
    def DeletePropertyAtPath(*args, **kwargs) -> None: ...
    @staticmethod
    def MovePrimAtPath(*args, **kwargs) -> None: ...
    @staticmethod
    def MovePropertyAtPath(*args, **kwargs) -> None: ...
    @staticmethod
    def RemoveDependentStage(*args, **kwargs) -> None: ...
    @staticmethod
    def RenamePrim(*args, **kwargs) -> None: ...
    @staticmethod
    def RenameProperty(*args, **kwargs) -> None: ...
    @staticmethod
    def ReparentPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def ReparentProperty(*args, **kwargs) -> None: ...
    @staticmethod
    def SetDependentStages(*args, **kwargs) -> None: ...
    pass
class Notice(Boost.Python.instance):
    class LayerMutingChanged(StageNotice, pxr.Tf.Notice, Boost.Python.instance):
        @staticmethod
        def GetMutedLayers(*args, **kwargs) -> None: ...
        @staticmethod
        def GetUnmutedLayers(*args, **kwargs) -> None: ...
        pass
    class ObjectsChanged(StageNotice, pxr.Tf.Notice, Boost.Python.instance):
        class PrimResyncType(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
            @staticmethod
            def GetValueFromName(*args, **kwargs) -> None: ...
            Delete: pxr.Usd.PrimResyncType # value = Usd.Notice.ObjectsChanged.PrimResyncType.Delete
            Invalid: pxr.Usd.PrimResyncType # value = Usd.Notice.ObjectsChanged.PrimResyncType.Invalid
            Other: pxr.Usd.PrimResyncType # value = Usd.Notice.ObjectsChanged.PrimResyncType.Other
            RenameAndReparentDestination: pxr.Usd.PrimResyncType # value = Usd.Notice.ObjectsChanged.PrimResyncType.RenameAndReparentDestination
            RenameAndReparentSource: pxr.Usd.PrimResyncType # value = Usd.Notice.ObjectsChanged.PrimResyncType.RenameAndReparentSource
            RenameDestination: pxr.Usd.PrimResyncType # value = Usd.Notice.ObjectsChanged.PrimResyncType.RenameDestination
            RenameSource: pxr.Usd.PrimResyncType # value = Usd.Notice.ObjectsChanged.PrimResyncType.RenameSource
            ReparentDestination: pxr.Usd.PrimResyncType # value = Usd.Notice.ObjectsChanged.PrimResyncType.ReparentDestination
            ReparentSource: pxr.Usd.PrimResyncType # value = Usd.Notice.ObjectsChanged.PrimResyncType.ReparentSource
            UnchangedPrimStack: pxr.Usd.PrimResyncType # value = Usd.Notice.ObjectsChanged.PrimResyncType.UnchangedPrimStack
            _baseName = 'Notice.ObjectsChanged.PrimResyncType'
            allValues: tuple # value = (Usd.Notice.ObjectsChanged.PrimResyncType.RenameSource, Usd.Notice.ObjectsChanged.PrimResyncType.RenameDestination, Usd.Notice.ObjectsChanged.PrimResyncType.ReparentSource, Usd.Notice.ObjectsChanged.PrimResyncType.ReparentDestination, Usd.Notice.ObjectsChanged.PrimResyncType.RenameAndReparentSource, Usd.Notice.ObjectsChanged.PrimResyncType.RenameAndReparentDestination, Usd.Notice.ObjectsChanged.PrimResyncType.Delete, Usd.Notice.ObjectsChanged.PrimResyncType.UnchangedPrimStack, Usd.Notice.ObjectsChanged.PrimResyncType.Other, Usd.Notice.ObjectsChanged.PrimResyncType.Invalid)
            pass
        @staticmethod
        def AffectedObject(*args, **kwargs) -> None: ...
        @staticmethod
        def ChangedInfoOnly(*args, **kwargs) -> None: ...
        @staticmethod
        def GetChangedFields(*args, **kwargs) -> None: ...
        @staticmethod
        def GetChangedInfoOnlyPaths(*args, **kwargs) -> None: ...
        @staticmethod
        def GetPrimResyncType(*args, **kwargs) -> None: ...
        @staticmethod
        def GetRenamedProperties(*args, **kwargs) -> None: ...
        @staticmethod
        def GetResolvedAssetPathsResyncedPaths(*args, **kwargs) -> None: ...
        @staticmethod
        def GetResyncedPaths(*args, **kwargs) -> None: ...
        @staticmethod
        def HasChangedFields(*args, **kwargs) -> None: ...
        @staticmethod
        def ResolvedAssetPathsResynced(*args, **kwargs) -> None: ...
        @staticmethod
        def ResyncedObject(*args, **kwargs) -> None: ...
        pass
    class StageContentsChanged(StageNotice, pxr.Tf.Notice, Boost.Python.instance):
        pass
    class StageEditTargetChanged(StageNotice, pxr.Tf.Notice, Boost.Python.instance):
        pass
    class StageNotice(pxr.Tf.Notice, Boost.Python.instance):
        @staticmethod
        def GetStage(*args, **kwargs) -> None: ...
        pass
    pass
class Object(Boost.Python.instance):
    @staticmethod
    def ClearAssetInfo(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearAssetInfoByKey(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearCustomData(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearCustomDataByKey(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearDisplayName(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearDocumentation(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearHidden(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearMetadata(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearMetadataByDictKey(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAllAuthoredMetadata(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAllMetadata(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAssetInfo(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAssetInfoByKey(*args, **kwargs) -> None: ...
    @staticmethod
    def GetCustomData(*args, **kwargs) -> None: ...
    @staticmethod
    def GetCustomDataByKey(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDescription(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDisplayName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDocumentation(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMetadata(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMetadataByDictKey(*args, **kwargs) -> None: ...
    @staticmethod
    def GetName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNamespaceDelimiter(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrimPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetStage(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAssetInfo(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAssetInfoKey(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredAssetInfo(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredAssetInfoKey(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredCustomData(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredCustomDataKey(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredDisplayName(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredDocumentation(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredHidden(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredMetadata(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredMetadataDictKey(*args, **kwargs) -> None: ...
    @staticmethod
    def HasCustomData(*args, **kwargs) -> None: ...
    @staticmethod
    def HasCustomDataKey(*args, **kwargs) -> None: ...
    @staticmethod
    def HasMetadata(*args, **kwargs) -> None: ...
    @staticmethod
    def HasMetadataDictKey(*args, **kwargs) -> None: ...
    @staticmethod
    def IsHidden(*args, **kwargs) -> None: ...
    @staticmethod
    def IsValid(*args, **kwargs) -> None: ...
    @staticmethod
    def SetAssetInfo(*args, **kwargs) -> None: ...
    @staticmethod
    def SetAssetInfoByKey(*args, **kwargs) -> None: ...
    @staticmethod
    def SetCustomData(*args, **kwargs) -> None: ...
    @staticmethod
    def SetCustomDataByKey(*args, **kwargs) -> None: ...
    @staticmethod
    def SetDisplayName(*args, **kwargs) -> None: ...
    @staticmethod
    def SetDocumentation(*args, **kwargs) -> None: ...
    @staticmethod
    def SetHidden(*args, **kwargs) -> None: ...
    @staticmethod
    def SetMetadata(*args, **kwargs) -> None: ...
    @staticmethod
    def SetMetadataByDictKey(*args, **kwargs) -> None: ...
    __instance_size__ = 56
    pass
class Payloads(Boost.Python.instance):
    @staticmethod
    def AddInternalPayload(*args, **kwargs) -> None: ...
    @staticmethod
    def AddPayload(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearPayloads(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def RemovePayload(*args, **kwargs) -> None: ...
    @staticmethod
    def SetPayloads(*args, **kwargs) -> None: ...
    pass
class Prim(Object, Boost.Python.instance):
    @staticmethod
    def AddAppliedSchema(*args, **kwargs) -> None: ...
    @staticmethod
    def ApplyAPI(*args, **kwargs) -> None: ...
    @staticmethod
    def CanApplyAPI(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearActive(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearChildrenReorder(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearInstanceable(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearPayload(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearPropertyOrder(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearTypeName(*args, **kwargs) -> None: ...
    @staticmethod
    def ComputeExpandedPrimIndex(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateAttribute(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateRelationship(*args, **kwargs) -> None: ...
    @staticmethod
    def FindAllAttributeConnectionPaths(*args, **kwargs) -> None: ...
    @staticmethod
    def FindAllRelationshipTargetPaths(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAllChildren(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAllChildrenNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAppliedSchemas(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAttribute(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAttributeAtPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAttributes(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAuthoredAttributes(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAuthoredProperties(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAuthoredPropertiesInNamespace(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAuthoredPropertyNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAuthoredRelationships(*args, **kwargs) -> None: ...
    @staticmethod
    def GetChild(*args, **kwargs) -> None: ...
    @staticmethod
    def GetChildren(*args, **kwargs) -> None: ...
    @staticmethod
    def GetChildrenNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetChildrenReorder(*args, **kwargs) -> None: ...
    @staticmethod
    def GetFilteredChildren(*args, **kwargs) -> None: ...
    @staticmethod
    def GetFilteredChildrenNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetFilteredNextSibling(*args, **kwargs) -> None: ...
    @staticmethod
    def GetInherits(*args, **kwargs) -> None: ...
    @staticmethod
    def GetInstances(*args, **kwargs) -> None: ...
    @staticmethod
    def GetKind(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNextSibling(*args, **kwargs) -> None: ...
    @staticmethod
    def GetObjectAtPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetParent(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPayloads(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrimAtPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrimDefinition(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrimInPrototype(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrimIndex(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrimStack(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrimStackWithLayerOffsets(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrimTypeInfo(*args, **kwargs) -> None: ...
    @staticmethod
    def GetProperties(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPropertiesInNamespace(*args, **kwargs) -> None: ...
    @staticmethod
    def GetProperty(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPropertyAtPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPropertyNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPropertyOrder(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrototype(*args, **kwargs) -> None: ...
    @staticmethod
    def GetReferences(*args, **kwargs) -> None: ...
    @staticmethod
    def GetRelationship(*args, **kwargs) -> None: ...
    @staticmethod
    def GetRelationshipAtPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetRelationships(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSpecializes(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSpecifier(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTypeName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetVariantSet(*args, **kwargs) -> None: ...
    @staticmethod
    def GetVariantSets(*args, **kwargs) -> None: ...
    @staticmethod
    def GetVersionIfHasAPIInFamily(*args, **kwargs) -> None: ...
    @staticmethod
    def GetVersionIfIsInFamily(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAPI(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAPIInFamily(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAttribute(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredActive(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredInherits(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredInstanceable(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredPayloads(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredReferences(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredSpecializes(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredTypeName(*args, **kwargs) -> None: ...
    @staticmethod
    def HasDefiningSpecifier(*args, **kwargs) -> None: ...
    @staticmethod
    def HasPayload(*args, **kwargs) -> None: ...
    @staticmethod
    def HasProperty(*args, **kwargs) -> None: ...
    @staticmethod
    def HasRelationship(*args, **kwargs) -> None: ...
    @staticmethod
    def HasVariantSets(*args, **kwargs) -> None: ...
    @staticmethod
    def IsA(*args, **kwargs) -> None: ...
    @staticmethod
    def IsAbstract(*args, **kwargs) -> None: ...
    @staticmethod
    def IsActive(*args, **kwargs) -> None: ...
    @staticmethod
    def IsComponent(*args, **kwargs) -> None: ...
    @staticmethod
    def IsDefined(*args, **kwargs) -> None: ...
    @staticmethod
    def IsGroup(*args, **kwargs) -> None: ...
    @staticmethod
    def IsInFamily(*args, **kwargs) -> None: ...
    @staticmethod
    def IsInPrototype(*args, **kwargs) -> None: ...
    @staticmethod
    def IsInstance(*args, **kwargs) -> None: ...
    @staticmethod
    def IsInstanceProxy(*args, **kwargs) -> None: ...
    @staticmethod
    def IsInstanceable(*args, **kwargs) -> None: ...
    @staticmethod
    def IsLoaded(*args, **kwargs) -> None: ...
    @staticmethod
    def IsModel(*args, **kwargs) -> None: ...
    @staticmethod
    def IsPathInPrototype(*args, **kwargs) -> None: ...
    @staticmethod
    def IsPrototype(*args, **kwargs) -> None: ...
    @staticmethod
    def IsPrototypePath(*args, **kwargs) -> None: ...
    @staticmethod
    def IsPseudoRoot(*args, **kwargs) -> None: ...
    @staticmethod
    def IsSubComponent(*args, **kwargs) -> None: ...
    @staticmethod
    def Load(*args, **kwargs) -> None: ...
    @staticmethod
    def MakeResolveTargetStrongerThanEditTarget(*args, **kwargs) -> None: ...
    @staticmethod
    def MakeResolveTargetUpToEditTarget(*args, **kwargs) -> None: ...
    @staticmethod
    def RemoveAPI(*args, **kwargs) -> None: ...
    @staticmethod
    def RemoveAppliedSchema(*args, **kwargs) -> None: ...
    @staticmethod
    def RemoveProperty(*args, **kwargs) -> None: ...
    @staticmethod
    def SetActive(*args, **kwargs) -> None: ...
    @staticmethod
    def SetChildrenReorder(*args, **kwargs) -> None: ...
    @staticmethod
    def SetInstanceable(*args, **kwargs) -> None: ...
    @staticmethod
    def SetKind(*args, **kwargs) -> None: ...
    @staticmethod
    def SetPayload(*args, **kwargs) -> None: ...
    @staticmethod
    def SetPropertyOrder(*args, **kwargs) -> None: ...
    @staticmethod
    def SetSpecifier(*args, **kwargs) -> None: ...
    @staticmethod
    def SetTypeName(*args, **kwargs) -> None: ...
    @staticmethod
    def Unload(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetSourcePrimIndex(*args, **kwargs) -> None: ...
    __instance_size__ = 56
    pass
class PrimCompositionQuery(Boost.Python.instance):
    class ArcIntroducedFilter(Boost.Python.enum, int):
        All = pxr.Usd.ArcIntroducedFilter.All
        IntroducedInRootLayerPrimSpec = pxr.Usd.ArcIntroducedFilter.IntroducedInRootLayerPrimSpec
        IntroducedInRootLayerStack = pxr.Usd.ArcIntroducedFilter.IntroducedInRootLayerStack
        __slots__ = ()
        names = {'All': pxr.Usd.ArcIntroducedFilter.All, 'IntroducedInRootLayerStack': pxr.Usd.ArcIntroducedFilter.IntroducedInRootLayerStack, 'IntroducedInRootLayerPrimSpec': pxr.Usd.ArcIntroducedFilter.IntroducedInRootLayerPrimSpec}
        values = {0: pxr.Usd.ArcIntroducedFilter.All, 1: pxr.Usd.ArcIntroducedFilter.IntroducedInRootLayerStack, 2: pxr.Usd.ArcIntroducedFilter.IntroducedInRootLayerPrimSpec}
        pass
    class ArcTypeFilter(Boost.Python.enum, int):
        All = pxr.Usd.ArcTypeFilter.All
        Inherit = pxr.Usd.ArcTypeFilter.Inherit
        InheritOrSpecialize = pxr.Usd.ArcTypeFilter.InheritOrSpecialize
        NotInheritOrSpecialize = pxr.Usd.ArcTypeFilter.NotInheritOrSpecialize
        NotReferenceOrPayload = pxr.Usd.ArcTypeFilter.NotReferenceOrPayload
        NotVariant = pxr.Usd.ArcTypeFilter.NotVariant
        Payload = pxr.Usd.ArcTypeFilter.Payload
        Reference = pxr.Usd.ArcTypeFilter.Reference
        ReferenceOrPayload = pxr.Usd.ArcTypeFilter.ReferenceOrPayload
        Specialize = pxr.Usd.ArcTypeFilter.Specialize
        Variant = pxr.Usd.ArcTypeFilter.Variant
        __slots__ = ()
        names = {'All': pxr.Usd.ArcTypeFilter.All, 'Reference': pxr.Usd.ArcTypeFilter.Reference, 'Payload': pxr.Usd.ArcTypeFilter.Payload, 'Inherit': pxr.Usd.ArcTypeFilter.Inherit, 'Specialize': pxr.Usd.ArcTypeFilter.Specialize, 'Variant': pxr.Usd.ArcTypeFilter.Variant, 'ReferenceOrPayload': pxr.Usd.ArcTypeFilter.ReferenceOrPayload, 'InheritOrSpecialize': pxr.Usd.ArcTypeFilter.InheritOrSpecialize, 'NotReferenceOrPayload': pxr.Usd.ArcTypeFilter.NotReferenceOrPayload, 'NotInheritOrSpecialize': pxr.Usd.ArcTypeFilter.NotInheritOrSpecialize, 'NotVariant': pxr.Usd.ArcTypeFilter.NotVariant}
        values = {0: pxr.Usd.ArcTypeFilter.All, 1: pxr.Usd.ArcTypeFilter.Reference, 2: pxr.Usd.ArcTypeFilter.Payload, 3: pxr.Usd.ArcTypeFilter.Inherit, 4: pxr.Usd.ArcTypeFilter.Specialize, 5: pxr.Usd.ArcTypeFilter.Variant, 6: pxr.Usd.ArcTypeFilter.ReferenceOrPayload, 7: pxr.Usd.ArcTypeFilter.InheritOrSpecialize, 8: pxr.Usd.ArcTypeFilter.NotReferenceOrPayload, 9: pxr.Usd.ArcTypeFilter.NotInheritOrSpecialize, 10: pxr.Usd.ArcTypeFilter.NotVariant}
        pass
    class DependencyTypeFilter(Boost.Python.enum, int):
        All = pxr.Usd.DependencyTypeFilter.All
        Ancestral = pxr.Usd.DependencyTypeFilter.Ancestral
        Direct = pxr.Usd.DependencyTypeFilter.Direct
        __slots__ = ()
        names = {'All': pxr.Usd.DependencyTypeFilter.All, 'Direct': pxr.Usd.DependencyTypeFilter.Direct, 'Ancestral': pxr.Usd.DependencyTypeFilter.Ancestral}
        values = {0: pxr.Usd.DependencyTypeFilter.All, 1: pxr.Usd.DependencyTypeFilter.Direct, 2: pxr.Usd.DependencyTypeFilter.Ancestral}
        pass
    class Filter(Boost.Python.instance):
        @property
        def arcIntroducedFilter(self) -> None:
            """
            :type: None
            """
        @property
        def arcTypeFilter(self) -> None:
            """
            :type: None
            """
        @property
        def dependencyTypeFilter(self) -> None:
            """
            :type: None
            """
        @property
        def hasSpecsFilter(self) -> None:
            """
            :type: None
            """
        __instance_size__ = 40
        pass
    class HasSpecsFilter(Boost.Python.enum, int):
        All = pxr.Usd.HasSpecsFilter.All
        HasNoSpecs = pxr.Usd.HasSpecsFilter.HasNoSpecs
        HasSpecs = pxr.Usd.HasSpecsFilter.HasSpecs
        __slots__ = ()
        names = {'All': pxr.Usd.HasSpecsFilter.All, 'HasSpecs': pxr.Usd.HasSpecsFilter.HasSpecs, 'HasNoSpecs': pxr.Usd.HasSpecsFilter.HasNoSpecs}
        values = {0: pxr.Usd.HasSpecsFilter.All, 1: pxr.Usd.HasSpecsFilter.HasSpecs, 2: pxr.Usd.HasSpecsFilter.HasNoSpecs}
        pass
    @staticmethod
    def GetCompositionArcs(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDirectInherits(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDirectReferences(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDirectRootLayerArcs(*args, **kwargs) -> None: ...
    @property
    def filter(self) -> None:
        """
        :type: None
        """
    pass
class PrimDefinition(Boost.Python.instance):
    class Attribute(Property, Boost.Python.instance):
        @staticmethod
        def GetFallbackValue(*args, **kwargs) -> None: ...
        @staticmethod
        def GetTypeName(*args, **kwargs) -> None: ...
        @staticmethod
        def GetTypeNameToken(*args, **kwargs) -> None: ...
        __instance_size__ = 40
        pass
    class Property(Boost.Python.instance):
        @staticmethod
        def GetDocumentation(*args, **kwargs) -> None: ...
        @staticmethod
        def GetMetadata(*args, **kwargs) -> None: ...
        @staticmethod
        def GetMetadataByDictKey(*args, **kwargs) -> None: ...
        @staticmethod
        def GetName(*args, **kwargs) -> None: ...
        @staticmethod
        def GetSpecType(*args, **kwargs) -> None: ...
        @staticmethod
        def GetVariability(*args, **kwargs) -> None: ...
        @staticmethod
        def IsAttribute(*args, **kwargs) -> None: ...
        @staticmethod
        def IsRelationship(*args, **kwargs) -> None: ...
        @staticmethod
        def ListMetadataFields(*args, **kwargs) -> None: ...
        __instance_size__ = 40
        pass
    class Relationship(Property, Boost.Python.instance):
        __instance_size__ = 40
        pass
    @staticmethod
    def FlattenTo(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAppliedAPISchemas(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAttributeDefinition(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAttributeFallbackValue(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDocumentation(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMetadata(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMetadataByDictKey(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPropertyDefinition(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPropertyDocumentation(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPropertyMetadata(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPropertyMetadataByDictKey(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPropertyNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetRelationshipDefinition(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeSpec(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaPropertySpec(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaRelationshipSpec(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSpecType(*args, **kwargs) -> None: ...
    @staticmethod
    def ListMetadataFields(*args, **kwargs) -> None: ...
    @staticmethod
    def ListPropertyMetadataFields(*args, **kwargs) -> None: ...
    pass
class PrimRange(Boost.Python.instance):
    class _Iterator(Boost.Python.instance):
        @staticmethod
        def GetCurrentPrim(*args, **kwargs) -> None: 
            """
            Since an iterator cannot be dereferenced in python, GetCurrentPrim()
             performs the same function: yielding the currently visited prim.
            """
        @staticmethod
        def IsPostVisit(*args, **kwargs) -> None: ...
        @staticmethod
        def IsValid(*args, **kwargs) -> None: 
            """
            true if the iterator is not yet exhausted
            """
        @staticmethod
        def PruneChildren(*args, **kwargs) -> None: ...
        pass
    @staticmethod
    def AllPrims(*args, **kwargs) -> None: ...
    @staticmethod
    def AllPrimsPreAndPostVisit(*args, **kwargs) -> None: ...
    @staticmethod
    def IsValid(*args, **kwargs) -> None: 
        """
        true if the iterator is not yet exhausted
        """
    @staticmethod
    def PreAndPostVisit(*args, **kwargs) -> None: ...
    @staticmethod
    def Stage(*args, **kwargs) -> None: ...
    pass
class PrimTypeInfo(Boost.Python.instance):
    @staticmethod
    def GetAppliedAPISchemas(*args, **kwargs) -> None: ...
    @staticmethod
    def GetEmptyPrimType(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrimDefinition(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaType(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaTypeName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTypeName(*args, **kwargs) -> None: ...
    pass
class Property(Object, Boost.Python.instance):
    @staticmethod
    def ClearDisplayGroup(*args, **kwargs) -> None: ...
    @staticmethod
    def FlattenTo(*args, **kwargs) -> None: ...
    @staticmethod
    def GetBaseName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDisplayGroup(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNamespace(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNestedDisplayGroups(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPropertyStack(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPropertyStackWithLayerOffsets(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredDisplayGroup(*args, **kwargs) -> None: ...
    @staticmethod
    def IsAuthored(*args, **kwargs) -> None: ...
    @staticmethod
    def IsAuthoredAt(*args, **kwargs) -> None: ...
    @staticmethod
    def IsCustom(*args, **kwargs) -> None: ...
    @staticmethod
    def IsDefined(*args, **kwargs) -> None: ...
    @staticmethod
    def SetCustom(*args, **kwargs) -> None: ...
    @staticmethod
    def SetDisplayGroup(*args, **kwargs) -> None: ...
    @staticmethod
    def SetNestedDisplayGroups(*args, **kwargs) -> None: ...
    @staticmethod
    def SplitName(*args, **kwargs) -> None: ...
    __instance_size__ = 56
    pass
class References(Boost.Python.instance):
    @staticmethod
    def AddInternalReference(*args, **kwargs) -> None: ...
    @staticmethod
    def AddReference(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearReferences(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def RemoveReference(*args, **kwargs) -> None: ...
    @staticmethod
    def SetReferences(*args, **kwargs) -> None: ...
    pass
class Relationship(Property, Object, Boost.Python.instance):
    @staticmethod
    def AddTarget(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearTargets(*args, **kwargs) -> None: ...
    @staticmethod
    def GetForwardedTargets(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTargets(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredTargets(*args, **kwargs) -> None: ...
    @staticmethod
    def RemoveTarget(*args, **kwargs) -> None: ...
    @staticmethod
    def SetTargets(*args, **kwargs) -> None: ...
    __instance_size__ = 56
    pass
class ResolveInfo(Boost.Python.instance):
    @staticmethod
    def GetNode(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSource(*args, **kwargs) -> None: ...
    @staticmethod
    def ValueIsBlocked(*args, **kwargs) -> None: ...
    __instance_size__ = 136
    pass
class ResolveInfoSource(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
    @staticmethod
    def GetValueFromName(*args, **kwargs) -> None: ...
    _baseName = ''
    allValues: tuple # value = (Usd.ResolveInfoSourceNone, Usd.ResolveInfoSourceFallback, Usd.ResolveInfoSourceDefault, Usd.ResolveInfoSourceTimeSamples, Usd.ResolveInfoSourceValueClips, Usd.ResolveInfoSourceSpline)
    pass
class ResolveTarget(Boost.Python.instance):
    @staticmethod
    def GetPrimIndex(*args, **kwargs) -> None: ...
    @staticmethod
    def GetStartLayer(*args, **kwargs) -> None: ...
    @staticmethod
    def GetStartNode(*args, **kwargs) -> None: ...
    @staticmethod
    def GetStopLayer(*args, **kwargs) -> None: ...
    @staticmethod
    def GetStopNode(*args, **kwargs) -> None: ...
    @staticmethod
    def IsNull(*args, **kwargs) -> None: ...
    __instance_size__ = 120
    pass
class SchemaBase(Boost.Python.instance):
    @staticmethod
    def GetPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaClassPrimDefinition(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaKind(*args, **kwargs) -> None: ...
    @staticmethod
    def IsAPISchema(*args, **kwargs) -> None: ...
    @staticmethod
    def IsAppliedAPISchema(*args, **kwargs) -> None: ...
    @staticmethod
    def IsConcrete(*args, **kwargs) -> None: ...
    @staticmethod
    def IsMultipleApplyAPISchema(*args, **kwargs) -> None: ...
    @staticmethod
    def IsTyped(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class SchemaKind(Boost.Python.enum, int):
    AbstractBase = pxr.Usd.SchemaKind.AbstractBase
    AbstractTyped = pxr.Usd.SchemaKind.AbstractTyped
    ConcreteTyped = pxr.Usd.SchemaKind.ConcreteTyped
    Invalid = pxr.Usd.SchemaKind.Invalid
    MultipleApplyAPI = pxr.Usd.SchemaKind.MultipleApplyAPI
    NonAppliedAPI = pxr.Usd.SchemaKind.NonAppliedAPI
    SingleApplyAPI = pxr.Usd.SchemaKind.SingleApplyAPI
    __slots__ = ()
    names = {'Invalid': pxr.Usd.SchemaKind.Invalid, 'AbstractBase': pxr.Usd.SchemaKind.AbstractBase, 'AbstractTyped': pxr.Usd.SchemaKind.AbstractTyped, 'ConcreteTyped': pxr.Usd.SchemaKind.ConcreteTyped, 'NonAppliedAPI': pxr.Usd.SchemaKind.NonAppliedAPI, 'SingleApplyAPI': pxr.Usd.SchemaKind.SingleApplyAPI, 'MultipleApplyAPI': pxr.Usd.SchemaKind.MultipleApplyAPI}
    values = {0: pxr.Usd.SchemaKind.Invalid, 1: pxr.Usd.SchemaKind.AbstractBase, 2: pxr.Usd.SchemaKind.AbstractTyped, 3: pxr.Usd.SchemaKind.ConcreteTyped, 4: pxr.Usd.SchemaKind.NonAppliedAPI, 5: pxr.Usd.SchemaKind.SingleApplyAPI, 6: pxr.Usd.SchemaKind.MultipleApplyAPI}
    pass
class SchemaRegistry(Boost.Python.instance):
    class SchemaInfo(Boost.Python.instance):
        @property
        def family(self) -> None:
            """
            :type: None
            """
        @property
        def identifier(self) -> None:
            """
            :type: None
            """
        @property
        def kind(self) -> None:
            """
            :type: None
            """
        @property
        def type(self) -> None:
            """
            :type: None
            """
        @property
        def version(self) -> None:
            """
            :type: None
            """
        pass
    class VersionPolicy(Boost.Python.enum, int):
        All = pxr.Usd.VersionPolicy.All
        GreaterThan = pxr.Usd.VersionPolicy.GreaterThan
        GreaterThanOrEqual = pxr.Usd.VersionPolicy.GreaterThanOrEqual
        LessThan = pxr.Usd.VersionPolicy.LessThan
        LessThanOrEqual = pxr.Usd.VersionPolicy.LessThanOrEqual
        __slots__ = ()
        names = {'All': pxr.Usd.VersionPolicy.All, 'GreaterThan': pxr.Usd.VersionPolicy.GreaterThan, 'GreaterThanOrEqual': pxr.Usd.VersionPolicy.GreaterThanOrEqual, 'LessThan': pxr.Usd.VersionPolicy.LessThan, 'LessThanOrEqual': pxr.Usd.VersionPolicy.LessThanOrEqual}
        values = {0: pxr.Usd.VersionPolicy.All, 1: pxr.Usd.VersionPolicy.GreaterThan, 2: pxr.Usd.VersionPolicy.GreaterThanOrEqual, 3: pxr.Usd.VersionPolicy.LessThan, 4: pxr.Usd.VersionPolicy.LessThanOrEqual}
        pass
    @staticmethod
    def BuildComposedPrimDefinition(*args, **kwargs) -> None: ...
    @staticmethod
    def FindAppliedAPIPrimDefinition(*args, **kwargs) -> None: ...
    @staticmethod
    def FindConcretePrimDefinition(*args, **kwargs) -> None: ...
    @staticmethod
    def FindSchemaInfo(*args, **kwargs) -> None: ...
    @staticmethod
    def FindSchemaInfosInFamily(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAPISchemaCanOnlyApplyToTypeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAPISchemaTypeName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAPITypeFromSchemaTypeName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAutoApplyAPISchemas(*args, **kwargs) -> None: ...
    @staticmethod
    def GetConcreteSchemaTypeName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetConcreteTypeFromSchemaTypeName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetEmptyPrimDefinition(*args, **kwargs) -> None: ...
    @staticmethod
    def GetFallbackPrimTypes(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMultipleApplyNameTemplateBaseName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaKind(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaTypeName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTypeFromName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTypeFromSchemaTypeName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTypeNameAndInstance(*args, **kwargs) -> None: ...
    @staticmethod
    def IsAbstract(*args, **kwargs) -> None: ...
    @staticmethod
    def IsAllowedAPISchemaInstanceName(*args, **kwargs) -> None: ...
    @staticmethod
    def IsAllowedSchemaFamily(*args, **kwargs) -> None: ...
    @staticmethod
    def IsAllowedSchemaIdentifier(*args, **kwargs) -> None: ...
    @staticmethod
    def IsAppliedAPISchema(*args, **kwargs) -> None: ...
    @staticmethod
    def IsConcrete(*args, **kwargs) -> None: ...
    @staticmethod
    def IsDisallowedField(*args, **kwargs) -> None: ...
    @staticmethod
    def IsMultipleApplyAPISchema(*args, **kwargs) -> None: ...
    @staticmethod
    def IsMultipleApplyNameTemplate(*args, **kwargs) -> None: ...
    @staticmethod
    def IsTyped(*args, **kwargs) -> None: ...
    @staticmethod
    def MakeMultipleApplyNameInstance(*args, **kwargs) -> None: ...
    @staticmethod
    def MakeMultipleApplyNameTemplate(*args, **kwargs) -> None: ...
    @staticmethod
    def MakeSchemaIdentifierForFamilyAndVersion(*args, **kwargs) -> None: ...
    @staticmethod
    def ParseSchemaFamilyAndVersionFromIdentifier(*args, **kwargs) -> None: ...
    @property
    def expired(self) -> None:
        """
        True if this object has expired, False otherwise.

        :type: None
        """
    pass
class Specializes(Boost.Python.instance):
    @staticmethod
    def AddSpecialize(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearSpecializes(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def RemoveSpecialize(*args, **kwargs) -> None: ...
    @staticmethod
    def SetSpecializes(*args, **kwargs) -> None: ...
    pass
class Stage(Boost.Python.instance):
    class InitialLoadSet(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
        @staticmethod
        def GetValueFromName(*args, **kwargs) -> None: ...
        _baseName = 'Stage'
        allValues: tuple # value = (Usd.Stage.LoadAll, Usd.Stage.LoadNone)
        pass
    @staticmethod
    def ClearDefaultPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearMetadata(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearMetadataByDictKey(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateClassPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateInMemory(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateNew(*args, **kwargs) -> None: ...
    @staticmethod
    def DefinePrim(*args, **kwargs) -> None: ...
    @staticmethod
    def ExpandPopulationMask(*args, **kwargs) -> None: ...
    @staticmethod
    def Export(*args, **kwargs) -> None: ...
    @staticmethod
    def ExportToString(*args, **kwargs) -> None: ...
    @staticmethod
    def FindLoadable(*args, **kwargs) -> None: ...
    @staticmethod
    def Flatten(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAttributeAtPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetColorConfigFallbacks(*args, **kwargs) -> None: ...
    @staticmethod
    def GetColorConfiguration(*args, **kwargs) -> None: ...
    @staticmethod
    def GetColorManagementSystem(*args, **kwargs) -> None: ...
    @staticmethod
    def GetCompositionErrors(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDefaultPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def GetEditTarget(*args, **kwargs) -> None: ...
    @staticmethod
    def GetEditTargetForLocalLayer(*args, **kwargs) -> None: ...
    @staticmethod
    def GetEndTimeCode(*args, **kwargs) -> None: ...
    @staticmethod
    def GetFramesPerSecond(*args, **kwargs) -> None: ...
    @staticmethod
    def GetGlobalVariantFallbacks(*args, **kwargs) -> None: ...
    @staticmethod
    def GetInterpolationType(*args, **kwargs) -> None: ...
    @staticmethod
    def GetLayerStack(*args, **kwargs) -> None: ...
    @staticmethod
    def GetLoadRules(*args, **kwargs) -> None: ...
    @staticmethod
    def GetLoadSet(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMetadata(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMetadataByDictKey(*args, **kwargs) -> None: ...
    @staticmethod
    def GetMutedLayers(*args, **kwargs) -> None: ...
    @staticmethod
    def GetObjectAtPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPathResolverContext(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPopulationMask(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrimAtPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPropertyAtPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrototypes(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPseudoRoot(*args, **kwargs) -> None: ...
    @staticmethod
    def GetRelationshipAtPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetRootLayer(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSessionLayer(*args, **kwargs) -> None: ...
    @staticmethod
    def GetStartTimeCode(*args, **kwargs) -> None: ...
    @staticmethod
    def GetTimeCodesPerSecond(*args, **kwargs) -> None: ...
    @staticmethod
    def GetUsedLayers(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredMetadata(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredMetadataDictKey(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredTimeCodeRange(*args, **kwargs) -> None: ...
    @staticmethod
    def HasDefaultPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def HasLocalLayer(*args, **kwargs) -> None: ...
    @staticmethod
    def HasMetadata(*args, **kwargs) -> None: ...
    @staticmethod
    def HasMetadataDictKey(*args, **kwargs) -> None: ...
    @staticmethod
    def IsLayerMuted(*args, **kwargs) -> None: ...
    @staticmethod
    def IsSupportedFile(*args, **kwargs) -> None: ...
    @staticmethod
    def Load(*args, **kwargs) -> None: ...
    @staticmethod
    def LoadAndUnload(*args, **kwargs) -> None: ...
    @staticmethod
    def MuteAndUnmuteLayers(*args, **kwargs) -> None: ...
    @staticmethod
    def MuteLayer(*args, **kwargs) -> None: ...
    @staticmethod
    def Open(*args, **kwargs) -> None: ...
    @staticmethod
    def OpenMasked(*args, **kwargs) -> None: ...
    @staticmethod
    def OverridePrim(*args, **kwargs) -> None: ...
    @staticmethod
    def Reload(*args, **kwargs) -> None: ...
    @staticmethod
    def RemovePrim(*args, **kwargs) -> None: ...
    @staticmethod
    def ResolveIdentifierToEditTarget(*args, **kwargs) -> None: ...
    @staticmethod
    def Save(*args, **kwargs) -> None: ...
    @staticmethod
    def SaveSessionLayers(*args, **kwargs) -> None: ...
    @staticmethod
    def SetColorConfigFallbacks(*args, **kwargs) -> None: ...
    @staticmethod
    def SetColorConfiguration(*args, **kwargs) -> None: ...
    @staticmethod
    def SetColorManagementSystem(*args, **kwargs) -> None: ...
    @staticmethod
    def SetDefaultPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def SetEditTarget(*args, **kwargs) -> None: ...
    @staticmethod
    def SetEndTimeCode(*args, **kwargs) -> None: ...
    @staticmethod
    def SetFramesPerSecond(*args, **kwargs) -> None: ...
    @staticmethod
    def SetGlobalVariantFallbacks(*args, **kwargs) -> None: ...
    @staticmethod
    def SetInterpolationType(*args, **kwargs) -> None: ...
    @staticmethod
    def SetLoadRules(*args, **kwargs) -> None: ...
    @staticmethod
    def SetMetadata(*args, **kwargs) -> None: ...
    @staticmethod
    def SetMetadataByDictKey(*args, **kwargs) -> None: ...
    @staticmethod
    def SetPopulationMask(*args, **kwargs) -> None: ...
    @staticmethod
    def SetStartTimeCode(*args, **kwargs) -> None: ...
    @staticmethod
    def SetTimeCodesPerSecond(*args, **kwargs) -> None: ...
    @staticmethod
    def Traverse(*args, **kwargs) -> None: ...
    @staticmethod
    def TraverseAll(*args, **kwargs) -> None: ...
    @staticmethod
    def Unload(*args, **kwargs) -> None: ...
    @staticmethod
    def UnmuteLayer(*args, **kwargs) -> None: ...
    @staticmethod
    def WriteFallbackPrimTypes(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetPcpCache(*args, **kwargs) -> None: ...
    @property
    def expired(self) -> None:
        """
        True if this object has expired, False otherwise.

        :type: None
        """
    LoadAll: pxr.Usd.InitialLoadSet # value = Usd.Stage.LoadAll
    LoadNone: pxr.Usd.InitialLoadSet # value = Usd.Stage.LoadNone
    pass
class StageCache(Boost.Python.instance):
    class Id(Boost.Python.instance):
        @staticmethod
        def FromLongInt(*args, **kwargs) -> None: ...
        @staticmethod
        def FromString(*args, **kwargs) -> None: ...
        @staticmethod
        def IsValid(*args, **kwargs) -> None: ...
        @staticmethod
        def ToLongInt(*args, **kwargs) -> None: ...
        @staticmethod
        def ToString(*args, **kwargs) -> None: ...
        __instance_size__ = 32
        pass
    @staticmethod
    def Clear(*args, **kwargs) -> None: ...
    @staticmethod
    def Contains(*args, **kwargs) -> None: ...
    @staticmethod
    def Erase(*args, **kwargs) -> None: ...
    @staticmethod
    def EraseAll(*args, **kwargs) -> None: ...
    @staticmethod
    def Find(*args, **kwargs) -> None: ...
    @staticmethod
    def FindAllMatching(*args, **kwargs) -> None: ...
    @staticmethod
    def FindOneMatching(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAllStages(*args, **kwargs) -> None: ...
    @staticmethod
    def GetDebugName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetId(*args, **kwargs) -> None: ...
    @staticmethod
    def Insert(*args, **kwargs) -> None: ...
    @staticmethod
    def IsEmpty(*args, **kwargs) -> None: ...
    @staticmethod
    def SetDebugName(*args, **kwargs) -> None: ...
    @staticmethod
    def Size(*args, **kwargs) -> None: ...
    @staticmethod
    def swap(*args, **kwargs) -> None: ...
    __instance_size__ = 112
    pass
class StageCacheContext(Boost.Python.instance):
    pass
class StageCacheContextBlockType(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
    @staticmethod
    def GetValueFromName(*args, **kwargs) -> None: ...
    _baseName = ''
    allValues: tuple # value = (Usd.BlockStageCaches, Usd.BlockStageCachePopulation, Usd._NoBlock)
    pass
class StageLoadRules(Boost.Python.instance):
    class Rule(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
        @staticmethod
        def GetValueFromName(*args, **kwargs) -> None: ...
        _baseName = 'StageLoadRules'
        allValues: tuple # value = (Usd.StageLoadRules.AllRule, Usd.StageLoadRules.OnlyRule, Usd.StageLoadRules.NoneRule)
        pass
    @staticmethod
    def AddRule(*args, **kwargs) -> None: ...
    @staticmethod
    def GetEffectiveRuleForPath(*args, **kwargs) -> None: ...
    @staticmethod
    def GetRules(*args, **kwargs) -> None: ...
    @staticmethod
    def IsLoaded(*args, **kwargs) -> None: ...
    @staticmethod
    def IsLoadedWithAllDescendants(*args, **kwargs) -> None: ...
    @staticmethod
    def IsLoadedWithNoDescendants(*args, **kwargs) -> None: ...
    @staticmethod
    def LoadAll(*args, **kwargs) -> None: ...
    @staticmethod
    def LoadAndUnload(*args, **kwargs) -> None: ...
    @staticmethod
    def LoadNone(*args, **kwargs) -> None: ...
    @staticmethod
    def LoadWithDescendants(*args, **kwargs) -> None: ...
    @staticmethod
    def LoadWithoutDescendants(*args, **kwargs) -> None: ...
    @staticmethod
    def Minimize(*args, **kwargs) -> None: ...
    @staticmethod
    def SetRules(*args, **kwargs) -> None: ...
    @staticmethod
    def Unload(*args, **kwargs) -> None: ...
    @staticmethod
    def swap(*args, **kwargs) -> None: ...
    AllRule: pxr.Usd.Rule # value = Usd.StageLoadRules.AllRule
    NoneRule: pxr.Usd.Rule # value = Usd.StageLoadRules.NoneRule
    OnlyRule: pxr.Usd.Rule # value = Usd.StageLoadRules.OnlyRule
    __instance_size__ = 48
    pass
class StagePopulationMask(Boost.Python.instance):
    @staticmethod
    def Add(*args, **kwargs) -> None: ...
    @staticmethod
    def All(*args, **kwargs) -> None: ...
    @staticmethod
    def GetIncludedChildNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetIntersection(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPaths(*args, **kwargs) -> None: ...
    @staticmethod
    def GetUnion(*args, **kwargs) -> None: ...
    @staticmethod
    def Includes(*args, **kwargs) -> None: ...
    @staticmethod
    def IncludesSubtree(*args, **kwargs) -> None: ...
    @staticmethod
    def Intersection(*args, **kwargs) -> None: ...
    @staticmethod
    def IsEmpty(*args, **kwargs) -> None: ...
    @staticmethod
    def Union(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class TimeCode(Boost.Python.instance):
    class Tokens(Boost.Python.instance):
        DEFAULT = 'DEFAULT'
        EARLIEST = 'EARLIEST'
        PRE_TIME = 'PRE_TIME'
        pass
    @staticmethod
    def Default(*args, **kwargs) -> None: ...
    @staticmethod
    def EarliestTime(*args, **kwargs) -> None: ...
    @staticmethod
    def GetValue(*args, **kwargs) -> None: ...
    @staticmethod
    def IsDefault(*args, **kwargs) -> None: ...
    @staticmethod
    def IsEarliestTime(*args, **kwargs) -> None: ...
    @staticmethod
    def IsNumeric(*args, **kwargs) -> None: ...
    @staticmethod
    def IsPreTime(*args, **kwargs) -> None: ...
    @staticmethod
    def PreTime(*args, **kwargs) -> None: ...
    @staticmethod
    def SafeStep(*args, **kwargs) -> None: ...
    @staticmethod
    def Test_TimeCodeSequenceRoundTrip(*args, **kwargs) -> None: ...
    __instance_size__ = 40
    pass
class Tokens(Boost.Python.instance):
    APISchemaBase = 'APISchemaBase'
    ClipsAPI = 'ClipsAPI'
    CollectionAPI = 'CollectionAPI'
    ColorSpaceAPI = 'ColorSpaceAPI'
    ColorSpaceDefinitionAPI = 'ColorSpaceDefinitionAPI'
    ModelAPI = 'ModelAPI'
    Typed = 'Typed'
    apiSchemas = 'apiSchemas'
    clipSets = 'clipSets'
    clips = 'clips'
    collection = 'collection'
    collection_MultipleApplyTemplate_ = 'collection:__INSTANCE_NAME__'
    collection_MultipleApplyTemplate_Excludes = 'collection:__INSTANCE_NAME__:excludes'
    collection_MultipleApplyTemplate_ExpansionRule = 'collection:__INSTANCE_NAME__:expansionRule'
    collection_MultipleApplyTemplate_IncludeRoot = 'collection:__INSTANCE_NAME__:includeRoot'
    collection_MultipleApplyTemplate_Includes = 'collection:__INSTANCE_NAME__:includes'
    collection_MultipleApplyTemplate_MembershipExpression = 'collection:__INSTANCE_NAME__:membershipExpression'
    colorSpaceDefinition = 'colorSpaceDefinition'
    colorSpaceDefinition_MultipleApplyTemplate_BlueChroma = 'colorSpaceDefinition:__INSTANCE_NAME__:blueChroma'
    colorSpaceDefinition_MultipleApplyTemplate_Gamma = 'colorSpaceDefinition:__INSTANCE_NAME__:gamma'
    colorSpaceDefinition_MultipleApplyTemplate_GreenChroma = 'colorSpaceDefinition:__INSTANCE_NAME__:greenChroma'
    colorSpaceDefinition_MultipleApplyTemplate_LinearBias = 'colorSpaceDefinition:__INSTANCE_NAME__:linearBias'
    colorSpaceDefinition_MultipleApplyTemplate_Name = 'colorSpaceDefinition:__INSTANCE_NAME__:name'
    colorSpaceDefinition_MultipleApplyTemplate_RedChroma = 'colorSpaceDefinition:__INSTANCE_NAME__:redChroma'
    colorSpaceDefinition_MultipleApplyTemplate_WhitePoint = 'colorSpaceDefinition:__INSTANCE_NAME__:whitePoint'
    colorSpaceName = 'colorSpace:name'
    custom = 'custom'
    exclude = 'exclude'
    expandPrims = 'expandPrims'
    expandPrimsAndProperties = 'expandPrimsAndProperties'
    explicitOnly = 'explicitOnly'
    fallbackPrimTypes = 'fallbackPrimTypes'
    pass
class Typed(SchemaBase, Boost.Python.instance):
    @staticmethod
    def Get(*args, **kwargs) -> None: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> None: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> None: ...
    __instance_size__ = 48
    pass
class UsdCollectionMembershipQuery(Boost.Python.instance):
    @staticmethod
    def GetAsPathExpansionRuleMap(*args, **kwargs) -> None: ...
    @staticmethod
    def GetIncludedCollections(*args, **kwargs) -> None: ...
    @staticmethod
    def HasExcludes(*args, **kwargs) -> None: ...
    @staticmethod
    def IsPathIncluded(*args, **kwargs) -> None: ...
    @staticmethod
    def UsesPathExpansionRuleMap(*args, **kwargs) -> None: ...
    __instance_size__ = 184
    pass
class UsdFileFormat(pxr.Sdf.FileFormat, Boost.Python.instance):
    class Tokens(Boost.Python.instance):
        FormatArg = 'format'
        Id = 'usd'
        Target = 'usd'
        Version = '1.0'
        pass
    @staticmethod
    def GetUnderlyingFormatForLayer(*args, **kwargs) -> None: ...
    pass
class VariantSet(Boost.Python.instance):
    @staticmethod
    def AddVariant(*args, **kwargs) -> None: ...
    @staticmethod
    def BlockVariantSelection(*args, **kwargs) -> None: ...
    @staticmethod
    def ClearVariantSelection(*args, **kwargs) -> None: ...
    @staticmethod
    def GetName(*args, **kwargs) -> None: ...
    @staticmethod
    def GetPrim(*args, **kwargs) -> None: ...
    @staticmethod
    def GetVariantEditContext(*args, **kwargs) -> None: ...
    @staticmethod
    def GetVariantEditTarget(*args, **kwargs) -> None: ...
    @staticmethod
    def GetVariantNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetVariantSelection(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredVariant(*args, **kwargs) -> None: ...
    @staticmethod
    def HasAuthoredVariantSelection(*args, **kwargs) -> None: ...
    @staticmethod
    def IsValid(*args, **kwargs) -> None: ...
    @staticmethod
    def SetVariantSelection(*args, **kwargs) -> None: ...
    pass
class VariantSets(Boost.Python.instance):
    @staticmethod
    def AddVariantSet(*args, **kwargs) -> None: ...
    @staticmethod
    def GetAllVariantSelections(*args, **kwargs) -> None: ...
    @staticmethod
    def GetNames(*args, **kwargs) -> None: ...
    @staticmethod
    def GetVariantSelection(*args, **kwargs) -> None: ...
    @staticmethod
    def GetVariantSet(*args, **kwargs) -> None: ...
    @staticmethod
    def HasVariantSet(*args, **kwargs) -> None: ...
    @staticmethod
    def SetSelection(*args, **kwargs) -> None: ...
    pass
class ZipFile(Boost.Python.instance):
    class FileInfo(Boost.Python.instance):
        @property
        def compressionMethod(self) -> None:
            """
            :type: None
            """
        @property
        def crc(self) -> None:
            """
            :type: None
            """
        @property
        def dataOffset(self) -> None:
            """
            :type: None
            """
        @property
        def encrypted(self) -> None:
            """
            :type: None
            """
        @property
        def size(self) -> None:
            """
            :type: None
            """
        @property
        def uncompressedSize(self) -> None:
            """
            :type: None
            """
        pass
    @staticmethod
    def DumpContents(*args, **kwargs) -> None: ...
    @staticmethod
    def GetFile(*args, **kwargs) -> None: ...
    @staticmethod
    def GetFileInfo(*args, **kwargs) -> None: ...
    @staticmethod
    def GetFileNames(*args, **kwargs) -> None: ...
    @staticmethod
    def Open(*args, **kwargs) -> None: ...
    pass
class ZipFileWriter(Boost.Python.instance):
    @staticmethod
    def AddFile(*args, **kwargs) -> None: ...
    @staticmethod
    def CreateNew(*args, **kwargs) -> None: ...
    @staticmethod
    def Discard(*args, **kwargs) -> None: ...
    @staticmethod
    def Save(*args, **kwargs) -> None: ...
    pass
class _CanApplyAPIResult(Boost.Python.instance):
    @property
    def whyNot(self) -> None:
        """
        :type: None
        """
    __instance_size__ = 64
    pass
class _CanApplyResult(Boost.Python.instance):
    @property
    def whyNot(self) -> None:
        """
        :type: None
        """
    __instance_size__ = 64
    pass
class _NonPopulatingStageCacheWrapper(Boost.Python.instance):
    pass
class _PrimFlagsConjunction(_PrimFlagsPredicate, Boost.Python.instance):
    pass
class _PrimFlagsDisjunction(_PrimFlagsPredicate, Boost.Python.instance):
    pass
class _PrimFlagsPredicate(Boost.Python.instance):
    @staticmethod
    def Contradiction(*args, **kwargs) -> None: ...
    @staticmethod
    def Tautology(*args, **kwargs) -> None: ...
    pass
class _Term(Boost.Python.instance):
    pass
class _UsdNamespaceEditorCanEditResult(Boost.Python.instance):
    @property
    def whyNot(self) -> None:
        """
        :type: None
        """
    __instance_size__ = 64
    pass
def ComputeIncludedObjectsFromCollection(*args, **kwargs) -> None:
    pass
def ComputeIncludedPathsFromCollection(*args, **kwargs) -> None:
    pass
def ComputePathExpressionFromCollectionMembershipQueryRuleMap(*args, **kwargs) -> None:
    pass
def Describe(*args, **kwargs) -> None:
    pass
def FlattenLayerStack(*args, **kwargs) -> None:
    pass
def FlattenLayerStackAdvanced(*args, **kwargs) -> None:
    pass
def FlattenLayerStackResolveAssetPath(*args, **kwargs) -> None:
    pass
def FlattenLayerStackResolveAssetPathAdvanced(*args, **kwargs) -> None:
    pass
def GetMajorVersion(*args, **kwargs) -> None:
    """
    Get the major version number for this build of USD.
    Returns a value of type int.
    USD versions are described as (major,minor,patch)
    """
def GetMinorVersion(*args, **kwargs) -> None:
    """
    Get the minor version number for this build of USD.
    Returns a value of type int.
    USD versions are described as (major,minor,patch)
    """
def GetPatchVersion(*args, **kwargs) -> None:
    """
    Get the patch version number for this build of USD.
    Returns a value of type int.
    USD versions are described as (major,minor,patch)
    """
def GetVersion(*args, **kwargs) -> None:
    """
    Get the complete version number for this build of USD.
    Returns a value of type tuple(int,int,int).
    USD versions are described as (major,minor,patch)
    """
def TraverseInstanceProxies(*args, **kwargs) -> None:
    pass
def UseButDoNotPopulateCache(*args, **kwargs) -> None:
    pass
def _TestPrimRangeRoundTrip(*args, **kwargs) -> None:
    pass
def _UnsafeGetStageForTesting(*args, **kwargs) -> None:
    pass
BlockStageCachePopulation: pxr.Usd.StageCacheContextBlockType # value = Usd.BlockStageCachePopulation
BlockStageCaches: pxr.Usd.StageCacheContextBlockType # value = Usd.BlockStageCaches
InterpolationTypeHeld: pxr.Usd.InterpolationType # value = Usd.InterpolationTypeHeld
InterpolationTypeLinear: pxr.Usd.InterpolationType # value = Usd.InterpolationTypeLinear
ListPositionBackOfAppendList: pxr.Usd.ListPosition # value = Usd.ListPositionBackOfAppendList
ListPositionBackOfPrependList: pxr.Usd.ListPosition # value = Usd.ListPositionBackOfPrependList
ListPositionFrontOfAppendList: pxr.Usd.ListPosition # value = Usd.ListPositionFrontOfAppendList
ListPositionFrontOfPrependList: pxr.Usd.ListPosition # value = Usd.ListPositionFrontOfPrependList
LoadWithDescendants: pxr.Usd.LoadPolicy # value = Usd.LoadWithDescendants
LoadWithoutDescendants: pxr.Usd.LoadPolicy # value = Usd.LoadWithoutDescendants
PrimAllPrimsPredicate: pxr.Usd._PrimFlagsPredicate
PrimDefaultPredicate: pxr.Usd._PrimFlagsConjunction
PrimHasDefiningSpecifier: pxr.Usd._Term
PrimIsAbstract: pxr.Usd._Term
PrimIsActive: pxr.Usd._Term
PrimIsDefined: pxr.Usd._Term
PrimIsGroup: pxr.Usd._Term
PrimIsInstance: pxr.Usd._Term
PrimIsLoaded: pxr.Usd._Term
PrimIsModel: pxr.Usd._Term
ResolveInfoSourceDefault: pxr.Usd.ResolveInfoSource # value = Usd.ResolveInfoSourceDefault
ResolveInfoSourceFallback: pxr.Usd.ResolveInfoSource # value = Usd.ResolveInfoSourceFallback
ResolveInfoSourceNone: pxr.Usd.ResolveInfoSource # value = Usd.ResolveInfoSourceNone
ResolveInfoSourceSpline: pxr.Usd.ResolveInfoSource # value = Usd.ResolveInfoSourceSpline
ResolveInfoSourceTimeSamples: pxr.Usd.ResolveInfoSource # value = Usd.ResolveInfoSourceTimeSamples
ResolveInfoSourceValueClips: pxr.Usd.ResolveInfoSource # value = Usd.ResolveInfoSourceValueClips
_NoBlock: pxr.Usd.StageCacheContextBlockType # value = Usd._NoBlock
__MFB_FULL_PACKAGE_NAME = 'usd'
