ATTRIBUTES = {
    "amethyst boiler": {"open", "machine"},
    "burner drill": {"open", "machine", "drill"},
    "caelium sieve": {"open", "machine"},
    "campfire": {"open", "craft"},
    "composter": {"open", "machine"},
    "copper anvil": {"open", "craft"},
    "copper boiler": {"open", "machine"},
    "copper constructor": {"open", "craft"},
    "copper press": {"open", "machine"},
    "destroyed void crate": {"open", "store"},
    "dye bench": {"open", "craft"},
    "furless rabbit": {"animal", "creature"},
    "furnace": {"open", "machine"},
    "judge": {"enemy", "creature"},
    "left": {"point"},
    "mana converter": {"open", "machine"},
    "manual press": {"open", "craft"},
    "masonry bench": {"open", "craft"},
    "mushroom shaper": {"open", "craft"},
    "mushroom table": {"store", "table"},
    "obelisk piece": {"open", "machine"},
    "packager bench": {"open", "craft"},
    "player": {"open", "craft"},
    "quartz adult": {"enemy", "creature"},
    "quartz altar": {"open", "craft"},
    "quartz child": {"enemy", "creature"},
    "rabbit adult": {"animal", "creature"},
    "rabbit child": {"animal", "creature"},
    "sawbench": {"open", "craft"},
    "sewbench": {"open", "craft"},
    "skeleton": {"enemy", "creature"},
    "slime": {"enemy", "creature"},
    "slime prince": {"enemy", "creature"},
    "slime shaper": {"open", "craft"},
    "slime table": {"store", "table"},
    "small barrel": {"open", "store"},
    "small crate": {"open", "store"},
    "tree constructor": {"open", "craft"},
    "up": {"point"},
    "void converter": {"open", "craft"},
    "void crate": {"open", "store"},
    "wood crucible": {"open", "machine"},
    "wooden bed": {"sleep"},
    "wooden sieve": {"open", "machine"},
    "wooden table": {"store", "table"},
    "workbench": {"open", "craft"},
}
