HEALTH = {
    "acorn": 8,
    "amethyst": 16,
    "amethyst axe": 12,
    "amethyst brick": 12,
    "amethyst brick floor": 8,
    "amethyst block": 32,
    "amethyst boiler": 40,
    "amethyst dirt": 12,
    "amethyst hammer": 12,
    "amethyst pickaxe": 12,
    "amethyst pipe 0": 12,
    "amethyst pipe 1": 12,
    "amethyst pump 0": 20,
    "amethyst pump 1": 20,
    "amethyst rune": 16,
    "amethyst shovel": 12,
    "amethyst sword": 12,
    "amethyst wrench": 12,
    "anklet of the tree": 12,
    "bluebell jar": 24,
    "blue dye": 6,
    "bluebell": 10,
    "bluebell grown": 14,
    "bookshelf": 8,
    "boots": 12,
    "bowl": 6,
    "brick": 12,
    "brick floor": 8,
    "brown dye": 6,
    "burner drill": 20,
    "caelium acorn": 24,
    "caelium ingot": 24,
    "caelium leaf": 30,
    "caelium sapling": 12,
    "caelium sieve": 24,
    "caelium treeling": 18,
    "caelium tree": 24,
    "campfire": 8,
    "carrot grown": 8,
    "carrot": 4,
    "citrine": 20,
    "citrine block": 40,
    "citrine rune": 20,
    "clay": 12,
    "coal": 8,
    "coal acorn": 12,
    "coal block": 32,
    "coal leaf": 15,
    "coal ore": 20,
    "coal sapling": 6,
    "coal treeling": 9,
    "coal tree": 12,
    "composter": 8,
    "copper acorn": 16,
    "copper anvil": 16,
    "copper axe": 12,
    "copper block": 24,
    "copper boiler": 40,
    "copper brick": 12,
    "copper brick floor": 8,
    "copper constructor": 32,
    "copper door": 8,
    "copper door open": 8,
    "copper gear": 10,
    "copper hammer": 12,
    "copper ingot": 16,
    "copper leaf": 20,
    "copper needle": 12,
    "copper ore": 30,
    "copper pickaxe": 12,
    "copper pipe 0": 12,
    "copper pipe 1": 12,
    "copper pit grown": 20,
    "copper press": 24,
    "copper pump 0": 20,
    "copper pump 1": 20,
    "copper sapling": 8,
    "copper shaft": 12,
    "copper sheet": 12,
    "copper shovel": 12,
    "copper sword": 12,
    "copper tank": 20,
    "copper tree": 16,
    "copper treeling": 12,
    "copper wrench": 12,
    "corpse": 1,
    "dirt": 5,
    "dye bench": 12,
    "fertilizer": 5,
    "flint axe": 8,
    "flint hammer": 8,
    "flint pickaxe": 8,
    "flint shovel": 8,
    "flint sword": 8,
    "flint": 16,
    "furless rabbit": 10,
    "furnace": 32,
    "gift": 4,
    "glass": 8,
    "glass key": 1,
    "ice": 12,
    "judge": 12,
    "junk": 1,
    "lava": 12,
    "lava rune": 24,
    "lavastone brick": 16,
    "lavastone brick floor": 12,
    "lavastone": 16,
    "lavastone floor": 12,
    "leaf": 10,
    "life crystal": 16,
    "log floor": 12,
    "log": 8,
    "mana": 1,
    "mana converter": 10,
    "manual press": 12,
    "masonry bench": 12,
    "moist dirt": 8,
    "mushroom block": 5,
    "mushroom door": 10,
    "mushroom door open": 10,
    "mushroom floor": 8,
    "mushroom shaper": 13,
    "mushroom stew": 6,
    "mushroom table": 10,
    "mushroom": 10,
    "obelisk piece": 10,
    "package": 4,
    "packager bench": 12,
    "paper": 8,
    "pebble": 8,
    "plant bouquet": 6,
    "potato": 6,
    "potato grown": 10,
    "pure crystal": 16,
    "purple dye": 6,
    "purple mana": 1,
    "quartz": 12,
    "quartz adult": 14,
    "quartz altar": 6,
    "quartz block": 24,
    "quartz child": 10,
    "rabbit adult": 10,
    "rabbit child": 6,
    "rabbit fur": 8,
    "rabbit meat": 6,
    "rail 0": 8,
    "rail 1": 8,
    "rail 2": 8,
    "rail 3": 8,
    "rail 4": 8,
    "rail 5": 8,
    "raw caelium": 20,
    "raw copper": 12,
    "raw tin": 16,
    "roasted mushroom": 8,
    "roasted rabbit meat": 10,
    "rock": 20,
    "rock axe": 10,
    "rock hammer": 10,
    "rock pickaxe": 10,
    "rock shovel": 10,
    "rock sword": 10,
    "sand": 6,
    "sapling": 4,
    "sawbench": 12,
    "sewbench": 12,
    "skeleton": 16,
    "slife crystal": 20,
    "slime": 20,
    "slime ball": 6,
    "slime block": 5,
    "slime crystal": 8,
    "slime door": 10,
    "slime door open": 10,
    "slime floor": 8,
    "slime prince": 100,
    "slime shaper": 20,
    "slime table": 10,
    "small backpack": 16,
    "small barrel": 10,
    "small crate": 10,
    "snow": 8,
    "snowball": 4,
    "spore": 4,
    "stick": 4,
    "stone brick": 16,
    "stone brick floor": 12,
    "stone": 16,
    "stone floor": 12,
    "thread": 12,
    "tin acorn": 20,
    "tin ingot": 20,
    "tin leaf": 25,
    "tin ore": 40,
    "tin sapling": 10,
    "tin treeling": 15,
    "tin tree": 20,
    "torch": 12,
    "tree": 8,
    "treeling": 6,
    "tree constructor": 16,
    "water": 8,
    "water axe": 10,
    "water hammer": 10,
    "water pickaxe": 10,
    "water shovel": 10,
    "water sword": 10,
    "white dye": 6,
    "wood crucible": 10,
    "wood door": 8,
    "wood door open": 8,
    "wood fence 0": 8,
    "wood fence 1": 8,
    "wood fence 2": 8,
    "wood floor": 6,
    "wood": 4,
    "wooden bed": 12,
    "wooden sieve": 12,
    "wooden table": 8,
    "workbench": 5,
}
