# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.plan_change_response_data import PlanChangeResponseData
from .list_plan_changes_params import ListPlanChangesParams


class ListPlanChangesResponse(UniversalBaseModel):
    data: typing.List[PlanChangeResponseData]
    params: ListPlanChangesParams = pydantic.Field()
    """
    Input parameters
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
