from google.protobuf import struct_pb2 as _struct_pb2
from zepben.protobuf.cim.iec61970.base.wires import RegulatingCondEq_pb2 as _RegulatingCondEq_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Iterable as _Iterable, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class PowerElectronicsConnection(_message.Message):
    __slots__ = ("rce", "maxIFaultNull", "maxIFaultSet", "maxQNull", "maxQSet", "minQNull", "minQSet", "pNull", "pSet", "qNull", "qSet", "ratedSNull", "ratedSSet", "ratedUNull", "ratedUSet", "powerElectronicsUnitMRIDs", "powerElectronicsConnectionPhaseMRIDs", "inverterStandardNull", "inverterStandardSet", "sustainOpOvervoltLimitNull", "sustainOpOvervoltLimitSet", "stopAtOverFreqNull", "stopAtOverFreqSet", "stopAtUnderFreqNull", "stopAtUnderFreqSet", "invVoltWattRespModeNull", "invVoltWattRespModeSet", "invWattRespV1Null", "invWattRespV1Set", "invWattRespV2Null", "invWattRespV2Set", "invWattRespV3Null", "invWattRespV3Set", "invWattRespV4Null", "invWattRespV4Set", "invWattRespPAtV1Null", "invWattRespPAtV1Set", "invWattRespPAtV2Null", "invWattRespPAtV2Set", "invWattRespPAtV3Null", "invWattRespPAtV3Set", "invWattRespPAtV4Null", "invWattRespPAtV4Set", "invVoltVarRespModeNull", "invVoltVarRespModeSet", "invVarRespV1Null", "invVarRespV1Set", "invVarRespV2Null", "invVarRespV2Set", "invVarRespV3Null", "invVarRespV3Set", "invVarRespV4Null", "invVarRespV4Set", "invVarRespQAtV1Null", "invVarRespQAtV1Set", "invVarRespQAtV2Null", "invVarRespQAtV2Set", "invVarRespQAtV3Null", "invVarRespQAtV3Set", "invVarRespQAtV4Null", "invVarRespQAtV4Set", "invReactivePowerModeNull", "invReactivePowerModeSet", "invFixReactivePowerNull", "invFixReactivePowerSet")
    RCE_FIELD_NUMBER: _ClassVar[int]
    MAXIFAULTNULL_FIELD_NUMBER: _ClassVar[int]
    MAXIFAULTSET_FIELD_NUMBER: _ClassVar[int]
    MAXQNULL_FIELD_NUMBER: _ClassVar[int]
    MAXQSET_FIELD_NUMBER: _ClassVar[int]
    MINQNULL_FIELD_NUMBER: _ClassVar[int]
    MINQSET_FIELD_NUMBER: _ClassVar[int]
    PNULL_FIELD_NUMBER: _ClassVar[int]
    PSET_FIELD_NUMBER: _ClassVar[int]
    QNULL_FIELD_NUMBER: _ClassVar[int]
    QSET_FIELD_NUMBER: _ClassVar[int]
    RATEDSNULL_FIELD_NUMBER: _ClassVar[int]
    RATEDSSET_FIELD_NUMBER: _ClassVar[int]
    RATEDUNULL_FIELD_NUMBER: _ClassVar[int]
    RATEDUSET_FIELD_NUMBER: _ClassVar[int]
    POWERELECTRONICSUNITMRIDS_FIELD_NUMBER: _ClassVar[int]
    POWERELECTRONICSCONNECTIONPHASEMRIDS_FIELD_NUMBER: _ClassVar[int]
    INVERTERSTANDARDNULL_FIELD_NUMBER: _ClassVar[int]
    INVERTERSTANDARDSET_FIELD_NUMBER: _ClassVar[int]
    SUSTAINOPOVERVOLTLIMITNULL_FIELD_NUMBER: _ClassVar[int]
    SUSTAINOPOVERVOLTLIMITSET_FIELD_NUMBER: _ClassVar[int]
    STOPATOVERFREQNULL_FIELD_NUMBER: _ClassVar[int]
    STOPATOVERFREQSET_FIELD_NUMBER: _ClassVar[int]
    STOPATUNDERFREQNULL_FIELD_NUMBER: _ClassVar[int]
    STOPATUNDERFREQSET_FIELD_NUMBER: _ClassVar[int]
    INVVOLTWATTRESPMODENULL_FIELD_NUMBER: _ClassVar[int]
    INVVOLTWATTRESPMODESET_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPV1NULL_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPV1SET_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPV2NULL_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPV2SET_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPV3NULL_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPV3SET_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPV4NULL_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPV4SET_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPPATV1NULL_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPPATV1SET_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPPATV2NULL_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPPATV2SET_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPPATV3NULL_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPPATV3SET_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPPATV4NULL_FIELD_NUMBER: _ClassVar[int]
    INVWATTRESPPATV4SET_FIELD_NUMBER: _ClassVar[int]
    INVVOLTVARRESPMODENULL_FIELD_NUMBER: _ClassVar[int]
    INVVOLTVARRESPMODESET_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPV1NULL_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPV1SET_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPV2NULL_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPV2SET_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPV3NULL_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPV3SET_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPV4NULL_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPV4SET_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPQATV1NULL_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPQATV1SET_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPQATV2NULL_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPQATV2SET_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPQATV3NULL_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPQATV3SET_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPQATV4NULL_FIELD_NUMBER: _ClassVar[int]
    INVVARRESPQATV4SET_FIELD_NUMBER: _ClassVar[int]
    INVREACTIVEPOWERMODENULL_FIELD_NUMBER: _ClassVar[int]
    INVREACTIVEPOWERMODESET_FIELD_NUMBER: _ClassVar[int]
    INVFIXREACTIVEPOWERNULL_FIELD_NUMBER: _ClassVar[int]
    INVFIXREACTIVEPOWERSET_FIELD_NUMBER: _ClassVar[int]
    rce: _RegulatingCondEq_pb2.RegulatingCondEq
    maxIFaultNull: _struct_pb2.NullValue
    maxIFaultSet: int
    maxQNull: _struct_pb2.NullValue
    maxQSet: float
    minQNull: _struct_pb2.NullValue
    minQSet: float
    pNull: _struct_pb2.NullValue
    pSet: float
    qNull: _struct_pb2.NullValue
    qSet: float
    ratedSNull: _struct_pb2.NullValue
    ratedSSet: int
    ratedUNull: _struct_pb2.NullValue
    ratedUSet: int
    powerElectronicsUnitMRIDs: _containers.RepeatedScalarFieldContainer[str]
    powerElectronicsConnectionPhaseMRIDs: _containers.RepeatedScalarFieldContainer[str]
    inverterStandardNull: _struct_pb2.NullValue
    inverterStandardSet: str
    sustainOpOvervoltLimitNull: _struct_pb2.NullValue
    sustainOpOvervoltLimitSet: int
    stopAtOverFreqNull: _struct_pb2.NullValue
    stopAtOverFreqSet: float
    stopAtUnderFreqNull: _struct_pb2.NullValue
    stopAtUnderFreqSet: float
    invVoltWattRespModeNull: _struct_pb2.NullValue
    invVoltWattRespModeSet: bool
    invWattRespV1Null: _struct_pb2.NullValue
    invWattRespV1Set: int
    invWattRespV2Null: _struct_pb2.NullValue
    invWattRespV2Set: int
    invWattRespV3Null: _struct_pb2.NullValue
    invWattRespV3Set: int
    invWattRespV4Null: _struct_pb2.NullValue
    invWattRespV4Set: int
    invWattRespPAtV1Null: _struct_pb2.NullValue
    invWattRespPAtV1Set: float
    invWattRespPAtV2Null: _struct_pb2.NullValue
    invWattRespPAtV2Set: float
    invWattRespPAtV3Null: _struct_pb2.NullValue
    invWattRespPAtV3Set: float
    invWattRespPAtV4Null: _struct_pb2.NullValue
    invWattRespPAtV4Set: float
    invVoltVarRespModeNull: _struct_pb2.NullValue
    invVoltVarRespModeSet: bool
    invVarRespV1Null: _struct_pb2.NullValue
    invVarRespV1Set: int
    invVarRespV2Null: _struct_pb2.NullValue
    invVarRespV2Set: int
    invVarRespV3Null: _struct_pb2.NullValue
    invVarRespV3Set: int
    invVarRespV4Null: _struct_pb2.NullValue
    invVarRespV4Set: int
    invVarRespQAtV1Null: _struct_pb2.NullValue
    invVarRespQAtV1Set: float
    invVarRespQAtV2Null: _struct_pb2.NullValue
    invVarRespQAtV2Set: float
    invVarRespQAtV3Null: _struct_pb2.NullValue
    invVarRespQAtV3Set: float
    invVarRespQAtV4Null: _struct_pb2.NullValue
    invVarRespQAtV4Set: float
    invReactivePowerModeNull: _struct_pb2.NullValue
    invReactivePowerModeSet: bool
    invFixReactivePowerNull: _struct_pb2.NullValue
    invFixReactivePowerSet: float
    def __init__(self, rce: _Optional[_Union[_RegulatingCondEq_pb2.RegulatingCondEq, _Mapping]] = ..., maxIFaultNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., maxIFaultSet: _Optional[int] = ..., maxQNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., maxQSet: _Optional[float] = ..., minQNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., minQSet: _Optional[float] = ..., pNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., pSet: _Optional[float] = ..., qNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., qSet: _Optional[float] = ..., ratedSNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., ratedSSet: _Optional[int] = ..., ratedUNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., ratedUSet: _Optional[int] = ..., powerElectronicsUnitMRIDs: _Optional[_Iterable[str]] = ..., powerElectronicsConnectionPhaseMRIDs: _Optional[_Iterable[str]] = ..., inverterStandardNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., inverterStandardSet: _Optional[str] = ..., sustainOpOvervoltLimitNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., sustainOpOvervoltLimitSet: _Optional[int] = ..., stopAtOverFreqNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., stopAtOverFreqSet: _Optional[float] = ..., stopAtUnderFreqNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., stopAtUnderFreqSet: _Optional[float] = ..., invVoltWattRespModeNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invVoltWattRespModeSet: bool = ..., invWattRespV1Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invWattRespV1Set: _Optional[int] = ..., invWattRespV2Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invWattRespV2Set: _Optional[int] = ..., invWattRespV3Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invWattRespV3Set: _Optional[int] = ..., invWattRespV4Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invWattRespV4Set: _Optional[int] = ..., invWattRespPAtV1Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invWattRespPAtV1Set: _Optional[float] = ..., invWattRespPAtV2Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invWattRespPAtV2Set: _Optional[float] = ..., invWattRespPAtV3Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invWattRespPAtV3Set: _Optional[float] = ..., invWattRespPAtV4Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invWattRespPAtV4Set: _Optional[float] = ..., invVoltVarRespModeNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invVoltVarRespModeSet: bool = ..., invVarRespV1Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invVarRespV1Set: _Optional[int] = ..., invVarRespV2Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invVarRespV2Set: _Optional[int] = ..., invVarRespV3Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invVarRespV3Set: _Optional[int] = ..., invVarRespV4Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invVarRespV4Set: _Optional[int] = ..., invVarRespQAtV1Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invVarRespQAtV1Set: _Optional[float] = ..., invVarRespQAtV2Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invVarRespQAtV2Set: _Optional[float] = ..., invVarRespQAtV3Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invVarRespQAtV3Set: _Optional[float] = ..., invVarRespQAtV4Null: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invVarRespQAtV4Set: _Optional[float] = ..., invReactivePowerModeNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invReactivePowerModeSet: bool = ..., invFixReactivePowerNull: _Optional[_Union[_struct_pb2.NullValue, str]] = ..., invFixReactivePowerSet: _Optional[float] = ...) -> None: ...
