# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/iec61970/base/wires/SVCControlMode.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<zepben/protobuf/cim/iec61970/base/wires/SVCControlMode.proto\x12\'zepben.protobuf.cim.iec61970.base.wires*q\n\x0eSVCControlMode\x12\x1c\n\x18SVC_CONTROL_MODE_UNKNOWN\x10\x00\x12#\n\x1fSVC_CONTROL_MODE_REACTIVE_POWER\x10\x01\x12\x1c\n\x18SVC_CONTROL_MODE_VOLTAGE\x10\x02\x42/\n+com.zepben.protobuf.cim.iec61970.base.wiresP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zepben.protobuf.cim.iec61970.base.wires.SVCControlMode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.zepben.protobuf.cim.iec61970.base.wiresP\001'
  _globals['_SVCCONTROLMODE']._serialized_start=105
  _globals['_SVCCONTROLMODE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
