from minjiang_client.languages import lang as lang

class ConfigManager:
    def __init__(self) -> None: ...
    def __getitem__(self, item): ...
    def keys(self): ...
    def items(self): ...
    def values(self): ...
    def len(self): ...
    @property
    def config_items(self) -> dict: ...
    @property
    def user_input(self) -> dict: ...
    def clear_configs(self) -> None: ...
    def input(self, field, value) -> None: ...
    def validate(self) -> None: ...
    def add_enum(self, field, title, options, multi_choose: bool = False, necessary: bool = True, default=None): ...
    def add_integer(self, field, title, min_val=None, max_val=None, necessary: bool = True, default=None): ...
    def add_float(self, field, title, min_val=None, max_val=None, necessary: bool = True, default=None): ...
    def add_dict(self, field, title, max_length=None, necessary: bool = True, default=None): ...
    def add_list(self, field, title, max_length=None, necessary: bool = True, default=None): ...
    def add_string(self, field, title, max_length=None, necessary: bool = True, multi_line: bool = False, default: str = ''): ...
    def add_boolean(self, field, title, necessary: bool = True, default: bool = False): ...
    def add_text(self, field, title): ...
