from ..Base import *
from ..Proxy import *
from ..AcadObject import *
from .AcadMaterial import AcadMaterial as AcadMaterial

class AcadMaterials(IAcadObjectCollection):
    def __init__(self, obj) -> None: ...
    def Add(self, Name: str) -> AcadMaterial: ...
    def Item(self, Index: int) -> AcadMaterial: ...
    def __iter__(self): ...
