# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.feature_usage_response_data import FeatureUsageResponseData
from .list_feature_usage_params import ListFeatureUsageParams


class ListFeatureUsageResponse(UniversalBaseModel):
    data: typing.List[FeatureUsageResponseData]
    params: ListFeatureUsageParams = pydantic.Field()
    """
    Input parameters
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
