from collections.abc import Sequence


class Graph:
    def __init__(self) -> None: ...

    def print(self) -> None: ...

    def create_node(self, op_type: str, name: str = '') -> OpNode: ...

    def add_input(self) -> ValueNode: ...

    def register_output(self, arg: ValueNode, /) -> None: ...

    def fuse(self) -> None: ...

    @property
    def nodes(self) -> list[OpNode]: ...

    @property
    def inputs(self) -> list[ValueNode]: ...

    @property
    def outputs(self) -> list[ValueNode]: ...

class OpNode:
    @property
    def op_type(self) -> str: ...

    @op_type.setter
    def op_type(self, arg: str, /) -> None: ...

    @property
    def name(self) -> str: ...

    @property
    def input_count(self) -> int: ...

    def add_input(self, arg: ValueNode, /) -> None: ...

    def add_output(self) -> ValueNode: ...

    @property
    def inputs(self) -> list[ValueNode]: ...

    @property
    def outputs(self) -> list[ValueNode]: ...

    def set_int_attr(self, arg0: str, arg1: int, /) -> None: ...

    def set_float_attr(self, arg0: str, arg1: float, /) -> None: ...

    def get_int_attr(self, arg: str, /) -> int: ...

    def get_float_attr(self, arg: str, /) -> float: ...

    def has_attr(self, arg: str, /) -> bool: ...

class ValueNode:
    @property
    def id(self) -> int: ...

    @property
    def shape(self) -> list[int]: ...

    @shape.setter
    def shape(self, arg: Sequence[int], /) -> None: ...

    @property
    def dtype(self) -> str: ...

    @dtype.setter
    def dtype(self, arg: str, /) -> None: ...

class IRBuilder:
    def __init__(self, arg: Graph, /) -> None: ...

    def create_input(self, shape: Sequence[int], dtype: str = 'float32') -> ValueNode: ...

    def create_op(self, op_type: str, inputs: Sequence[ValueNode], out_shape: Sequence[int] = [], name: str = '') -> ValueNode: ...

    def mark_output(self, arg: ValueNode, /) -> None: ...
