"""
Creates a test case class for use with the unittest library that is built into Python.
"""

from heaserver.service.testcase.microservicetestcase import get_test_case_cls_default
from heaserver.service.testcase.dockermongo import MockDockerMongoManager
from heaserver.activity import service
from heaobject.user import NONE_USER
from heaobject.activity import Status
from heaobject.project import AWSS3Project
from heaobject.root import Permission
from heaserver.service.testcase.expectedvalues import Action


db_store = {
    service.MONGODB_DESKTOP_OBJECT_ACTION_COLLECTION: [{
        'id': '666f6f2d6261722d71757578',
        'instance_id': 'heaobject.activity.DesktopObjectAction^666f6f2d6261722d71757578',
        'created': None,
        'derived_by': None,
        'derived_from': [],
        'description': None,
        'display_name': 'Reximus',
        'invites': [],
        'modified': None,
        'name': 'reximus',
        'owner': NONE_USER,
        'shares': [],
        'user_shares': [],
        'group_shares': [],
        'status': Status.SUCCEEDED.name,
        'user_id': NONE_USER,
        'source': None,
        'source_detail': None,
        'type': 'heaobject.activity.DesktopObjectAction',
        'old_object_uri': None,
        'new_object_uri': 'awss3projects/666f6f2d6261722d71757578',
        'old_object_type_name': None,
        'new_object_type_name': AWSS3Project.get_type_name(),
        'old_object_id': None,
        'new_object_id': '666f6f2d6261722d71757578',
        'new_object_display_name': 'Reximus',
        'application_id': None,
        'code': None,
        'duration': None,
        'ended': None,
        'human_readable_duration': None,
        'mime_type': 'application/x.desktopobjectaction',
        'new_volume_id': None,
        'old_volume_id': None,
        'requested': '2022-05-17T00:00:00-06:00',
        'status_updated': '2022-05-17T00:00:00-06:00',
        'began': '2022-05-17T00:00:00-06:00',
        'type_display_name': 'Desktop Object Action',
        'request_url': None,
        'context': None,
        'old_context_dependent_object_path': None,
        'new_context_dependent_object_path': None,
        'dynamic_permission_supported': False,
        'super_admin_default_permissions': [p.name for p in Permission.non_creator_permissions()]
    },
    {
        'id': '0123456789ab0123456789ab',
        'instance_id': 'heaobject.activity.DesktopObjectAction^0123456789ab0123456789ab',
        'created': None,
        'derived_by': None,
        'derived_from': [],
        'description': None,
        'display_name': 'Luximus',
        'invites': [],
        'modified': None,
        'name': 'luximus',
        'owner': NONE_USER,
        'shares': [],
        'user_shares': [],
        'group_shares': [],
        'status': Status.SUCCEEDED.name,
        'user_id': NONE_USER,
        'source': None,
        'source_detail': None,
        'type': 'heaobject.activity.DesktopObjectAction',
        'old_object_uri': 'awss3projects/0123456789ab0123456789ab',
        'new_object_uri': 'awss3projects/0123456789ab0123456789ab',
        'old_object_type_name': AWSS3Project.get_type_name(),
        'new_object_type_name': AWSS3Project.get_type_name(),
        'old_object_id': '0123456789ab0123456789ab',
        'new_object_id': '0123456789ab0123456789ab',
        'new_object_display_name': 'Luximus',
        'application_id': None,
        'code': None,
        'duration': None,
        'ended': None,
        'human_readable_duration': None,
        'mime_type': 'application/x.desktopobjectaction',
        'new_volume_id': None,
        'old_volume_id': None,
        'requested': '2022-05-17T00:00:00-06:00',
        'status_updated': '2022-05-17T00:00:00-06:00',
        'began': '2022-05-17T00:00:00-06:00',
        'type_display_name': 'Desktop Object Action',
        'request_url': None,
        'context': None,
        'old_context_dependent_object_path': None,
        'new_context_dependent_object_path': None,
        'dynamic_permission_supported': False,
        'super_admin_default_permissions': [p.name for p in Permission.non_creator_permissions()]
    },
    {
        'id': '0123456789ab0123456789ac',
        'instance_id': 'heaobject.activity.DesktopObjectAction^0123456789ab0123456789ac',
        'created': None,
        'derived_by': None,
        'derived_from': [],
        'description': None,
        'display_name': 'Joe',
        'invites': [],
        'modified': None,
        'name': 'joe',
        'owner': NONE_USER,
        'shares': [],
        'user_shares': [],
        'group_shares': [],
        'status': Status.SUCCEEDED.name,
        'user_id': NONE_USER,
        'source': None,
        'source_detail': None,
        'type': 'heaobject.activity.DesktopObjectAction',
        'old_object_uri': 'awss3projects/0123456789ab0123456789ac',
        'new_object_uri': None,
        'old_object_type_name': AWSS3Project.get_type_name(),
        'new_object_type_name': None,
        'old_object_id': '0123456789ab0123456789ac',
        'new_object_id': None,
        'new_object_display_name': 'Joe',
        'application_id': None,
        'code': None,
        'duration': None,
        'ended': None,
        'human_readable_duration': None,
        'mime_type': 'application/x.desktopobjectaction',
        'new_volume_id': None,
        'old_volume_id': None,
        'requested': '2022-05-17T00:00:00-06:00',
        'status_updated': '2022-05-17T00:00:00-06:00',
        'began': '2022-05-17T00:00:00-06:00',
        'type_display_name': 'Desktop Object Action',
        'request_url': None,
        'context': None,
        'old_context_dependent_object_path': None,
        'new_context_dependent_object_path': None,
        'dynamic_permission_supported': False,
        'super_admin_default_permissions': [p.name for p in Permission.non_creator_permissions()]
    }],
    'recentlyaccessedviews': [{
        'id': '666f6f2d6261722d71757578',
        'instance_id': 'heaobject.activity.RecentlyAccessedView^666f6f2d6261722d71757578',
        'accessed': '2022-05-17T00:00:00-06:00',
        'actual_object_id': '666f6f2d6261722d71757578',
        'actual_object_type_name': 'heaobject.project.AWSS3Project',
        'actual_object_uri': 'awss3projects/666f6f2d6261722d71757578',
        'type': 'heaobject.activity.RecentlyAccessedView',
        'created': None,
        'modified': None,
        'derived_by': None,
        'derived_from': [],
        'description': None,
        'name': None,
        'display_name': 'Reximus',
        'invites': [],
        'owner': NONE_USER,
        'shares': [],
        'user_shares': [],
        'group_shares': [],
        'source': None,
        'source_detail': None,
        'type_display_name': 'Recently Accessed View',
        'context': None,
        'context_dependent_object_path': None,
        'dynamic_permission_supported': False,
        'super_admin_default_permissions': []

    },
    {
        'id': '0123456789ab0123456789ab',
        'instance_id': 'heaobject.activity.RecentlyAccessedView^0123456789ab0123456789ab',
        'accessed': '2022-05-17T00:00:00-06:00',
        'actual_object_id': '0123456789ab0123456789ab',
        'actual_object_type_name': 'heaobject.project.AWSS3Project',
        'actual_object_uri': 'awss3projects/0123456789ab0123456789ab',
        'type': 'heaobject.activity.RecentlyAccessedView',
        'created': None,
        'modified': None,
        'derived_by': None,
        'derived_from': [],
        'description': None,
        'name': None,
        'display_name': 'Luximus',
        'invites': [],
        'owner': NONE_USER,
        'shares': [],
        'user_shares': [],
        'group_shares': [],
        'source': None,
        'source_detail': None,
        'type_display_name': 'Recently Accessed View',
        'context': None,
        'context_dependent_object_path': None,
        'dynamic_permission_supported': False,
        'super_admin_default_permissions': []
    }
    ],
    'desktopobjectsummaryviews': [{
        'id': '666f6f2d6261722d71757578',
        'instance_id': 'heaobject.activity.DesktopObjectSummaryView^666f6f2d6261722d71757578',
        'accessed': '2022-05-17T00:00:00-06:00',
        'actual_object_id': '666f6f2d6261722d71757578',
        'actual_object_type_name': 'heaobject.project.AWSS3Project',
        'actual_object_uri': 'awss3projects/666f6f2d6261722d71757578',
        'type': 'heaobject.activity.DesktopObjectSummaryView',
        'created': None,
        'modified': None,
        'derived_by': None,
        'derived_from': [],
        'description': None,
        'name': None,
        'display_name': 'Reximus',
        'invites': [],
        'owner': NONE_USER,
        'shares': [],
        'user_shares': [],
        'group_shares': [],
        'source': None,
        'source_detail': None,
        'type_display_name': 'Desktop Object Summary View',
        'context': None,
        'context_dependent_object_path': None,
        'status': 'PRESENT',
        'dynamic_permission_supported': False,
        'super_admin_default_permissions': []
    },
    {
        'id': '0123456789ab0123456789ab',
        'instance_id': 'heaobject.activity.DesktopObjectSummaryView^0123456789ab0123456789ab',
        'accessed': '2022-05-17T00:00:00-06:00',
        'actual_object_id': '0123456789ab0123456789ab',
        'actual_object_type_name': 'heaobject.project.AWSS3Project',
        'actual_object_uri': 'awss3projects/0123456789ab0123456789ab',
        'type': 'heaobject.activity.DesktopObjectSummaryView',
        'created': None,
        'modified': None,
        'derived_by': None,
        'derived_from': [],
        'description': None,
        'name': None,
        'display_name': 'Luximus',
        'invites': [],
        'owner': NONE_USER,
        'shares': [],
        'user_shares': [],
        'group_shares': [],
        'source': None,
        'source_detail': None,
        'type_display_name': 'Desktop Object Summary View',
        'context': None,
        'context_dependent_object_path': None,
        'status': 'PRESENT',
        'dynamic_permission_supported': False,
        'super_admin_default_permissions': []
    },
    {
        'id': '0123456789ab0123456789ac',
        'instance_id': 'heaobject.activity.DesktopObjectSummaryView^0123456789ab0123456789ac',
        'accessed': '2022-05-17T00:00:00-06:00',
        'actual_object_id': '0123456789ab0123456789ac',
        'actual_object_type_name': 'heaobject.project.AWSS3Project',
        'actual_object_uri': 'awss3projects/0123456789ab0123456789ac',
        'type': 'heaobject.activity.DesktopObjectSummaryView',
        'created': None,
        'modified': None,
        'derived_by': None,
        'derived_from': [],
        'description': None,
        'name': None,
        'display_name': 'Untitled Desktop Object Summary View',
        'invites': [],
        'owner': NONE_USER,
        'shares': [],
        'user_shares': [],
        'group_shares': [],
        'source': None,
        'source_detail': None,
        'type_display_name': 'Desktop Object Summary View',
        'context': None,
        'context_dependent_object_path': None,
        'status': 'DELETED',
        'dynamic_permission_supported': False,
        'super_admin_default_permissions': []
    }]}

RecentlyAccessedViewsByTypeTestCase = get_test_case_cls_default(coll='recentlyaccessedviews',
                                                         wstl_package=service.__package__,
                                                         href='http://localhost:8080/recentlyaccessedviews/bytype/heaobject.project.AWSS3Project/',
                                                         fixtures=db_store,
                                                         db_manager_cls=MockDockerMongoManager,
                                                         get_all_actions=[Action(name='heaserver-activity-recentlyaccessed-get-actual',
                                                            url='http://localhost:8080/{+actual_object_uri}',
                                                            rel=['hea-actual'])])


DesktopObjectSummaryViewsByTypeTestCase = get_test_case_cls_default(coll='desktopobjectsummaryviews',
                                                         wstl_package=service.__package__,
                                                         href='http://localhost:8080/desktopobjectsummaryviews/bytype/heaobject.project.AWSS3Project/',
                                                         fixtures=db_store,
                                                         db_manager_cls=MockDockerMongoManager,
                                                         get_all_actions=[Action(name='heaserver-activity-desktopobjectsummaries-get-actual',
                                                            url='http://localhost:8080/{+actual_object_uri}',
                                                            rel=['hea-actual'])])


TestCase = get_test_case_cls_default(coll=service.MONGODB_DESKTOP_OBJECT_ACTION_COLLECTION,
                                     href='http://localhost:8080/desktopobjectactions/',
                                     wstl_package=service.__package__,
                                     fixtures=db_store,
                                     db_manager_cls=MockDockerMongoManager,
                                     get_actions=[Action(name='heaserver-activity-desktopobjectaction-get-properties',
                                                         rel=['hea-properties']),
                                                  Action(name='heaserver-activity-desktopobjectaction-get-self',
                                                         url='http://localhost:8080/desktopobjectactions/{id}',
                                                         rel=['self']),
                                                  Action(name='heaserver-activity-desktopobjectaction-get-old-object-uri',
                                                         url='http://localhost:8080/{+old_object_uri}',
                                                         rel=['hea-desktop-object'],
                                                         itemif='old_object_uri is not None and new_object_uri is None'),
                                                  Action(name='heaserver-activity-desktopobjectaction-get-new-object-uri',
                                                         url='http://localhost:8080/{+new_object_uri}',
                                                         rel=['hea-desktop-object'],
                                                         itemif='new_object_uri is not None')
                                                  ],
                                     get_all_actions=[Action(name='heaserver-activity-desktopobjectaction-get-properties',
                                                             rel=['hea-properties']),
                                                      Action(name='heaserver-activity-desktopobjectaction-get-self',
                                                             url='http://localhost:8080/desktopobjectactions/{id}',
                                                             rel=['self']),
                                                      Action(name='heaserver-activity-desktopobjectaction-get-old-object-uri',
                                                             url='http://localhost:8080/{+old_object_uri}',
                                                             rel=['hea-desktop-object'],
                                                             itemif='old_object_uri is not None and new_object_uri is None'),
                                                      Action(name='heaserver-activity-desktopobjectaction-get-new-object-uri',
                                                             url='http://localhost:8080/{+new_object_uri}',
                                                             rel=['hea-desktop-object'],
                                                             itemif='new_object_uri is not None')])
