__title__ = "pymodi-plus"
__version__ = "0.4.2"
__author__ = "LUXROBO"
__email__ = "module.dev@luxrobo.com"
__description__ = "Python API for controlling modular electronics, MODI+."
__url__ = "https://github.com/LUXROBO/pymodi-plus"
__license__ = "MIT"
__summary__ = "Python API for controlling modular electronics, MODI+."
