# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from fastapi import *
from run import run_serve
from serve.base import BaseLitAPI
from serve.filebase import RequestLitAPI
from serve.nnfilebase import NNRequestLitAPI


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import fastapi
import argparse
import importlib
import sys
import typing
import litserve
import _frozen_importlib_external
import abc
import starlette
import starlette.datastructures
import io
import uniserve.RequestLitAPI