# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cim/extensions/iec61968/assetinfo/RelayInfo.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.protobuf.cim.iec61968.assets import AssetInfo_pb2 as zepben_dot_protobuf_dot_cim_dot_iec61968_dot_assets_dot_AssetInfo__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAzepben/protobuf/cim/extensions/iec61968/assetinfo/RelayInfo.proto\x12\x31zepben.protobuf.cim.extensions.iec61968.assetinfo\x1a\x33zepben/protobuf/cim/iec61968/assets/AssetInfo.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa1\x02\n\tRelayInfo\x12:\n\x02\x61i\x18\x01 \x01(\x0b\x32..zepben.protobuf.cim.iec61968.assets.AssetInfo\x12\x36\n\x10\x63urveSettingNull\x18\x02 \x01(\x0e\x32\x1a.google.protobuf.NullValueH\x00\x12\x19\n\x0f\x63urveSettingSet\x18\x03 \x01(\tH\x00\x12\x15\n\rrecloseDelays\x18\x04 \x03(\x01\x12\x35\n\x0frecloseFastNull\x18\x05 \x01(\x0e\x32\x1a.google.protobuf.NullValueH\x01\x12\x18\n\x0erecloseFastSet\x18\x06 \x01(\x08H\x01\x42\x0e\n\x0c\x63urveSettingB\r\n\x0brecloseFastB9\n5com.zepben.protobuf.cim.extensions.iec61968.assetinfoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zepben.protobuf.cim.extensions.iec61968.assetinfo.RelayInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n5com.zepben.protobuf.cim.extensions.iec61968.assetinfoP\001'
  _globals['_RELAYINFO']._serialized_start=204
  _globals['_RELAYINFO']._serialized_end=493
# @@protoc_insertion_point(module_scope)
