from ..Base import *
from ..Proxy import *
from ..AcadObject import *

class AcadViews(IAcadObjectCollection):
    def __init__(self, obj) -> None: ...
    def Add(self, Name: str) -> AcadView: ...
    def Item(self, Index: int | str) -> AcadView: ...
    def __iter__(self): ...
