# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.api.edb.v1 import bondwire_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2
from ansys.api.edb.v1 import edb_messages_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


class BondwireServiceStub(object):
    """Bondwire service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/Create',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireCreateMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                )
        self.GetMaterial = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/GetMaterial',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireBoolMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                )
        self.SetMaterial = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/SetMaterial',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetMaterialMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetType = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/GetType',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireTypeMessage.FromString,
                )
        self.SetType = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/SetType',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetBondwireTypeMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetCrossSectionType = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/GetCrossSectionType',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.GetCrossSectionTypeMessage.FromString,
                )
        self.SetCrossSectionType = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/SetCrossSectionType',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetCrossSectionTypeMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetCrossSectionHeight = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/GetCrossSectionHeight',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.ValueMessage.FromString,
                )
        self.SetCrossSectionHeight = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/SetCrossSectionHeight',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetCrossSectionHeightMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetDefinitionName = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/GetDefinitionName',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireBoolMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                )
        self.SetDefinitionName = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/SetDefinitionName',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetDefinitionNameMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetStartElevation = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/GetStartElevation',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjPairMessage.FromString,
                )
        self.SetStartElevation = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/SetStartElevation',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetElevationMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetEndElevation = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/GetEndElevation',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjPairMessage.FromString,
                )
        self.SetEndElevation = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/SetEndElevation',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetElevationMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetTraj = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/GetTraj',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireTrajMessage.FromString,
                )
        self.SetTraj = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/SetTraj',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetBondwireTrajMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetWidthValue = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/GetWidthValue',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.ValueMessage.FromString,
                )
        self.SetWidthValue = channel.unary_unary(
                '/ansys.api.edb.v1.BondwireService/SetWidthValue',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireValueMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class BondwireServiceServicer(object):
    """Bondwire service definition
    """

    def Create(self, request, context):
        """summary: Create Bondwire
        io_flags:
        - buffer
        - returns_future
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMaterial(self, request, context):
        """summary: Get Material
        io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMaterial(self, request, context):
        """summary: Set Material
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetType(self, request, context):
        """summary: Get Bondwire Type
        io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetType(self, request, context):
        """summary: Set Bondwire Type
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCrossSectionType(self, request, context):
        """summary: Get Cross Section Type
        io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCrossSectionType(self, request, context):
        """summary: Set Type
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCrossSectionHeight(self, request, context):
        """summary: Get Cross Section Type
        io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCrossSectionHeight(self, request, context):
        """summary: Set Type
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDefinitionName(self, request, context):
        """summary: Get Bondwire Definition Name
        io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefinitionName(self, request, context):
        """summary: Set Bondwire Definition Name
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStartElevation(self, request, context):
        """summary: Get Start Elevation Layer
        io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStartElevation(self, request, context):
        """summary: Set Start Elevation Layer
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEndElevation(self, request, context):
        """summary: Get End Elevation Layer
        io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEndElevation(self, request, context):
        """summary: Set End Elevation Layer
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTraj(self, request, context):
        """summary: Get Trajectory Values
        io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTraj(self, request, context):
        """summary: Set Trajectory Values
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWidthValue(self, request, context):
        """summary: Get Width Value
        io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWidthValue(self, request, context):
        """summary: Set Width Value
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BondwireServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireCreateMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ),
            'GetMaterial': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMaterial,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireBoolMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'SetMaterial': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMaterial,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetMaterialMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetType,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireTypeMessage.SerializeToString,
            ),
            'SetType': grpc.unary_unary_rpc_method_handler(
                    servicer.SetType,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetBondwireTypeMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetCrossSectionType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCrossSectionType,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.GetCrossSectionTypeMessage.SerializeToString,
            ),
            'SetCrossSectionType': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCrossSectionType,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetCrossSectionTypeMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetCrossSectionHeight': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCrossSectionHeight,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.ValueMessage.SerializeToString,
            ),
            'SetCrossSectionHeight': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCrossSectionHeight,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetCrossSectionHeightMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetDefinitionName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefinitionName,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireBoolMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'SetDefinitionName': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefinitionName,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetDefinitionNameMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetStartElevation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStartElevation,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjPairMessage.SerializeToString,
            ),
            'SetStartElevation': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStartElevation,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetElevationMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetEndElevation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEndElevation,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjPairMessage.SerializeToString,
            ),
            'SetEndElevation': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEndElevation,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetElevationMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetTraj': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTraj,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireTrajMessage.SerializeToString,
            ),
            'SetTraj': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTraj,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetBondwireTrajMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetWidthValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWidthValue,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.ValueMessage.SerializeToString,
            ),
            'SetWidthValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWidthValue,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireValueMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.edb.v1.BondwireService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BondwireService(object):
    """Bondwire service definition
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/Create',
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireCreateMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMaterial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/GetMaterial',
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireBoolMessage.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMaterial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/SetMaterial',
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetMaterialMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/GetType',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireTypeMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/SetType',
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetBondwireTypeMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCrossSectionType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/GetCrossSectionType',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.GetCrossSectionTypeMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetCrossSectionType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/SetCrossSectionType',
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetCrossSectionTypeMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCrossSectionHeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/GetCrossSectionHeight',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.ValueMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetCrossSectionHeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/SetCrossSectionHeight',
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetCrossSectionHeightMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDefinitionName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/GetDefinitionName',
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireBoolMessage.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDefinitionName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/SetDefinitionName',
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetDefinitionNameMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStartElevation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/GetStartElevation',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjPairMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetStartElevation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/SetStartElevation',
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetElevationMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEndElevation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/GetEndElevation',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjPairMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetEndElevation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/SetEndElevation',
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetElevationMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTraj(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/GetTraj',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireTrajMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTraj(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/SetTraj',
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.SetBondwireTrajMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWidthValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/GetWidthValue',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.ValueMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetWidthValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.BondwireService/SetWidthValue',
            ansys_dot_api_dot_edb_dot_v1_dot_bondwire__pb2.BondwireValueMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
