"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.edb.v1.connectable_pb2
import ansys.api.edb.v1.edb_messages_pb2
import google.protobuf.empty_pb2
import grpc

class ConnectableServiceStub:
    """Connectable Service definition"""
    def __init__(self, channel: grpc.Channel) -> None: ...
    GetObjType: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.connectable_pb2.LayoutObjTypeMessage] = ...
    """summary: Gets the layout object type.
    io_flags:
      - cache
    """

    FindByIdAndType: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.connectable_pb2.FindByIdLayoutObjMessage,
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...
    """summary: Find a Connectable object by Database ID and type.
    io_flags:
      - cache
    """

    GetId: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.edb_messages_pb2.EDBInternalIdMessage] = ...
    """summary: Get the unique, persistent ID for the Connectable object.
    io_flags:
      - cache
    """

    GetComponent: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...
    """summary: Gets the Component of the connectable object.
    io_flags:
      - cache
    """

    GetGroup: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...
    """summary: Gets the group of the connectable object.
    io_flags:
      - cache
    """

    SetGroup: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.PointerPropertyMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """summary: Sets the group of the connectable object.
    io_flags:
      - buffer
    """

    GetNet: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...
    """summary: Gets the net of the connectable object.
    io_flags:
      - cache
    """

    SetNet: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.connectable_pb2.SetNetMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """summary: Sets the net of the connectable object.
    io_flags:
      - buffer
    """


class ConnectableServiceServicer(metaclass=abc.ABCMeta):
    """Connectable Service definition"""
    @abc.abstractmethod
    def GetObjType(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.connectable_pb2.LayoutObjTypeMessage:
        """summary: Gets the layout object type.
        io_flags:
          - cache
        """
        pass

    @abc.abstractmethod
    def FindByIdAndType(self,
        request: ansys.api.edb.v1.connectable_pb2.FindByIdLayoutObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage:
        """summary: Find a Connectable object by Database ID and type.
        io_flags:
          - cache
        """
        pass

    @abc.abstractmethod
    def GetId(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.EDBInternalIdMessage:
        """summary: Get the unique, persistent ID for the Connectable object.
        io_flags:
          - cache
        """
        pass

    @abc.abstractmethod
    def GetComponent(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage:
        """summary: Gets the Component of the connectable object.
        io_flags:
          - cache
        """
        pass

    @abc.abstractmethod
    def GetGroup(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage:
        """summary: Gets the group of the connectable object.
        io_flags:
          - cache
        """
        pass

    @abc.abstractmethod
    def SetGroup(self,
        request: ansys.api.edb.v1.edb_messages_pb2.PointerPropertyMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """summary: Sets the group of the connectable object.
        io_flags:
          - buffer
        """
        pass

    @abc.abstractmethod
    def GetNet(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage:
        """summary: Gets the net of the connectable object.
        io_flags:
          - cache
        """
        pass

    @abc.abstractmethod
    def SetNet(self,
        request: ansys.api.edb.v1.connectable_pb2.SetNetMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """summary: Sets the net of the connectable object.
        io_flags:
          - buffer
        """
        pass


def add_ConnectableServiceServicer_to_server(servicer: ConnectableServiceServicer, server: grpc.Server) -> None: ...
