# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/edb/v1/die_property.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ansys.api.edb.v1 import edb_messages_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2
try:
  google_dot_protobuf_dot_wrappers__pb2 = ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.google_dot_protobuf_dot_wrappers__pb2
except AttributeError:
  google_dot_protobuf_dot_wrappers__pb2 = ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.google.protobuf.wrappers_pb2
try:
  google_dot_protobuf_dot_empty__pb2 = ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.google_dot_protobuf_dot_empty__pb2
except AttributeError:
  google_dot_protobuf_dot_empty__pb2 = ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.google.protobuf.empty_pb2
try:
  google_dot_protobuf_dot_any__pb2 = ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.google_dot_protobuf_dot_any__pb2
except AttributeError:
  google_dot_protobuf_dot_any__pb2 = ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.google.protobuf.any_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ansys/api/edb/v1/die_property.proto\x12\x10\x61nsys.api.edb.v1\x1a#ansys/api/edb/v1/edb_messages.proto\"=\n\x0e\x44ieTypeMessage\x12+\n\x08\x64ie_type\x18\x01 \x01(\x0e\x32\x19.ansys.api.edb.v1.DieType\"}\n\x16\x44ieTypePropertyMessage\x12/\n\x06target\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12\x32\n\x08\x64ie_type\x18\x02 \x01(\x0b\x32 .ansys.api.edb.v1.DieTypeMessage\"R\n\x15\x44ieOrientationMessage\x12\x39\n\x0f\x64ie_orientation\x18\x01 \x01(\x0e\x32 .ansys.api.edb.v1.DieOrientation\"\x92\x01\n\x1d\x44ieOrientationPropertyMessage\x12/\n\x06target\x18\x01 \x01(\x0b\x32\x1f.ansys.api.edb.v1.EDBObjMessage\x12@\n\x0f\x64ie_orientation\x18\x02 \x01(\x0b\x32\'.ansys.api.edb.v1.DieOrientationMessage*L\n\x0e\x44ieOrientation\x12\x1b\n\x17\x44IE_ORIENTATION_CHIP_UP\x10\x00\x12\x1d\n\x19\x44IE_ORIENTATION_CHIP_DOWN\x10\x01*J\n\x07\x44ieType\x12\x11\n\rDIE_TYPE_NONE\x10\x00\x12\x15\n\x11\x44IE_TYPE_FLIPCHIP\x10\x01\x12\x15\n\x11\x44IE_TYPE_WIREBOND\x10\x02\x32\xa5\x05\n\x12\x44iePropertyService\x12\x43\n\x06\x43reate\x12\x16.google.protobuf.Empty\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12K\n\x05\x43lone\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\x1f.ansys.api.edb.v1.EDBObjMessage\"\x00\x12Q\n\nGetDieType\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a .ansys.api.edb.v1.DieTypeMessage\"\x00\x12P\n\nSetDieType\x12(.ansys.api.edb.v1.DieTypePropertyMessage\x1a\x16.google.protobuf.Empty\"\x00\x12N\n\tGetHeight\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\x1e.ansys.api.edb.v1.ValueMessage\"\x00\x12M\n\tSetHeight\x12&.ansys.api.edb.v1.ValuePropertyMessage\x1a\x16.google.protobuf.Empty\"\x00\x12\\\n\x0eGetOrientation\x12\x1f.ansys.api.edb.v1.EDBObjMessage\x1a\'.ansys.api.edb.v1.DieOrientationMessage\"\x00\x12[\n\x0eSetOrientation\x12/.ansys.api.edb.v1.DieOrientationPropertyMessage\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ansys.api.edb.v1.die_property_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DIEORIENTATION._serialized_start=517
  _DIEORIENTATION._serialized_end=593
  _DIETYPE._serialized_start=595
  _DIETYPE._serialized_end=669
  _DIETYPEMESSAGE._serialized_start=94
  _DIETYPEMESSAGE._serialized_end=155
  _DIETYPEPROPERTYMESSAGE._serialized_start=157
  _DIETYPEPROPERTYMESSAGE._serialized_end=282
  _DIEORIENTATIONMESSAGE._serialized_start=284
  _DIEORIENTATIONMESSAGE._serialized_end=366
  _DIEORIENTATIONPROPERTYMESSAGE._serialized_start=369
  _DIEORIENTATIONPROPERTYMESSAGE._serialized_end=515
  _DIEPROPERTYSERVICE._serialized_start=672
  _DIEPROPERTYSERVICE._serialized_end=1349
# @@protoc_insertion_point(module_scope)
