# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.api.edb.v1 import edb_messages_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2
from ansys.api.edb.v1 import group_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_group__pb2
from ansys.api.edb.v1 import hierarchy_obj_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_hierarchy__obj__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class GroupServiceStub(object):
    """Group service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/ansys.api.edb.v1.GroupService/Create',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_hierarchy__obj__pb2.ObjectNameInLayoutMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                )
        self.FindByName = channel.unary_unary(
                '/ansys.api.edb.v1.GroupService/FindByName',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_hierarchy__obj__pb2.ObjectNameInLayoutMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                )
        self.AddMember = channel.unary_unary(
                '/ansys.api.edb.v1.GroupService/AddMember',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_group__pb2.GroupModifyMemberMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.RemoveMember = channel.unary_unary(
                '/ansys.api.edb.v1.GroupService/RemoveMember',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_group__pb2.GroupModifyMemberMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Ungroup = channel.unary_unary(
                '/ansys.api.edb.v1.GroupService/Ungroup',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.BoolPropertyMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetMembers = channel.unary_unary(
                '/ansys.api.edb.v1.GroupService/GetMembers',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjCollectionMessage.FromString,
                )
        self.StreamMembers = channel.unary_stream(
                '/ansys.api.edb.v1.GroupService/StreamMembers',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjCollectionMessage.FromString,
                )
        self.GetGroupType = channel.unary_unary(
                '/ansys.api.edb.v1.GroupService/GetGroupType',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_group__pb2.GroupTypeMessage.FromString,
                )


class GroupServiceServicer(object):
    """Group service definition
    """

    def Create(self, request, context):
        """summary: Create a group
        io_flags:
        - buffer
        - returns_future
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindByName(self, request, context):
        """summary: Finds a group by name in the given layout
        io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMember(self, request, context):
        """summary: Add a member to the group
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveMember(self, request, context):
        """summary: Remove a member from the group
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ungroup(self, request, context):
        """summary: Ungroup this group
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMembers(self, request, context):
        """summary: Get iterable for group members
        io_flags:
        - read_no_cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMembers(self, request, context):
        """summary: Stream iterable for group members
        io_flags:
        - read_no_cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupType(self, request, context):
        """summary: Get the type of the group
        io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_hierarchy__obj__pb2.ObjectNameInLayoutMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ),
            'FindByName': grpc.unary_unary_rpc_method_handler(
                    servicer.FindByName,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_hierarchy__obj__pb2.ObjectNameInLayoutMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ),
            'AddMember': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMember,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_group__pb2.GroupModifyMemberMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveMember': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveMember,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_group__pb2.GroupModifyMemberMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Ungroup': grpc.unary_unary_rpc_method_handler(
                    servicer.Ungroup,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.BoolPropertyMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMembers,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjCollectionMessage.SerializeToString,
            ),
            'StreamMembers': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMembers,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjCollectionMessage.SerializeToString,
            ),
            'GetGroupType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupType,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_group__pb2.GroupTypeMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.edb.v1.GroupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GroupService(object):
    """Group service definition
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.GroupService/Create',
            ansys_dot_api_dot_edb_dot_v1_dot_hierarchy__obj__pb2.ObjectNameInLayoutMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.GroupService/FindByName',
            ansys_dot_api_dot_edb_dot_v1_dot_hierarchy__obj__pb2.ObjectNameInLayoutMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.GroupService/AddMember',
            ansys_dot_api_dot_edb_dot_v1_dot_group__pb2.GroupModifyMemberMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.GroupService/RemoveMember',
            ansys_dot_api_dot_edb_dot_v1_dot_group__pb2.GroupModifyMemberMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ungroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.GroupService/Ungroup',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.BoolPropertyMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.GroupService/GetMembers',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjCollectionMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ansys.api.edb.v1.GroupService/StreamMembers',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjCollectionMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGroupType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.GroupService/GetGroupType',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_group__pb2.GroupTypeMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
