# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.api.edb.v1 import edb_messages_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2
from ansys.api.edb.v1 import hfss_simulation_setup_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_hfss__simulation__setup__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class HfssSimulationSetupServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMeshOperations = channel.unary_unary(
                '/ansys.api.edb.v1.HfssSimulationSetupService/GetMeshOperations',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_hfss__simulation__setup__pb2.MeshOperationsMessage.FromString,
                )
        self.SetMeshOperations = channel.unary_unary(
                '/ansys.api.edb.v1.HfssSimulationSetupService/SetMeshOperations',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_hfss__simulation__setup__pb2.MeshOperationsPropertyMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class HfssSimulationSetupServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMeshOperations(self, request, context):
        """io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMeshOperations(self, request, context):
        """io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HfssSimulationSetupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMeshOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeshOperations,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_hfss__simulation__setup__pb2.MeshOperationsMessage.SerializeToString,
            ),
            'SetMeshOperations': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMeshOperations,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_hfss__simulation__setup__pb2.MeshOperationsPropertyMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.edb.v1.HfssSimulationSetupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HfssSimulationSetupService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMeshOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.HfssSimulationSetupService/GetMeshOperations',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_hfss__simulation__setup__pb2.MeshOperationsMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMeshOperations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.HfssSimulationSetupService/SetMeshOperations',
            ansys_dot_api_dot_edb_dot_v1_dot_hfss__simulation__setup__pb2.MeshOperationsPropertyMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
