"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.edb.v1.edb_messages_pb2
import ansys.api.edb.v1.inst_array_pb2
import ansys.api.edb.v1.point_data_pb2
import google.protobuf.empty_pb2
import grpc

class InstArrayServiceStub:
    """Instance Array service definition"""
    def __init__(self, channel: grpc.Channel) -> None: ...
    Create: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.inst_array_pb2.InstArrayCreationMessage,
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...
    """io_flags:
      - buffer
      - returns_future
    """

    FindByName: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.StringPropertyMessage,
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...
    """io_flags:
      - cache
    """

    GetOrig: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.point_data_pb2.PointMessage] = ...
    """io_flas:
      - cache
    """

    GetXAxis: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.point_data_pb2.PointMessage] = ...
    """io_flags:
      - cache
    """

    SetXAxis: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.point_data_pb2.PointPropertyMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """io_flags:
      - buffer
    """

    GetYAxis: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.point_data_pb2.PointMessage] = ...
    """io_flags:
      - cache
    """

    SetYAxis: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.point_data_pb2.PointPropertyMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """io_flags:
      - buffer
    """

    GetXCount: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.edb_messages_pb2.ValueMessage] = ...
    """io_flags:
      - cache
    """

    SetXCount: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.ValuePropertyMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """io_flags:
      - buffer
    """

    GetYCount: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.edb_messages_pb2.ValueMessage] = ...
    """io_flags:
      - cache
    """

    SetYCount: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.ValuePropertyMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """io_flags:
      - buffer
    """

    Decompose: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """io_flags:
      - buffer
    """


class InstArrayServiceServicer(metaclass=abc.ABCMeta):
    """Instance Array service definition"""
    @abc.abstractmethod
    def Create(self,
        request: ansys.api.edb.v1.inst_array_pb2.InstArrayCreationMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage:
        """io_flags:
          - buffer
          - returns_future
        """
        pass

    @abc.abstractmethod
    def FindByName(self,
        request: ansys.api.edb.v1.edb_messages_pb2.StringPropertyMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage:
        """io_flags:
          - cache
        """
        pass

    @abc.abstractmethod
    def GetOrig(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.point_data_pb2.PointMessage:
        """io_flas:
          - cache
        """
        pass

    @abc.abstractmethod
    def GetXAxis(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.point_data_pb2.PointMessage:
        """io_flags:
          - cache
        """
        pass

    @abc.abstractmethod
    def SetXAxis(self,
        request: ansys.api.edb.v1.point_data_pb2.PointPropertyMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """io_flags:
          - buffer
        """
        pass

    @abc.abstractmethod
    def GetYAxis(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.point_data_pb2.PointMessage:
        """io_flags:
          - cache
        """
        pass

    @abc.abstractmethod
    def SetYAxis(self,
        request: ansys.api.edb.v1.point_data_pb2.PointPropertyMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """io_flags:
          - buffer
        """
        pass

    @abc.abstractmethod
    def GetXCount(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.ValueMessage:
        """io_flags:
          - cache
        """
        pass

    @abc.abstractmethod
    def SetXCount(self,
        request: ansys.api.edb.v1.edb_messages_pb2.ValuePropertyMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """io_flags:
          - buffer
        """
        pass

    @abc.abstractmethod
    def GetYCount(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.ValueMessage:
        """io_flags:
          - cache
        """
        pass

    @abc.abstractmethod
    def SetYCount(self,
        request: ansys.api.edb.v1.edb_messages_pb2.ValuePropertyMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """io_flags:
          - buffer
        """
        pass

    @abc.abstractmethod
    def Decompose(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """io_flags:
          - buffer
        """
        pass


def add_InstArrayServiceServicer_to_server(servicer: InstArrayServiceServicer, server: grpc.Server) -> None: ...
