"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import ansys.api.edb.v1.edb_messages_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class _LayerType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _LayerTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LayerType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    SIGNAL_LAYER: LayerType.ValueType = ...  # 0
    DIELECTRIC_LAYER: LayerType.ValueType = ...  # 1
    CONDUCTING_LAYER: LayerType.ValueType = ...  # 2
    AIRLINES_LAYER: LayerType.ValueType = ...  # 3
    ERRORS_LAYER: LayerType.ValueType = ...  # 4
    SYMBOL_LAYER: LayerType.ValueType = ...  # 5
    MEASURE_LAYER: LayerType.ValueType = ...  # 6
    ASSEMBLY_LAYER: LayerType.ValueType = ...  # 8
    SILKSCREEN_LAYER: LayerType.ValueType = ...  # 9
    SOLDER_MASK_LAYER: LayerType.ValueType = ...  # 10
    SOLDER_PASTE_LAYER: LayerType.ValueType = ...  # 11
    GLUE_LAYER: LayerType.ValueType = ...  # 12
    WIREBOND_LAYER: LayerType.ValueType = ...  # 13
    USER_LAYER: LayerType.ValueType = ...  # 14
    SIWAVE_HFSS_SOLVER_REGIONS: LayerType.ValueType = ...  # 16
    POST_PROCESSING_LAYER: LayerType.ValueType = ...  # 17
    OUTLINE_LAYER: LayerType.ValueType = ...  # 18
    LAYER_TYPES_COUNT: LayerType.ValueType = ...  # 19
    UNDEFINED_LAYER_TYPE: LayerType.ValueType = ...  # -1
class LayerType(_LayerType, metaclass=_LayerTypeEnumTypeWrapper):
    pass

SIGNAL_LAYER: LayerType.ValueType = ...  # 0
DIELECTRIC_LAYER: LayerType.ValueType = ...  # 1
CONDUCTING_LAYER: LayerType.ValueType = ...  # 2
AIRLINES_LAYER: LayerType.ValueType = ...  # 3
ERRORS_LAYER: LayerType.ValueType = ...  # 4
SYMBOL_LAYER: LayerType.ValueType = ...  # 5
MEASURE_LAYER: LayerType.ValueType = ...  # 6
ASSEMBLY_LAYER: LayerType.ValueType = ...  # 8
SILKSCREEN_LAYER: LayerType.ValueType = ...  # 9
SOLDER_MASK_LAYER: LayerType.ValueType = ...  # 10
SOLDER_PASTE_LAYER: LayerType.ValueType = ...  # 11
GLUE_LAYER: LayerType.ValueType = ...  # 12
WIREBOND_LAYER: LayerType.ValueType = ...  # 13
USER_LAYER: LayerType.ValueType = ...  # 14
SIWAVE_HFSS_SOLVER_REGIONS: LayerType.ValueType = ...  # 16
POST_PROCESSING_LAYER: LayerType.ValueType = ...  # 17
OUTLINE_LAYER: LayerType.ValueType = ...  # 18
LAYER_TYPES_COUNT: LayerType.ValueType = ...  # 19
UNDEFINED_LAYER_TYPE: LayerType.ValueType = ...  # -1
global___LayerType = LayerType


class _TopBottomAssociation:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _TopBottomAssociationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TopBottomAssociation.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    TOP_ASSOCIATED: TopBottomAssociation.ValueType = ...  # 0
    NO_TOP_BOTTOM_ASSOCIATED: TopBottomAssociation.ValueType = ...  # 1
    BOTTOM_ASSOCIATED: TopBottomAssociation.ValueType = ...  # 2
    TOP_BOTTOM_ASSOCIATION_COUNT: TopBottomAssociation.ValueType = ...  # 4
    INVALID_TOP_BOTTOM_ASSOCIATION: TopBottomAssociation.ValueType = ...  # -1
class TopBottomAssociation(_TopBottomAssociation, metaclass=_TopBottomAssociationEnumTypeWrapper):
    pass

TOP_ASSOCIATED: TopBottomAssociation.ValueType = ...  # 0
NO_TOP_BOTTOM_ASSOCIATED: TopBottomAssociation.ValueType = ...  # 1
BOTTOM_ASSOCIATED: TopBottomAssociation.ValueType = ...  # 2
TOP_BOTTOM_ASSOCIATION_COUNT: TopBottomAssociation.ValueType = ...  # 4
INVALID_TOP_BOTTOM_ASSOCIATION: TopBottomAssociation.ValueType = ...  # -1
global___TopBottomAssociation = TopBottomAssociation


class _DrawOverride:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _DrawOverrideEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DrawOverride.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    NO_OVERRIDE: DrawOverride.ValueType = ...  # 0
    FILL: DrawOverride.ValueType = ...  # 1
    WIREFRAME: DrawOverride.ValueType = ...  # -1
class DrawOverride(_DrawOverride, metaclass=_DrawOverrideEnumTypeWrapper):
    pass

NO_OVERRIDE: DrawOverride.ValueType = ...  # 0
FILL: DrawOverride.ValueType = ...  # 1
WIREFRAME: DrawOverride.ValueType = ...  # -1
global___DrawOverride = DrawOverride


class _LayerVisibility:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _LayerVisibilityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LayerVisibility.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    LAYER_VISIBILITY_PLACEHOLDER: LayerVisibility.ValueType = ...  # 0
    """DO NOT USE - THIS IS A PROTO3 REQUIREMENT"""

    PRIMITIVE_VISIBLE: LayerVisibility.ValueType = ...  # 1
    PATH_VISIBLE: LayerVisibility.ValueType = ...  # 2
    PAD_VISIBLE: LayerVisibility.ValueType = ...  # 4
    HOLE_VISIBLE: LayerVisibility.ValueType = ...  # 8
    COMPONENT_VISIBLE: LayerVisibility.ValueType = ...  # 16
    ALL_VISIBLE: LayerVisibility.ValueType = ...  # 31
class LayerVisibility(_LayerVisibility, metaclass=_LayerVisibilityEnumTypeWrapper):
    pass

LAYER_VISIBILITY_PLACEHOLDER: LayerVisibility.ValueType = ...  # 0
"""DO NOT USE - THIS IS A PROTO3 REQUIREMENT"""

PRIMITIVE_VISIBLE: LayerVisibility.ValueType = ...  # 1
PATH_VISIBLE: LayerVisibility.ValueType = ...  # 2
PAD_VISIBLE: LayerVisibility.ValueType = ...  # 4
HOLE_VISIBLE: LayerVisibility.ValueType = ...  # 8
COMPONENT_VISIBLE: LayerVisibility.ValueType = ...  # 16
ALL_VISIBLE: LayerVisibility.ValueType = ...  # 31
global___LayerVisibility = LayerVisibility


class LayerCreationMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    type: global___LayerType.ValueType = ...
    def __init__(self,
        *,
        name : typing.Text = ...,
        type : global___LayerType.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","type",b"type"]) -> None: ...
global___LayerCreationMessage = LayerCreationMessage

class LayerTypeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TYPE_FIELD_NUMBER: builtins.int
    type: global___LayerType.ValueType = ...
    def __init__(self,
        *,
        type : global___LayerType.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["type",b"type"]) -> None: ...
global___LayerTypeMessage = LayerTypeMessage

class SetLayerTypeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LAYER_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    @property
    def layer(self) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...
    type: global___LayerType.ValueType = ...
    def __init__(self,
        *,
        layer : typing.Optional[ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...,
        type : global___LayerType.ValueType = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["layer",b"layer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["layer",b"layer","type",b"type"]) -> None: ...
global___SetLayerTypeMessage = SetLayerTypeMessage

class SetNameMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LAYER_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    @property
    def layer(self) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...
    name: typing.Text = ...
    def __init__(self,
        *,
        layer : typing.Optional[ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...,
        name : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["layer",b"layer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["layer",b"layer","name",b"name"]) -> None: ...
global___SetNameMessage = SetNameMessage

class CloneMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LAYER_FIELD_NUMBER: builtins.int
    COPY_ID_FIELD_NUMBER: builtins.int
    @property
    def layer(self) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...
    copy_id: builtins.bool = ...
    def __init__(self,
        *,
        layer : typing.Optional[ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...,
        copy_id : builtins.bool = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["layer",b"layer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["copy_id",b"copy_id","layer",b"layer"]) -> None: ...
global___CloneMessage = CloneMessage

class TopBottomAssociationMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TOP_BOTTOM_ASSOCIATION_FIELD_NUMBER: builtins.int
    top_bottom_association: global___TopBottomAssociation.ValueType = ...
    def __init__(self,
        *,
        top_bottom_association : global___TopBottomAssociation.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["top_bottom_association",b"top_bottom_association"]) -> None: ...
global___TopBottomAssociationMessage = TopBottomAssociationMessage

class SetTopBottomAssociationMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LAYER_FIELD_NUMBER: builtins.int
    TOP_BOTTOM_ASSOCIATION_FIELD_NUMBER: builtins.int
    @property
    def layer(self) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...
    top_bottom_association: global___TopBottomAssociation.ValueType = ...
    def __init__(self,
        *,
        layer : typing.Optional[ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...,
        top_bottom_association : global___TopBottomAssociation.ValueType = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["layer",b"layer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["layer",b"layer","top_bottom_association",b"top_bottom_association"]) -> None: ...
global___SetTopBottomAssociationMessage = SetTopBottomAssociationMessage

class SetColorMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LAYER_FIELD_NUMBER: builtins.int
    COLOR_FIELD_NUMBER: builtins.int
    @property
    def layer(self) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...
    color: builtins.int = ...
    def __init__(self,
        *,
        layer : typing.Optional[ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...,
        color : builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["layer",b"layer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["color",b"color","layer",b"layer"]) -> None: ...
global___SetColorMessage = SetColorMessage

class SetVisibilityMaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LAYER_FIELD_NUMBER: builtins.int
    VISIBILITY_MASK_FIELD_NUMBER: builtins.int
    @property
    def layer(self) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...
    visibility_mask: builtins.int = ...
    def __init__(self,
        *,
        layer : typing.Optional[ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...,
        visibility_mask : builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["layer",b"layer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["layer",b"layer","visibility_mask",b"visibility_mask"]) -> None: ...
global___SetVisibilityMaskMessage = SetVisibilityMaskMessage

class SetLockedMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LAYER_FIELD_NUMBER: builtins.int
    IS_LOCKED_FIELD_NUMBER: builtins.int
    @property
    def layer(self) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...
    is_locked: builtins.bool = ...
    def __init__(self,
        *,
        layer : typing.Optional[ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...,
        is_locked : builtins.bool = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["layer",b"layer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["is_locked",b"is_locked","layer",b"layer"]) -> None: ...
global___SetLockedMessage = SetLockedMessage

class SetTransparencyMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LAYER_FIELD_NUMBER: builtins.int
    TRANSPARENCY_FIELD_NUMBER: builtins.int
    @property
    def layer(self) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...
    transparency: builtins.int = ...
    def __init__(self,
        *,
        layer : typing.Optional[ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...,
        transparency : builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["layer",b"layer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["layer",b"layer","transparency",b"transparency"]) -> None: ...
global___SetTransparencyMessage = SetTransparencyMessage

class DrawOverrideMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DRAW_OVERRIDE_FIELD_NUMBER: builtins.int
    draw_override: global___DrawOverride.ValueType = ...
    def __init__(self,
        *,
        draw_override : global___DrawOverride.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["draw_override",b"draw_override"]) -> None: ...
global___DrawOverrideMessage = DrawOverrideMessage

class SetDrawOverrideMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LAYER_FIELD_NUMBER: builtins.int
    DRAW_OVERRIDE_FIELD_NUMBER: builtins.int
    @property
    def layer(self) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...
    draw_override: global___DrawOverride.ValueType = ...
    def __init__(self,
        *,
        layer : typing.Optional[ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...,
        draw_override : global___DrawOverride.ValueType = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["layer",b"layer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["draw_override",b"draw_override","layer",b"layer"]) -> None: ...
global___SetDrawOverrideMessage = SetDrawOverrideMessage

class ZoneMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LAYER_FIELD_NUMBER: builtins.int
    ZONE_FIELD_NUMBER: builtins.int
    @property
    def layer(self) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...
    zone: builtins.int = ...
    def __init__(self,
        *,
        layer : typing.Optional[ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...,
        zone : builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["layer",b"layer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["layer",b"layer","zone",b"zone"]) -> None: ...
global___ZoneMessage = ZoneMessage

class SetIsInZoneMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ZONE_MSG_FIELD_NUMBER: builtins.int
    IN_ZONE_FIELD_NUMBER: builtins.int
    @property
    def zone_msg(self) -> global___ZoneMessage: ...
    in_zone: builtins.bool = ...
    def __init__(self,
        *,
        zone_msg : typing.Optional[global___ZoneMessage] = ...,
        in_zone : builtins.bool = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["zone_msg",b"zone_msg"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["in_zone",b"in_zone","zone_msg",b"zone_msg"]) -> None: ...
global___SetIsInZoneMessage = SetIsInZoneMessage

class ZonesMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ZONES_FIELD_NUMBER: builtins.int
    @property
    def zones(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(self,
        *,
        zones : typing.Optional[typing.Iterable[builtins.int]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["zones",b"zones"]) -> None: ...
global___ZonesMessage = ZonesMessage
