# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.api.edb.v1 import edb_messages_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


class NetlistModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/ansys.api.edb.v1.NetlistModelService/Create',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                )
        self.GetNetlist = channel.unary_unary(
                '/ansys.api.edb.v1.NetlistModelService/GetNetlist',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                )
        self.SetNetlist = channel.unary_unary(
                '/ansys.api.edb.v1.NetlistModelService/SetNetlist',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.StringPropertyMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class NetlistModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """io_flags:
        - buffer
        - returns_future
        - write_no_cache_invalidation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetlist(self, request, context):
        """io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNetlist(self, request, context):
        """io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetlistModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ),
            'GetNetlist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetlist,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'SetNetlist': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNetlist,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.StringPropertyMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.edb.v1.NetlistModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NetlistModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.NetlistModelService/Create',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNetlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.NetlistModelService/GetNetlist',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetNetlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.NetlistModelService/SetNetlist',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.StringPropertyMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
