"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import ansys.api.edb.v1.edb_messages_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class DiameterMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DIAMETER1_FIELD_NUMBER: builtins.int
    DIAMETER2_FIELD_NUMBER: builtins.int
    @property
    def diameter1(self) -> ansys.api.edb.v1.edb_messages_pb2.ValueMessage: ...
    @property
    def diameter2(self) -> ansys.api.edb.v1.edb_messages_pb2.ValueMessage: ...
    def __init__(self,
        *,
        diameter1 : typing.Optional[ansys.api.edb.v1.edb_messages_pb2.ValueMessage] = ...,
        diameter2 : typing.Optional[ansys.api.edb.v1.edb_messages_pb2.ValueMessage] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["diameter1",b"diameter1","diameter2",b"diameter2"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["diameter1",b"diameter1","diameter2",b"diameter2"]) -> None: ...
global___DiameterMessage = DiameterMessage

class SetDiameterMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TARGET_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    @property
    def target(self) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...
    @property
    def value(self) -> global___DiameterMessage: ...
    def __init__(self,
        *,
        target : typing.Optional[ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...,
        value : typing.Optional[global___DiameterMessage] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["target",b"target","value",b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["target",b"target","value",b"value"]) -> None: ...
global___SetDiameterMessage = SetDiameterMessage
