# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ansys.api.edb.v1 import edb_messages_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2
from ansys.api.edb.v1 import hierarchy_obj_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_hierarchy__obj__pb2
from ansys.api.edb.v1 import structure_3d_pb2 as ansys_dot_api_dot_edb_dot_v1_dot_structure__3d__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


class Structure3DServiceStub(object):
    """Structure3D service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/ansys.api.edb.v1.Structure3DService/Create',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_hierarchy__obj__pb2.ObjectNameInLayoutMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                )
        self.GetMaterial = channel.unary_unary(
                '/ansys.api.edb.v1.Structure3DService/GetMaterial',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.BoolPropertyMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                )
        self.SetMaterial = channel.unary_unary(
                '/ansys.api.edb.v1.Structure3DService/SetMaterial',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.StringPropertyMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetThickness = channel.unary_unary(
                '/ansys.api.edb.v1.Structure3DService/GetThickness',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.ValueMessage.FromString,
                )
        self.SetThickness = channel.unary_unary(
                '/ansys.api.edb.v1.Structure3DService/SetThickness',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.ValuePropertyMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetMeshClosureProp = channel.unary_unary(
                '/ansys.api.edb.v1.Structure3DService/GetMeshClosureProp',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
                response_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_structure__3d__pb2.ClosureMessage.FromString,
                )
        self.SetMeshClosureProp = channel.unary_unary(
                '/ansys.api.edb.v1.Structure3DService/SetMeshClosureProp',
                request_serializer=ansys_dot_api_dot_edb_dot_v1_dot_structure__3d__pb2.SetClosureMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class Structure3DServiceServicer(object):
    """Structure3D service definition
    """

    def Create(self, request, context):
        """summary: Create a structure3D
        io_flags:
        - buffer
        - returns_future
        - write_no_cache_invalidation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMaterial(self, request, context):
        """summary: Get material
        io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMaterial(self, request, context):
        """summary: Set material
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThickness(self, request, context):
        """summary: Get thickness
        io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetThickness(self, request, context):
        """summary: Set thickness
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMeshClosureProp(self, request, context):
        """summary: Get mesh closure property
        io_flags:
        - cache
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMeshClosureProp(self, request, context):
        """summary: Set mesh closure property
        io_flags:
        - buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Structure3DServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_hierarchy__obj__pb2.ObjectNameInLayoutMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ),
            'GetMaterial': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMaterial,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.BoolPropertyMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'SetMaterial': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMaterial,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.StringPropertyMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetThickness': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThickness,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.ValueMessage.SerializeToString,
            ),
            'SetThickness': grpc.unary_unary_rpc_method_handler(
                    servicer.SetThickness,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.ValuePropertyMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMeshClosureProp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeshClosureProp,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
                    response_serializer=ansys_dot_api_dot_edb_dot_v1_dot_structure__3d__pb2.ClosureMessage.SerializeToString,
            ),
            'SetMeshClosureProp': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMeshClosureProp,
                    request_deserializer=ansys_dot_api_dot_edb_dot_v1_dot_structure__3d__pb2.SetClosureMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.edb.v1.Structure3DService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Structure3DService(object):
    """Structure3D service definition
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.Structure3DService/Create',
            ansys_dot_api_dot_edb_dot_v1_dot_hierarchy__obj__pb2.ObjectNameInLayoutMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMaterial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.Structure3DService/GetMaterial',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.BoolPropertyMessage.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMaterial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.Structure3DService/SetMaterial',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.StringPropertyMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetThickness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.Structure3DService/GetThickness',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.ValueMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetThickness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.Structure3DService/SetThickness',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.ValuePropertyMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMeshClosureProp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.Structure3DService/GetMeshClosureProp',
            ansys_dot_api_dot_edb_dot_v1_dot_edb__messages__pb2.EDBObjMessage.SerializeToString,
            ansys_dot_api_dot_edb_dot_v1_dot_structure__3d__pb2.ClosureMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMeshClosureProp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.edb.v1.Structure3DService/SetMeshClosureProp',
            ansys_dot_api_dot_edb_dot_v1_dot_structure__3d__pb2.SetClosureMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
