from .classes import ClassesGroup as ClassesGroup, ClassificationSystemClass as ClassificationSystemClass
from .link import Link as Link
from .utils import Utils as Utils

class ClassificationSystem(dict):
    def __init__(self, data: dict, validate: bool = False) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def identifier(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def links(self) -> list[Link]: ...
    @property
    def description(self) -> str | None: ...
    @property
    def version(self) -> str: ...
    @property
    def authority_name(self) -> str | None: ...
    def classes(self, class_name_or_id: str | None = None, style_format_name_or_id: str | None = None) -> ClassesGroup | ClassificationSystemClass: ...
