from .classification_system import ClassificationSystem as ClassificationSystem
from .mappings import MappingGroup as MappingGroup
from .style_formats import StyleFormats as StyleFormats
from .style_utils import SldGenerator as SldGenerator
from .utils import Utils as Utils
from typing import Any

class LCCS:
    def __init__(self, url: str, validate: bool = False, access_token=None, language=None) -> None: ...
    @property
    def allowed_language(self): ...
    @property
    def classification_systems(self): ...
    def classification_system(self, system: str) -> ClassificationSystem: ...
    def available_mappings(self, system_source: str) -> list: ...
    def mappings(self, system_source: str, system_target: str) -> MappingGroup: ...
    def available_style_formats(self) -> list: ...
    def style_formats(self, system) -> list[StyleFormats]: ...
    def get_style(self, system, style_format, path=None): ...
    def add_classification_system(self, system_path: str | dict) -> list[dict]: ...
    def update_class(self, system: str, class_id: int, class_info: dict) -> list[dict]: ...
    def add_classes(self, system: str, classes: str | list[dict[str, Any]]) -> dict[str, Any]: ...
    def add_style(self, system: str, style_format: str, style_path: str = None, style_tex: str = None, style_name: str = None, style_extension: str = None) -> list[dict]: ...
    def add_mapping(self, system_source: str, system_target: str, mappings) -> list: ...
    def add_style_format(self, name: str) -> dict: ...
    def delete_classification_system(self, system: str) -> int: ...
    def delete_class(self, system: str, class_name_or_id: str) -> int: ...
    def delete_style_format(self, style_format: str) -> int: ...
    def delete_style(self, system: str, style_format: str) -> int: ...
    def delete_mapping(self, system_source: str, system_target: str) -> int: ...
    def create_style(self, system: str, style_format: str, options: dict, rules: list): ...
    @property
    def url(self): ...
