class Link(dict):
    def __init__(self, data) -> None: ...
    @property
    def rel(self) -> str: ...
    @property
    def href(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def title(self) -> str: ...
