from .link import Link as Link

class StyleFormats(dict):
    def __init__(self, data, validate: bool = False) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def links(self) -> list[Link]: ...
