"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filesystemcollectorconf import (
    FilesystemCollectorConf,
    FilesystemCollectorConfTypedDict,
)
from cribl_control_plane import models, utils
from cribl_control_plane.types import BaseModel
from cribl_control_plane.utils import validate_open_enum
from enum import Enum
from pydantic import field_serializer
from pydantic.functional_validators import PlainValidator
from typing_extensions import Annotated, TypedDict


class CollectorFilesystemType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Collector type: filesystem"""

    FILESYSTEM = "filesystem"


class CollectorFilesystemTypedDict(TypedDict):
    r"""Filesystem collector configuration"""

    type: CollectorFilesystemType
    r"""Collector type: filesystem"""
    conf: FilesystemCollectorConfTypedDict


class CollectorFilesystem(BaseModel):
    r"""Filesystem collector configuration"""

    type: Annotated[CollectorFilesystemType, PlainValidator(validate_open_enum(False))]
    r"""Collector type: filesystem"""

    conf: FilesystemCollectorConf

    @field_serializer("type")
    def serialize_type(self, value):
        if isinstance(value, str):
            try:
                return models.CollectorFilesystemType(value)
            except ValueError:
                return value
        return value
