from enum import Enum


class EventType(Enum):
    MESSAGE_CREATED = "MESSAGE_CREATED"
    MESSAGE_UPDATED = "MESSAGE_UPDATED"
    CHANNEL_CREATED = "CHANNEL_CREATED"
    CHANNEL_UPDATED = "CHANNEL_UPDATED"
    HEARTBEAT = "HEARTBEAT"
    AUTHOR_UPDATED = "AUTHOR_UPDATED"
    MESSAGE_DELETED = "MESSAGE_DELETED"
    TYPING_STARTED = "TYPING_STARTED"
    CHANNEL_DELETED = "CHANNEL_DELETED"
