# -*- coding: utf-8 -*-

from typing import Any, AsyncGenerator, Dict, List, Optional, Set
import aiohttp
from main import *

class OneSymbole(SymbolIndex):
    rest_session: Optional[aiohttp.ClientSession]
    def __init__(self, symbol: str, errors_queue:QueueStream=None, *args: Any, **kwargs: Any) -> None: ...
    async def orderbook_stream(self, limit: int = 5000) -> AsyncGenerator[Dict[str, Dict[float, float]], None]: ...
    async def trades_stream(self) -> AsyncGenerator[Dict[str, Any], None]: ...
    async def klines_stream(self, interval: str) -> AsyncGenerator[Dict[str, Any], None]: ...
    async def get_symbol_info(self) -> Dict[str, Any]: ...
    async def klines_rest(
        self, interval: str, limit: int = 1000,
        start_time: Optional[int] = None, end_time: Optional[int] = None
    ) -> List[Dict[str, Any]]: ...

class PublicSymbols(AllSymbolsIndex):
    rest_session: Optional[aiohttp.ClientSession]
    def __init__(self, errors_queue:QueueStream=None, *args: Any, **kwargs: Any) -> None: ...
    async def get_all_spot_symbols(self, _type_: str = "short") -> Any: ...
