from __future__ import annotations
from importlib.metadata import version as _pkg_version
from ngsdiffgeo.manifolds import CigarSoliton
from ngsdiffgeo.manifolds import EuclideanMetric
from ngsdiffgeo.manifolds import Heisenberg
from ngsdiffgeo.manifolds import HyperbolicH2
from ngsdiffgeo.manifolds import HyperbolicH3
from ngsdiffgeo.manifolds import PoincareDisk
from ngsdiffgeo.manifolds import Sphere2
from ngsdiffgeo.manifolds import Sphere3
from ngsdiffgeo.manifolds import TestMetric
from ngsdiffgeo.manifolds import WarpedProduct
from ngsdiffgeo.ngsdiffgeo import Alternation
from ngsdiffgeo.ngsdiffgeo import GradCF
from ngsdiffgeo.ngsdiffgeo import GradProxy
from ngsdiffgeo.ngsdiffgeo import MakeTensorField
from ngsdiffgeo.ngsdiffgeo import MakeVectorField
from ngsdiffgeo.ngsdiffgeo import TensorProduct
from ngsdiffgeo.wrappers import KForm
from ngsdiffgeo.wrappers import OneForm
from ngsdiffgeo.wrappers import RiemannianManifold
from ngsdiffgeo.wrappers import ScalarField
from ngsdiffgeo.wrappers import TensorField
from ngsdiffgeo.wrappers import ThreeForm
from ngsdiffgeo.wrappers import TwoForm
from ngsdiffgeo.wrappers import VectorField
from ngsdiffgeo.wrappers import Wedge
from ngsdiffgeo.wrappers import d
from ngsdiffgeo.wrappers import delta
from ngsdiffgeo.wrappers import star
import ngsolve as ngsolve
from ngsolve.fem import Einsum
from . import manifolds
from . import ngsdiffgeo
from . import wrappers
__all__: list[str] = ['Alternation', 'CigarSoliton', 'Einsum', 'EuclideanMetric', 'GradCF', 'GradProxy', 'Heisenberg', 'HyperbolicH2', 'HyperbolicH3', 'KForm', 'MakeTensorField', 'MakeVectorField', 'OneForm', 'PoincareDisk', 'RiemannianManifold', 'ScalarField', 'Sphere2', 'Sphere3', 'TensorField', 'TensorProduct', 'TestMetric', 'ThreeForm', 'TwoForm', 'VectorField', 'WarpedProduct', 'Wedge', 'd', 'delta', 'manifolds', 'ngsdiffgeo', 'ngsolve', 'star', 'wrappers']
__version__: str = '0+unknown'
