"""

Python-side wrappers for ngsdiffgeo pybind classes.
"""
from __future__ import annotations
import importlib as importlib
from ngsdiffgeo import ngsdiffgeo as _cpp
import ngsdiffgeo.ngsdiffgeo
from ngsdiffgeo.ngsdiffgeo import KForm as _CPP_KForm
from ngsdiffgeo.ngsdiffgeo import OneForm as _CPP_OneForm
from ngsdiffgeo.ngsdiffgeo import RiemannianManifold as _CPP_RiemannianManifold
from ngsdiffgeo.ngsdiffgeo import ScalarField as _CPP_ScalarField
from ngsdiffgeo.ngsdiffgeo import TensorField as _CPP_TensorField
from ngsdiffgeo.ngsdiffgeo import ThreeForm as _CPP_ThreeForm
from ngsdiffgeo.ngsdiffgeo import TwoForm as _CPP_TwoForm
from ngsdiffgeo.ngsdiffgeo import VectorField as _CPP_VectorField
import ngsolve as ngsolve
__all__: list = ['KForm', 'GenericKForm', 'ScalarField', 'OneForm', 'TwoForm', 'ThreeForm', 'as_scalarfield', 'as_oneform', 'as_twoform', 'as_threeform', 'as_kform', 'VectorField', 'TensorField', 'as_vectorfield', 'as_tensorfield', 'Wedge', 'd', 'star', 'delta', 'RiemannianManifold']
class GenericKForm(ngsdiffgeo.ngsdiffgeo.KForm):
    def __add__(self, other):
        ...
    def __init__(self, cf, *, k, dim):
        ...
    def __mul__(self, other):
        ...
    def __radd__(self, other):
        ...
    def __rmul__(self, other):
        ...
    def __sub__(self, other):
        ...
    def __truediv__(self, other):
        ...
    def _wrap(self, cf):
        ...
class KForm:
    """
    
        Public Python 'KForm' wrapper/factory.
    
        - `isinstance(x, dg.KForm)` is True for any pybind k-form (including wrappers).
        - Calling `dg.KForm(cf, k=..., dim=...)` returns a typed wrapper instance.
        
    """
    @classmethod
    def __new__(cls, cf, *args, k = None, dim = None, **kwargs):
        ...
class OneForm(ngsdiffgeo.ngsdiffgeo.OneForm):
    def __add__(self, other):
        ...
    def __init__(self, cf):
        ...
    def __mul__(self, other):
        ...
    def __radd__(self, other):
        ...
    def __rmul__(self, other):
        ...
    def __sub__(self, other):
        ...
    def __truediv__(self, other):
        ...
    def _wrap(self, cf):
        ...
class RiemannianManifold(ngsdiffgeo.ngsdiffgeo.RiemannianManifold):
    def Contraction(self, tf, vf, slot = 0):
        ...
    def CovCurl(self, tf):
        ...
    def CovDef(self, tf):
        ...
    def CovDeriv(self, tf, vb = None):
        ...
    def CovDiv(self, tf, vb = None):
        ...
    def CovEin(self, tf):
        ...
    def CovHesse(self, tf):
        ...
    def CovInc(self, tf, matrix = False):
        ...
    def CovLaplace(self, tf):
        ...
    def CovRot(self, tf):
        ...
    def Cross(self, tf1, tf2):
        ...
    def InnerProduct(self, tf1, tf2, vb = None):
        ...
    def J(self, tf, vb = None):
        ...
    def KForm(self, cf, k):
        ...
    def LichnerowiczLaplacian(self, tf):
        ...
    def S(self, tf, vb = None):
        ...
    def Trace(self, tf, vb = None, index1 = 0, index2 = 1):
        ...
    def Transpose(self, tf, index1 = 0, index2 = 1):
        ...
    def __init__(self, metric):
        ...
    def delta(self, a):
        ...
    def star(self, a, vb = ...):
        ...
    @property
    def Curvature(self):
        ...
    @property
    def Einstein(self):
        ...
    @property
    def G(self):
        ...
    @property
    def G_deriv(self):
        ...
    @property
    def G_inv(self):
        ...
    @property
    def Gauss(self):
        ...
    @property
    def GeodesicCurvature(self):
        ...
    @property
    def MeanCurvature(self):
        ...
    @property
    def Ricci(self):
        ...
    @property
    def Riemann(self):
        ...
    @property
    def SFF(self):
        ...
    @property
    def Scalar(self):
        ...
    @property
    def normal(self):
        ...
    @property
    def tangent(self):
        ...
class ScalarField(ngsdiffgeo.ngsdiffgeo.ScalarField):
    def __add__(self, other):
        ...
    def __init__(self, cf, *, dim = -1):
        ...
    def __mul__(self, other):
        ...
    def __radd__(self, other):
        ...
    def __rmul__(self, other):
        ...
    def __sub__(self, other):
        ...
    def __truediv__(self, other):
        ...
    def _wrap(self, cf, k = 0):
        ...
class TensorField(ngsdiffgeo.ngsdiffgeo.TensorField):
    def __add__(self, other):
        ...
    def __init__(self, cf, covariant_indices):
        ...
    def __mul__(self, other):
        ...
    def __radd__(self, other):
        ...
    def __rmul__(self, other):
        ...
    def __sub__(self, other):
        ...
    def __truediv__(self, other):
        ...
    def _wrap(self, cf):
        ...
class ThreeForm(ngsdiffgeo.ngsdiffgeo.ThreeForm):
    def __add__(self, other):
        ...
    def __init__(self, cf, *, dim = -1):
        ...
    def __mul__(self, other):
        ...
    def __radd__(self, other):
        ...
    def __rmul__(self, other):
        ...
    def __sub__(self, other):
        ...
    def __truediv__(self, other):
        ...
    def _wrap(self, cf):
        ...
class TwoForm(ngsdiffgeo.ngsdiffgeo.TwoForm):
    def __add__(self, other):
        ...
    def __init__(self, cf, *, dim = -1):
        ...
    def __mul__(self, other):
        ...
    def __radd__(self, other):
        ...
    def __rmul__(self, other):
        ...
    def __sub__(self, other):
        ...
    def __truediv__(self, other):
        ...
    def _wrap(self, cf):
        ...
class VectorField(ngsdiffgeo.ngsdiffgeo.VectorField):
    def __add__(self, other):
        ...
    def __init__(self, cf):
        ...
    def __mul__(self, other):
        ...
    def __radd__(self, other):
        ...
    def __rmul__(self, other):
        ...
    def __sub__(self, other):
        ...
    def __truediv__(self, other):
        ...
    def _wrap(self, cf):
        ...
class _KFormMeta(type):
    @classmethod
    def __instancecheck__(cls, obj):
        ...
def Wedge(a, b):
    ...
def _call_if_callable(x):
    ...
def _infer_dim(obj):
    """
    Try to infer dimension. Returns int or None.
    """
def as_kform(cf, *, k, dim = None):
    ...
def as_oneform(cf):
    ...
def as_scalarfield(cf, *, dim = -1):
    ...
def as_tensorfield(cf, *, covariant_indices = None, dim = -1):
    ...
def as_threeform(cf, *, dim):
    ...
def as_twoform(cf, *, dim):
    ...
def as_vectorfield(cf):
    ...
def d(a):
    ...
def delta(a, M):
    ...
def star(a, M, vb = ...):
    ...
