# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from zepben.protobuf.cc import cc_requests_pb2 as zepben_dot_protobuf_dot_cc_dot_cc__requests__pb2
from zepben.protobuf.cc import cc_responses_pb2 as zepben_dot_protobuf_dot_cc_dot_cc__responses__pb2
from zepben.protobuf.connection import connection_requests_pb2 as zepben_dot_protobuf_dot_connection_dot_connection__requests__pb2
from zepben.protobuf.metadata import metadata_requests_pb2 as zepben_dot_protobuf_dot_metadata_dot_metadata__requests__pb2
from zepben.protobuf.metadata import metadata_responses_pb2 as zepben_dot_protobuf_dot_metadata_dot_metadata__responses__pb2


class CustomerConsumerStub(object):
    """*
    A service providing consumer access to the customer details.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getIdentifiedObjects = channel.stream_stream(
                '/zepben.protobuf.cc.CustomerConsumer/getIdentifiedObjects',
                request_serializer=zepben_dot_protobuf_dot_cc_dot_cc__requests__pb2.GetIdentifiedObjectsRequest.SerializeToString,
                response_deserializer=zepben_dot_protobuf_dot_cc_dot_cc__responses__pb2.GetIdentifiedObjectsResponse.FromString,
                )
        self.getCustomersForContainer = channel.stream_stream(
                '/zepben.protobuf.cc.CustomerConsumer/getCustomersForContainer',
                request_serializer=zepben_dot_protobuf_dot_cc_dot_cc__requests__pb2.GetCustomersForContainerRequest.SerializeToString,
                response_deserializer=zepben_dot_protobuf_dot_cc_dot_cc__responses__pb2.GetCustomersForContainerResponse.FromString,
                )
        self.getMetadata = channel.unary_unary(
                '/zepben.protobuf.cc.CustomerConsumer/getMetadata',
                request_serializer=zepben_dot_protobuf_dot_metadata_dot_metadata__requests__pb2.GetMetadataRequest.SerializeToString,
                response_deserializer=zepben_dot_protobuf_dot_metadata_dot_metadata__responses__pb2.GetMetadataResponse.FromString,
                )
        self.checkConnection = channel.unary_unary(
                '/zepben.protobuf.cc.CustomerConsumer/checkConnection',
                request_serializer=zepben_dot_protobuf_dot_connection_dot_connection__requests__pb2.CheckConnectionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class CustomerConsumerServicer(object):
    """*
    A service providing consumer access to the customer details.
    """

    def getIdentifiedObjects(self, request_iterator, context):
        """*
        Get identified objects.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCustomersForContainer(self, request_iterator, context):
        """*
        Get customers for a given EquipmentContainer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMetadata(self, request, context):
        """*
        Get Metadata related to the service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkConnection(self, request, context):
        """*
        Return an empty response for SDK connection tests.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerConsumerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getIdentifiedObjects': grpc.stream_stream_rpc_method_handler(
                    servicer.getIdentifiedObjects,
                    request_deserializer=zepben_dot_protobuf_dot_cc_dot_cc__requests__pb2.GetIdentifiedObjectsRequest.FromString,
                    response_serializer=zepben_dot_protobuf_dot_cc_dot_cc__responses__pb2.GetIdentifiedObjectsResponse.SerializeToString,
            ),
            'getCustomersForContainer': grpc.stream_stream_rpc_method_handler(
                    servicer.getCustomersForContainer,
                    request_deserializer=zepben_dot_protobuf_dot_cc_dot_cc__requests__pb2.GetCustomersForContainerRequest.FromString,
                    response_serializer=zepben_dot_protobuf_dot_cc_dot_cc__responses__pb2.GetCustomersForContainerResponse.SerializeToString,
            ),
            'getMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.getMetadata,
                    request_deserializer=zepben_dot_protobuf_dot_metadata_dot_metadata__requests__pb2.GetMetadataRequest.FromString,
                    response_serializer=zepben_dot_protobuf_dot_metadata_dot_metadata__responses__pb2.GetMetadataResponse.SerializeToString,
            ),
            'checkConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.checkConnection,
                    request_deserializer=zepben_dot_protobuf_dot_connection_dot_connection__requests__pb2.CheckConnectionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zepben.protobuf.cc.CustomerConsumer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CustomerConsumer(object):
    """*
    A service providing consumer access to the customer details.
    """

    @staticmethod
    def getIdentifiedObjects(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/zepben.protobuf.cc.CustomerConsumer/getIdentifiedObjects',
            zepben_dot_protobuf_dot_cc_dot_cc__requests__pb2.GetIdentifiedObjectsRequest.SerializeToString,
            zepben_dot_protobuf_dot_cc_dot_cc__responses__pb2.GetIdentifiedObjectsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getCustomersForContainer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/zepben.protobuf.cc.CustomerConsumer/getCustomersForContainer',
            zepben_dot_protobuf_dot_cc_dot_cc__requests__pb2.GetCustomersForContainerRequest.SerializeToString,
            zepben_dot_protobuf_dot_cc_dot_cc__responses__pb2.GetCustomersForContainerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zepben.protobuf.cc.CustomerConsumer/getMetadata',
            zepben_dot_protobuf_dot_metadata_dot_metadata__requests__pb2.GetMetadataRequest.SerializeToString,
            zepben_dot_protobuf_dot_metadata_dot_metadata__responses__pb2.GetMetadataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def checkConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zepben.protobuf.cc.CustomerConsumer/checkConnection',
            zepben_dot_protobuf_dot_connection_dot_connection__requests__pb2.CheckConnectionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
