# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tpu_info.proto import tpu_metric_service_pb2 as tpu__info_dot_proto_dot_tpu__metric__service__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tpu_info/proto/tpu_metric_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RuntimeMetricServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRuntimeMetric = channel.unary_unary(
                '/tpu.monitoring.runtime.RuntimeMetricService/GetRuntimeMetric',
                request_serializer=tpu__info_dot_proto_dot_tpu__metric__service__pb2.MetricRequest.SerializeToString,
                response_deserializer=tpu__info_dot_proto_dot_tpu__metric__service__pb2.MetricResponse.FromString,
                _registered_method=True)
        self.ListSupportedMetrics = channel.unary_unary(
                '/tpu.monitoring.runtime.RuntimeMetricService/ListSupportedMetrics',
                request_serializer=tpu__info_dot_proto_dot_tpu__metric__service__pb2.ListSupportedMetricsRequest.SerializeToString,
                response_deserializer=tpu__info_dot_proto_dot_tpu__metric__service__pb2.ListSupportedMetricsResponse.FromString,
                _registered_method=True)
        self.GetTpuRuntimeStatus = channel.unary_unary(
                '/tpu.monitoring.runtime.RuntimeMetricService/GetTpuRuntimeStatus',
                request_serializer=tpu__info_dot_proto_dot_tpu__metric__service__pb2.GetTpuRuntimeStatusRequest.SerializeToString,
                response_deserializer=tpu__info_dot_proto_dot_tpu__metric__service__pb2.GetTpuRuntimeStatusResponse.FromString,
                _registered_method=True)


class RuntimeMetricServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRuntimeMetric(self, request, context):
        """GetRuntimeMetric returns the TPU metrics data for the MetricRequest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSupportedMetrics(self, request, context):
        """ListSupportedMetrics lists the supported metrics for
        ListSupportedMetricsRequest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTpuRuntimeStatus(self, request, context):
        """GetTpuRuntimeStatus returns the TPU runtime status for the
        GetTpuRuntimeStatusRequest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeMetricServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRuntimeMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeMetric,
                    request_deserializer=tpu__info_dot_proto_dot_tpu__metric__service__pb2.MetricRequest.FromString,
                    response_serializer=tpu__info_dot_proto_dot_tpu__metric__service__pb2.MetricResponse.SerializeToString,
            ),
            'ListSupportedMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSupportedMetrics,
                    request_deserializer=tpu__info_dot_proto_dot_tpu__metric__service__pb2.ListSupportedMetricsRequest.FromString,
                    response_serializer=tpu__info_dot_proto_dot_tpu__metric__service__pb2.ListSupportedMetricsResponse.SerializeToString,
            ),
            'GetTpuRuntimeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTpuRuntimeStatus,
                    request_deserializer=tpu__info_dot_proto_dot_tpu__metric__service__pb2.GetTpuRuntimeStatusRequest.FromString,
                    response_serializer=tpu__info_dot_proto_dot_tpu__metric__service__pb2.GetTpuRuntimeStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tpu.monitoring.runtime.RuntimeMetricService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tpu.monitoring.runtime.RuntimeMetricService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeMetricService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRuntimeMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tpu.monitoring.runtime.RuntimeMetricService/GetRuntimeMetric',
            tpu__info_dot_proto_dot_tpu__metric__service__pb2.MetricRequest.SerializeToString,
            tpu__info_dot_proto_dot_tpu__metric__service__pb2.MetricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSupportedMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tpu.monitoring.runtime.RuntimeMetricService/ListSupportedMetrics',
            tpu__info_dot_proto_dot_tpu__metric__service__pb2.ListSupportedMetricsRequest.SerializeToString,
            tpu__info_dot_proto_dot_tpu__metric__service__pb2.ListSupportedMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTpuRuntimeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tpu.monitoring.runtime.RuntimeMetricService/GetTpuRuntimeStatus',
            tpu__info_dot_proto_dot_tpu__metric__service__pb2.GetTpuRuntimeStatusRequest.SerializeToString,
            tpu__info_dot_proto_dot_tpu__metric__service__pb2.GetTpuRuntimeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
