"""DNP3 Object definitions per IEEE 1815-2012.

This module contains data object definitions for all supported groups and variations.
"""

from dnp3.objects.analog_input import (
    AnalogInput16,
    AnalogInput16NoFlag,
    AnalogInput32,
    AnalogInput32NoFlag,
    AnalogInputDouble,
    AnalogInputEvent16,
    AnalogInputEvent16Time,
    AnalogInputEvent32,
    AnalogInputEvent32Time,
    AnalogInputEventDouble,
    AnalogInputEventDoubleTime,
    AnalogInputEventFloat,
    AnalogInputEventFloatTime,
    AnalogInputFloat,
)
from dnp3.objects.base import (
    DNP3Object,
    EventObject,
    GroupVariation,
    PointValue,
    StaticObject,
    TimestampedValue,
)
from dnp3.objects.binary_input import (
    BinaryInputEvent,
    BinaryInputEventRelativeTime,
    BinaryInputEventTime,
    BinaryInputFlags,
)
from dnp3.objects.binary_output import (
    CROB,
    BinaryOutputEvent,
    BinaryOutputEventTime,
    BinaryOutputFlags,
    CommandStatus,
    ControlCode,
)
from dnp3.objects.class_data import (
    ClassData0,
    ClassData1,
    ClassData2,
    ClassData3,
)
from dnp3.objects.counter import (
    Counter16,
    Counter16NoFlag,
    Counter32,
    Counter32NoFlag,
    CounterEvent16,
    CounterEvent16Time,
    CounterEvent32,
    CounterEvent32Time,
    FrozenCounter16,
    FrozenCounter16Time,
    FrozenCounter32,
    FrozenCounter32Time,
)
from dnp3.objects.registry import (
    get_registered,
    get_size,
    is_registered,
    lookup,
    lookup_gv,
    register,
)
from dnp3.objects.time import (
    TimeAndDate,
    TimeCTO,
    TimeCTOUnsync,
    TimeDelayCoarse,
    TimeDelayFine,
)

__all__ = [
    "CROB",
    "AnalogInput16",
    "AnalogInput16NoFlag",
    "AnalogInput32",
    "AnalogInput32NoFlag",
    "AnalogInputDouble",
    "AnalogInputEvent16",
    "AnalogInputEvent16Time",
    "AnalogInputEvent32",
    "AnalogInputEvent32Time",
    "AnalogInputEventDouble",
    "AnalogInputEventDoubleTime",
    "AnalogInputEventFloat",
    "AnalogInputEventFloatTime",
    "AnalogInputFloat",
    "BinaryInputEvent",
    "BinaryInputEventRelativeTime",
    "BinaryInputEventTime",
    "BinaryInputFlags",
    "BinaryOutputEvent",
    "BinaryOutputEventTime",
    "BinaryOutputFlags",
    "ClassData0",
    "ClassData1",
    "ClassData2",
    "ClassData3",
    "CommandStatus",
    "ControlCode",
    "Counter16",
    "Counter16NoFlag",
    "Counter32",
    "Counter32NoFlag",
    "CounterEvent16",
    "CounterEvent16Time",
    "CounterEvent32",
    "CounterEvent32Time",
    "DNP3Object",
    "EventObject",
    "FrozenCounter16",
    "FrozenCounter16Time",
    "FrozenCounter32",
    "FrozenCounter32Time",
    "GroupVariation",
    "PointValue",
    "StaticObject",
    "TimeAndDate",
    "TimeCTO",
    "TimeCTOUnsync",
    "TimeDelayCoarse",
    "TimeDelayFine",
    "TimestampedValue",
    "get_registered",
    "get_size",
    "is_registered",
    "lookup",
    "lookup_gv",
    "register",
]
