"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
We expect to remove this file."""

from abc import (
    ABCMeta,
    abstractmethod,
)
from chalk._gen.chalk.streaming.v1.simple_streaming_service_pb2 import (
    SimpleStreamingUnaryInvokeRequest,
    SimpleStreamingUnaryInvokeResponse,
)
from grpc import (
    Channel,
    Server,
    ServicerContext,
    UnaryUnaryMultiCallable,
)

class SimpleStreamingServiceStub:
    def __init__(self, channel: Channel) -> None: ...
    SimpleStreamingUnaryInvoke: UnaryUnaryMultiCallable[
        SimpleStreamingUnaryInvokeRequest,
        SimpleStreamingUnaryInvokeResponse,
    ]
    """Runs a simple streaming plan with the given request.
    This is a simplified version of the streaming invoker service.
    """

class SimpleStreamingServiceServicer(metaclass=ABCMeta):
    @abstractmethod
    def SimpleStreamingUnaryInvoke(
        self,
        request: SimpleStreamingUnaryInvokeRequest,
        context: ServicerContext,
    ) -> SimpleStreamingUnaryInvokeResponse:
        """Runs a simple streaming plan with the given request.
        This is a simplified version of the streaming invoker service.
        """

def add_SimpleStreamingServiceServicer_to_server(servicer: SimpleStreamingServiceServicer, server: Server) -> None: ...
