import click
from rich.console import Console
from rich.panel import Panel
from rich.text import Text
from rich.markdown import Markdown
from rich import box
from rich.table import Table
from rhamaa.commands.cms import cms

console = Console()

ASCII_LOGO = '''\
....................................................................................................
..............................@@@@@@@@..............................................................
............................@@@@@@@@@@@@@...........................................................
..........................#@@@@@@@@@@@@@@@ .........................................................
........................@@@@@@@.....%...%@@@@....... ...............................................
.......................@@.@@@@...@....@#..@-@@...=@@@@@@@#..........................................
...................... @@.@@@@@ .........@@@@#..@@@@#.*@@@@ ........................................
........................@@@@@@@@-..@.@..@@@@...@@@+......@@@........................................
..........................@@@@@@........@@.... @@@.......@@@........................................
......................@@@@@@@@@@...... .@@.....@@@......-@@@ .......................................
....................@@@@@@@@@@@@@.. ...@@*.....@@@....@@@@@.........................................
..................@@@@@@@@@@@@@@@@@@@@@@.......@@@....@@%...........................................
.................@@@@@@@@@@@@@@@@@@@@@@........@@@..................................................
................@@@@@@@@@..@@@@@@@@@@@@@......@@@@..................................................
...............@@@@@@@@@@@@#.@@@@@@@@@@@@....#@@@...................................................
...............@@@@@@@@@@@@@..@@@@@@@@@@@...%@@@....................................................
..............-@@@@@@@@@@@@@..@@@@@@.@@@@@.@@@@.....................................................
..............@@@@@@@@@@@@@...:@@@@@..#@@@@@@@......................................................
..............@@@@@@@@@@@@@@-...@@@@@...@@@@@%......................................................
..............#@@@@@@@@@@@@@@....@@@@@..:@@@@@......................................................
................ ................................................................ ..................
..............@@@@@@@@@...@@@....@@@.....@@@@.....@@@@.....@@@@.....@@@@.........@@@@...............
..............@@@....@@@..@@@....@@@.....@@@@@....@@@@@...@@@@@.....@@@@@.......@@@@@...............
..............@@@....@@@..@@@....@@@....@@@.@@+...@@@@@@ @@@@@@....@@@.@@%.....@@@.@@@..............
..............@@@@@@@@@...@@@@@@@@@@...@@@..@@@ ..@@@.@@@@@.@@@...@@@..@@@.....@@@..@@@.............
..............@@@@@@@@....@@@....@@@...@@@@@@@@@..@@@..@@@..@@@...@@@@@@@@@...@@@@@@@@@.............
..............@@@...@@@...@@@....@@@..@@@@@@@@@@..@@@...@ ..@@@..@@@@@@@@@@=..@@@@@@@@@@............
..............@@@....@@@..@@@....@@@.#@@#.....@@@.@@@...... @@@.@@@-.....@@@.@@@.....%@@@...........
....................................................................................................
'''

HELP_COMMANDS = [
    ("cms start <ProjectName>", "[green]Create a new Wagtail project[/green]"),
    ("cms startapp <AppName>", "[yellow]Create a new Django app (minimal or wagtail)[/yellow]"),
    ("cms startapp --list", "[blue]List available prebuilt apps[/blue]"),
    ("cms startapp <AppName> --prebuild <key>", "[cyan]Install prebuilt app[/cyan]"),
    ("cms run", "[bright_green]Start development server[/bright_green]"),
    ("cms check", "[bright_yellow]Run system checks[/bright_yellow]"),
    ("cms status", "[bright_blue]Show project status[/bright_blue]"),
    ("help", "[magenta]Show this help message[/magenta]")
]

HELP_PANEL_TEXT = "[bold yellow]Rhamaa CLI[/bold yellow] - Accelerate your Wagtail development!\n"

@click.group(invoke_without_command=True)
@click.pass_context
def main(ctx):
    """Rhamaa CLI for Wagtail development."""
    if ctx.invoked_subcommand is None:
        show_logo_and_help()
    else:
        pass

@main.command()
def help():
    """Show help information with logo."""
    show_logo_and_help()

def show_logo_and_help():
    console.print(Panel(Text(ASCII_LOGO, justify="center"), style="bold magenta", box=box.DOUBLE, expand=False))
    table = Table(show_header=True, header_style="bold blue", box=box.ROUNDED, expand=False)
    table.add_column("Command", style="bold white", width=22)
    table.add_column("Description", style="bold", min_width=32)
    for cmd, desc in HELP_COMMANDS:
        table.add_row(f"rhamaa {cmd}", desc)
    console.print(Panel(HELP_PANEL_TEXT, style="bold yellow", box=box.ROUNDED, expand=False))
    console.print(table)
    console.print("[dim]Docs: https://github.com/RhamaaCMS/RhamaaCLI | Made with [bold magenta]Rich[/bold magenta][/dim]", justify="center")

main.add_command(cms)
